Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-03, with the labels that each got.

#1109 refactor: improve address list style when creating a new wallet
  src/renderer/components/Button/ButtonReload.vue
  src/renderer/pages/Wallet/WalletNew.vue
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#1115 fix: several BIP 38 issues and refactor the implementation
  __tests__/unit/pages/Wallet/WalletNew.spec.js
  __tests__/unit/plugins/background-worker.spec.js
  __tests__/unit/services/bip38.spec.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionForm/mixin-on-submit.js
  src/renderer/components/Wallet/WalletSignModal.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/main.js
  src/renderer/pages/Wallet/WalletImport.vue
  src/renderer/pages/Wallet/WalletNew.vue
  src/renderer/pages/Wallet/mixin-on-create.js
  src/renderer/plugins/background-worker.js
  src/renderer/services/bip38.js
  src/renderer/workers/bip38-worker.js
Labels: Complexity: High, Type: Bugfix, Type: Refactor

#1059 feat: load x ledger wallets
  __tests__/unit/components/Modal/ModalAdditionalLedgers.spec.js
  __tests__/unit/components/Wallet/WalletButtons/WalletButtonAdditionalLedgers.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  src/renderer/App.vue
  src/renderer/components/Button/ButtonModal.vue
  src/renderer/components/Modal/ModalAdditionalLedgers.vue
  src/renderer/components/Modal/index.js
  src/renderer/components/Wallet/WalletButtons/WalletButtonAdditionalLedgers.vue
  src/renderer/components/Wallet/WalletButtons/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/services/client.js
  src/renderer/services/synchronizer/ledger.js
  src/renderer/store/modules/ledger.js
Labels: Complexity: High, Status: Needs Review, Type: Feature

#1108 refactor: synch dynamic fees only when `InputFee` is active
  __tests__/unit/components/Input/InputFee.spec.js
  __tests__/unit/services/synchronizer.spec.js
  src/renderer/components/Input/InputFee.vue
  src/renderer/services/client.js
  src/renderer/services/synchronizer.js
  src/renderer/store/index.js
  src/renderer/store/modules/network.js
  src/renderer/store/modules/peer.js
  src/renderer/store/modules/session.js
  src/renderer/store/modules/transaction.js
Labels: Complexity: High, Status: Needs Changes, Type: Refactor

#1116 refactor: display the identicon and improve style on confirmation of new wallet
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Wallet/WalletNew.vue
Labels: Complexity: Low, Type: Refactor

#1122 chore: change Node version to 11.10.1 to avoid problems on CI
  .circleci/config.yml
Labels: Complexity: Low, Type: Task

#1121 perf: delay and change the interval of synchronization
  src/renderer/App.vue
  src/renderer/services/synchronizer.js
Labels: Complexity: Low, Type: Performance

#957 misc: add Italian language
  config/index.js
  src/renderer/i18n/date-time-formats.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/i18n/number-formats.js
Labels: Bounty: Tier 3, Status: Member Approved, Status: Needs Changes, Type: Feature

#1123 fix: don't display loading on the dashboard if there are no wallets
  src/renderer/components/Dashboard/DashboardTransactions.vue
Labels: Complexity: Low, Type: Bugfix

#1125 fix: change UI language when changing profile
  src/renderer/store/modules/session.js
Labels: Complexity: Low, Type: Bugfix

#1126 fix: show the pointer cursor on letter avatars
  src/renderer/components/Profile/ProfileAvatar.vue
  src/renderer/pages/Profile/ProfileAll.vue
Labels: Complexity: Low, Type: Bugfix

#1127 fix: language selection on profile creation
  src/renderer/components/Input/InputLanguage.vue
Labels: Complexity: Low, Type: Bugfix

#1128 chore: bump to 2.3.0
  package.json
Labels: Complexity: Low, Type: Task

#1130 perf: cache rendered pages that are not tied to the current session profile
  src/renderer/App.vue
  src/renderer/router/index.js
Labels: Complexity: Low, Type: Performance

#1132 fix: enable the translation of empty transaction table message
  src/renderer/components/Dashboard/DashboardTransactions.vue
  src/renderer/components/Transaction/TransactionTable.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1124 perf: save regular and Ledger wallets at once instead of dispatching multiple Vuex actions
  __tests__/unit/services/synchronizer/wallets.spec.js
  src/renderer/services/synchronizer/wallets.js
  src/renderer/store/modules/ledger.js
  src/renderer/store/modules/wallet.js
Labels: Complexity: Undetermined, Type: Performance

#1118 fix: do not store Ledger connection timer since it is not used
  __tests__/unit/store/modules/ledger.spec.js
  src/renderer/services/ledger-service.js
  src/renderer/store/modules/ledger.js
Labels: Complexity: Low, Type: Bugfix, Type: Performance, Type: Refactor

#1139 fix: static fee default if fee statistics empty
  __tests__/unit/components/Input/InputFee.spec.js
  src/renderer/components/Input/InputFee.vue
Labels: Complexity: Low, Type: Bugfix

#1129 feat: truncate the transaction block ID on the transaction show modal if necessary
  src/renderer/components/Transaction/TransactionShow.vue
Labels: Complexity: Low, Type: Feature

#1135 perf: cache all the pages that do not use a parametrized URL
  src/renderer/App.vue
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/pages/Wallet/WalletAll.vue
Labels: Type: Performance

#1147 chore: bump to 2.3.1
  package.json
Labels: Complexity: Low, Type: Task

#1152 fix: ledger issues
  __tests__/unit/services/synchronizer/wallets.spec.js
  src/renderer/App.vue
  src/renderer/services/synchronizer/wallets.js
  src/renderer/store/modules/ledger.js
Labels: Complexity: Medium, Type: Bugfix

#1150 chore: bump to 2.3.2
  package.json
Labels: Complexity: Low, Type: Task

#1154 fix: do not override the state when updating wallets at once
  __tests__/unit/store/modules/ledger.spec.js
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/store/modules/ledger.js
Labels: Complexity: Low, Type: Bugfix

#1140 fix: disable market chart setting if market not enabled
  src/renderer/components/ListDivided/ListDividedItem.vue
  src/renderer/pages/Profile/ProfileEdition.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1145 fix: add margin only when confirmations truthy & chores
  __tests__/unit/__utils__/setup.js
  __tests__/unit/components/Menu/MenuStep.spec.js
  src/renderer/components/Collapse/CollapseAccordion.vue
  src/renderer/components/Menu/MenuNavigation/MenuNavigation.vue
  src/renderer/components/Menu/MenuStep/MenuStep.vue
  src/renderer/components/Transaction/TransactionShow.vue
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/mixins/collections.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1156 chore: update ACF address
  config/networks/mainnet.json
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved, Type: Task

#1155 misc: Italian translation update
  src/renderer/i18n/locales/it-IT.js
Labels: Bounty: Tier 6, Complexity: Low, Status: Member Approved

#1157 chore: upgrade `@arkecosystem/crypto` to 2.2.2
  package.json
  src/renderer/services/client.js
  yarn.lock
Labels: Complexity: Medium, Type: Task

#1159 feat: initial plugin system implementation
  package.json
  plugins/.gitkeep
  src/renderer/App.vue
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuPlugins.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Input/InputGrid/InputGridItem.vue
  src/renderer/components/Menu/MenuOptions/MenuOptions.vue
  src/renderer/components/Plugin/PluginTable.vue
  src/renderer/components/Profile/ProfileAvatar.vue
  src/renderer/components/Selection/SelectionAvatar.vue
  src/renderer/components/Selection/mixin-selection-image.js
  src/renderer/components/Selection/mixin-selection.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/main.js
  src/renderer/models/profile.js
  src/renderer/pages/Plugins.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/plugins/plugin-manager.js
  src/renderer/router/index.js
  src/renderer/services/plugin-manager.js
  src/renderer/store/index.js
  src/renderer/store/modules/plugin.js
  yarn.lock
Labels: Complexity: Undetermined, Status: In Progress, Type: Feature
