Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-02, with the labels that each got.

#1052 fix: make contacts container scrollable
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
Labels: Complexity: Medium, Status: Member Approved, Status: Needs Review, Type: Bugfix

#1054 feat: component `InputLanguage` and add language flags to profile
  __tests__/unit/components/Menu/MenuDropdown.spec.js
  config/index.js
  src/main/menu.js
  src/renderer/assets/images/flags/bg-BG.svg
  src/renderer/assets/images/flags/cs-CZ.svg
  src/renderer/assets/images/flags/da-DK.svg
  src/renderer/assets/images/flags/de-DE.svg
  src/renderer/assets/images/flags/el-GR.svg
  src/renderer/assets/images/flags/en-US.svg
  src/renderer/assets/images/flags/es-ES.svg
  src/renderer/assets/images/flags/fr-FR.svg
  src/renderer/assets/images/flags/it-IT.svg
  src/renderer/assets/images/flags/ja-JP.svg
  src/renderer/assets/images/flags/ko-KR.svg
  src/renderer/assets/images/flags/nb-NO.svg
  src/renderer/assets/images/flags/nl-NL.svg
  src/renderer/assets/images/flags/pl-PL.svg
  src/renderer/assets/images/flags/pt-BR.svg
  src/renderer/assets/images/flags/ro-RO.svg
  src/renderer/assets/images/flags/ru-RU.svg
  src/renderer/assets/images/flags/se-SE.svg
  src/renderer/assets/images/flags/sk-SK.svg
  src/renderer/assets/images/flags/tr-TR.svg
  src/renderer/assets/images/flags/uk-UA.svg
  src/renderer/assets/images/flags/vi-VN.svg
  src/renderer/assets/images/flags/zh-CN.svg
  src/renderer/components/Input/InputLanguage.vue
  src/renderer/components/Input/InputSelect.vue
  src/renderer/components/Input/index.js
  src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdownHandler.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdownItem.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
Labels: Complexity: Undetermined, Status: Needs Changes, Status: Needs Review, Type: Feature

#1045 docs: update CHANGELOG
  CHANGELOG.md
Labels: Type: Documentation

#1048 fix: do not treat addresses that are on NEO as invalid
  src/renderer/components/Input/InputAddress.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#1061 feat: keep the expand button at the top
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/pages/Wallet/WalletShow.vue
Labels: Status: Needs Review, Type: Feature

#1053 misc/feat: copy button in wallet table, redirect & success message
  src/renderer/components/Button/ButtonClipboard.vue
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Contact/ContactNew.vue
Labels: Bounty: Tier 3, Complexity: Low, Status: Member Approved, Status: Needs Changes, Status: Needs Review, Type: Feature

#1062 fix: docs filepath
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved, Status: Needs Review, Type: Bugfix

#1044 refactor: correctly sort wallets and contacts in overview and sidebar
  __tests__/unit/components/utils/Sorting.spec.js
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/components/utils/Sorting.js
  src/renderer/mixins/wallet.js
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/store/modules/wallet.js
Labels: Bounty: Tier 2, Status: Member Approved, Status: Needs Changes

#1065 fix: dashboard transaction loading and sidebar placeholder
  src/renderer/components/Dashboard/DashboardTransactions.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1064 fix: add subject to clipboard button upon resetting tooltip
  src/renderer/components/Button/ButtonClipboard.vue
Labels: Complexity: Low, Status: Member Approved, Status: Needs Review, Type: Bugfix

#1072 feat: allow navigating to delegate addresses on the vote delegate modal
  src/renderer/components/Transaction/TransactionForm/TransactionForm.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Wallet/WalletAddress.vue
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#1077 feat: ask users, when leaving the profile edition without having saved it, if they want to do it
  __tests__/unit/pages/Profile/ProfileAll.spec.js
  config/index.js
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Contact/ContactRemovalConfirmation.vue
  src/renderer/components/Modal/ModalConfirmation.vue
  src/renderer/components/Profile/ProfileLeavingConfirmation.vue
  src/renderer/components/Profile/ProfileRemovalConfirmation.vue
  src/renderer/components/Profile/index.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Wallet/WalletRemovalConfirmation.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Profile/ProfileAll.vue
  src/renderer/pages/Profile/ProfileEdition.vue
Labels: Status: Needs Review, Type: Bugfix, Type: Feature

#1074 feat: revamp the introductory screens and allow choosing language
  src/renderer/App.vue
  src/renderer/assets/images/flags/README.md
  src/renderer/assets/images/pages/background-intro-mobile.png
  src/renderer/assets/images/pages/background-intro.png
  src/renderer/assets/images/pages/background-welcome.png
  src/renderer/assets/images/pages/intro/duty.png
  src/renderer/assets/images/pages/intro/duty.svg
  src/renderer/assets/images/pages/intro/power.png
  src/renderer/assets/images/pages/intro/power.svg
  src/renderer/assets/images/pages/intro/responsibility.png
  src/renderer/assets/images/pages/intro/responsibility.svg
  src/renderer/assets/images/pages/intro/turn.png
  src/renderer/assets/images/pages/intro/turn.svg
  src/renderer/assets/images/pages/intro/welcome.svg
  src/renderer/components/App/AppIntro/AppIntro.vue
  src/renderer/components/App/AppIntro/AppIntroScreen.vue
  src/renderer/components/App/AppIntro/index.js
  src/renderer/components/App/AppIntroScreen.vue
  src/renderer/components/App/AppWelcome.vue
  src/renderer/components/App/index.js
  src/renderer/components/App/mobile/AppIntroScreenMobile.vue
  src/renderer/components/App/mobile/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/styles/_theme.css
Labels: Status: Needs Review, Type: Feature

#1080 feat: add remote sorting to delegate table
  __tests__/unit/store/modules/delegate.spec.js
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue
  src/renderer/services/client.js
Labels: Bounty: Tier 2, Complexity: Low, Status: Member Approved, Type: Feature

#1081 misc: configure the new Ark Shield address
  config/networks/mainnet.json
Labels: Complexity: Low, Status: Needs Review, Type: Maintenance

#1079 feat: add the time format setting to the profile creation
  src/renderer/i18n/locales/en-US.js
  src/renderer/mixins/formatter.js
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
Labels: Complexity: Low, Status: Needs Changes, Type: Feature

#1068 feat: include a menu to filter and sort the wallets of the sidebar
  __tests__/unit/components/Wallet/WalletAddress.spec.js
  __tests__/unit/components/Wallet/WalletSidebar.spec.js
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Menu/MenuOptions/MenuOptionsItem.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFiltersSearchInput.vue
  src/renderer/directives/click-outside.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/store/modules/wallet.js
  src/renderer/styles/_theme.css
  tailwind.js
Labels: Complexity: High, Type: Feature

#1076 chore: add scripts to detect missing translations
  README.md
  package.json
  yarn.lock
Labels: Status: Needs Review, Type: Feature

#1075 chore: upgrade to node 11 and fix all failing unit tests
  .circleci/config.yml
  .nvmrc
  README.md
  __tests__/e2e.jest.conf.js
  __tests__/e2e/__utils__/setup.js
  __tests__/e2e/app.spec.js
  __tests__/e2e/first-screen.spec.js
  __tests__/e2e/pages/1-window.spec.js
  __tests__/e2e/pages/2-welcome.spec.js
  __tests__/e2e/pages/3-profile-new.spec.js
  __tests__/e2e/profile-new.js
  __tests__/unit.jest.conf.js
  __tests__/unit/__fixtures__/store/network.js
  __tests__/unit/__fixtures__/store/profile.js
  __tests__/unit/__utils__/setup.js
  __tests__/unit/components/Contact/ContactRenameModal.spec.js
  __tests__/unit/components/Menu/MenuDropdown.spec.js
  __tests__/unit/components/Modal/ModalRename.spec.js
  __tests__/unit/components/Modal/ModalWindow.spec.js
  __tests__/unit/components/Transaction/TransactionModal.spec.js
  __tests__/unit/components/Wallet/WalletDelegates.spec.js
  __tests__/unit/components/Wallet/WalletHeading.spec.js
  __tests__/unit/components/Wallet/WalletRenameModal.spec.js
  __tests__/unit/mixins/currency.spec.js
  __tests__/unit/pages/Profile/ProfileAll.spec.js
  __tests__/unit/pages/Wallet/WalletAll.spec.js
  __tests__/unit/pages/Wallet/WalletNew.spec.js
  __tests__/unit/store/modules/delegate.spec.js
  __tests__/unit/store/modules/peer.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  package.json
  src/main/index.js
  src/renderer/components/App/AppIntro/AppIntro.vue
  src/renderer/components/App/AppIntro/AppIntroScreen.vue
  src/renderer/store/plugins/vuex-persist-migrations.js
  yarn.lock
Labels: Complexity: High, Status: Needs Changes, Status: Needs Review, Type: Task

#1088 misc: add COSS to known wallets
  config/networks/mainnet.json
Labels: Complexity: Low, Status: Needs Review, Type: Maintenance

#1073 feat: infer the market ticker of custom networks by checking CryptoCompare
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/services/crypto-compare.js
  src/renderer/store/modules/market.js
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#1093 refactor: speed session load up by using 1 mutation instead of dispatching lots of actions
  src/renderer/store/modules/session.js
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#1095 fix: compile portal-vue to not display developer note in production
  .electron-vue/webpack.renderer.config.js
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#1043 feat: verify, when sending transactions, that the 2nd passphrase is correct
  src/renderer/components/Passphrase/PassphraseInput.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
Labels: Status: Needs Review, Type: Feature

#1094 fix: get balance for unowned wallets
  __tests__/unit/components/Wallet/WalletHeadingInfo.spec.js
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Status: Needs Review, Type: Bugfix

#1085 docs: fix typos on translation instructions
  README.md
Labels: Status: Needs Review, Type: Documentation

#1087 fix: use the cursor pointer on the pagination "rows per page" dropdown
  src/renderer/styles/_table.css
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#1102 chore: stage linted files before commit
  .lintstagedrc
  package.json
Labels: Complexity: Low, Status: Member Approved, Status: Needs Review, Type: Task

#1103 refactor: revamp how transactions are loaded on the dashboard
  __tests__/unit/components/Dashboard/DashboardTransactions.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  src/renderer/components/Dashboard/DashboardTransactions.vue
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue
  src/renderer/pages/Dashboard.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/services/synchronizer.js
  src/renderer/services/synchronizer/wallets.js
  src/renderer/store/modules/transaction.js
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#1099 fix: show voted delegates in wallet table
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/models/wallet.js
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
Labels: Complexity: Low, Status: Member Approved, Status: Needs Changes, Status: Needs Review, Type: Bugfix

#1106 refactor: request wallets data and transactions in parallel during synchronization
  __tests__/unit/services/synchronizer/wallets.spec.js
  src/renderer/services/synchronizer/wallets.js
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#1092 feat: display the ticker price on the dashboard, even when the chart is disabled
  src/renderer/components/MarketChart/MarketChartHeader.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Dashboard.vue
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#1086 fix: use the configured time format on the market chart
  __tests__/unit/components/MarketChart/MarketChart.spec.js
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/mixins/formatter.js
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#1107 fix: request multiple wallets or transactions at once when the API allows it
  __tests__/unit/services/client.spec.js
  src/renderer/services/client.js
  src/renderer/store/modules/peer.js
Labels: Complexity: High, Status: Needs Review, Type: Bugfix

#1089 fix: how cryptocurrencies are formatted when localized and displaying with symbols
  __tests__/unit/__utils__/setup.js
  __tests__/unit/mixins/currency.spec.js
  src/renderer/mixins/currency.js
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#1105 feat: highlight the wallet sidebar filters button when they are active
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#1104 feat: ignore the case of the query when filtering by name of wallets, contacts, Ledgers, known wallets or delegates
  __tests__/unit/components/Wallet/WalletSidebar.spec.js
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#1091 feat: move "Chart on dashboard" setting to profile creation and edition
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#1078 refactor: improve avatar alignment and wallet grid style
  __tests__/unit/components/Menu/MenuDropdown.spec.js
  __tests__/unit/pages/Wallet/WalletAll.spec.js
  src/renderer/assets/svg/more.svg
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/Button/ButtonLetter.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue
  src/renderer/components/Profile/ProfileAvatar.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/styles/_theme.css
  tailwind.js
Labels: Complexity: Medium, Status: Needs Changes, Type: Refactor

#826 refactor: maxlength of vendorField
  config/index.js
  config/networks/devnet.json
  config/networks/mainnet.json
  src/renderer/components/Input/InputText.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/network.js
Labels: Bounty: Tier 4, Status: Member Approved, Status: Needs Changes, Type: Refactor
