Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-06, with the labels that each got.

#1277 fix: use webview instead of iframe for changelly
  src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
Labels: Complexity: Low, Type: Bugfix

#1284 v2.4.1
  package.json
  src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
  src/renderer/services/client.js
  yarn.lock
Labels: Complexity: Low

#1291 refactor: use nock to mock tests
  __tests__/unit/services/crypto-compare.spec.js
  __tests__/unit/services/release.spec.js
  __tests__/unit/store/modules/delegate.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  __tests__/unit/store/modules/peer.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  package.json
  yarn.lock
Labels: Complexity: High, Type: Refactor

#1282 revert: worker changes from commit e42290
  .electron-vue/build.js
  .electron-vue/webpack.renderer.config.js
  __tests__/unit/services/bip38.spec.js
  __tests__/unit/store/modules/delegate.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  __tests__/unit/store/modules/peer.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  package.json
  src/renderer/components/Transaction/TransactionForm/mixin-on-submit.js
  src/renderer/components/Wallet/WalletSignModal.vue
  src/renderer/pages/Wallet/mixin-on-create.js
  src/renderer/services/background-http-client.js
  src/renderer/services/bip38.js
  src/renderer/services/client.js
  src/renderer/services/crypto-compare.js
  src/renderer/services/http.js
  src/renderer/services/release.js
  src/renderer/services/wallet.js
  src/renderer/services/worker.js
  src/renderer/store/modules/peer.js
  src/renderer/workers/bip38-worker.js
  src/renderer/workers/bip38.js
  src/renderer/workers/http.js
  yarn.lock
Labels: Complexity: High

#1300 fix: ledger options on build
  src/renderer/components/Wallet/WalletButtons/WalletButtonLedgerSettings.vue
Labels: Complexity: Low, Type: Bugfix

#1297 fix: prioritize Ledger wallets on the wallet sidebar
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#1294 fix: duplicated key warning on new wallet page
  src/renderer/pages/Wallet/WalletNew.vue
Labels: Complexity: Low, Type: Bugfix

#1204 fix: don't close custom peer modal when clicking inside
  __tests__/unit/components/Network/NetworkCustomPeerModal.spec.js
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
  src/renderer/components/Button/ButtonModal.vue
  src/renderer/components/Network/NetworkCustomPeerModal.vue
  src/renderer/components/Network/index.js
Labels: Complexity: Low, Type: Bugfix

#1301 refactor: wallet address & balance clickable on WalletAll page
  src/renderer/pages/Wallet/WalletAll.vue
Labels: Complexity: Low, Status: Member Approved, Type: Refactor

#1292 fix: ledger wallet sidebar filter
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue
Labels: Complexity: Low, Type: Bugfix

#1296 fix: ledger whitescreen
  .circleci/config.yml
  __tests__/unit/__mocks__/@ledgerhq/hw-transport-node-hid-singleton.js
  __tests__/unit/services/ledger-service.spec.js
  package.json
  src/renderer/services/ledger-service.js
  src/renderer/store/modules/ledger.js
  yarn.lock
Labels: Complexity: Medium, Type: Bugfix

#1281 fix: open transaction modal on dashboard
  __tests__/unit/services/uri-handler.spec.js
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/services/uri-handler.js
Labels: Complexity: Low, Type: Bugfix

#1302 fix: don't switch twice when selecting wallet on WalletSidebar
  src/renderer/components/Menu/MenuNavigation/MenuNavigation.vue
  src/renderer/components/Menu/MenuNavigation/MenuNavigationItem.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
Labels: Complexity: Low, Type: Bugfix

#1303 chore: bump version to 2.5.0
  package.json
Labels: Complexity: Low, Type: Task

#1306 misc: italian language update
  src/renderer/i18n/locales/it-IT.js
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved

#1305 fix: sidebar popup button click to close
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
Labels: Complexity: High, Type: Bugfix

#1273 feat: add a button to navigate back to the previous wallet page
  src/renderer/App.vue
  src/renderer/components/App/AppBackButton.vue
  src/renderer/components/App/index.js
  src/renderer/components/Wallet/WalletAddress.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
Labels: Complexity: Low, Status: Needs Changes, Type: Feature
