Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-05, with the labels that each got.

#1218 fix: username validation when registering a new delegate
  __tests__/unit/services/wallet.spec.js
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/services/wallet.js
Labels: Complexity: Medium, Status: Needs Changes, Type: Bugfix

#1180 feat(plugins): implement ability to overwrite elements with slots
  src/renderer/components/App/AppFooter.vue
  src/renderer/components/Plugin/PluginWrapper.vue
  src/renderer/plugins/plugin-manager.js
Labels: Complexity: Low, Type: Feature

#1191 feat(plugins): require permissions to include content on the app
  postcss.config.js
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Feature

#1219 fix: show the market chart when enabling it on the profile
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/components/utils/LineChart.js
  src/renderer/pages/Dashboard.vue
Labels: Complexity: Low, Type: Bugfix

#1194 feat(plugins): allow adding custom themes
  __tests__/unit/pages/Wallet/WalletNew.spec.js
  package.json
  src/index.ejs
  src/renderer/App.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/mixins/session.js
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/services/plugin-manager.js
  src/renderer/store/modules/plugin.js
  src/renderer/store/modules/session.js
  yarn.lock
Labels: Complexity: Medium, Type: Feature

#1186 feat(plugins): add the plugins section to the main sidebar
  src/renderer/assets/svg/plugins.svg
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Feature

#1192 fix(plugins): load menu routes correctly
  src/main/index.js
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuPlugins.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Bugfix

#1227 fix(plugins): plugins paths for vue when creating components
  package.json
  src/renderer/services/plugin-manager.js
  yarn.lock
Labels: Complexity: Low, Type: Bugfix

#1231 fix: peer management on v2.4+
  __tests__/unit/store/modules/peer.spec.js
  package.json
  src/renderer/models/peer.js
  src/renderer/services/client.js
  src/renderer/store/modules/peer.js
  yarn.lock
Labels: Complexity: Undetermined, Type: Bugfix

#1230 fix: fee statistics for 2.4
  src/renderer/services/client.js
Labels: Complexity: Low, Type: Bugfix

#1226 fix(plugins): avatar plugin selection
  src/renderer/components/Input/InputGrid/InputGrid.vue
  src/renderer/components/Input/InputGrid/InputGridModal.vue
Labels: Complexity: Low, Type: Bugfix

#1232 fix: detect successful transactions correctly
  src/renderer/components/Transaction/TransactionModal.vue
Labels: Complexity: Low, Type: Bugfix

#1233 feat: sync the `vendorField` maximum length from the network
  __tests__/unit/store/modules/peer.spec.js
  config/networks/devnet.json
  config/networks/mainnet.json
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/models/network.js
  src/renderer/services/client.js
Labels: Complexity: Low, Type: Feature

#1228 fix(plugins): use light theme if plugin is removed before disabling
  src/renderer/App.vue
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/mixins/session.js
Labels: Complexity: Low, Type: Bugfix

#1235 fix(plugins): do not allow choosing a plugin theme during profile creation
  src/renderer/pages/Profile/ProfileNew.vue
Labels: Complexity: Low, Type: Bugfix

#1243 chore: update changelly url
  src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
Labels: Complexity: Low, Type: Task

#1242 fix: stop hover from displacing address container
  src/renderer/pages/Wallet/WalletNew.vue
Labels: Bounty: Tier 4, Complexity: Medium, Status: Member Approved, Type: Bugfix

#1247 fix: vue-i18n-extract commands
  package.json
  yarn.lock
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1245 feat(plugins): add a button to discover more plugins on an external URL
  config/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Plugins.vue
Labels: Complexity: Medium, Type: Feature

#1248 feat(plugins): button to open the plugin installation folder
  config/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Plugins.vue
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Feature

#1249 fix: provides the network wif to sign transactions
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/services/client.js
Labels: Complexity: Low, Type: Bugfix

#1250 fix(plugins): render components in production
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Bugfix

#1229 refactor: require user action when generating 2nd passphrase
  src/renderer/components/Button/ButtonReload.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/i18n/locales/en-US.js
Labels: Bounty: Tier 3, Complexity: Low, Status: Member Approved, Type: Refactor

#1148 feat: store sidebar sorting and filters
  __tests__/unit/components/Wallet/WalletSidebar.spec.js
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue
  src/renderer/models/profile.js
  src/renderer/pages/Dashboard.vue
  src/renderer/store/modules/session.js
Labels: Complexity: Medium, Status: Member Approved, Status: Needs Changes, Type: Feature

#1146 feat: add option to hide the wallet button text
  __tests__/unit/components/Wallet/WalletButtons/WalletButtonLedgerSettings.spec.js
  __tests__/unit/store/modules/session.spec.js
  src/renderer/assets/svg/ledger.svg
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Menu/MenuOptions/MenuOptionsItem.vue
  src/renderer/components/Modal/ModalAdditionalLedgers.vue
  src/renderer/components/Wallet/WalletButtons/WalletButtonAdditionalLedgers.vue
  src/renderer/components/Wallet/WalletButtons/WalletButtonCreate.vue
  src/renderer/components/Wallet/WalletButtons/WalletButtonImport.vue
  src/renderer/components/Wallet/WalletButtons/WalletButtonLedgerSettings.vue
  src/renderer/components/Wallet/WalletButtons/index.js
  src/renderer/components/Wallet/WalletHeading/WalletHeadingMenuLedger.vue
  src/renderer/components/Wallet/WalletHeading/index.js
  src/renderer/directives/click-outside.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/profile.js
  src/renderer/pages/Dashboard.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/store/modules/session.js
Labels: Bounty: Tier 1, Complexity: Medium, Status: Member Approved, Type: Feature

#1256 feat(plugins): button to reload plugins
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Plugins.vue
Labels: Complexity: Low, Type: Feature

#1258 fix: vendorField transaction assignment
  src/renderer/services/client.js
Labels: Complexity: Low, Type: Bugfix

#1251 fix(plugins): position of the arrow of the plugin items menu
  src/renderer/components/App/AppSidemenu/AppSidemenuPlugins.vue
Labels: Complexity: Low, Type: Bugfix

#1234 fix: get children of TransitionGroup when available & word-break of vendorfield
  src/renderer/components/Transaction/TransactionTable.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/mixins/collections.js
Labels: Bounty: Tier 3, Complexity: Low, Status: Member Approved, Type: Bugfix

#1259 feat: show remaining bytes in vendorfield helper text
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/i18n/locales/en-US.js
Labels: Bounty: Tier 3, Complexity: Low, Status: Member Approved, Type: Feature

#1255 fix: plugin table sorting
  src/renderer/components/Plugin/PluginTable.vue
  src/renderer/models/profile.js
  src/renderer/pages/Plugins.vue
  src/renderer/services/plugin-manager.js
  src/renderer/store/modules/session.js
Labels: Bounty: Tier 3, Complexity: Low, Type: Bugfix

#1257 feat(plugins): warn about using the plugin system
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuPluginConfirmation.vue
  src/renderer/components/Modal/ModalConfirmation.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/profile.js
Labels: Complexity: Medium, Type: Feature

#1267 chore: use organization-wide GitHub Configuration
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/Bug_report.md
  .github/ISSUE_TEMPLATE/Feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Complexity: Medium, Type: Task

#1268 misc: Italian language update
  src/renderer/i18n/locales/it-IT.js
Labels: Bounty: Tier 3, Status: Member Approved

#1260 fix(plugins): tidy permission method names & check exists
  src/renderer/services/plugin-manager.js
Labels: Complexity: Undetermined, Type: Bugfix

#1270 feat: use the theme colours for the wallet filters instead of white
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue
Labels: Complexity: Low, Type: Feature

#1271 deps: upgrade `axios` (CVE-2019-10742)
  __tests__/unit/store/modules/peer.spec.js
  package.json
  yarn.lock
Labels: Complexity: Low

#1101 fix: saving of invalid profile name on leave
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Profile/ProfileEdition.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Status: Needs Changes, Type: Bugfix

#1201 fix: display the wallet sidebar filters on the right position
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue
Labels: Complexity: Low, Type: Bugfix

#1272 refactor: add the status icon and plus/minus sign in the transaction viewer
  src/renderer/components/Transaction/TransactionAmount.vue
  src/renderer/components/Transaction/TransactionShow.vue
  src/renderer/components/Transaction/TransactionStatusIcon.vue
  src/renderer/components/Transaction/TransactionTable.vue
Labels: Complexity: Medium, Type: Refactor
