Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-07, with the labels that each got.

#1274 feat: add a switch button on the dashboard to show or hide the market chart
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/components/MarketChart/MarketChartHeader.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Dashboard.vue
Labels: Complexity: Medium, Status: Needs Changes, Type: Feature

#1309 refactor: add tooltip to wallet name
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved, Type: Refactor

#1313 refactor: make complete back button clickable and use localized text
  src/renderer/components/App/AppBackButton.vue
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved, Type: Refactor

#1312 refactor: show tooltips only when value truncated
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved, Type: Refactor

#1318 chore: bump to 2.5.1
  package.json
Labels: Complexity: Low, Type: Task

#1319 refactor: move back button to the tab menu
  src/renderer/App.vue
  src/renderer/components/App/AppBackButton.vue
  src/renderer/components/App/index.js
  src/renderer/components/Menu/MenuTab/MenuTab.vue
  src/renderer/components/Menu/MenuTab/MenuTabItem.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
Labels: Complexity: Medium, Type: Refactor

#1317 refactor: handle response as string and build transactions with BigNumber
  __tests__/unit/__fixtures__/store/delegate.js
  __tests__/unit/components/Input/InputCurrency.spec.js
  __tests__/unit/components/Input/InputFee.spec.js
  __tests__/unit/components/Menu/MenuNavigation.spec.js
  __tests__/unit/mixins/currency.spec.js
  __tests__/unit/pages/Profile/ProfileAll.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/store/modules/delegate.spec.js
  __tests__/unit/store/modules/profile.spec.js
  src/renderer/components/Input/InputCurrency.vue
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirm.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
  src/renderer/mixins/currency.js
  src/renderer/models/base.js
  src/renderer/models/delegate.js
  src/renderer/models/peer.js
  src/renderer/models/profile.js
  src/renderer/models/transaction.js
  src/renderer/models/wallet.js
  src/renderer/pages/Profile/ProfileAll.vue
  src/renderer/plugins/bignumber.js
  src/renderer/services/client.js
  src/renderer/store/modules/delegate.js
  src/renderer/store/modules/profile.js
  yarn.lock
Labels: Complexity: High, Type: Refactor

#1320 chore: merge develop into master
  __tests__/unit/__fixtures__/store/delegate.js
  __tests__/unit/components/Input/InputCurrency.spec.js
  __tests__/unit/components/Input/InputFee.spec.js
  __tests__/unit/components/Menu/MenuNavigation.spec.js
  __tests__/unit/mixins/currency.spec.js
  __tests__/unit/pages/Profile/ProfileAll.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/store/modules/delegate.spec.js
  __tests__/unit/store/modules/profile.spec.js
  package.json
  src/renderer/App.vue
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Input/InputCurrency.vue
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/components/MarketChart/MarketChartHeader.vue
  src/renderer/components/Menu/MenuTab/MenuTab.vue
  src/renderer/components/Menu/MenuTab/MenuTabItem.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirm.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Wallet/WalletAddress.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/mixins/currency.js
  src/renderer/models/base.js
  src/renderer/models/delegate.js
  src/renderer/models/peer.js
  src/renderer/models/profile.js
  src/renderer/models/transaction.js
  src/renderer/models/wallet.js
  src/renderer/pages/Dashboard.vue
  src/renderer/pages/Profile/ProfileAll.vue
  src/renderer/plugins/bignumber.js
  src/renderer/services/client.js
  src/renderer/store/modules/delegate.js
  src/renderer/store/modules/profile.js
Labels: Complexity: Undetermined, Type: Task

#1308 feat: make screenshot protection setting persistent
  src/renderer/App.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/profile.js
  src/renderer/store/modules/app.js
  src/renderer/store/modules/session.js
Labels: Bounty: Tier 3, Status: Member Approved, Type: Feature

#1329 chore: setup probot/stale configuration
  .github/stale.yml
Labels: Complexity: Low, Type: Task

#1330 chore(readme): add lead maintainer information
  README.md
Labels: Complexity: Low, Type: Task

#1323 feat: toggle wallet dropdown on right mouse click
  src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
  src/renderer/pages/Wallet/WalletAll.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Feature

#1332 refactor: upgrade the crypto package to latest version
  __tests__/unit/store/modules/ledger.spec.js
  package.json
  src/renderer/services/client.js
  src/renderer/services/transaction.js
  src/renderer/services/wallet.js
  src/renderer/store/modules/ledger.js
  src/renderer/workers/bip38-worker.js
  yarn.lock
Labels: Complexity: High, Type: Refactor

#1333 chore: upgrade to Electron 5 and Node 12
  .circleci/config.yml
  .nvmrc
  package.json
  src/main/index.js
  yarn.lock
Labels: Complexity: Undetermined

#1331 refactor: remove v1 support & improve peer discovery
  __tests__/unit/__fixtures__/store/network.js
  __tests__/unit/__fixtures__/store/peer.js
  __tests__/unit/components/Network/NetworkModal.spec.js
  __tests__/unit/components/Transaction/TransactionModal.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/services/release.spec.js
  __tests__/unit/store/modules/delegate.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  __tests__/unit/store/modules/peer.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  package.json
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/peer.js
  src/renderer/services/client.js
  src/renderer/services/crypto-compare.js
  src/renderer/services/release.js
  src/renderer/services/wallet.js
  src/renderer/store/migrations/2.6.0 - fix peer schema.js
  src/renderer/store/modules/delegate.js
  src/renderer/store/modules/ledger.js
  src/renderer/store/modules/network.js
  src/renderer/store/modules/peer.js
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor

#1340 chore: update current vote wording
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Task

#1217 feat: unify the grid layout of wallets and contacts
  src/renderer/components/Wallet/WalletGrid.vue
  src/renderer/components/Wallet/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
Labels: Complexity: High, Status: Member Approved, Type: Feature

#1325 refactor: add animations to market chart and store options
  __tests__/unit/components/MarketChart/MarketChartHeader.spec.js
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/components/MarketChart/MarketChartHeader.vue
  src/renderer/models/profile.js
  src/renderer/pages/Dashboard.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/store/migrations/2.5.2 - add marketChartOptions to profile.js
  src/renderer/store/modules/session.js
Labels: Bounty: Tier 2, Complexity: High, Status: Member Approved, Type: Refactor

#1339 fix: populate network data
  __tests__/unit/components/Network/NetworkModal.spec.js
  src/renderer/components/Network/NetworkModal.vue
Labels: Complexity: Medium, Type: Bugfix

#1344 fix: enable webviews
  src/main/index.js
Labels: Complexity: Low, Type: Bugfix

#1343 fix: custom adapter for 'got' requests
  .electron-vue/webpack.main.config.js
  .electron-vue/webpack.renderer.config.js
  .electron-vue/webpack.web.config.js
  package.json
  src/renderer/plugins/got.js
  yarn.lock
Labels: Complexity: High, Status: Needs Changes, Type: Bugfix

#1345 feat: plugin system updates
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/http.js
  src/renderer/store/modules/profile.js
  src/renderer/store/modules/wallet.js
Labels: Complexity: Medium, Type: Feature
