Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-09, with the labels that each got.

#1402 fix: properly format crypto currencies
  __tests__/unit/mixins/currency.spec.js
  __tests__/unit/mixins/formatter.spec.js
  __tests__/unit/pages/Profile/ProfileAll.spec.js
  src/renderer/mixins/currency.js
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#1143 fix: close transaction show modal when clicking on addresses and navigate to transactions tab always
  src/renderer/components/Transaction/TransactionForm/TransactionForm.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Transaction/TransactionShow.vue
  src/renderer/components/Wallet/WalletAddress.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
Labels: Complexity: Low, Status: Collaborator Approved, Status: Needs Review, Type: Bugfix

#1355 chore(deps): update all electron dependencies
  package.json
  yarn.lock
Labels: Complexity: Undetermined, Type: Task

#1383 feat: load transaction from file
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormTransfer.spec.js
  src/renderer/assets/svg/load.svg
  src/renderer/components/Modal/ModalAdditionalLedgers.vue
  src/renderer/components/Modal/ModalExportWallets.vue
  src/renderer/components/Modal/ModalWindow.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/mixins/electron.js
Labels: Bounty: Tier 2, Complexity: Medium, Status: Member Approved, Status: Needs Review, Type: Feature

#1398 feat: use websockets in plugins
  __tests__/unit/services/plugin-manager/websocket.spec.js
  package.json
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/websocket.js
  yarn.lock
Labels: Complexity: Medium, Status: Member Approved, Status: Needs Testcase, Type: Feature

#1433 chore: bump version to 2.6.1
  package.json
Labels: Complexity: Low, Type: Task

#1434 merge develop to master
  .codacy.yml
  .electron-vue/webpack.renderer.config.js
  .gitignore
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormTransfer.spec.js
  __tests__/unit/mixins/currency.spec.js
  __tests__/unit/mixins/formatter.spec.js
  __tests__/unit/pages/Profile/ProfileAll.spec.js
  __tests__/unit/services/plugin-manager/websocket.spec.js
  __tests__/unit/store/modules/peer.spec.js
  package.json
  src/renderer/assets/svg/load.svg
  src/renderer/components/Input/InputAddress.vue
  src/renderer/components/Modal/ModalAdditionalLedgers.vue
  src/renderer/components/Modal/ModalExportWallets.vue
  src/renderer/components/Modal/ModalWindow.vue
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/components/Transaction/TransactionForm/TransactionForm.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Transaction/TransactionShow.vue
  src/renderer/components/Wallet/WalletAddress.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
  src/renderer/components/Wallet/WalletSelection.vue
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/mixins/currency.js
  src/renderer/mixins/electron.js
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/websocket.js
  src/renderer/store/modules/peer.js
  yarn-error.log
  yarn.lock
Labels: Complexity: Undetermined

#1324 feat: make the window modal minimizable
  __tests__/unit/components/Modal/ModalWindow.spec.js
  package.json
  src/renderer/App.vue
  src/renderer/assets/svg/minus.svg
  src/renderer/assets/svg/resize.svg
  src/renderer/components/Button/ButtonClose.vue
  src/renderer/components/Modal/ModalWindow.vue
  yarn.lock
Labels: Complexity: Medium, Status: Needs Changes, Type: Feature

#1443 refactor: don't parse transaction fees as int
  __tests__/unit/services/client.spec.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/services/client.js
Labels: Bounty: Tier 4, Complexity: Medium, Status: Member Approved, Type: Refactor

#1442 refactor: fetch wallet vote directly instead of requesting transactions
  __tests__/unit/services/client.spec.js
  src/renderer/services/client.js
  src/renderer/store/modules/ledger.js
Labels: Bounty: Tier 3, Complexity: Medium, Status: Member Approved, Type: Refactor

#1445 fix: ledger device path empty in production
  package.json
  yarn.lock
Labels: Complexity: Medium, Type: Bugfix

#1444 fix: unconfirmed votes
  __tests__/unit/services/client.spec.js
  __tests__/unit/services/synchronizer/wallets.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  src/renderer/services/client.js
  src/renderer/services/synchronizer/wallets.js
  src/renderer/store/modules/transaction.js
Labels: Complexity: Low, Type: Bugfix

#1439 refactor(aip-11): transaction forms
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionForm/mixin-on-submit.js
  src/renderer/components/Transaction/TransactionForm/mixin.js
Labels: Complexity: High, Type: Refactor

#1456 chore(deps): upgrade vm2 to 3.8.4
  package.json
  yarn.lock
Labels: Complexity: Low, Type: Task

#1395 feat: pending balance tooltip with unconfirmed transactions
  __tests__/unit/components/Wallet/WalletHeadingInfo.spec.js
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/plugins/bignumber.js
Labels: Complexity: Low, Status: Member Approved, Status: Needs Changes, Status: Needs Discussion, Type: Feature

#1311 fix: store server used to import as peer
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/store/modules/peer.js
Labels: Complexity: Low, Status: Needs Changes, Type: Bugfix

#1451 refactor(plugins): add websocket methods
  __tests__/unit/services/plugin-manager/websocket.spec.js
  src/renderer/services/plugin-manager/websocket.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Refactor

#1436 fix: include ledger wallets in plugins
  __tests__/unit/store/modules/wallet.spec.js
  src/renderer/store/modules/ledger.js
  src/renderer/store/modules/wallet.js
Labels: Complexity: Low, Status: Member Approved, Status: Needs Testcase, Type: Bugfix

#1452 feat: timers in plugins
  __tests__/unit/services/plugin-manager/timers.spec.js
  src/renderer/services/plugin-manager.js
Labels: Bounty: Tier 4, Complexity: Medium, Status: Member Approved, Status: Needs Changes, Type: Feature

#1462 ci: setup github action workflow for testing
  .circleci/config.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  README.md
  package.json
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review

#1463 fix: re-add network address version property
  .github/workflows/lint.yml
  .github/workflows/test.yml
  __tests__/unit/components/Network/NetworkModal.spec.js
  src/renderer/components/Network/NetworkModal.vue
Labels: Complexity: Low, Type: Bugfix

#1468 fix: wallet password message signing
  src/renderer/components/Wallet/WalletSignModal.vue
Labels: Complexity: Low, Type: Bugfix

#1471 ci: upload build artifacts if tests pass
  .github/workflows/test.yml
  package.json
  scripts/version-artifacts.sh
Labels: Complexity: Medium

#1472 chore: adjust workflows to match all branches on push
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: Complexity: Low, Status: Contributor Approved, Type: Task
