Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-12, with the labels that each got.

#1562 fix: transaction amount on confirmation modal
  src/renderer/services/client.js
  src/renderer/services/transaction.js
  src/renderer/store/modules/transaction.js
Labels: Complexity: Low, Type: Bugfix

#1552 fix: hidden delegate dropdown on search
  src/renderer/components/Wallet/WalletSelectDelegate.vue
Labels: Complexity: Low, Type: Bugfix

#1551 fix: add network fails
  __tests__/unit/components/Network/NetworkModal.spec.js
  src/renderer/components/Network/NetworkModal.vue
Labels: Complexity: Medium, Type: Bugfix

#1469 fix: network modal missing version
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Bugfix

#1568 chore: update status badge and other readme tweaks
  README.md
Labels: Bounty: Tier 6, Complexity: Low, Status: Member Approved, Type: Task

#1571 fix: unknown typo
  src/renderer/components/App/AppUpdater.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
Labels: Complexity: Undetermined, Type: Bugfix

#1575 chore: add test coverage reporters
  __tests__/unit.jest.conf.js
Labels: Complexity: Low, Type: Task

#1574 chore: update electron-builder
  package.json
  yarn.lock
Labels: Complexity: Medium, Type: Task

#1573 refactor: remove wallet api and peer version
  __tests__/unit/services/client.spec.js
  __tests__/unit/store/modules/delegate.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  __tests__/unit/store/modules/peer.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/peer.js
  src/renderer/services/client.js
  src/renderer/store/modules/ledger.js
  src/renderer/store/modules/peer.js
Labels: Complexity: Medium, Type: Refactor

#1572 fix: ledger transaction amount on confirm modal
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
Labels: Complexity: Low, Type: Bugfix

#1578 refactor: plugins allow sandbox destroy
  __tests__/unit/services/plugin-manager.spec.js
  __tests__/unit/services/plugin-manager/sandbox/alerts-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/audio-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/events-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/font-awesome-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/http-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/messaging-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/peer-current-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/profile-all-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/profile-current-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/route-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/storage-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/timers-sandbox.spec.js
  __tests__/unit/services/plugin-manager/sandbox/websocket-sandbox.spec.js
  __tests__/unit/services/plugin-manager/setup/avatars-setup.spec.js
  __tests__/unit/services/plugin-manager/setup/components-setup.spec.js
  __tests__/unit/services/plugin-manager/setup/menu-items-setup.spec.js
  __tests__/unit/services/plugin-manager/setup/register-setup.spec.js
  __tests__/unit/services/plugin-manager/setup/routes-setup.spec.js
  __tests__/unit/services/plugin-manager/setup/themes-setup.spec.js
  __tests__/unit/services/plugin-manager/setup/ui-components-setup.spec.js
  __tests__/unit/services/plugin-manager/setup/wallet-tabs-setup.spec.js
  __tests__/unit/services/plugin-manager/setup/webframe-setup.spec.js
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/plugin-sandbox.js
  src/renderer/services/plugin-manager/plugin-setup.js
  src/renderer/services/plugin-manager/sandbox/alerts-sandbox.js
  src/renderer/services/plugin-manager/sandbox/audio-sandbox.js
  src/renderer/services/plugin-manager/sandbox/events-sandbox.js
  src/renderer/services/plugin-manager/sandbox/font-awesome-sandbox.js
  src/renderer/services/plugin-manager/sandbox/http-sandbox.js
  src/renderer/services/plugin-manager/sandbox/messaging-sandbox.js
  src/renderer/services/plugin-manager/sandbox/peer-current-sandbox.js
  src/renderer/services/plugin-manager/sandbox/profile-all-sandbox.js
  src/renderer/services/plugin-manager/sandbox/profile-current-sandbox.js
  src/renderer/services/plugin-manager/sandbox/route-sandbox.js
  src/renderer/services/plugin-manager/sandbox/storage-sandbox.js
  src/renderer/services/plugin-manager/sandbox/timers-sandbox.js
  src/renderer/services/plugin-manager/sandbox/websocket-sandbox.js
  src/renderer/services/plugin-manager/setup/avatars-setup.js
  src/renderer/services/plugin-manager/setup/components-setup.js
  src/renderer/services/plugin-manager/setup/font-awesome-setup.js
  src/renderer/services/plugin-manager/setup/menu-items-setup.js
  src/renderer/services/plugin-manager/setup/register-setup.js
  src/renderer/services/plugin-manager/setup/routes-setup.js
  src/renderer/services/plugin-manager/setup/themes-setup.js
  src/renderer/services/plugin-manager/setup/ui-components-setup.js
  src/renderer/services/plugin-manager/setup/wallet-tabs-setup.js
  src/renderer/services/plugin-manager/setup/webframe-setup.js
Labels: Complexity: High, Type: Refactor

#1579 chore: bump version 2.7.0
  package.json
Labels: Complexity: Low, Type: Task

#1580 chore: bump workflow version 2.7.0
  .github/workflows/test.yml
Labels: Complexity: Low, Type: Task

#1582 fix: delete plugin path of installed plugin when updating and various tweaks
  __tests__/unit/services/plugin-manager.spec.js
  src/main/plugin-manager.js
  src/renderer/App.vue
  src/renderer/pages/PluginManager.vue
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/errors.js
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix
