Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-01, with the labels that each got.

#929 fix: uri ledger issue with 1 non-ledger wallet
  src/renderer/components/Wallet/WalletSelection.vue
Labels: Type: Bugfix

#930 fix: set default fees on transfer screen so send all properly works
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
Labels: Status: Needs Review, Type: Bugfix

#936 fix: confirm modal default portal target
  __tests__/unit/components/Modal/ModalConfirmation.spec.js
  src/renderer/components/Modal/ModalConfirmation.vue
Labels: Status: Needs Review, Type: Bugfix

#941 refactor: get ledger address & public key together
  __tests__/unit/__mocks__/@arkecosystem/ledger-transport.js
  __tests__/unit/services/ledger-service.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  src/renderer/services/ledger-service.js
  src/renderer/store/modules/ledger.js
Labels: Status: Needs Review, Type: Refactor

#927 refactor: transaction helper props in store getters
  __tests__/unit/store/modules/transaction.spec.js
  src/renderer/store/modules/transaction.js
Labels: Bounty: Tier 4, Type: Refactor

#942 chore: add codecov
  .circleci/config.yml
  package.json
  yarn.lock
Labels: Status: Needs Review, Type: Maintenance

#921 misc: ui tweaks and typos
  __tests__/unit/components/MarketChart/MarketChartHeader.spec.js
  __tests__/unit/components/Transaction/TransactionModal.spec.js
  src/renderer/components/MarketChart/MarketChartHeader.vue
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingPrimaryActions.vue
  src/renderer/components/Wallet/WalletRenameModal.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Contact/ContactNew.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/pages/Wallet/WalletImport.vue
  src/renderer/pages/Wallet/WalletNew.vue
Labels: Bounty: Tier 4, Status: Needs Review, Type: Refactor

#943 refactor: ledger throw errors
  __tests__/unit/store/modules/ledger.spec.js
  src/renderer/store/modules/ledger.js
Labels: Type: Bugfix, Type: Refactor

#939 feat: Clarify custom peer disconnection
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Wallet/WalletNew.vue
Labels: Bounty: Tier 4, Type: Feature

#919 refactor: new profile creation page
  src/renderer/App.vue
  src/renderer/assets/images/pages/profile-new/background-step-1-dark.png
  src/renderer/assets/images/pages/profile-new/background-step-1.png
  src/renderer/assets/images/pages/profile-new/background-step-2-dark.png
  src/renderer/assets/images/pages/profile-new/background-step-2.png
  src/renderer/assets/images/pages/profile-new/background-step-3-dark.png
  src/renderer/assets/images/pages/profile-new/background-step-3.png
  src/renderer/assets/images/pages/profile-new/step-1.svg
  src/renderer/assets/images/pages/profile-new/step-2.svg
  src/renderer/assets/images/pages/profile-new/step-3.svg
  src/renderer/assets/svg/moon.svg
  src/renderer/assets/svg/sun.svg
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/Input/InputGrid/InputGridItem.vue
  src/renderer/components/Input/InputGrid/InputGridModal.vue
  src/renderer/components/Menu/MenuStep/MenuStepItem.vue
  src/renderer/components/Selection/SelectionAvatar.vue
  src/renderer/components/Selection/SelectionNetwork.vue
  src/renderer/components/Selection/SelectionTheme.vue
  src/renderer/components/Selection/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
  tailwind.js
Labels: Type: Refactor

#816 Design improvements
  src/renderer/components/Transaction/TransactionTable.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Wallet/WalletShow.vue
Labels: Bounty: Tier 5, Status: Needs Review, Type: Refactor

#823 docs: explain how to translate the app
  README.md
Labels: Type: Documentation

#916 refactor: intro screens text content
  src/renderer/components/App/AppIntroScreen.vue
  src/renderer/components/App/mobile/AppIntroScreenMobile.vue
  src/renderer/i18n/locales/en-US.js
Labels: Bounty: Tier 5, Status: Needs Review, Type: Refactor

#949 fix: handle unsuccessful unvote transaction
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
Labels: Bounty: Tier 4, Complexity: Low, Type: Bugfix

#953 fix: change delegate voting banner if wallet is not owned
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/i18n/locales/en-US.js
Labels: Bounty: Tier 4

#959 fix: load all networks correctly
  __tests__/unit/store/modules/network.spec.js
  src/renderer/App.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/store/modules/network.js
Labels: Status: Needs Review, Type: Bugfix

#950 fix: do not display the not-voting icon before knowing if the wallet is voting
  src/renderer/components/Wallet/WalletHeading/WalletHeadingPrimaryActions.vue
Labels: Status: Needs Review, Type: Bugfix

#937 feat: broadcast to multiple peers
  __tests__/unit/__fixtures__/store/peer.js
  __tests__/unit/store/modules/peer.spec.js
  config/index.js
  config/peers/devnet.json
  config/peers/mainnet.json
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Transaction/TransactionShow.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingPrimaryActions.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/profile.js
  src/renderer/services/client.js
  src/renderer/store/modules/peer.js
  src/renderer/store/modules/session.js
Labels: Bounty: Tier 1, Type: Feature

#947 feat: optional profile avatar
  __tests__/unit/components/Button/ButtonLetter.spec.js
  __tests__/unit/pages/Wallet/WalletAll.spec.js
  src/renderer/assets/svg/checkmark.svg
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/Button/ButtonLetter.vue
  src/renderer/components/Button/index.js
  src/renderer/components/Input/InputField.vue
  src/renderer/components/Input/InputGrid/InputGrid.vue
  src/renderer/components/Input/InputGrid/InputGridItem.vue
  src/renderer/components/Input/InputGrid/InputGridModal.vue
  src/renderer/components/ListDivided/ListDividedItem.vue
  src/renderer/components/Selection/SelectionAvatar.vue
  src/renderer/components/Selection/SelectionBackground.vue
  src/renderer/components/Selection/mixin-selection.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/profile.js
  src/renderer/pages/Profile/ProfileAll.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/styles/_general.css
Labels: Type: Feature

#961 refactor: update changelly widget
  config/index.js
  src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
Labels: Status: Needs Review, Type: Refactor

#964 fix: computed voted delegate name
  __tests__/unit/components/Wallet/WalletAddress.spec.js
  src/renderer/components/Wallet/WalletAddress.vue
Labels: Type: Bugfix

#956 refactor: multi-wallet endpoints
  __tests__/unit/__fixtures__/store/ledger.js
  __tests__/unit/components/Dashboard/DashboardTransactions.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/services/synchronizer/wallets.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  src/renderer/App.vue
  src/renderer/components/Dashboard/DashboardTransactions.vue
  src/renderer/services/client.js
  src/renderer/services/synchronizer.js
  src/renderer/services/synchronizer/ledger.js
  src/renderer/services/synchronizer/wallets.js
  src/renderer/store/modules/ledger.js
Labels: Priority: Critical, Status: Needs Review, Type: Refactor

#960 fix: address truncation in transaction table
  src/renderer/components/Transaction/TransactionTable.vue
  src/renderer/components/Wallet/WalletAddress.vue
Labels: Type: Bug

#970 fix: tooltip position of truncated address
  src/renderer/components/Wallet/WalletAddress.vue
Labels: Status: Needs Review, Type: Bugfix

#975 core: update @arkecosystem/client
  package.json
  yarn.lock
Labels: Status: Needs Review, Type: Task

#971 fix: load the stored data when installing new version
  package.json
  src/main/index.js
  src/main/menu.js
Labels: Status: Needs Review, Type: Bugfix

#688 feat: disable 'sendall' when user focuses amount
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
Labels: Bounty: Tier 4, Type: Refactor

#978 fix: display the right error message on the fee slider
  src/renderer/components/Input/InputCurrency.vue
Labels: Status: Needs Review, Type: Bugfix

#852 feat: support for tabular layout
  __tests__/unit/pages/Wallet/WalletAll.spec.js
  src/renderer/assets/svg/grid.svg
  src/renderer/assets/svg/tabular.svg
  src/renderer/components/Button/ButtonLayout.vue
  src/renderer/components/Button/index.js
  src/renderer/components/Wallet/WalletButtons/WalletButtonCreate.vue
  src/renderer/components/Wallet/WalletButtons/WalletButtonImport.vue
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/filters/truncate.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/store/modules/session.js
  src/renderer/styles/_table.css
Labels: Bounty: Tier 1, Type: Feature

#981 fix: do not hide part of the dropdowns of the profile edition
  src/renderer/pages/Profile/ProfileEdition.vue
Labels: Status: Needs Review, Type: Bugfix

#980 fix: the network settings was partially hidden when using a letter avatar
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
Labels: Status: Needs Review, Type: Bugfix

#984 improvement: new background for profile edition page
  src/renderer/assets/images/pages/profile-new/background-step-3-dark.png
  src/renderer/assets/images/pages/profile-new/background-step-3.png
  src/renderer/pages/Profile/ProfileEdition.vue
Labels: Status: Needs Review, Type: Feature

#979 fix: dashboard duplicate transaction refresh
  src/renderer/components/Dashboard/DashboardTransactions.vue
Labels: Status: Needs Review, Type: Bugfix

#986 fix: persist wallet layout
  __tests__/unit/pages/Wallet/WalletAll.spec.js
  src/renderer/models/profile.js
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/store/modules/session.js
Labels: Type: Bugfix, Type: Refactor

#987 chore: bump version
  package.json
Labels: Status: Needs Review, Type: Task

#996 improvement: make wallet heading name more visible in dark mode
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
  src/renderer/styles/_theme.css
  tailwind.js
Labels: Bounty: Tier 5

#1000 fix: correctly handle zero balance on wallet heading info
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
Labels: Bounty: Tier 5, Type: Bugfix

#1005 fix: conditional alignment of items
  src/renderer/components/ListDivided/ListDividedItem.vue
Labels: Bounty: Tier 5, Type: Bugfix

#982 feat/refactor: adjust announcement section to fit new design
  src/renderer/assets/svg/mark-all.svg
  src/renderer/components/Announcements/AnnouncementsPost.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Announcements.vue
Labels: Bounty: Tier 3, Status: Needs Changes, Type: Feature

#1003 refactor: new instructions section for wallet import/new and network overview page
  src/renderer/assets/images/pages/network-selection/background-dark.png
  src/renderer/assets/images/pages/network-selection/background.png
  src/renderer/assets/images/pages/network-selection/background.svg
  src/renderer/assets/images/pages/wallet-new/background-step-1-dark.png
  src/renderer/assets/images/pages/wallet-new/background-step-1.png
  src/renderer/assets/images/pages/wallet-new/background-step-2-dark.png
  src/renderer/assets/images/pages/wallet-new/background-step-2.png
  src/renderer/assets/images/pages/wallet-new/background-step-3-dark.png
  src/renderer/assets/images/pages/wallet-new/background-step-3.png
  src/renderer/assets/images/pages/wallet-new/background-step-5-dark.png
  src/renderer/assets/images/pages/wallet-new/background-step-5.png
  src/renderer/assets/images/pages/wallet-new/backup-wallet.svg
  src/renderer/assets/images/pages/wallet-new/choose-wallet.svg
  src/renderer/assets/images/pages/wallet-new/encrypt-wallet.svg
  src/renderer/assets/images/pages/wallet-new/import-wallet.svg
  src/renderer/assets/images/pages/wallet-new/protect-wallet.svg
  src/renderer/assets/images/pages/wallet-new/verify-passphrase.svg
  src/renderer/pages/NetworkOverview.vue
  src/renderer/pages/Wallet/WalletImport.vue
  src/renderer/pages/Wallet/WalletNew.vue
Labels: Status: Needs Review, Type: Refactor, review

#1006 refactor: new wallet selection styles and ui
  src/renderer/pages/Wallet/WalletNew.vue
  src/renderer/styles/_theme.css
Labels: Bounty: Tier 4

#1008 fix: do not shake when generating new wallets
  src/renderer/pages/Wallet/WalletNew.vue
Labels: Status: Needs Review, Type: Bugfix, review

#1010 refactor: success/error colors and delay on clipboard button tooltip
  src/renderer/components/Button/ButtonClipboard.vue
  src/renderer/styles/_tooltip.css
Labels: Bounty: Tier 4, Type: Refactor

#1012 feat: adapt the contact creation page to new style
  __tests__/unit/pages/Contact/ContactNew.spec.js
  src/renderer/assets/images/pages/contact-new/wallet.svg
  src/renderer/i18n/locales/en-US.js
  src/renderer/mixins/session.js
  src/renderer/pages/Contact/ContactNew.vue
Labels: Status: Needs Changes, Type: Feature

#995 refactor: remove unnecessary delegate api calls
  __tests__/unit/__fixtures__/store/delegate.js
  __tests__/unit/store/modules/delegate.spec.js
  __tests__/unit/store/modules/delegates.spec.js
  src/renderer/App.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/models/delegate.js
  src/renderer/services/client.js
  src/renderer/store/modules/delegate.js
Labels: Status: Needs Review, Type: Bugfix, Type: Refactor

#1014 feat/fix: validation on sign/verify modals & signed messages alignment
  src/renderer/components/Input/InputPassword.vue
  src/renderer/components/Passphrase/PassphraseInput.vue
  src/renderer/components/Wallet/WalletSignModal.vue
  src/renderer/components/Wallet/WalletSignVerify/WalletSignVerify.vue
  src/renderer/components/Wallet/WalletVerifyModal.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Profile/ProfileEdition.vue
Labels: Bounty: Tier 4, Status: Needs Changes, Type: Refactor

#991 feat: different style for names provided by the network & ui fixes
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/styles/_badges.css
  src/renderer/styles/style.css
Labels: Bounty: Tier 3, Status: Needs Changes, Type: Feature

#1015 feat: allow expanding and collapsing the wallet/contact sidebar
  src/renderer/assets/svg/collapse.svg
  src/renderer/assets/svg/expand.svg
  src/renderer/assets/svg/filter.svg
  src/renderer/assets/svg/sort.svg
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Dashboard.vue
  src/renderer/pages/Wallet/WalletShow.vue
Labels: Status: Needs Review, Type: Feature

#1016 fix: inconsistencies between network versions
  __tests__/unit/store/modules/peer.spec.js
  package.json
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/services/client.js
  src/renderer/store/modules/peer.js
  yarn.lock
Labels: Status: Needs Review, Type: Bugfix

#1017 fix: add forged to delegate model
  __tests__/unit/__fixtures__/store/delegate.js
  __tests__/unit/store/modules/delegate.spec.js
  src/renderer/models/delegate.js
Labels: Status: Needs Testcase, Type: Bugfix

#1002 feat: persistent sorting in wallet/contact table
  __tests__/unit/store/modules/session.spec.js
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/models/profile.js
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/store/modules/session.js
Labels: Status: Needs Review, Status: Needs Testcase, Type: Feature

#1019 refactor: replace the profile avatars with a new component `ProfileAvatar`
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/Button/ButtonLetter.vue
  src/renderer/components/Profile/ProfileAvatar.vue
  src/renderer/components/Profile/ProfileRemovalConfirmation.vue
  src/renderer/components/Profile/index.js
  src/renderer/pages/Profile/ProfileAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/styles/_avatars.css
  tailwind.js
Labels: Status: Needs Review, Type: Bugfix, Type: Refactor

#1031 fix: importing of profile avatar selection modal component
  src/renderer/components/Input/InputGrid/InputGridModal.vue
Labels: Status: Needs Review, Type: Bugfix

#1007 feat: adapt the contacts page to new design
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Contact/ContactAll.vue
Labels: Status: Needs Review, Type: Feature

#1025 misc: invert identicon hover behaviour
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
Labels: Bounty: Tier 5, Type: Refactor

#1021 feat: add sidebar animation
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/i18n/locales/en-US.js
Labels: Bounty: Tier 3, Type: Feature

#1033 fix: errors during and after removing profiles
  __tests__/unit/components/Profile/ProfileRemovalConfirmation.spec.js
  src/renderer/components/Input/InputGrid/InputGridItem.vue
  src/renderer/components/Profile/ProfileRemovalConfirmation.vue
  src/renderer/pages/Profile/ProfileAll.vue
  src/renderer/store/modules/session.js
Labels: Status: Needs Review, Type: Bugfix

#1023 feat: loading screen when broadcasting to many peers
  src/renderer/components/Modal/ModalLoader.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/services/client.js
Labels: Status: Needs Review, Type: Feature

#994 fix: allow selecting the balance on the wallet page heading
  __tests__/unit/components/Wallet/WalletHeadingInfo.spec.js
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
  src/renderer/components/Wallet/WalletIdenticon.vue
  src/renderer/pages/Contact/ContactAll.vue
Labels: Status: Needs Review, Type: Bugfix

#1032 fix: show the "Unvote" action at the bottom of the delegate tab when using the Ledger
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
Labels: Status: Needs Review, Type: Bugfix

#1038 fix: broadcasting modal not closing
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
Labels: Bounty: Tier 4, Type: Bugfix

#1036 fix: peer status inconsistent
  package.json
  yarn.lock
Labels: Status: Needs Review, Type: Bugfix

#1022 feat: use network static fees as max
  __tests__/unit/__fixtures__/services/client.js
  __tests__/unit/components/Input/InputFee.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  src/renderer/components/Input/InputFee.vue
  src/renderer/services/client.js
  src/renderer/store/modules/peer.js
  src/renderer/store/modules/transaction.js
Labels: Status: Needs Review, Type: Feature

#1009 fix: pasting or writing numbers with colon (",") on the send transfer inputs
  __tests__/unit/components/Input/InputCurrency.spec.js
  src/renderer/components/Input/InputCurrency.vue
Labels: Status: Needs Review, Type: Bugfix

#1028 refactor: increase ui/ux on qr code scanner
  src/renderer/components/Modal/ModalQrCodeScanner.vue
  src/renderer/components/Modal/ModalWindow.vue
Labels: Bounty: Tier 3, Status: Needs Review, Type: Refactor

#967 feat: db migration system
  __tests__/unit/store/plugins/vuex-persist-migrations.spec.js
  src/renderer/store/index.js
  src/renderer/store/migrations/2.2.0 - initial migration.js
  src/renderer/store/modules/app.js
  src/renderer/store/plugins/vuex-persist-migrations.js
Labels: Status: Needs Review, Type: Feature

#1034 refactor: overall latest transactions per profile
  __tests__/unit/services/client.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  src/renderer/components/Dashboard/DashboardTransactions.vue
  src/renderer/components/Transaction/TransactionAmount.vue
  src/renderer/pages/Dashboard.vue
  src/renderer/services/client.js
  src/renderer/store/modules/transaction.js
Labels: Bounty: Tier 4
