Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-04, with the labels that each got.

#1164 fix: improve validation for epoch format
  src/renderer/components/Network/NetworkModal.vue
Labels: Complexity: Low, Type: Bugfix

#1160 chore: upgrade Vue and other dependencies
  .circleci/config.yml
  __tests__/e2e.jest.conf.js
  __tests__/unit.jest.conf.js
  package.json
  yarn.lock
Labels: Complexity: Undetermined, Type: Task

#1120 feat: allow using a pool of background workers
  .electron-vue/build.js
  .electron-vue/webpack.renderer.config.js
  __tests__/unit/services/bip38.spec.js
  __tests__/unit/store/modules/delegate.spec.js
  package.json
  src/renderer/components/Transaction/TransactionForm/mixin-on-submit.js
  src/renderer/components/Wallet/WalletSignModal.vue
  src/renderer/pages/Wallet/mixin-on-create.js
  src/renderer/services/background-http-client.js
  src/renderer/services/bip38.js
  src/renderer/services/client.js
  src/renderer/services/crypto-compare.js
  src/renderer/services/http.js
  src/renderer/services/release.js
  src/renderer/services/wallet.js
  src/renderer/services/worker.js
  src/renderer/store/modules/peer.js
  src/renderer/workers/bip38-worker.js
  src/renderer/workers/bip38.js
  src/renderer/workers/http.js
  yarn.lock
Labels: Complexity: High, Type: Feature, Type: Refactor

#1165 feat(plugins): include audio permission
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Feature

#1177 chore: git-ignore `plugins` folder
  .gitignore
Labels: Complexity: Low, Type: Task

#1174 fix: `InputSelect` dropdowns
  src/renderer/components/Input/InputSelect.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdownHandler.vue
Labels: Complexity: Medium, Type: Bugfix

#1172 fix: other network fees when higher than ARK static fees
  __tests__/unit/services/client.spec.js
  src/renderer/services/client.js
Labels: Complexity: Low, Status: Needs Changes, Type: Bugfix

#1176 feat(plugins): ask for confirmation to enable plugins
  src/renderer/components/Plugin/PluginEnableConfirmation.vue
  src/renderer/components/Plugin/PluginTable.vue
  src/renderer/components/Plugin/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Plugins.vue
Labels: Complexity: Medium, Type: Feature

#1175 fix: main sidebar menus (settings and peers/networks)
  src/renderer/directives/click-outside.js
Labels: Complexity: Low, Type: Bugfix

#1184 fix: the wallet selection dropdown and the wallet sidebar filters
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdownItem.vue
  src/renderer/components/Menu/MenuNavigation/MenuNavigationItem.vue
  src/renderer/components/Menu/MenuOptions/MenuOptionsItem.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue
  src/renderer/directives/click-outside.js
Labels: Complexity: Low, Type: Bugfix

#1170 fix(plugins): define the context of all hooks
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Bugfix

#1185 fix: do not fail when navigating to other page while loading transactions
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue
Labels: Complexity: Low, Type: Bugfix

#1179 feat(plugins): allow adding new tabs to the wallet page
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/services/plugin-manager.js
  src/renderer/store/modules/plugin.js
Labels: Complexity: Medium, Type: Feature

#1190 fix: do not use getStruct in ledger transactions
  src/renderer/services/transaction.js
Labels: Complexity: Low, Type: Bugfix

#1173 fix: add network modal validation
  __tests__/unit/__utils__/validation.js
  __tests__/unit/components/Network/NetworkModal.spec.js
  src/renderer/components/Input/InputText.vue
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/store/modules/network.js
Labels: Complexity: Low, Status: In Progress, Type: Bugfix

#1195 feat: ensure plugins directory exists
  package.json
  src/renderer/services/plugin-manager.js
  yarn.lock
Labels: Complexity: Low, Type: Feature

#1196 chore: remove mario from contributors
  README.md
  package.json
Labels: Complexity: Low, Type: Task

#1198 fix(plugins): avatar plugins not working correctly
  src/renderer/App.vue
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/Input/InputGrid/InputGridItem.vue
  src/renderer/components/Profile/ProfileAvatar.vue
  src/renderer/components/Selection/mixin-selection-image.js
  src/renderer/pages/Profile/ProfileNew.vue
Labels: Complexity: Undetermined, Type: Bugfix

#1202 fix: align the add profile placeholder
  src/renderer/pages/Profile/ProfileAll.vue
Labels: Complexity: Low, Type: Bugfix

#1203 fix: days on the X axis of the market chart
  src/renderer/components/MarketChart/MarketChart.vue
Labels: Complexity: Low, Type: Bugfix

#1205 fix: profile model validation to use letter avatar
  src/renderer/models/profile.js
Labels: Complexity: Low, Type: Bugfix

#1209 feat: remove productivity and missed blocks from delegates
  __tests__/unit/__fixtures__/services/client.js
  __tests__/unit/__fixtures__/store/delegate.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/store/modules/delegate.spec.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/models/delegate.js
  src/renderer/services/client.js
  src/renderer/store/modules/delegate.js
Labels: Complexity: Medium, Type: Feature

#1211 feat: display more information on the modals for sending transactions
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirm.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmSecondSignature.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmTransfer.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmVote.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
Labels: Complexity: Medium, Type: Feature

#1206 fix: fetch fees only if the network is available
  src/renderer/store/modules/network.js
Labels: Complexity: Low, Type: Bugfix

#1210 fix: network model validation to accept numbers in slip44
  src/renderer/models/network.js
Labels: Complexity: Low, Type: Bugfix

#1214 fix: do not break letter avatars when switching languages
  src/renderer/components/Input/InputGrid/InputGrid.vue
  src/renderer/components/Input/InputGrid/InputGridItem.vue
  src/renderer/components/Selection/SelectionAvatar.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
Labels: Complexity: Low, Type: Bugfix

#1213 fix: value of letter avatar on profile creation
  src/renderer/components/Profile/ProfileAvatar.vue
  src/renderer/models/profile.js
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/store/migrations/2.4.0 - fix letter avatars.js
Labels: Complexity: Low, Type: Bugfix

#1208 feat: include the new icon for disconnecting from custom peer
  src/renderer/assets/svg/disconnect.svg
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
Labels: Complexity: Low, Type: Feature

#1215 fix: do not allow that the last profile is removed
  src/renderer/pages/Profile/ProfileAll.vue
Labels: Complexity: Low, Type: Bugfix

#1216 fix: ledger cold wallet send
  src/renderer/services/synchronizer/wallets.js
Labels: Complexity: Low, Type: Bugfix
