Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-10, with the labels that each got.

#1437 feat(aip-11): v2 transactions with nonces
  package.json
  src/renderer/App.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/models/network.js
  src/renderer/services/client.js
  src/renderer/services/synchronizer.js
  src/renderer/store/modules/network.js
  src/renderer/store/modules/peer.js
  yarn.lock
Labels: Complexity: Medium, Status: Needs Testcase, Type: Feature

#1509 ci: update workflow triggers
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: Complexity: Low

#1510 fix: provide default port when adding custom network
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/services/client.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1508 refactor: custom network during onboarding
  src/renderer/components/Selection/SelectionNetwork.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/services/client.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Refactor

#954 feat: implement auto updater
  __tests__/unit/components/ProgressBar/ProgressBar.spec.js
  __tests__/unit/services/release.spec.js
  app-update.yml
  package.json
  src/main/index.js
  src/main/updater.js
  src/renderer/App.vue
  src/renderer/assets/images/pages/updater/computer-dark.svg
  src/renderer/assets/images/pages/updater/computer-light.svg
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuImportantNotification.vue
  src/renderer/components/App/AppUpdater.vue
  src/renderer/components/App/index.js
  src/renderer/components/Modal/ModalWindow.vue
  src/renderer/components/ProgressBar/ProgressBar.vue
  src/renderer/components/ProgressBar/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/services/release.js
  src/renderer/store/index.js
  src/renderer/store/modules/app.js
  src/renderer/store/modules/updater.js
  yarn.lock
Labels: Status: In Progress, Status: Needs Changes, Type: Feature

#1505 fix: get version of custom peer
  __tests__/unit/store/modules/peer.spec.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/store/modules/peer.js
Labels: Bounty: Tier 4, Status: Member Approved

#1522 ci: set shell to `cmd` on windows build steps
  .github/workflows/test.yml
Labels: Complexity: Low, Status: Contributor Approved, Type: Task

#1527 refactor(plugins): support ark uri scheme in webframes
  __tests__/unit/components/utils/WebFrame.spec.js
  src/renderer/components/utils/WebFrame.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Refactor

#1500 refactor(plugins): add destroy method and binary websocket support
  __tests__/unit/services/plugin-manager/sandbox/websocket-sandbox.spec.js
  src/renderer/services/plugin-manager/sandbox/websocket-sandbox.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Status: Needs Review, Type: Refactor

#1516 fix: return copy of wallet sidebar filters from state
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue
  src/renderer/store/modules/session.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1494 deps: update vue-good-table
  __tests__/unit/components/utils/merge-table-transactions.spec.js
  __tests__/unit/pages/Profile/ProfileAll.spec.js
  __tests__/unit/services/client.spec.js
  package.json
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirm.vue
  src/renderer/components/Transaction/TransactionTable.vue
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue
  src/renderer/components/utils/TableWrapper.js
  src/renderer/components/utils/merge-table-transactions.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/services/client.js
  src/renderer/store/modules/transaction.js
  src/renderer/styles/_table.css
  yarn.lock
Labels: Bounty: Tier 4, Complexity: Medium, Status: Member Approved
