Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-11, with the labels that each got.

#1538 ci: add dependency caching
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: Complexity: Low, Status: Needs Review

#1540 fix: new transactions notice
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue
Labels: Complexity: Low, Type: Bugfix

#1536 fix(plugins): vue package in production
  __tests__/unit/services/plugin-manager/plugin-sandbox.spec.js
  __tests__/unit/services/plugin-manager/setup/components-setup.spec.js
  src/renderer/services/plugin-manager/plugin-sandbox.js
  src/renderer/services/plugin-manager/plugin-setup.js
  src/renderer/services/plugin-manager/setup/components-setup.js
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#1529 fix: parse uri
  src/main/index.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1533 feat: specify sender wallet and nethash in uri
  __tests__/unit/services/client.spec.js
  __tests__/unit/services/uri-handler.spec.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/services/client.js
  src/renderer/services/uri-handler.js
Labels: Bounty: Tier 4, Complexity: Medium, Status: Member Approved, Type: Feature

#1543 fix: render chart when expanding and fix mutation error
  __tests__/unit/components/MarketChart/MarketChart.spec.js
  __tests__/unit/store/modules/session.spec.js
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/pages/Dashboard.vue
  src/renderer/store/modules/session.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Status: Needs Testcase, Type: Bugfix

#1544 fix: left aligned sortable table headers
  src/renderer/styles/_table.css
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1548 feat(plugins): global storage
  __tests__/unit/services/plugin-manager/sandbox/storage-sandbox.spec.js
  src/renderer/services/plugin-manager/sandbox/storage-sandbox.js
  src/renderer/store/modules/plugin.js
Labels: Bounty: Tier 4, Complexity: Medium, Status: Member Approved, Type: Feature

#1547 fix(plugins): fix context of methods
  __tests__/unit/services/plugin-manager/component/create-component.spec.js
  src/renderer/services/plugin-manager/component/create-component.js
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#1549 chore(workflow): run lint after unit tests
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: Complexity: Low, Type: Task

#1550 docs: stop translations
  README.md
Labels: Complexity: Low, Type: Documentation

#1465 misc: add translate for pt-br
  config/index.js
  src/renderer/i18n/date-time-formats.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/pt-BR.js
Labels: Bounty: Tier 3, Complexity: Undetermined, Status: Member Approved

#1519 misc: it-IT update
  src/renderer/i18n/locales/it-IT.js
Labels: Bounty: Tier 6, Complexity: Low, Status: Member Approved

#1558 chore: update plugin menu icons
  src/renderer/assets/svg/manage-plugins.svg
  src/renderer/assets/svg/my-plugins.svg
  src/renderer/assets/svg/plugins.svg
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
Labels: Complexity: Medium, Type: Task

#1560 refactor: load initial file with resources
  __tests__/unit/services/plugin-manager/plugin-sandbox.spec.js
  src/renderer/services/plugin-manager/plugin-sandbox.js
  src/renderer/services/plugin-manager/plugin-setup.js
Labels: Complexity: Low, Type: Refactor

#1555 refactor: menu consistencies
  src/renderer/components/App/AppSidemenu/AppSidemenuPlugins.vue
  src/renderer/components/Menu/MenuOptions/MenuOptions.vue
Labels: Complexity: Low, Type: Refactor

#1563 fix: prevent href breakout
  __tests__/unit/services/plugin-manager/component/create-component.spec.js
  src/renderer/services/plugin-manager/component/get-context.js
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix
