Repository ArkEcosystem/desktop-wallet, pull requests merged in 2019-08, with the labels that each got.

#1351 chore(deps): use bip38@2.0.3 to support electron v4 and later
  package.json
  yarn.lock
Labels: Complexity: Low, Type: Task

#1352 chore(deps): update eslint dependencies
  .eslintignore
  __tests__/e2e/app.spec.js
  __tests__/unit.jest.conf.js
  __tests__/unit/__utils__/validation.js
  __tests__/unit/components/Button/ButtonGeneric.spec.js
  __tests__/unit/components/ListDivided.spec.js
  __tests__/unit/components/Modal/ModalWindow.spec.js
  __tests__/unit/components/Passphrase/PassphraseVerification.spec.js
  __tests__/unit/components/Profile/ProfileRemovalConfirmation.spec.js
  __tests__/unit/components/Transaction/TransactionModal.spec.js
  __tests__/unit/components/Transaction/TransactionShow.spec.js
  __tests__/unit/components/Wallet/WalletDelegates.spec.js
  __tests__/unit/components/Wallet/WalletHeading.spec.js
  __tests__/unit/components/Wallet/WalletTransactions.spec.js
  __tests__/unit/pages/Profile/ProfileAll.spec.js
  __tests__/unit/pages/Wallet/WalletAll.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/store/modules/announcements.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  __tests__/unit/store/plugins/vuex-persist-migrations.spec.js
  config/index.js
  package.json
  src/renderer/components/Input/InputAddress.vue
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Menu/MenuOptions/MenuOptions.vue
  src/renderer/components/Modal/ModalExportWallets.vue
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/components/Plugin/PluginTable.vue
  src/renderer/components/Search/SearchFilter/SearchFilter.vue
  src/renderer/components/Selection/mixin-selection-image.js
  src/renderer/components/Wallet/WalletAddress.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/services/client.js
  src/renderer/services/plugin-manager.js
  src/renderer/services/uri-handler.js
  src/renderer/services/wallet.js
  src/renderer/store/modules/announcements.js
  src/renderer/store/modules/ledger.js
  src/renderer/store/modules/peer.js
  yarn.lock
Labels: Complexity: High, Type: Task

#1353 chore(deps): update all vue dependencies
  package.json
  yarn.lock
Labels: Complexity: Medium, Type: Task

#1354 chore(deps): update build and file dependencies
  package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#1346 feat: add shortcut and menu item to open settings
  src/main/menu.js
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
Labels: Complexity: Low, Type: Feature

#1349 feat: allow key-value storage for plugins
  src/renderer/services/plugin-manager.js
  src/renderer/store/modules/plugin.js
Labels: Complexity: Medium, Type: Feature

#1359 fix: Bugs related to amount and fee transaction inputs
  src/renderer/components/Input/InputCurrency.vue
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#1358 refactor: check if username exists in delegate registration form
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/services/wallet.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Refactor

#1361 fix: update wallet header on ledger disconnect
  src/renderer/components/Wallet/WalletHeading/WalletHeading.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1368 fix: stop fee update using api version as timeout
  src/renderer/store/modules/network.js
Labels: Complexity: Low, Type: Bugfix

#1362 feat: plugin system improvements
  config/index.js
  src/renderer/services/plugin-manager.js
  yarn.lock
Labels: Complexity: Low, Type: Feature

#1360 feat: font awesome support in plugins
  package.json
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/font-awesome-sandbox.js
  yarn.lock
Labels: Complexity: Low, Type: Feature

#1363 feat: use last fee option
  __tests__/unit/components/Input/InputFee.spec.js
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/profile.js
  src/renderer/store/modules/session.js
Labels: Complexity: Medium, Status: In Progress, Status: Member Approved

#1371 feat: do not create wallet if fails encryption of password
  src/renderer/pages/Wallet/mixin-on-create.js
Labels: Complexity: Low, Type: Feature

#1370 fix: ledger rejecting transaction
  src/renderer/services/ledger-service.js
  src/renderer/store/modules/ledger.js
Labels: Complexity: Low, Type: Bugfix

#1357 feat: allow plugin access to current peer
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Feature

#1372 feat: allow use of the loader spinner in plugins
  src/renderer/services/plugin-manager.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Feature

#1369 fix: update ModalQrCodeScanner component
  README.md
  src/renderer/components/Modal/ModalQrCodeScanner.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1376 fix: touch model after scanning passphrase and fix paper wallet parsing
  __tests__/unit/mixins/qr.spec.js
  src/renderer/components/Input/InputAddress.vue
  src/renderer/components/Passphrase/PassphraseInput.vue
  src/renderer/mixins/qr.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1378 fix: add gradients and scrolling to intro pages
  src/renderer/components/App/AppIntro/AppIntro.vue
  src/renderer/components/App/AppIntro/AppIntroScreen.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/styles/_theme.css
  tailwind.js
Labels: Bounty: Tier 4, Complexity: Medium, Status: Member Approved, Type: Bugfix

#1338 feat: automate deployment on Github with Travis
  .travis.yml
  package.json
Labels: Complexity: Low, Type: Feature

#1379 misc: italian language update
  src/renderer/i18n/locales/it-IT.js
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved

#1381 refactor: use spread operator instead of lodash's clone before updating profile
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingMenuLedger.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.vue
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Dashboard.vue
  src/renderer/pages/Plugins.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/services/synchronizer/wallets.js
Labels: Bounty: Tier 4, Complexity: Medium, Status: Member Approved, Type: Refactor

#1382 refactor: improve enable plugin workflow
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuPluginConfirmation.vue
  src/renderer/components/Plugin/PluginEnableConfirmation.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Medium, Type: Refactor

#1380 feat: table wrapper component for plugins
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/wallet-components.js
Labels: Complexity: Low, Type: Feature

#1365 refactor: improve loading components within plugin system
  config/index.js
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Refactor

#1387 feat: allow plugins to go to routes
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Status: Member Approved, Type: Feature

#1391 fix: exporting wallets on mainnet not working due to multipliedBy being undefined
  src/renderer/plugins/bignumber.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1388 misc: it-IT update - follows #1382
  src/renderer/i18n/locales/it-IT.js
Labels: Bounty: Tier 6, Complexity: Low, Status: Member Approved

#1385 feat: iframe to wallet one-way communication
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Status: Member Approved, Type: Feature

#1392 fix: truncate wallet name in grid view, scroll on InputText and reload wallets after rename
  src/renderer/components/Input/InputText.vue
  src/renderer/components/Wallet/WalletGrid.vue
  src/renderer/pages/Wallet/WalletAll.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1396 refactor(plugins): implement custom iframe component
  __tests__/unit/components/utils/WebFrame.spec.js
  src/renderer/components/utils/WebFrame.js
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/wallet-components.js
Labels: Complexity: Medium, Type: Refactor

#1400 fix: webframe same origin
  __tests__/unit/components/utils/WebFrame.spec.js
  src/renderer/components/utils/WebFrame.js
Labels: Complexity: Low, Type: Bugfix

#1386 refactor: improve passphrase detection in vendorfield
  __tests__/unit/__mocks__/@/services/wallet.js
  __tests__/unit/components/Input/InputText.spec.js
  __tests__/unit/services/wallet.spec.js
  src/renderer/components/Input/InputField.vue
  src/renderer/components/Input/InputText.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Refactor

#1401 fix: plugin component events
  config/index.js
  config/plugin-validation.json
  src/renderer/services/plugin-manager.js
Labels: Complexity: High, Type: Bugfix

#1403 chore: correct typo Applying
  src/renderer/store/plugins/vuex-persist-migrations.js
Labels: Complexity: Low, Type: Task

#1404 fix: market chart migration
  src/renderer/store/migrations/2.5.2 - add marketChartOptions to profile.js
Labels: Complexity: High, Type: Bugfix

#1405 fix: design height on large pages
  src/renderer/App.vue
Labels: Complexity: Low, Type: Bugfix

#1407 fix: details modal not showing to recently registered delegates
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletSelectDelegate.vue
Labels: Complexity: Low, Type: Bugfix

#1408 fix: check unconfirmed votes when updating transactions
  __tests__/unit/__fixtures__/store/profile.js
  __tests__/unit/components/Input/InputFee.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/services/synchronizer/wallets.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/services/client.js
  src/renderer/services/synchronizer.js
  src/renderer/services/synchronizer/wallets.js
  src/renderer/store/modules/transaction.js
Labels: Complexity: Low, Type: Bugfix

#1406 fix: webframe redirects
  __tests__/unit.jest.conf.js
  __tests__/unit/__utils__/setup.js
  __tests__/unit/components/utils/WebFrame.spec.js
  src/renderer/components/utils/WebFrame.js
  src/renderer/services/plugin-manager.js
  static/webview-preload.js
Labels: Complexity: Low, Type: Bugfix

#1409 fix: new delegate registration transaction message
  src/renderer/services/synchronizer/wallets.js
Labels: Complexity: Low, Type: Bugfix

#1414 fix: voting explanation delegate count
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Bugfix

#1413 fix: screenshot protection
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
Labels: Complexity: Low, Type: Bugfix

#1416 fix: increase transaction modal width
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionModal.vue
Labels: Complexity: Low, Type: Bugfix

#1422 fix: add additional blocked events
  config/plugin-validation.json
Labels: Complexity: Low, Type: Bugfix

#1417 chore: bump version to 2.6.0
  package.json
  yarn-error.log
Labels: Complexity: Undetermined, Type: Task

#1428 fix: allow the Changelly widget to open popups
  src/renderer/components/Wallet/WalletExchange/WalletExchange.vue
Labels: Complexity: Low, Type: Bugfix

#1426 fix: bridgechain peer issues
  .electron-vue/webpack.renderer.config.js
  __tests__/unit/store/modules/peer.spec.js
  package.json
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/store/modules/peer.js
  yarn.lock
Labels: Complexity: Low, Type: Bugfix

#1427 fix: development mode message in production
  .electron-vue/webpack.renderer.config.js
  .gitignore
  package.json
  yarn-error.log
Labels: Complexity: Low, Type: Bugfix

#1410 feat: show if voted delegate is not active in wallet table
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/it-IT.js
Labels: Bounty: Tier 3, Complexity: Low, Status: Member Approved, Type: Feature

#1394 refactor: get wallet names in wallet selection / input address
  src/renderer/components/Input/InputAddress.vue
  src/renderer/components/Wallet/WalletSelection.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Refactor

#1430 fix: port used from github peer list
  package.json
  yarn.lock
Labels: Complexity: Low, Type: Bugfix
