Repository ArkEcosystem/desktop-wallet, pull requests merged in 2020-07, with the labels that each got.

#2309 test: mock date globally
  jest.setup.js
  package.json
  src/domains/plugin/components/Comments/Comments.test.tsx
  src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap
  src/domains/plugin/components/Comments/components/Reply/Reply.test.tsx
  src/domains/plugin/components/Comments/components/Reply/__snapshots__/Reply.test.tsx.snap
  src/domains/plugin/components/Comments/utils.test.ts
  src/domains/plugin/pages/PluginDetails/PluginDetails.test.tsx
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2312 refactor: add LayoutControls component
  src/app/assets/svg/grid.svg
  src/app/assets/svg/list.svg
  src/app/components/LayoutControls/LayoutControls.test.tsx
  src/app/components/LayoutControls/LayoutControls.tsx
  src/app/components/LayoutControls/__snapshots__/LayoutControls.test.tsx.snap
  src/app/components/LayoutControls/index.ts
  src/domains/dashboard/components/Wallets/Wallets.test.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/WalletsControls.test.tsx
  src/domains/dashboard/components/WalletsControls/WalletsControls.tsx
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugin/components/PluginManagerControls/PluginManagerControls.test.tsx
  src/domains/plugin/components/PluginManagerControls/PluginManagerControls.tsx
  src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2308 chore: add theme selection to stories
  .storybook/main.js
  .storybook/preview.js
  package.json
  yarn.lock
Labels: Complexity: Low, Type: Feature

#2305 chore: fix select ui in transaction send form
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.styles.ts
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2313 chore: add placeholder props for the `HeaderSearchBar` component
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.test.tsx
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2311 feat: add TimeAgo component
  src/__snapshots__/index.test.ts.snap
  src/app/i18n/common/i18n.ts
  src/domains/plugin/components/Comments/Comments.stories.tsx
  src/domains/plugin/components/Comments/Comments.tsx
  src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap
  src/domains/plugin/components/Comments/components/Reply/Reply.tsx
  src/domains/plugin/components/Comments/components/Reply/__snapshots__/Reply.test.tsx.snap
  src/domains/plugin/components/Comments/components/TimeAgo/TimeAgo.test.tsx
  src/domains/plugin/components/Comments/components/TimeAgo/TimeAgo.tsx
  src/domains/plugin/components/Comments/components/TimeAgo/__snapshots__/TimeAgo.test.tsx.snap
  src/domains/plugin/components/Comments/components/TimeAgo/index.ts
  src/domains/plugin/components/Comments/utils.test.ts
  src/domains/plugin/components/Comments/utils.ts
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2304 chore: reference i18n keys in tests instead of hardcoded values
  src/__snapshots__/index.test.ts.snap
  src/app/components/Clipboard/Clipboard.test.tsx
  src/app/components/Collapse/CollapseToggleButton.test.tsx
  src/app/components/Collapse/CollapseToggleButton.tsx
  src/app/i18n/common/i18n.ts
Labels: Complexity: Medium, Type: Task

#2316 chore: update Platform SDK
  package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2317 refactor: update `Avatar` component to use svg
  src/app/components/Avatar/Avatar.stories.tsx
  src/app/components/Avatar/Avatar.test.tsx
  src/app/components/Avatar/Avatar.tsx
  src/app/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap
  src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap
  src/domains/vote/components/DelegateListItem/__snapshots__/DelegateListItem.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap
  src/domains/wallet/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2307 feat: add votes page
  src/__snapshots__/index.test.ts.snap
  src/app/assets/images/index.ts
  src/app/components/SelectAsset/SelectAsset.tsx
  src/app/components/SelectAsset/__snapshots__/SelectAsset.test.tsx.snap
  src/app/i18n/helpers/index.ts
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/vote/components/AddressList/AddressList.tsx
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/AddressListItem/AddressListItem.stories.tsx
  src/domains/vote/components/AddressListItem/AddressListItem.test.tsx
  src/domains/vote/components/AddressListItem/AddressListItem.tsx
  src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap
  src/domains/vote/components/AddressListItem/index.ts
  src/domains/vote/components/DelegateList/DelegateList.tsx
  src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap
  src/domains/vote/components/DelegateListItem/DelegateListItem.stories.tsx
  src/domains/vote/components/DelegateListItem/DelegateListItem.test.tsx
  src/domains/vote/components/DelegateListItem/DelegateListItem.tsx
  src/domains/vote/components/DelegateListItem/__snapshots__/DelegateListItem.test.tsx.snap
  src/domains/vote/components/DelegateListItem/index.ts
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
  src/domains/vote/data.ts
  src/domains/vote/i18n.ts
  src/domains/vote/images/index.ts
  src/domains/vote/images/placeholder-votes.svg
  src/domains/vote/pages/Votes/Votes.stories.tsx
  src/domains/vote/pages/Votes/Votes.test.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/vote/pages/Votes/index.ts
Labels: Complexity: Medium, Type: Feature

#2318 refactor: styleguide rules on `TransactionSend` page
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx
  src/domains/transaction/components/TotalAmountBox/__snapshots__/TotalAmountBox.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.stories.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2323 refactor: styleguide rules on `ResignRegistration`
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2321 refactor: styleguide rules on `SendVoteTransaction` page
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.stories.tsx
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2320 refactor: styleguide rules on `SendIPFSTransaction` page
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.stories.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2299 fix: ui tweaks plugin details
  src/app/assets/svg/index.ts
  src/app/assets/svg/report.svg
  src/app/assets/svg/verified.svg
  src/domains/plugin/components/Comments/Comments.tsx
  src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap
  src/domains/plugin/components/PluginHeader/PluginHeader.tsx
  src/domains/plugin/components/PluginHeader/__snapshots__/PluginHeader.test.tsx.snap
  src/domains/plugin/components/PluginHeader/components/PluginSpecs/PluginSpecs.tsx
  src/domains/plugin/components/PluginHeader/components/PluginSpecs/__snapshots__/PluginSpecs.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/PluginDetails.tsx
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#2326 refactor: styleguide rules on `Registration`
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2314 fix: ark uri scheme
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
Labels: Complexity: Low, Type: Bugfix

#2322 refactor: export AvatarWrapper
  package.json
  src/app/components/Avatar/Avatar.tsx
  src/app/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  src/domains/profile/components/ProfileCard/ProfileCard.stories.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.test.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.stories.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap
  src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap
  src/domains/vote/components/DelegateListItem/__snapshots__/DelegateListItem.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap
  src/domains/wallet/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  yarn.lock
Labels: Complexity: High

#2332 chore: remove `NavigationHeader` component
  src/app/components/NavigationHeader/NavigationHeader.stories.tsx
  src/app/components/NavigationHeader/NavigationHeader.test.tsx
  src/app/components/NavigationHeader/NavigationHeader.tsx
  src/app/components/NavigationHeader/__snapshots__/NavigationHeader.test.tsx.snap
  src/app/components/NavigationHeader/index.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#2330 refactor: breadcrumbs component ui adjustments
  src/app/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/app/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/app/components/Divider/Divider.styles.ts
  src/app/components/Divider/Divider.tsx
  src/app/components/Divider/__snapshots__/Divider.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2329 refactor: table component ui adjustments
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Table/Table.tsx
  src/app/components/Table/__snapshots__/Table.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap
  src/domains/plugin/components/BlacklistPlugins/__snapshots__/BlacklistPlugins.test.tsx.snap
  src/domains/plugin/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2327 refactor: plugin manager style updates
  src/app/assets/svg/dash.svg
  src/app/assets/svg/file.svg
  src/app/assets/svg/index.ts
  src/app/components/LayoutControls/LayoutControls.tsx
  src/app/components/LayoutControls/__snapshots__/LayoutControls.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/WalletsControls.tsx
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/components/PluginListItem/PluginListItem.stories.tsx
  src/domains/plugin/components/PluginListItem/PluginListItem.tsx
  src/domains/plugin/components/PluginListItem/__snapshots__/PluginListItem.test.tsx.snap
  src/domains/plugin/components/PluginManagerControls/PluginManagerControls.tsx
  src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/images/plugin-manager-home-banner.svg
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/styles/base.css
Labels: Complexity: Undetermined, Type: Refactor

#2328 feat: welcome -> create profile routing
  cypress.json
  cypress/integration/welcome-routing.spec.js
  package.json
  src/app/components/Card/Card.test.tsx
  src/app/components/Card/Card.tsx
  src/app/components/Card/__snapshots__/Card.test.tsx.snap
  src/app/components/Card/__snapshots__/CardControl.test.tsx.snap
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/network/components/NetworkCard/__snapshots__/NetworkCard.test.tsx.snap
  src/domains/profile/components/ProfileCard/ProfileCard.stories.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/Welcome/Welcome.test.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/profile/routing.ts
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  yarn.lock
Labels: Complexity: High, Type: Feature

#2336 refactor: styleguide rules on help pages
  src/app/components/SearchBar/SearchBarOptions/SearchBarOptions.tsx
  src/app/components/SearchBar/SearchBarOptions/__snapshots__/SearchBarOptions.test.tsx.snap
  src/domains/help/components/ContactUs/ContactUs.tsx
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2338 refactor: registration style guide updates
  src/__snapshots__/index.test.ts.snap
  src/domains/transaction/components/LinkCollection/LinkCollection.test.tsx
  src/domains/transaction/components/LinkCollection/LinkCollection.tsx
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/LinkList/LinkList.tsx
  src/domains/transaction/i18n.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2337 refactor: modal ux
  src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap
  src/domains/plugin/components/BlacklistPlugins/__snapshots__/BlacklistPlugins.test.tsx.snap
  src/domains/plugin/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap
  src/domains/plugin/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
  src/domains/profile/components/ProfileCreated/__snapshots__/ProfileCreated.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/__snapshots__/RepositoryModal.test.tsx.snap
  src/domains/setting/components/AdvancedMode/__snapshots__/AdvancedMode.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
  src/domains/wallet/components/LedgerWallet/__snapshots__/LedgerWallet.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/components/VerifyMessageStatus/__snapshots__/VerifyMessageStatus.test.tsx.snap
  src/domains/wallet/components/WalletUpdate/__snapshots__/WalletUpdate.test.tsx.snap
Labels: Complexity: High

#2339 refactor: apply ui guidelines on `ProfileCreated` modal
  src/domains/profile/components/ProfileCreated/ProfileCreated.tsx
  src/domains/profile/components/ProfileCreated/__snapshots__/ProfileCreated.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2341 refactor: style guide padding on registration pages
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2343 refactor: votes page ui adjustments
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/AddressListItem/AddressListItem.tsx
  src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap
  src/domains/vote/components/DelegateList/DelegateList.tsx
  src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap
  src/domains/vote/components/DelegateListItem/DelegateListItem.tsx
  src/domains/vote/components/DelegateListItem/__snapshots__/DelegateListItem.test.tsx.snap
  src/domains/vote/pages/Votes/Votes.test.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2344 refactor: apply ui guidelines on plugin domain modals
  src/app/components/SearchBar/SearchBar.tsx
  src/app/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/components/InstallPlugin/InstallPlugin.tsx
  src/domains/plugin/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2340 refactor: apply ui guidelines on `Setting` modals
  src/domains/setting/components/AdvancedMode/AdvancedMode.tsx
  src/domains/setting/components/AdvancedMode/__snapshots__/AdvancedMode.test.tsx.snap
  src/domains/setting/components/CustomPeers/CustomPeers.stories.tsx
  src/domains/setting/components/CustomPeers/CustomPeers.tsx
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/PeerList.stories.tsx
  src/domains/setting/components/PeerList/PeerList.tsx
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2331 feat: add app wrapper
  src/__snapshots__/index.test.ts.snap
  src/app/__snapshots__/index.test.tsx.snap
  src/app/components/Notifications/Notifications.tsx
  src/app/index.test.tsx
  src/app/index.tsx
  src/index.tsx
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2350 chore: remove `NetworkCard` component
  src/domains/network/components/NetworkCard/NetworkCard.stories.tsx
  src/domains/network/components/NetworkCard/NetworkCard.test.tsx
  src/domains/network/components/NetworkCard/NetworkCard.tsx
  src/domains/network/components/NetworkCard/__snapshots__/NetworkCard.test.tsx.snap
  src/domains/network/components/NetworkCard/index.ts
  src/domains/network/data.ts
Labels: Complexity: Medium, Type: Task

#2349 fix: help pages ui adjustments
  src/domains/help/pages/Article/Article.tsx
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/Faq.tsx
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/Main.tsx
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2348 refactor: ledger ui adjustments
  src/domains/transaction/components/LedgerConfirmation/LedgerConfirmation.stories.tsx
  src/domains/transaction/components/LedgerConfirmation/LedgerConfirmation.test.tsx
  src/domains/transaction/components/LedgerConfirmation/LedgerConfirmation.tsx
  src/domains/transaction/components/LedgerConfirmation/__snapshots__/LedgerConfirmation.test.tsx.snap
  src/domains/transaction/components/LedgerConfirmation/index.ts
  src/domains/transaction/i18n.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
Labels: Complexity: Medium, Type: Refactor

#2346 refactor: apply ui guidelines on `Contact` domain modals
  src/domains/contact/components/ContactForm/ContactForm.test.tsx
  src/domains/contact/components/ContactForm/ContactForm.tsx
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/CreateContact.stories.tsx
  src/domains/contact/components/CreateContact/CreateContact.tsx
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/UpdateContact.stories.tsx
  src/domains/contact/components/UpdateContact/UpdateContact.tsx
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/contact/pages/Contacts/Contacts.stories.tsx
  src/domains/contact/pages/Contacts/Contacts.test.tsx
  src/domains/contact/pages/Contacts/Contacts.tsx
Labels: Complexity: High, Type: Refactor

#2345 feat: add demo environment
  cypress/integration/startup.spec.js
  package.json
  src/app/contexts/Environment.tsx
  src/app/index.tsx
  src/domains/profile/pages/Welcome/Welcome.test.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/routing.ts
  src/tests/fixtures/identity.ts
Labels: Complexity: Low, Type: Feature

#2351 refactor: add plugin modal banners
  src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/components/BestPlugins/BestPlugins.tsx
  src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap
  src/domains/plugin/components/BlacklistPlugins/BlacklistPlugins.tsx
  src/domains/plugin/components/BlacklistPlugins/__snapshots__/BlacklistPlugins.test.tsx.snap
  src/domains/plugin/components/FeaturedPlugins/FeaturedPlugins.tsx
  src/domains/plugin/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap
  src/domains/plugin/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
  src/domains/plugin/images/best-plugins-banner.svg
  src/domains/plugin/images/index.ts
  src/domains/profile/components/ProfileCreated/__snapshots__/ProfileCreated.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/__snapshots__/RepositoryModal.test.tsx.snap
  src/domains/setting/components/AdvancedMode/__snapshots__/AdvancedMode.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
  src/domains/wallet/components/LedgerWallet/__snapshots__/LedgerWallet.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/components/VerifyMessageStatus/__snapshots__/VerifyMessageStatus.test.tsx.snap
  src/domains/wallet/components/WalletUpdate/__snapshots__/WalletUpdate.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2353 refactor: add padding above steps
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/SendVoteTransaction.stories.tsx
  src/domains/vote/components/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2354 chore: correct z-index in `PluginManagerNavigationBar`
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2355 refactor: apply header ui guidelines on pages
  src/app/components/Header/Header.tsx
  src/app/components/Header/__snapshots__/Header.test.tsx.snap
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/help/pages/Faq/Faq.tsx
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/Main.tsx
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2358 refactor: install plugin ui guidelines
  src/domains/plugin/components/InstallPlugin/InstallPlugin.stories.tsx
  src/domains/plugin/components/InstallPlugin/InstallPlugin.test.tsx
  src/domains/plugin/components/InstallPlugin/InstallPlugin.tsx
  src/domains/plugin/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
  src/domains/plugin/images/.gitkeep
  src/domains/plugin/pages/.gitkeep
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2356 refactor: settings page style guide
  src/app/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/app/components/ListDivided/ListDivided.tsx
  src/app/components/ListDivided/ListDividedItem.tsx
  src/app/components/ListDivided/__snapshots__/ListDivided.test.tsx.snap
  src/app/components/ListDivided/__snapshots__/ListDividedItem.test.tsx.snap
  src/app/components/SideBar/SideBar.tsx
  src/app/components/SideBar/SideBarItem/SideBarItem.tsx
  src/app/components/SideBar/SideBarItem/__snapshots__/SideBarItem.test.tsx.snap
  src/app/components/SideBar/__snapshots__/SideBar.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/components/PeerList/PeerList.tsx
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/Settings.stories.tsx
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/setting/pages/Settings/available-settings/Peer.tsx
  src/domains/setting/pages/Settings/available-settings/Plugins.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.stories.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Undetermined, Type: Refactor

#2357 refactor: apply header ui guidelines on `Exchange` page
  src/domains/exchange/pages/Exchange/Exchange.tsx
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2359 refactor: apply style guide to verify message
  src/domains/wallet/components/VerifyMessage/VerifyMessage.tsx
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2361 feat: add `TruncateMiddle` component
  src/app/components/Address/Address.test.tsx
  src/app/components/Address/Address.tsx
  src/app/components/Address/__snapshots__/Address.test.tsx.snap
  src/app/components/Address/utils.ts
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/TransactionListItem/__snapshots__/TransactionListItem.test.tsx.snap
  src/app/components/TruncateMiddle/TruncateMiddle.stories.tsx
  src/app/components/TruncateMiddle/TruncateMiddle.test.tsx
  src/app/components/TruncateMiddle/TruncateMiddle.tsx
  src/app/components/TruncateMiddle/index.ts
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Feature

#2366 refactor: `CircularProgressBar` component ui adjustments
  src/app/components/CircularProgressBar/CircularProgressBar.stories.tsx
  src/app/components/CircularProgressBar/CircularProgressBar.test.tsx
  src/app/components/CircularProgressBar/CircularProgressBar.tsx
  src/app/components/CircularProgressBar/__snapshots__/CircularProgressBar.test.tsx.snap
  src/domains/plugin/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2364 feat: add custom `Link` component
  src/app/assets/svg/redirect.svg
  src/app/components/Icon/Icon.tsx
  src/app/components/Link/Link.stories.tsx
  src/app/components/Link/Link.test.tsx
  src/app/components/Link/Link.tsx
  src/app/components/Link/__snapshots__/Link.test.tsx.snap
  src/app/components/Link/index.ts
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/__snapshots__/RepositoryModal.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/components/RepositoryLink/__snapshots__/RepositoryLink.test.tsx.snap
Labels: Complexity: Medium, Type: Feature

#2365 chore: fix no contacts banner
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2360 refactor: apply style guide to signed message modal
  src/app/components/TransactionDetail/TransactionDetail.tsx
  src/app/components/TransactionDetail/__snapshots__/TransactionDetail.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SignMessage/SignMessage.tsx
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2362 refactor: send ipfs ui updates
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx
  src/domains/transaction/components/TotalAmountBox/__snapshots__/TotalAmountBox.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2347 feat: add dashboard routes
  cypress.json
  cypress/integration/portfolio-routing.spec.js
  src/app/__snapshots__/index.test.tsx.snap
  src/domains/dashboard/pages/index.ts
  src/domains/dashboard/routing.ts
  src/router/index.tsx
Labels: Complexity: Medium, Type: Feature

#2368 refactor: ux and styleguide adjustments on `SelectDropdown`
  src/app/components/Select/Select.stories.tsx
  src/app/components/SelectDropdown/SelectDropdown.stories.tsx
  src/app/components/SelectDropdown/SelectDropdown.test.tsx
  src/app/components/SelectDropdown/SelectDropdown.tsx
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/SelectDropdown/styles.ts
  src/domains/transaction/components/LinkCollection/LinkCollection.test.tsx
  src/domains/transaction/components/LinkCollection/LinkCollection.tsx
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
Labels: Complexity: Undetermined

#2369 refactor: replace select list in pages
  src/app/components/Form/Form.stories.tsx
  src/domains/help/components/ContactUs/ContactUs.tsx
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/setting/pages/Settings/available-settings/Plugins.tsx
  src/domains/transaction/pages/Registration/Registration.test.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
Labels: Complexity: Undetermined

#2371 fix: `CreateProfile` ui adjustments
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2372 refactor: ui adjustments on `HeaderSearchBar`
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.test.tsx
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/app/components/Header/HeaderSearchBar/__snapshots__/HeaderSearchBar.test.tsx.snap
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2373 chore: select list ux adjustments
  src/app/components/SelectDropdown/SelectDropdown.tsx
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/SelectDropdown/styles.ts
  src/domains/help/components/ContactUs/ContactUs.tsx
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/transaction/components/LinkCollection/LinkCollection.tsx
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2375 chore: banner alignment fix
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/exchange/pages/Exchange/Exchange.tsx
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2377 feat: add `RouterView` component to render default layout
  src/__snapshots__/index.test.ts.snap
  src/app/App.tsx
  src/app/__snapshots__/index.test.tsx.snap
  src/app/components/Layout/Layout.test.tsx
  src/app/components/Layout/Layout.tsx
  src/app/components/Layout/__snapshots__/Layout.test.tsx.snap
  src/app/components/Layout/index.tsx
  src/app/contexts/Environment/Environment.tsx
  src/app/hooks/env.ts
  src/app/index.tsx
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/routing.ts
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/routing.ts
  src/domains/exchange/pages/Exchange/Exchange.tsx
  src/domains/exchange/routing.ts
  src/domains/help/pages/Article/Article.tsx
  src/domains/help/pages/Faq/Faq.tsx
  src/domains/help/pages/Main/Main.tsx
  src/domains/help/routing.ts
  src/domains/plugin/pages/PluginDetails/PluginDetails.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/routing.ts
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/routing.ts
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/setting/routing.ts
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/index.tsx
  src/router/RouterView.test.tsx
  src/router/RouterView.tsx
  src/router/__snapshots__/RouterView.test.tsx.snap
  src/router/index.tsx
Labels: Complexity: High, Type: Feature

#2376 refactor: select asset in import wallet
  src/domains/wallet/pages/ImportWallet/ImportWallet.stories.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2388 chore: add tooltips to ContactListItem
  src/app/i18n/common/i18n.ts
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
Labels: Complexity: Low, Type: Task

#2387 chore: adjust h1 font weight
  src/app/__snapshots__/index.test.tsx.snap
  src/app/components/Header/Header.tsx
  src/app/components/Header/__snapshots__/Header.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/styles/headings.css
Labels: Complexity: High, Type: Task

#2386 refactor: add renderWithRouter helper method
  src/app/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/app/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/components/Link/Link.test.tsx
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/SideBar/SideBar.test.tsx
  src/app/components/SideBar/SideBarItem/SideBarItem.test.tsx
  src/app/index.test.tsx
  src/domains/contact/pages/Contacts/Contacts.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/HistoryModal.test.tsx
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/RepositoryModal.test.tsx
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/__snapshots__/RepositoryModal.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/components/RepositoryLink/RepositoryLink.test.tsx
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/components/RepositoryLink/__snapshots__/RepositoryLink.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.test.tsx
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/vote/pages/Votes/Votes.test.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/utils/testing-library.tsx
Labels: Complexity: High, Type: Refactor

#2381 refactor: reduce `Toggle` switch size
  src/app/components/Toggle/Toggle.tsx
  src/app/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2385 refactor: update input border
  src/app/components/Input/Input.tsx
  src/app/components/Input/__snapshots__/Input.test.tsx.snap
  src/app/components/Input/__snapshots__/InputCounter.test.tsx.snap
  src/app/components/Input/__snapshots__/InputCurrency.test.tsx.snap
  src/app/components/Input/__snapshots__/InputGroup.test.tsx.snap
  src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap
  src/app/components/Input/__snapshots__/InputRange.test.tsx.snap
  src/app/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/app/components/Select/__snapshots__/Select.test.tsx.snap
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/TextArea/__snapshots__/TextArea.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2384 chore: move svg banners to images folder
  src/app/assets/images/confirmed-banner.svg
  src/app/assets/images/index.ts
  src/app/assets/images/mistake-banner.svg
  src/app/assets/images/register-banner.svg
  src/app/assets/svg/index.ts
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/wallet/components/VerifyMessageStatus/VerifyMessageStatus.tsx
  src/domains/wallet/components/VerifyMessageStatus/__snapshots__/VerifyMessageStatus.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2383 feat: add tooltip for `SelectAsset`
  src/app/components/SelectAsset/SelectAsset.tsx
  src/app/components/SelectAsset/__snapshots__/SelectAsset.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Feature

#2378 refactor: `CreateWallet` ui guidelines
  src/domains/wallet/pages/CreateWallet/CreateWallet.stories.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2380 chore: modal icon ui adjustments
  src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap
  src/domains/plugin/components/BlacklistPlugins/__snapshots__/BlacklistPlugins.test.tsx.snap
  src/domains/plugin/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap
  src/domains/plugin/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/components/ProfileCreated/__snapshots__/ProfileCreated.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/__snapshots__/RepositoryModal.test.tsx.snap
  src/domains/setting/components/AdvancedMode/__snapshots__/AdvancedMode.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
  src/domains/wallet/components/LedgerWallet/__snapshots__/LedgerWallet.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/components/VerifyMessageStatus/__snapshots__/VerifyMessageStatus.test.tsx.snap
  src/domains/wallet/components/WalletUpdate/__snapshots__/WalletUpdate.test.tsx.snap
Labels: Complexity: High, Status: Needs Review, Type: Task

#2390 refactor: rename `assets` to `networks`
  src/app/components/FilterNetwork/FilterNetwork.stories.tsx
  src/app/components/FilterNetwork/FilterNetwork.test.tsx
  src/app/components/FilterNetwork/FilterNetwork.tsx
  src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap
  src/app/components/FilterNetwork/index.ts
  src/app/components/SearchBar/SearchBarFilters/SearchBarFilters.tsx
  src/app/components/SelectAsset/SelectAsset.stories.tsx
  src/app/components/SelectAsset/SelectAsset.test.tsx
  src/app/components/SelectAsset/SelectAsset.tsx
  src/app/components/SelectAsset/__snapshots__/SelectAsset.test.tsx.snap
  src/app/components/SelectAsset/index.ts
  src/app/components/SelectNetwork/SelectNetwork.stories.tsx
  src/app/components/SelectNetwork/SelectNetwork.test.tsx
  src/app/components/SelectNetwork/SelectNetwork.tsx
  src/app/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/contact/components/ContactForm/ContactForm.test.tsx
  src/domains/contact/components/ContactForm/ContactForm.tsx
  src/domains/contact/components/CreateContact/CreateContact.stories.tsx
  src/domains/contact/components/CreateContact/CreateContact.tsx
  src/domains/contact/components/UpdateContact/UpdateContact.stories.tsx
  src/domains/contact/components/UpdateContact/UpdateContact.tsx
  src/domains/contact/data.ts
  src/domains/contact/pages/Contacts/Contacts.stories.tsx
  src/domains/contact/pages/Contacts/Contacts.test.tsx
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/dashboard/components/FilterWallets/FilterWallets.tsx
  src/domains/setting/components/CustomPeers/CustomPeers.stories.tsx
  src/domains/setting/components/CustomPeers/CustomPeers.tsx
  src/domains/setting/components/PeerList/PeerList.stories.tsx
  src/domains/setting/components/PeerList/PeerList.tsx
  src/domains/setting/data.ts
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.stories.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/data.ts
  src/domains/transaction/pages/Registration/Registration.stories.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.stories.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.stories.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/vote/data.ts
  src/domains/vote/pages/Votes/Votes.stories.tsx
  src/domains/vote/pages/Votes/Votes.test.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/data.ts
  src/domains/wallet/pages/CreateWallet/CreateWallet.stories.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.stories.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
Labels: Complexity: Undetermined, Type: Refactor

#2391 chore: ui fixes
  src/app/components/Input/InputPassword.tsx
  src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.stories.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#2393 chore: fix card handleclick error on `Card`
  src/app/components/Card/Card.tsx
Labels: Complexity: Low, Type: Bugfix

#2399 feat: add `NewsCard` component
  src/domains/news/components/NewsCard/NewsCard.stories.tsx
  src/domains/news/components/NewsCard/NewsCard.test.tsx
  src/domains/news/components/NewsCard/NewsCard.tsx
  src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap
  src/domains/news/components/NewsCard/index.tsx
  src/domains/news/data.ts
Labels: Complexity: Medium, Type: Feature

#2397 refactor: add `position` prop to Badges component
  src/app/components/Avatar/Avatar.tsx
  src/app/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  src/app/components/Badge/Badge.stories.tsx
  src/app/components/Badge/Badge.styles.ts
  src/app/components/Badge/Badge.test.tsx
  src/app/components/Badge/Badge.tsx
  src/app/components/Badge/__snapshots__/Badge.test.tsx.snap
  src/app/components/FilterNetwork/FilterNetwork.tsx
  src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/TransactionListItem/__snapshots__/TransactionListItem.test.tsx.snap
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/FilterWallets/FilterWallets.tsx
  src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/Recipient/__snapshots__/Recipient.test.tsx.snap
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap
  src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap
  src/domains/vote/components/DelegateListItem/__snapshots__/DelegateListItem.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap
  src/domains/wallet/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2396 refactor: add `ButtonVariant` constraint
  src/app/components/Button/Button.stories.tsx
  src/app/components/Button/Button.tsx
  src/types.d.ts
Labels: Complexity: Low, Type: Refactor

#2395 refactor: apply ui guidelines in `SendVoteTransaction`
  src/domains/vote/components/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/components/VoteList/VoteList.tsx
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2374 feat: add story and tests for `TransactionSuccessful` component
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.stories.tsx
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.test.tsx
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/index.ts
Labels: Complexity: High, Type: Feature

#2400 fix: remove style element in welcome-banner.svg
  src/domains/profile/images/welcome-banner.svg
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#2398 refactor: style adjustments of `FilterWallets` component
  src/app/components/Toggle/Toggle.tsx
  src/app/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/domains/dashboard/components/FilterWallets/FilterWallets.test.tsx
  src/domains/dashboard/components/FilterWallets/FilterWallets.tsx
  src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#2401 refactor: send vote tx ui adjustments
  src/app/components/TransactionDetail/TransactionDetail.tsx
  src/domains/vote/components/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
Labels: Complexity: High

#2392 refactor: transfer multipayment ux
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormTransfer.spec.js
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Input/InputToggle/InputToggleChoice.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/styles/_theme.css
  tailwind.js
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2402 feat: add extra slot in `HeaderSearchBar`
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.test.tsx
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: Low, Type: Feature

#2403 chore: remove `<style>` element from svgs
  .svgo.yml
  src/app/assets/images/confirmed-banner.svg
  src/app/assets/images/delete-banner.svg
  src/app/assets/images/mistake-banner.svg
  src/app/assets/svg/currencies/eth.svg
  src/app/assets/svg/file-password.svg
  src/app/assets/svg/placeholder.svg
  src/app/assets/svg/plugin.svg
  src/app/assets/svg/plugins.svg
  src/app/assets/svg/portfolio-tag.svg
  src/app/assets/svg/portfolio.svg
  src/app/components/Badge/Badge.stories.tsx
  src/domains/contact/images/contacts-banner.svg
  src/domains/offline/images/cannot-connect-banner.svg
  src/domains/profile/images/profile-created-banner.svg
  src/domains/transaction/images/confirm-transaction-ledger-banner.svg
  src/domains/transaction/images/transaction_successful.svg
  src/domains/vote/images/placeholder-votes.svg
  src/domains/wallet/images/name-wallet.svg
  src/domains/wallet/images/waiting-ledger.svg
  src/domains/wallet/images/wallet-update-ready.svg
  src/domains/wallet/images/wallet-update.svg
Labels: Complexity: Medium

#2406 chore: multipayment notice min. recipients
  src/renderer/components/Transaction/TransactionRecipientList.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Task

#2407 chore: version 2.9.3
  .github/workflows/draft-artifacts.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  package.json
Labels: Complexity: Medium, Type: Task

#2405 feat: add `SearchBarPluginFilters` component
  src/app/components/SearchBar/SearchBarPluginFilters/SearchBarPluginFilters.stories.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/SearchBarPluginFilters.test.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/SearchBarPluginFilters.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap
  src/app/components/SearchBar/SearchBarPluginFilters/index.ts
Labels: Complexity: Undetermined, Type: Feature

#2411 chore: add `hideViewAll` props to `FilterNetwork` component
  src/app/components/FilterNetwork/FilterNetwork.stories.tsx
  src/app/components/FilterNetwork/FilterNetwork.test.tsx
  src/app/components/FilterNetwork/FilterNetwork.tsx
  src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#2409 refactor: `PluginManager` navigation ui adjustments
  src/app/components/LayoutControls/LayoutControls.tsx
  src/app/components/LayoutControls/__snapshots__/LayoutControls.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugin/components/PluginManagerControls/PluginManagerControls.tsx
  src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.test.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/styles.ts
  src/domains/plugin/pages/PluginManager/PluginManager.stories.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2408 fix: remove duplicate exchange banner
  src/domains/exchange/pages/Exchange/Exchange.tsx
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
Labels: Complexity: Undetermined, Type: Bugfix

#2410 feat: add `NewsOptions` and `SelectCategory` components
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/app/i18n/helpers/index.ts
  src/domains/news/components/NewsCard/NewsCard.tsx
  src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap
  src/domains/news/components/NewsOptions/NewsOptions.stories.tsx
  src/domains/news/components/NewsOptions/NewsOptions.test.tsx
  src/domains/news/components/NewsOptions/NewsOptions.tsx
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/news/components/NewsOptions/components/SelectCategory/SelectCategory.stories.tsx
  src/domains/news/components/NewsOptions/components/SelectCategory/SelectCategory.test.tsx
  src/domains/news/components/NewsOptions/components/SelectCategory/SelectCategory.tsx
  src/domains/news/components/NewsOptions/components/SelectCategory/__snapshots__/SelectCategory.test.tsx.snap
  src/domains/news/components/NewsOptions/components/SelectCategory/index.tsx
  src/domains/news/components/NewsOptions/index.tsx
  src/domains/news/data.ts
  src/domains/news/i18n.ts
Labels: Complexity: High, Type: Feature

#2414 refactor: fix paddings in plugin navigation
  src/app/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/app/components/Divider/Divider.styles.ts
  src/app/components/Divider/__snapshots__/Divider.test.tsx.snap
  src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/styles.ts
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2415 refactor: remove white shadow from `shadow-xl`
  src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Low, Type: Refactor

#2416 stage: 2.9.3
  .github/workflows/draft-artifacts.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormTransfer.spec.js
  package.json
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Input/InputToggle/InputToggleChoice.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionRecipientList.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/store/modules/peer/index.js
  src/renderer/styles/_theme.css
  tailwind.js
  yarn.lock
Labels: Complexity: High

#2417 release: 2.9.3
  .github/workflows/draft-artifacts.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormTransfer.spec.js
  package.json
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Input/InputToggle/InputToggleChoice.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionRecipientList.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/store/modules/peer/index.js
  src/renderer/styles/_theme.css
  tailwind.js
  yarn.lock
Labels: Complexity: High, Type: Release

#2418 refactor: add `thick` variant in `Checkbox`
  src/app/components/Checkbox/Checkbox.stories.tsx
  src/app/components/Checkbox/Checkbox.styles.ts
  src/app/components/Checkbox/Checkbox.test.tsx
  src/app/components/Checkbox/Checkbox.tsx
  src/app/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Labels: Complexity: High

#2419 feat: add `TransactionTable` component
  src/app/assets/svg/edit.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/received.svg
  src/app/assets/svg/sent.svg
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowConfirmation.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowConfirmation.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowInfo.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowInfo.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowRecipientIcon.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionTable.models.ts
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/index.ts
Labels: Complexity: Undetermined, Type: Feature

#2420 feat: integrate `SearchBarPluginFilters` in `PluginManager`
  src/app/assets/svg/reset.svg
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/SearchBarPluginFilters.test.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/SearchBarPluginFilters.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: Undetermined, Type: Feature

#2421 fix: dynamic badge shadow
  src/app/components/Badge/Badge.styles.ts
  src/app/components/Badge/__snapshots__/Badge.test.tsx.snap
  src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap
  src/app/components/Layout/__snapshots__/Layout.test.tsx.snap
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2422 fix: adjust avatar size and margins in transaction components
  src/app/components/TransactionDetail/TransactionDetail.tsx
  src/app/components/TransactionDetail/__snapshots__/TransactionDetail.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/components/VoteList/VoteList.tsx
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
Labels: Complexity: Undetermined, Type: Bugfix

#2423 chore: adjust dimensions in Sent icon usage
  src/app/components/Layout/__snapshots__/Layout.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.tsx
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/IpfsDetail.tsx
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.tsx
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
Labels: Complexity: High, Type: Task

#2424 refactor: vertical icon alignment and font color in transaction table
  src/app/components/Address/Address.tsx
  src/app/components/Address/__snapshots__/Address.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Table/Table.tsx
  src/app/components/Table/__snapshots__/Table.test.tsx.snap
  src/app/components/TransactionListItem/__snapshots__/TransactionListItem.test.tsx.snap
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap
  src/domains/plugin/components/BlacklistPlugins/__snapshots__/BlacklistPlugins.test.tsx.snap
  src/domains/plugin/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowConfirmation.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowInfo.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap
  src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/styles/variables.css
Labels: Complexity: Undetermined, Type: Refactor

#2426 feat: add `AddAssets` modal
  src/domains/news/components/AddAssets/AddAssets.stories.tsx
  src/domains/news/components/AddAssets/AddAssets.test.tsx
  src/domains/news/components/AddAssets/AddAssets.tsx
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/news/components/AddAssets/index.tsx
Labels: Complexity: High, Type: Feature

#2427 chore: adjust margin of last asset
  src/domains/news/components/AddAssets/AddAssets.tsx
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#2425 refactor: set margin on sort icon
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Table/Table.tsx
  src/app/components/Table/__snapshots__/Table.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap
  src/domains/plugin/components/BlacklistPlugins/__snapshots__/BlacklistPlugins.test.tsx.snap
  src/domains/plugin/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2428 feat: add `PluginsCategory` page
  src/domains/plugin/i18n.ts
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.stories.tsx
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.test.tsx
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.tsx
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/index.tsx
Labels: Complexity: Undetermined, Type: Feature

#2430 chore: fix shadow in `xl`
  src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Low, Type: Task

#2429 refactor: ui adjustments in `PluginManager`
  src/app/components/LayoutControls/LayoutControls.tsx
  src/app/components/LayoutControls/__snapshots__/LayoutControls.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.stories.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.tsx
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2431 fix: use neutral variable in `shadow-xl`
  src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Low, Type: Bugfix

#2432 refactor: ui adjustments on plugin pages
  src/app/components/SearchBar/SearchBarPluginFilters/SearchBarPluginFilters.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap
  src/domains/plugin/components/PluginCard/PluginCard.tsx
  src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/components/PluginListItem/PluginListItem.tsx
  src/domains/plugin/components/PluginListItem/__snapshots__/PluginListItem.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/styles.ts
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.tsx
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2433 feat: add wallets routing
  cypress/integration/wallets-routing.spec.js
  src/app/components/Layout/Layout.test.tsx
  src/app/components/Layout/__snapshots__/Layout.test.tsx.snap
  src/app/components/WalletCard/WalletCard.test.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/hooks/env.ts
  src/domains/dashboard/components/Wallets/Wallets.test.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/data.ts
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/wallet/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/components/WalletRegistrations/WalletRegistrations.tsx
  src/domains/wallet/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap
  src/domains/wallet/components/WalletVote/WalletVote.tsx
  src/domains/wallet/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.stories.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/data.ts
  src/domains/wallet/pages/WalletDetails/index.ts
  src/domains/wallet/pages/index.ts
  src/domains/wallet/routing.ts
  src/router/index.tsx
  src/setupTests.ts
Labels: Complexity: Undetermined, Type: Feature

#2413 feat: add `News` page
  src/app/assets/images/index.ts
  src/app/assets/svg/blockfolio.svg
  src/app/assets/svg/index.ts
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/news/components/BlockfolioAd/BlockfolioAd.stories.tsx
  src/domains/news/components/BlockfolioAd/BlockfolioAd.test.tsx
  src/domains/news/components/BlockfolioAd/BlockfolioAd.tsx
  src/domains/news/components/BlockfolioAd/__snapshots__/BlockfolioAd.test.tsx.snap
  src/domains/news/components/BlockfolioAd/index.tsx
  src/domains/news/components/NewsCard/NewsCard.tsx
  src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap
  src/domains/news/components/NewsOptions/NewsOptions.stories.tsx
  src/domains/news/components/NewsOptions/NewsOptions.tsx
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/news/components/NewsOptions/components/SelectCategory/SelectCategory.tsx
  src/domains/news/components/NewsOptions/components/SelectCategory/__snapshots__/SelectCategory.test.tsx.snap
  src/domains/news/data.ts
  src/domains/news/i18n.ts
  src/domains/news/images/blockfolio-banner.png
  src/domains/news/images/download-app-store.svg
  src/domains/news/images/download-google-play.svg
  src/domains/news/images/index.ts
  src/domains/news/pages/News/News.stories.tsx
  src/domains/news/pages/News/News.test.tsx
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/news/pages/News/index.ts
Labels: Complexity: High, Type: Feature

#2437 chore: plugins ui adjustments
  src/domains/plugin/components/PluginList/PluginList.tsx
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
Labels: Complexity: Undetermined, Type: Task

#2436 feat: add news routing
  cypress/integration/navbar-routing.spec.js
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/news/pages/index.ts
  src/domains/news/routing.ts
  src/router/index.tsx
Labels: Complexity: Undetermined, Type: Feature

#2442 refactor: remove readonly and add disabled property
  src/app/components/Card/Card.stories.tsx
  src/app/components/Card/CardControl.tsx
  src/app/components/Card/__snapshots__/CardControl.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2441 fix: update delete-banner.svg
  src/app/assets/images/delete-banner.svg
Labels: Complexity: Low, Type: Bugfix

#2440 fix: remove storybook warns
  src/app/components/Notifications/Notifications.stories.tsx
  src/app/components/SearchResource/SearchResource.tsx
  src/app/components/TextArea/TextArea.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.stories.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/AddressListItem/AddressListItem.tsx
  src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap
  src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap
  src/domains/vote/components/DelegateListItem/DelegateListItem.tsx
  src/domains/vote/components/DelegateListItem/__snapshots__/DelegateListItem.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/ReceiveFunds.tsx
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2439 feat: add plugin details routing
  cypress/integration/plugins-routing.spec.js
  src/domains/plugin/components/PluginGrid/PluginGrid.tsx
  src/domains/plugin/data.ts
  src/domains/plugin/pages/PluginDetails/PluginDetails.stories.tsx
  src/domains/plugin/pages/PluginDetails/PluginDetails.test.tsx
  src/domains/plugin/pages/PluginDetails/PluginDetails.tsx
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/routing.ts
Labels: Complexity: Undetermined, Type: Feature

#2438 refactor: dashboard wallet size
  src/app/components/Slider/Slider.tsx
  src/domains/dashboard/components/Wallets/Wallets.stories.tsx
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#2444 feat: create `AddRecipient`
  src/domains/transaction/components/AddRecipient/AddRecipient.stories.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.styles.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/AddRecipient/index.ts
  src/domains/transaction/components/RecipientList/RecipientList.models.ts
  src/domains/transaction/components/RecipientList/RecipientList.styles.ts
  src/domains/transaction/components/RecipientList/RecipientList.tsx
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: Undetermined, Type: Feature

#2447 feat: search contact modal ux
  src/domains/contact/components/ContactListItem/ContactListItem.models.ts
  src/domains/contact/components/ContactListItem/ContactListItem.test.tsx
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/SearchContact.stories.tsx
  src/domains/contact/components/SearchContact/SearchContact.test.tsx
  src/domains/contact/components/SearchContact/SearchContact.tsx
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
Labels: Complexity: High, Status: Needs Review

#2452 feat: create `SelectAddress` component
  src/domains/profile/components/SelectAddress/SelectAddress.stories.tsx
  src/domains/profile/components/SelectAddress/SelectAddress.styles.ts
  src/domains/profile/components/SelectAddress/SelectAddress.test.tsx
  src/domains/profile/components/SelectAddress/SelectAddress.tsx
  src/domains/profile/components/SelectAddress/__snapshots__/SelectAddress.test.tsx.snap
  src/domains/profile/components/SelectAddress/index.ts
Labels: Complexity: High, Type: Feature

#2450 chore: plugin manager ui adjustments
  src/app/components/NavigationBar/NavigationBar.stories.tsx
  src/domains/plugin/components/PluginGrid/PluginGrid.tsx
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.stories.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.stories.tsx
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.test.tsx
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
Labels: Complexity: High, Type: Task

#2453 feat: add `SelectAddress` component in `AddRecipient`
  src/domains/transaction/components/AddRecipient/AddRecipient.stories.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
Labels: Complexity: High, Type: Feature

#2451 test: fix registration warnings
  src/domains/transaction/pages/Registration/Registration.test.tsx
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.test.tsx
Labels: Complexity: Low, Status: Needs Review, Test: Unit

#2454 refactor: mnemonic random words check
  src/domains/wallet/components/MnemonicList/MnemonicList.stories.tsx
  src/domains/wallet/components/MnemonicList/MnemonicList.test.tsx
  src/domains/wallet/components/MnemonicList/MnemonicList.tsx
  src/domains/wallet/components/MnemonicVerification/MnemonicVerification.stories.tsx
  src/domains/wallet/components/MnemonicVerification/MnemonicVerification.test.tsx
  src/domains/wallet/components/MnemonicVerification/MnemonicVerification.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.stories.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
Labels: Complexity: Medium, Type: Refactor

#2456 feat: add story for the `DeleteResource` component
  src/app/components/DeleteResource/DeleteResource.stories.tsx
  src/app/components/DeleteResource/DeleteResource.test.tsx
  src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap
Labels: Complexity: Low, Type: Feature

#2457 feat: add story and tests for the `SearchResource` component
  src/app/components/SearchResource/SearchResource.stories.tsx
  src/app/components/SearchResource/SearchResource.test.tsx
  src/app/components/SearchResource/__snapshots__/SearchResource.test.tsx.snap
Labels: Complexity: Medium, Type: Feature

#2458 chore: add networks to peer list
  src/domains/setting/components/PeerList/PeerList.tsx
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/Peer.tsx
Labels: Complexity: High, Type: Task

#2448 test: improve environment context usage
  jest.setup.js
  src/app/App.test.tsx
  src/app/App.tsx
  src/app/__snapshots__/App.test.tsx.snap
  src/app/__snapshots__/index.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/WalletCard/WalletCard.test.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/contexts/Environment/Environment.test.tsx
  src/app/contexts/Environment/Environment.tsx
  src/app/hooks/env.test.tsx
  src/app/hooks/env.ts
  src/app/index.test.tsx
  src/domains/contact/components/ContactListItem/ContactListItem.test.tsx
  src/domains/dashboard/components/Wallets/Wallets.test.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/Exchange.test.tsx
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/Article.test.tsx
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/Faq.test.tsx
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/Main.test.tsx
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/News.test.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/PluginDetails.test.tsx
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.test.tsx
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.test.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.test.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.test.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.test.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.test.tsx
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.test.tsx
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/tests/fixtures/env/data.json
  src/tests/fixtures/identity.ts
  src/tests/mocks/StubStorage/StubStorage.ts
  src/utils/testing-library.tsx
Labels: Complexity: Undetermined, Test: Unit

#2455 fix: update `Input` component
  src/app/components/Input/Input.tsx
  src/app/components/Input/InputGroup.tsx
  src/app/components/Input/__snapshots__/Input.test.tsx.snap
  src/app/components/Input/__snapshots__/InputCounter.test.tsx.snap
  src/app/components/Input/__snapshots__/InputCurrency.test.tsx.snap
  src/app/components/Input/__snapshots__/InputGroup.test.tsx.snap
  src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap
  src/app/components/Input/__snapshots__/InputRange.test.tsx.snap
  src/app/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/app/components/SearchResource/__snapshots__/SearchResource.test.tsx.snap
  src/app/components/Select/__snapshots__/Select.test.tsx.snap
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/TextArea/__snapshots__/TextArea.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/SelectAddress/__snapshots__/SelectAddress.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#2459 chore: remove `SelectDelegate` modal
  src/app/components/Modal/Modal.test.tsx
  src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/SelectDelegate.stories.tsx
  src/domains/transaction/components/SelectDelegate/SelectDelegate.test.tsx
  src/domains/transaction/components/SelectDelegate/SelectDelegate.tsx
  src/domains/transaction/components/SelectDelegate/__snapshots__/SelectDelegate.test.tsx.snap
  src/domains/transaction/components/SelectDelegate/index.ts
  src/domains/transaction/i18n.tsx
Labels: Complexity: Undetermined, Type: Task

#2462 refactor: integrate `AddRecipient` in `SendTransaction`
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/svg/index.ts
  src/app/assets/svg/questionmark.svg
  src/domains/profile/components/SelectAddress/SelectAddress.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.models.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.styles.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/RecipientList/RecipientList.tsx
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.stories.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.stories.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2461 feat: implement profile creating
  src/domains/profile/pages/CreateProfile/CreateProfile.stories.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2463 refactor: select inputs ui fixes
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/SelectDropdown/styles.ts
  src/app/components/SelectNetwork/SelectNetwork.tsx
  src/app/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#2471 chore: `SignMessage` ui adjustments
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/wallet/components/SignMessage/SignMessage.tsx
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2464 feat: add transactions routing
  cypress/integration/navbar-routing.spec.js
  cypress/integration/transactions-routing.spec.js
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Button/Button.stories.tsx
  src/app/components/Button/Button.styles.ts
  src/app/components/Button/Button.test.tsx
  src/app/components/Button/__snapshots__/Button.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/SearchResource/SearchResource.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/offline/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/ReceiveFunds.tsx
  src/domains/wallet/components/SignMessage/SignMessage.tsx
  src/domains/wallet/components/WalletHeader/WalletHeader.stories.tsx
  src/domains/wallet/components/WalletHeader/WalletHeader.test.tsx
  src/domains/wallet/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/types.d.ts
Labels: Complexity: Undetermined, Status: Needs Review

#2472 chore: update Platform SDK dependencies
  package.json
  src/app/App.tsx
  src/app/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/profile/components/SelectAddress/__snapshots__/SelectAddress.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/Recipient/__snapshots__/Recipient.test.tsx.snap
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowRecipientIcon.test.tsx.snap
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/AddressList/__snapshots__/AddressList.test.tsx.snap
  src/domains/vote/components/AddressListItem/__snapshots__/AddressListItem.test.tsx.snap
  src/domains/vote/components/DelegateList/__snapshots__/DelegateList.test.tsx.snap
  src/domains/vote/components/DelegateListItem/__snapshots__/DelegateListItem.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap
  src/domains/wallet/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  yarn.lock
Labels: Complexity: High, Type: Task

#2473 fix: test errors
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/wallet/components/MnemonicVerification/MnemonicVerification.test.tsx
  src/domains/wallet/components/MnemonicVerification/MnemonicVerification.tsx
Labels: Complexity: Low, Type: Bugfix

#2474 fix: icon style conflicts
  .svgo.yml
  src/app/assets/svg/currencies/eth.svg
Labels: Complexity: Low, Type: Bugfix

#2475 fix: dropdown options events
  src/app/components/Dropdown/Dropdown.tsx
Labels: Complexity: Low, Type: Bugfix

#2476 refactor: registration select address
  src/domains/profile/components/SelectAddress/SelectAddress.tsx
  src/domains/profile/components/SelectAddress/__snapshots__/SelectAddress.test.tsx.snap
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.stories.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2477 fix: wallets slider ui adjustments
  src/app/components/Slider/Slider.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#2480 feat: create `SelectRecipient` form input
  src/domains/profile/components/SelectRecipient/SelectRecipient.stories.tsx
  src/domains/profile/components/SelectRecipient/SelectRecipient.test.tsx
  src/domains/profile/components/SelectRecipient/SelectRecipient.tsx
  src/domains/profile/components/SelectRecipient/__snapshots__/SelectRecipient.test.tsx.snap
  src/domains/profile/components/SelectRecipient/index.ts
Labels: Complexity: High, Type: Feature

#2482 refactor: create profile routing & e2e tests
  cypress/integration/profile-routing.spec.js
  src/domains/profile/pages/CreateProfile/CreateProfile.stories.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
Labels: Complexity: Low, Test: Unit

#2481 refactor: integrate `SelectRecipient` in send transaction form
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2478 refactor: remove native select profile field
  src/app/components/Address/Address.test.tsx
  src/app/components/Address/__snapshots__/Address.test.tsx.snap
  src/domains/profile/components/ProfileFormField/ProfileFormField.test.tsx
  src/domains/profile/components/ProfileFormField/ProfileFormField.tsx
  src/domains/profile/components/ProfileFormField/__snapshots__/ProfileFormField.test.tsx.snap
  src/domains/profile/components/ProfileFormField/index.ts
Labels: Complexity: High, Type: Refactor

#2484 chore: input ui fix
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/app/components/Input/Input.tsx
  src/app/components/Input/__snapshots__/Input.test.tsx.snap
  src/app/components/Input/__snapshots__/InputCounter.test.tsx.snap
  src/app/components/Input/__snapshots__/InputCurrency.test.tsx.snap
  src/app/components/Input/__snapshots__/InputGroup.test.tsx.snap
  src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap
  src/app/components/Input/__snapshots__/InputRange.test.tsx.snap
  src/app/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/app/components/SearchResource/__snapshots__/SearchResource.test.tsx.snap
  src/app/components/Select/__snapshots__/Select.test.tsx.snap
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/SelectDropdown/styles.ts
  src/app/components/SelectNetwork/SelectNetwork.tsx
  src/app/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/app/components/TextArea/__snapshots__/TextArea.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/news/components/NewsOptions/NewsOptions.tsx
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/SelectAddress/__snapshots__/SelectAddress.test.tsx.snap
  src/domains/profile/components/SelectRecipient/__snapshots__/SelectRecipient.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/components/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Status: Needs Review

#2483 feat: implement profile settings
  cypress/integration/setting-routing.spec.js
  src/domains/setting/pages/Settings/Settings.stories.tsx
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/setting/pages/Settings/available-settings/index.ts
Labels: Complexity: Low, Type: Feature

#2486 fix: correct `SearchBar` font size
  src/app/components/SearchBar/SearchBar.tsx
  src/app/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/app/components/SearchResource/__snapshots__/SearchResource.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#2491 refactor: `CreateProfile` page ui adjustments
  src/app/components/ListDivided/ListDivided.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor
