Repository ArkEcosystem/desktop-wallet, pull requests merged in 2020-09, with the labels that each got.

#2767 test: add e2e tests for multiple transfer
  src/domains/transaction/e2e/multiple-transfer.e2e.ts
Labels: Complexity: Medium, Test: Unit

#2766 refactor: modal close button and spacing
  src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/app/components/SearchResource/__snapshots__/SearchResource.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/exchange/components/AddExchange/AddExchange.tsx
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/components/BestPlugins/BestPlugins.tsx
  src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap
  src/domains/plugin/components/BlacklistPlugins/BlacklistPlugins.tsx
  src/domains/plugin/components/BlacklistPlugins/__snapshots__/BlacklistPlugins.test.tsx.snap
  src/domains/plugin/components/FeaturedPlugins/FeaturedPlugins.tsx
  src/domains/plugin/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap
  src/domains/plugin/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/DeleteProfile/__snapshots__/DeleteProfile.test.tsx.snap
  src/domains/profile/components/ProfileCreated/__snapshots__/ProfileCreated.test.tsx.snap
  src/domains/profile/components/SearchAddress/__snapshots__/SearchAddress.test.tsx.snap
  src/domains/profile/components/SignIn/__snapshots__/SignIn.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/__snapshots__/RepositoryModal.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/components/AdvancedMode/__snapshots__/AdvancedMode.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
  src/domains/wallet/components/LedgerWallet/__snapshots__/LedgerWallet.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/components/VerifyMessageStatus/__snapshots__/VerifyMessageStatus.test.tsx.snap
  src/domains/wallet/components/WalletUpdate/__snapshots__/WalletUpdate.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2764 style: updates the color palette
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/styles/variables.css
  src/tailwind.config.js
Labels: Complexity: High, Type: Standards

#2768 refactor: conditionally show/hide pagination buttons and news fixes
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Pagination/Pagination.stories.tsx
  src/app/components/Pagination/Pagination.test.tsx
  src/app/components/Pagination/Pagination.tsx
  src/app/components/Pagination/__snapshots__/Pagination.test.tsx.snap
  src/app/components/Pagination/components/CompactPagination/CompactPagination.test.tsx
  src/app/components/Pagination/components/CompactPagination/CompactPagination.tsx
  src/app/components/Pagination/components/CompactPagination/__snapshots__/CompactPagination.test.tsx.snap
  src/domains/news/components/NewsCard/NewsCard.tsx
  src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap
  src/domains/news/pages/News/News.test.tsx
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/components/Comments/__snapshots__/Comments.test.tsx.snap
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/HistoryModal.tsx
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2765 test: add e2e tests for single transfer
  src/domains/transaction/e2e/single-transfer.e2e.ts
Labels: Complexity: Medium, Test: Unit

#2762 feat: receive funds
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/SearchResource/SearchResource.tsx
  src/app/components/SearchResource/__snapshots__/SearchResource.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.stories.tsx
  src/app/components/WalletListItem/WalletListItem.test.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/SearchAddress/__snapshots__/SearchAddress.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/ReceiveFunds.stories.tsx
  src/domains/wallet/components/ReceiveFunds/ReceiveFunds.tsx
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/components/SearchWallet/SearchWallet.stories.tsx
  src/domains/wallet/components/SearchWallet/SearchWallet.tsx
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2758 fix: use default timeout to fetch the plugin logo
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Bugfix

#2743 feat: implement AIP36 transaction types
  __tests__/unit/__mocks__/@/services/wallet.js
  __tests__/unit/__utils__/setup.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirm.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainRegistration.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainResignation.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainUpdate.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessRegistration.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessResignation.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessUpdate.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBridgechain/TransactionFormBridgechainRegistration.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBridgechain/TransactionFormBridgechainResignation.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBridgechain/TransactionFormBridgechainUpdate.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBusiness/TransactionFormBusinessRegistration.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBusiness/TransactionFormBusinessResignation.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBusiness/TransactionFormBusinessUpdate.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBusiness/mixin.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormVote.spec.js
  __tests__/unit/components/Wallet/WalletBusiness/WalletBusiness.spec.js
  __tests__/unit/components/Wallet/WalletBusiness/WalletBusinessBridgechains.spec.js
  __tests__/unit/components/Wallet/WalletBusiness/WalletBusinessBridgechainsTable.spec.js
  __tests__/unit/components/Wallet/WalletBusiness/WalletBusinessShowBridgechain.spec.js
  __tests__/unit/services/wallet.spec.js
  config/index.js
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirm.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainRegistration.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainResignation.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainUpdate.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/index.js
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessRegistration.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessResignation.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessUpdate.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/index.js
  src/renderer/components/Transaction/TransactionForm/TransactionForm.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/TransactionFormBridgechainRegistration.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/TransactionFormBridgechainResignation.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/TransactionFormBridgechainUpdate.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/index.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBusiness/TransactionFormBusinessRegistration.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormBusiness/TransactionFormBusinessResignation.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBusiness/TransactionFormBusinessUpdate.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormBusiness/index.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormBusiness/mixin.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Wallet/WalletAddress.vue
  src/renderer/components/Wallet/WalletBusiness/WalletBusiness.vue
  src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechains.vue
  src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechainsTable.vue
  src/renderer/components/Wallet/WalletBusiness/WalletBusinessShowBridgechain.vue
  src/renderer/components/Wallet/WalletBusiness/index.js
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingSecondaryActions.vue
  src/renderer/components/Wallet/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/mixins/index.js
  src/renderer/mixins/transaction-types.js
  src/renderer/services/transaction.js
  src/renderer/services/wallet.js
Labels: Complexity: High, Type: Feature

#2771 chore: update Platform SDK dependencies
  package.json
  src/app/App.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/utils/testing-library.tsx
  yarn.lock
Labels: Complexity: High

#2772 test: fix e2e errors
  src/app/App.tsx
  src/domains/news/e2e/news-routing.e2e.ts
  src/domains/profile/e2e/welcome-screen.e2e.ts
  src/domains/profile/middleware.test.ts
  src/utils/electron-utils.test.ts
  src/utils/electron-utils.ts
Labels: Complexity: Low, Status: Needs Review, Test: Unit

#2748 feat: sync wallet data
  package.json
  src/__snapshots__/index.test.ts.snap
  src/app/App.test.tsx
  src/app/App.tsx
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/services/Scheduler.test.ts
  src/app/services/Scheduler.ts
  src/app/services/index.ts
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/vote/components/AddressTable/AddressRow/AddressRow.test.tsx
  src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
  src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRow.test.tsx.snap
  src/domains/vote/components/AddressTable/AddressTable.test.tsx
  src/domains/vote/pages/Votes/Votes.test.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/wallet/components/ReceiveFunds/ReceiveFunds.test.tsx
  src/domains/wallet/components/ReceiveFunds/ReceiveFunds.tsx
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/tests/fixtures/env/storage.json
  src/tests/fixtures/exchange/cryptocompare.json
  src/utils/testing-library.tsx
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#2777 feat: sync fees using scheduler
  src/app/App.tsx
  src/app/services/Scheduler.test.ts
  src/app/services/Scheduler.ts
Labels: Complexity: Low, Type: Feature

#2774 chore: fix transaction success title typo
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2781 test(e2e): use mocks for network requests and run tests in split
  .github/workflows/e2e.yml
  .github/workflows/test.yml
  .gitignore
  package.json
  src/app/App.tsx
  src/domains/contact/e2e/contacts-routing.e2e.ts
  src/domains/contact/e2e/create-contact.e2e.ts
  src/domains/contact/e2e/delete-contact.e2e.ts
  src/domains/contact/e2e/update-contact.e2e.ts
  src/domains/dashboard/e2e/dashboard-routing.e2e.ts
  src/domains/dashboard/e2e/navbar-routing.e2e.ts
  src/domains/news/e2e/filtering.e2e.ts
  src/domains/news/e2e/news-routing.e2e.ts
  src/domains/plugin/e2e/plugins-routing.e2e.ts
  src/domains/profile/e2e/create-profile-action.e2e.ts
  src/domains/profile/e2e/create-profile-routing.e2e.ts
  src/domains/profile/e2e/delete-profile-action.e2e.ts
  src/domains/profile/e2e/my-registrations-routing.e2e.ts
  src/domains/profile/e2e/navigate-profile-settings.e2e.ts
  src/domains/profile/e2e/welcome-screen.e2e.ts
  src/domains/setting/e2e/save-settings.e2e.ts
  src/domains/setting/e2e/settings-routing.e2e.ts
  src/domains/splash/e2e/splash-screen.e2e.ts
  src/domains/transaction/e2e/delegate-registration.e2e.ts
  src/domains/transaction/e2e/delegate-resignation.e2e.ts
  src/domains/transaction/e2e/multiple-transfer.e2e.ts
  src/domains/transaction/e2e/single-transfer.e2e.ts
  src/domains/transaction/e2e/transactions-routing.e2e.ts
  src/domains/vote/e2e/votes.e2e.ts
  src/domains/wallet/e2e/create-wallet-action.e2e.ts
  src/domains/wallet/e2e/delete-wallet-action.e2e.ts
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
  src/domains/wallet/e2e/sign-message-action.e2e.ts
  src/domains/wallet/e2e/update-wallet-name-action.e2e.ts
  src/domains/wallet/e2e/verify-message-action.e2e.ts
  src/domains/wallet/e2e/wallet-details.e2e.ts
  src/domains/wallet/e2e/wallets-routing.e2e.ts
  src/tests/fixtures/coins/ark/transactions.json
  src/utils/e2e-utils.test.ts
  src/utils/e2e-utils.ts
Labels: Complexity: Undetermined

#2778 test: add e2e tests for ipfs transaction
  .github/workflows/e2e.yml
  src/domains/transaction/e2e/ipfs-transaction.e2e.ts
Labels: Complexity: Medium, Test: Unit

#2776 test: update e2e transaction tests and some tweaks
  src/domains/transaction/e2e/common.ts
  src/domains/transaction/e2e/delegate-registration.e2e.ts
  src/domains/transaction/e2e/delegate-resignation.e2e.ts
  src/domains/transaction/e2e/multiple-transfer.e2e.ts
  src/domains/transaction/e2e/single-transfer.e2e.ts
  src/domains/transaction/e2e/transactions-routing.e2e.ts
Labels: Complexity: Medium, Test: Unit

#2783 chore: update Platform SDK dependencies
  package.json
  src/app/services/HttpClient.test.ts
  src/app/services/HttpClient.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  yarn.lock
Labels: Complexity: High

#2759 feat: implement business registrations in `MyRegistrations`
  src/app/__snapshots__/App.test.tsx.snap
  src/domains/profile/data.ts
  src/domains/profile/e2e/my-registrations-routing.e2e.ts
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/BusinessRowItem.tsx
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/BusinessTable.stories.tsx
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/BusinessTable.test.tsx
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/BusinessTable.tsx
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/transaction/e2e/ipfs-transaction.e2e.ts
  src/tests/fixtures/registrations/businesses.json
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2782 fix: flush transaction history
  src/app/i18n/common/i18n.ts
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2645 feat: implement `HttpClient#withSocksProxy`
  config-overrides.js
  package.json
  src/app/services/HttpClient.test.ts
  src/app/services/HttpClient.ts
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/tests/fixtures/coins/ark/wallets/D6Z26L69gdk9qYmTv5uzk3uGepigtHY4ax.json
  src/utils/e2e-utils.ts
  yarn.lock
Labels: Complexity: High

#2779 refactor: combine SearchWallet and SearchAddress components
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.test.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/profile/components/SearchAddress/SearchAddress.stories.tsx
  src/domains/profile/components/SearchAddress/SearchAddress.test.tsx
  src/domains/profile/components/SearchAddress/SearchAddress.tsx
  src/domains/profile/components/SearchAddress/__snapshots__/SearchAddress.test.tsx.snap
  src/domains/profile/components/SearchAddress/index.ts
  src/domains/profile/components/SelectAddress/SelectAddress.test.tsx
  src/domains/profile/components/SelectAddress/SelectAddress.tsx
  src/domains/profile/i18n.ts
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/pages/Registration/Registration.test.tsx
  src/domains/wallet/components/ReceiveFunds/ReceiveFunds.tsx
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/components/SearchWallet/SearchWallet.models.ts
  src/domains/wallet/components/SearchWallet/SearchWallet.stories.tsx
  src/domains/wallet/components/SearchWallet/SearchWallet.test.tsx
  src/domains/wallet/components/SearchWallet/SearchWallet.tsx
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/tests/fixtures/env/storage.json
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#2787 refactor: close bottom menu when clicking on wallet
  src/app/components/WalletListItem/WalletListItem.test.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/dashboard/components/Wallets/Wallets.test.tsx
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/WalletBottomSheetMenu.stories.tsx
  src/domains/wallet/components/WalletBottomSheetMenu/WalletBottomSheetMenu.test.tsx
  src/domains/wallet/components/WalletBottomSheetMenu/WalletBottomSheetMenu.tsx
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2786 feat: add react-toastify
  config-overrides.js
  package.json
  src/app/App.tsx
  src/app/__snapshots__/App.test.tsx.snap
  src/app/services/ToastService.test.ts
  src/app/services/ToastService.ts
  src/app/services/index.ts
  src/styles/app.css
  src/styles/toasts.css
  yarn.lock
Labels: Complexity: Medium, Type: Feature

#2789 refactor: remove blockchain registrations
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/BlockchainTable.stories.tsx
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/BlockchainTable.test.tsx
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/BlockchainTable.tsx
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/index.ts
Labels: Complexity: Undetermined, Type: Refactor

#2788 chore: update Platform SDK dependencies
  package.json
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/BusinessTable.test.tsx
  yarn.lock
Labels: Complexity: High

#2790 refactor: agnostic entity table
  src/domains/profile/e2e/my-registrations-routing.e2e.ts
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/BusinessTable.stories.tsx
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/index.ts
  src/domains/profile/pages/MyRegistrations/components/EntityTable/EntityTable.stories.tsx
  src/domains/profile/pages/MyRegistrations/components/EntityTable/EntityTable.test.tsx
  src/domains/profile/pages/MyRegistrations/components/EntityTable/EntityTable.tsx
  src/domains/profile/pages/MyRegistrations/components/EntityTable/EntityTableRowItem.tsx
  src/domains/profile/pages/MyRegistrations/components/EntityTable/__snapshots__/EntityTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/EntityTable/index.ts
Labels: Complexity: Undetermined

#2792 fix: stop duplicate fee syncing
  src/app/App.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.test.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.test.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.test.tsx
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.test.tsx
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/utils/testing-library.tsx
Labels: Complexity: Medium

#2794 ci: run drafts only on `3.0-react` branch
  .github/workflows/draft-artifacts.yml
Labels: Complexity: Low

#2795 refactor: remove last fee
  src/app/components/Input/InputRange.stories.tsx
  src/domains/transaction/components/BusinessRegistrationForm/BusinessRegistrationForm.test.tsx
  src/domains/transaction/components/BusinessRegistrationForm/BusinessRegistrationForm.tsx
  src/domains/transaction/components/BusinessRegistrationForm/__snapshots__/BusinessRegistrationForm.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/InputFee/InputFee.stories.tsx
  src/domains/transaction/components/InputFee/InputFee.test.tsx
  src/domains/transaction/components/InputFee/InputFee.tsx
  src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.stories.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.models.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.models.ts
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.tsx
  src/domains/transaction/pages/SendEntityResignation/Step1.tsx
  src/domains/transaction/pages/SendEntityResignation/Step2.tsx
  src/domains/transaction/pages/SendEntityResignation/Step4.tsx
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/Step1.tsx
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/SendVote.test.tsx
  src/domains/transaction/pages/SendVote/Step1.tsx
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
Labels: Complexity: High

#2785 feat: second signature registration
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step1.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step2.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step3.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step4.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/index.ts
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/tests/fixtures/coins/ark/transactions/second-signature-registration.json
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#2799 feat: sync wallet votes when import a wallet
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/tests/fixtures/coins/ark/wallets/DC8ghUdhS8w8d11K8cFQ37YsLBFhL3Dq2P.json
  src/utils/e2e-utils.ts
Labels: Complexity: Low, Type: Feature

#2798 feat: implement plugins in `MyRegistrations`
  src/domains/profile/e2e/my-registrations-routing.e2e.ts
  src/domains/profile/i18n.ts
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/EntityTable/EntityTable.stories.tsx
  src/domains/profile/pages/MyRegistrations/components/EntityTable/EntityTable.test.tsx
  src/domains/profile/pages/MyRegistrations/components/EntityTable/EntityTable.tsx
  src/domains/profile/pages/MyRegistrations/components/EntityTable/EntityTableRowItem.tsx
  src/domains/profile/pages/MyRegistrations/components/EntityTable/__snapshots__/EntityTable.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/tests/fixtures/registrations/plugins.json
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2803 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High

#2813 feat: add avatar preview
  package.json
  src/app/components/SelectProfileImage/SelectProfileImage.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  yarn.lock
Labels: Complexity: High, Type: Feature

#2816 refactor: transfer details adjustments
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransferDetail/TransferDetail.test.tsx
  src/domains/transaction/components/TransferDetail/TransferDetail.tsx
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/i18n.ts
Labels: Complexity: Undetermined, Type: Refactor

#2760 feat: business entity registration
  config-overrides.js
  package.json
  src/app/components/Form/FormField.tsx
  src/domains/transaction/components/BusinessRegistrationForm/BusinessRegistrationForm.test.tsx
  src/domains/transaction/components/BusinessRegistrationForm/BusinessRegistrationForm.tsx
  src/domains/transaction/components/BusinessRegistrationForm/__snapshots__/BusinessRegistrationForm.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.test.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx
  src/domains/transaction/components/EntityRegistrationForm/Step2.tsx
  src/domains/transaction/components/EntityRegistrationForm/Step3.tsx
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/InputFee/InputFee.tsx
  src/domains/transaction/components/LinkCollection/LinkCollection.models.ts
  src/domains/transaction/components/LinkCollection/LinkCollection.stories.tsx
  src/domains/transaction/components/LinkCollection/LinkCollection.test.tsx
  src/domains/transaction/components/LinkCollection/LinkCollection.tsx
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/LinkList/LinkList.stories.tsx
  src/domains/transaction/components/LinkList/LinkList.test.tsx
  src/domains/transaction/components/LinkList/LinkList.tsx
  src/domains/transaction/entity/providers.test.ts
  src/domains/transaction/entity/providers.ts
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.models.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/Step1.tsx
  src/domains/transaction/pages/SendEntityUpdate/Step2.tsx
  src/tests/fixtures/coins/ark/transactions/entity-registration.json
  src/tests/fixtures/coins/ark/transactions/entity-resignation.json
  src/tests/fixtures/coins/ark/transactions/entity-update.json
  yarn.lock
Labels: Complexity: Undetermined, Type: Feature

#2811 feat: implement profile reset
  src/app/components/NavigationBar/NavigationBar.stories.tsx
  src/data/platform-sdk.ts
  src/domains/profile/components/DeleteProfile/DeleteProfile.tsx
  src/domains/profile/components/ResetProfile/ResetProfile.test.tsx
  src/domains/profile/components/ResetProfile/ResetProfile.tsx
  src/domains/profile/components/ResetProfile/__snapshots__/ResetProfile.test.tsx.snap
  src/domains/profile/components/ResetProfile/index.ts
  src/domains/profile/i18n.ts
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/e2e/reset-profile.e2e.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/setting/pages/Settings/available-settings/Peer.tsx
  src/domains/setting/pages/Settings/available-settings/Plugins.tsx
  src/tests/fixtures/env/storage.json
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2804 feat: add reusable `EmptyResults` component
  src/app/assets/images/index.ts
  src/app/assets/images/no-results.svg
  src/app/components/EmptyResults/EmptyResults.stories.tsx
  src/app/components/EmptyResults/EmptyResults.test.tsx
  src/app/components/EmptyResults/EmptyResults.tsx
  src/app/components/EmptyResults/__snapshots__/EmptyResults.test.tsx.snap
  src/app/components/EmptyResults/index.ts
  src/app/i18n/common/i18n.ts
  src/domains/news/e2e/filtering.e2e.ts
  src/domains/news/i18n.ts
  src/domains/news/images/index.ts
  src/domains/news/pages/News/News.test.tsx
  src/domains/news/pages/News/News.tsx
Labels: Complexity: High, Type: Feature

#2810 feat: sign transactions with 2nd mnemonic
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.test.tsx
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.tsx
  src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap
  src/domains/transaction/components/AuthenticationStep/index.ts
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/e2e/delegate-registration.e2e.ts
  src/domains/transaction/e2e/delegate-resignation.e2e.ts
  src/domains/transaction/e2e/ipfs-transaction.e2e.ts
  src/domains/transaction/e2e/multiple-transfer.e2e.ts
  src/domains/transaction/e2e/single-transfer.e2e.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.models.ts
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.test.tsx
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.tsx
  src/domains/transaction/pages/SendEntityResignation/Step3.tsx
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/index.ts
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
  src/domains/transaction/pages/SendIpfs/Step3.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/Step3.tsx
  src/domains/transaction/pages/SendTransfer/Step4.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/SendVote.test.tsx
  src/domains/transaction/pages/SendVote/SendVote.tsx
  src/domains/transaction/pages/SendVote/Step3.tsx
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
Labels: Complexity: Undetermined, Type: Feature

#2805 feat: implement search in `MyRegistrations`
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.test.tsx
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/profile/e2e/my-registrations-search.e2e.ts
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/utils.ts
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
Labels: Complexity: Undetermined, Type: Feature

#2824 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High

#2823 fix: top margin on sections
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Layout/components/Section/Section.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/EntityTable/__snapshots__/EntityTable.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Bugfix

#2829 chore: add compendia/bind icon
  src/app/assets/svg/currencies/bind.svg
  src/app/assets/svg/currencies/index.ts
  src/domains/network/data.ts
  src/domains/setting/data.ts
  src/domains/wallet/data.ts
Labels: Complexity: Low

#2830 chore: rename currency icons to match their symbol
  src/app/assets/svg/currencies/index.ts
  src/app/components/Badge/Badge.stories.tsx
  src/app/components/Circle/Circle.stories.tsx
  src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap
  src/app/components/Icon/__snapshots__/Icon.test.tsx.snap
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/Slider/Slider.stories.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/network/data.ts
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/components/PeerListItem/__snapshots__/PeerListItem.test.tsx.snap
  src/domains/setting/data.ts
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/EntityResignationSteps/Step2/EntitySecondStep.tsx
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/Step2.tsx
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/Step2.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/Step2.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/Step1.tsx
  src/domains/transaction/pages/SendVote/Step2.tsx
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/components/SearchWallet/SearchWallet.tsx
  src/domains/wallet/data.ts
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium

#2836 refactor: use NetworkIcon in wallet card and list
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/WalletCard/WalletCard.stories.tsx
  src/app/components/WalletCard/WalletCard.test.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/contact/components/ContactForm/ContactForm.tsx
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/network/components/NetworkIcon/NetworkIcon.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
Labels: Complexity: Undetermined, Type: Refactor

#2835 refactor: upgrade react-hook-form to 6.x
  package.json
  src/app/components/Form/Form.tsx
  src/app/components/Form/FormField.test.tsx
  src/app/components/Form/FormField.tsx
  src/app/components/Input/InputAddress.tsx
  src/domains/contact/components/ContactForm/ContactForm.tsx
  src/domains/profile/components/SignIn/SignIn.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/available-settings/Password.tsx
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.test.tsx
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.test.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx
  src/domains/transaction/components/EntityRegistrationForm/Step2.tsx
  src/domains/transaction/components/EntityRegistrationForm/Step3.tsx
  src/domains/transaction/components/LinkCollection/LinkCollection.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.test.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step1.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step2.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step3.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.stories.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.tsx
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
  src/domains/transaction/pages/SendIpfs/Step1.tsx
  src/domains/transaction/pages/SendIpfs/Step2.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/Step1.tsx
  src/domains/transaction/pages/SendTransfer/Step2.tsx
  src/domains/transaction/pages/SendVote/SendVote.tsx
  src/domains/transaction/pages/SendVote/Step1.tsx
  src/domains/wallet/components/UpdateWalletName/UpdateWalletName.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/Step1.tsx
  src/domains/wallet/pages/CreateWallet/Step2.tsx
  src/domains/wallet/pages/CreateWallet/Step3.tsx
  src/domains/wallet/pages/CreateWallet/Step4.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/Step1.tsx
  src/domains/wallet/pages/ImportWallet/Step2.tsx
  src/domains/wallet/pages/ImportWallet/Step3.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor

#2837 fix: icons in news components
  src/app/components/FilterNetwork/FilterNetwork.tsx
  src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap
  src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/news/components/NewsCard/NewsCard.tsx
  src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap
  src/domains/news/components/NewsOptions/NewsOptions.test.tsx
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/news/data.ts
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2826 refactor: update types according to AIP36 changes
  config/index.js
  src/renderer/components/Wallet/WalletAddress.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/mixins/transaction-types.js
Labels: Complexity: Medium, Type: Refactor

#2840 fix: margins on my registrations
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateRowItem.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateTable.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateRowItem.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/EntityTable/EntityTable.tsx
  src/domains/profile/pages/MyRegistrations/components/EntityTable/__snapshots__/EntityTable.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Bugfix

#2843 refactor: support and persist multiple active filters
  package.json
  src/domains/news/components/NewsOptions/NewsOptions.stories.tsx
  src/domains/news/components/NewsOptions/NewsOptions.test.tsx
  src/domains/news/components/NewsOptions/NewsOptions.tsx
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/news/e2e/filtering.e2e.ts
  src/domains/news/pages/News/News.test.tsx
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor

#2841 refactor: update synchronized data
  src/__snapshots__/index.test.ts.snap
  src/app/App.test.tsx
  src/app/App.tsx
  src/app/__snapshots__/App.test.tsx.snap
  src/app/hooks/use-synchronizer.test.tsx
  src/app/hooks/use-synchronizer.tsx
  src/app/services/Scheduler.test.ts
  src/app/services/Scheduler.ts
  src/app/services/index.ts
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowConfirmation.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.test.tsx
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.tsx
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#2834 feat: use real data for `PercentageBar` component
  src/app/components/PercentageBar/PercentageBar.stories.tsx
  src/app/components/PercentageBar/PercentageBar.test.tsx
  src/app/components/PercentageBar/PercentageBar.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.stories.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Labels: Complexity: Low, Type: Feature

#2844 feat: implement mnemonic download
  filePath
  src/app/components/Alert/Alert.tsx
  src/app/components/Alert/__snapshots__/Alert.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/plugin/components/PluginInfo/__snapshots__/PluginInfo.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step1.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step2.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/Step2.tsx
  src/domains/wallet/pages/CreateWallet/Step4.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/styles/toasts.css
  src/utils/electron-utils.test.ts
  src/utils/electron-utils.ts
Labels: Complexity: Undetermined, Type: Feature

#2833 feat: consume fees to build transactions
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.test.tsx
  src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.tsx
  src/domains/transaction/pages/SendEntityUpdate/Step1.tsx
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/Step1.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendVote/Step1.tsx
Labels: Status: Needs Review, Type: Feature

#2845 fix: remove negative margin on first bar item
  src/app/components/PercentageBar/PercentageBar.tsx
  src/app/components/PercentageBar/__snapshots__/PercentageBar.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#2846 refactor: use index as key for mnemonic list
  src/domains/wallet/components/MnemonicList/MnemonicList.tsx
  src/domains/wallet/components/MnemonicVerification/MnemonicVerificationProgress.tsx
  src/domains/wallet/components/MnemonicVerification/__snapshots__/MnemonicVerificationProgress.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2853 test: add e2e tests to send a vote transaction
  src/domains/vote/e2e/votes.e2e.ts
Labels: Complexity: Medium, Test: Unit

#2852 refactor: add `Select All` button to news options
  src/app/i18n/common/i18n.ts
  src/domains/news/components/NewsOptions/NewsOptions.tsx
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/news/components/NewsOptions/components/SelectCategory/SelectCategory.stories.tsx
  src/domains/news/data.ts
  src/domains/news/e2e/filtering.e2e.ts
  src/domains/news/pages/News/News.test.tsx
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2832 feat: implement `SendEntityUpdate`
  package.json
  src/app/hooks/validations.ts
  src/app/i18n/common/i18n.ts
  src/domains/profile/e2e/common.ts
  src/domains/profile/e2e/my-registrations-routing.e2e.ts
  src/domains/profile/e2e/my-registrations-search.e2e.ts
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateRowItem.test.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateRowItem.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateTable.test.tsx
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.test.tsx
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.test.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx
  src/domains/transaction/components/EntityRegistrationForm/FormStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/ReviewStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/SentStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/index.ts
  src/domains/transaction/components/LinkCollection/LinkCollection.tsx
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/e2e/common.ts
  src/domains/transaction/e2e/delegate-resignation.e2e.ts
  src/domains/transaction/e2e/entity-update.e2e.ts
  src/domains/transaction/e2e/transactions-routing.e2e.ts
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step3.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.test.tsx
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.test.tsx
  src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.tsx
  src/domains/transaction/pages/SendEntityUpdate/Step1.tsx
  src/domains/transaction/pages/SendEntityUpdate/Step2.tsx
  src/domains/transaction/pages/SendEntityUpdate/Step3.tsx
  src/domains/transaction/pages/SendEntityUpdate/Step4.tsx
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/utils.ts
  src/domains/transaction/routing.ts
  src/domains/transaction/validations/Authentication.ts
  src/domains/transaction/validations/EntityRegistration.ts
  src/domains/transaction/validations/index.ts
  src/tests/fixtures/ipfs/QmRwgWaaEyYgGqp55196TsFDQLW4NZkyTnPwiSVhJ7NPRV.json
  src/tests/fixtures/registrations/DC8ghUdhS8w8d11K8cFQ37YsLBFhL3Dq2P-businesses.json
  src/utils/e2e-utils.ts
  yarn.lock
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2856 refactor: adjust styles of `TotalAmountBox` and remove hardcoded ticker
  src/app/__snapshots__/App.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/ReviewStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/EntityResignationSteps/Step2/EntitySecondStep.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step4.tsx
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.stories.tsx
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.test.tsx
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx
  src/domains/transaction/components/TotalAmountBox/__snapshots__/TotalAmountBox.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.test.tsx
  src/domains/transaction/pages/SendEntityResignation/Step2.tsx
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/Step2.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/Step2.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/Step2.tsx
Labels: Complexity: High, Type: Refactor

#2857 feat: add tx modal to wallet details page
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Feature

#2854 refactor: transfer form adjustments
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/RecipientList/RecipientList.models.ts
  src/domains/transaction/components/RecipientList/RecipientList.stories.tsx
  src/domains/transaction/components/RecipientList/RecipientList.test.tsx
  src/domains/transaction/components/RecipientList/RecipientList.tsx
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/Step1.tsx
  src/domains/transaction/pages/SendTransfer/Step2.tsx
  src/domains/transaction/pages/SendTransfer/Step4.tsx
  src/domains/transaction/pages/SendTransfer/Step5.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#2855 fix: error when importing first wallet of network
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/Step1.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#2858 refactor: delegate registration form adjustments
  src/app/hooks/validations.ts
  src/app/i18n/common/i18n.ts
  src/domains/profile/e2e/create-profile-action.e2e.ts
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/validations/DelegateRegistration.ts
  src/domains/transaction/validations/index.ts
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2851 refactor: adjust styles of import success step
  src/domains/transaction/e2e/common.ts
  src/domains/transaction/e2e/ipfs-transaction.e2e.ts
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/Step3.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2860 release: 2.9.4
  .github/workflows/draft-artifacts.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  package.json
Labels: Complexity: Medium, Type: Task

#2859 refactor: add vote and register buttons to wallet details
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/WalletRegistrations.test.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/WalletRegistrations.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.test.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2818 fix: adjust fee value conversion logic between ways of input
  src/app/components/Input/InputCurrency.test.tsx
  src/app/components/Input/InputCurrency.tsx
  src/app/components/Input/InputRange.stories.tsx
  src/app/components/Input/InputRange.test.tsx
  src/app/components/Input/InputRange.tsx
  src/app/components/Input/__snapshots__/InputRange.test.tsx.snap
  src/app/components/SelectDropdown/SelectDropdown.stories.tsx
  src/domains/news/e2e/filtering.e2e.ts
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/InputFee/InputFee.stories.tsx
  src/domains/transaction/components/InputFee/InputFee.test.tsx
  src/domains/transaction/components/InputFee/InputFee.tsx
  src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step1.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/Step1.tsx
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2863 chore: remove hardcoded color in compendia icon
  src/app/assets/svg/currencies/bind.svg
Labels: Complexity: Low, Type: Task

#2868 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2875 feat: add pagination to the list of delegates
  src/domains/vote/components/DelegateTable/DelegateTable.test.tsx
  src/domains/vote/components/DelegateTable/DelegateTable.tsx
  src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
Labels: Complexity: High, Type: Feature

#2872 test: fix `InputCurrency` tests
  src/app/components/Input/InputCurrency.test.tsx
Labels: Complexity: Low, Test: Unit

#2871 feat: add second signature detail
  src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.stories.tsx
  src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.test.tsx
  src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.tsx
  src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SecondSignatureDetail/index.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/i18n.ts
Labels: Complexity: Undetermined, Type: Feature

#2879 refactor: show network icons only on input focus
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/contact/e2e/create-contact.e2e.ts
  src/domains/contact/e2e/update-contact.e2e.ts
  src/domains/network/components/SelectNetwork/SelectNetwork.test.tsx
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/e2e/common.ts
  src/domains/transaction/e2e/ipfs-transaction.e2e.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/vote/e2e/votes.e2e.ts
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/e2e/create-wallet-action.e2e.ts
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/Step1.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/Step1.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2881 refactor: adjustments and fixes in send ipfs steps
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.tsx
  src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
  src/domains/transaction/pages/SendIpfs/Step1.tsx
  src/domains/transaction/pages/SendIpfs/Step2.tsx
  src/domains/transaction/pages/SendIpfs/Step4.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/Step1.tsx
  src/domains/wallet/pages/CreateWallet/Step2.tsx
  src/domains/wallet/pages/CreateWallet/Step3.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/Step1.tsx
  src/domains/wallet/pages/ImportWallet/Step2.tsx
  src/domains/wallet/pages/ImportWallet/Step3.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2874 feat: show pending transactions
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.test.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowInfo.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.tsx
  src/tests/fixtures/env/storage.json
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2847 feat: send multisignature registration
  src/domains/profile/components/SelectRecipient/SelectRecipient.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.test.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx
  src/domains/transaction/components/EntityRegistrationForm/SentStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/MultiSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/MultiSignatureRegistrationForm.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/Step1.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/Step2.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/AddParticipant.test.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/AddParticipant.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/index.ts
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.test.tsx
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.models.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step3.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.tsx
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/tests/fixtures/coins/ark/transactions/multisignature-registration.json
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2867 fix: not a number in amount box
  src/app/components/Input/InputCurrency.test.tsx
  src/app/components/Input/InputCurrency.tsx
  src/app/components/Input/InputRange.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx
  src/domains/transaction/components/EntityRegistrationForm/ReviewStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/SentStep.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/MultiSignatureRegistrationForm.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/Step2.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step4.tsx
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/Step2.tsx
  src/domains/transaction/pages/SendTransfer/Step2.tsx
  src/domains/transaction/pages/SendVote/SendVote.test.tsx
  src/domains/transaction/pages/SendVote/Step2.tsx
  src/domains/transaction/utils.test.ts
  src/domains/transaction/utils.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2886 refactor: adjustments and fixes in transfer details
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.test.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.tsx
  src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionAmount/TransactionAmount.tsx
  src/domains/transaction/components/TransactionDetail/TransactionRecipients/TransactionRecipients.test.tsx
  src/domains/transaction/components/TransactionDetail/TransactionRecipients/TransactionRecipients.tsx
  src/domains/transaction/components/TransactionDetail/TransactionRecipients/__snapshots__/TransactionRecipients.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransferDetail/TransferDetail.tsx
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/tests/fixtures/transactions/index.ts
Labels: Complexity: Undetermined, Type: Refactor

#2887 refactor: adjustments and fixes in ipfs details
  src/app/assets/svg/ipfs.svg
  src/domains/transaction/components/IpfsDetail/IpfsDetail.test.tsx
  src/domains/transaction/components/IpfsDetail/IpfsDetail.tsx
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/Step2.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2885 refactor: adjustments and fixes in send vote steps
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.tsx
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionDetail.tsx
  src/domains/transaction/components/TransactionDetail/TransactionNetwork/TransactionNetwork.test.tsx
  src/domains/transaction/components/TransactionDetail/TransactionNetwork/TransactionNetwork.tsx
  src/domains/transaction/components/TransactionDetail/TransactionNetwork/__snapshots__/TransactionNetwork.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionNetwork/index.ts
  src/domains/transaction/components/TransactionDetail/TransactionSender/TransactionSender.tsx
  src/domains/transaction/components/TransactionDetail/TransactionSender/__snapshots__/TransactionSender.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/index.ts
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendTransfer/Step4.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/SendVote.test.tsx
  src/domains/transaction/pages/SendVote/SendVote.tsx
  src/domains/transaction/pages/SendVote/Step1.tsx
  src/domains/transaction/pages/SendVote/Step2.tsx
  src/domains/transaction/pages/SendVote/Step4.tsx
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/components/VoteList/VoteList.tsx
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2888 refactor: fix network select in votes page
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2891 refactor: adjustments and fixes in second signature details
  src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.test.tsx
  src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.tsx
  src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2889 refactor: adjustments and fixes in `TransactionSuccessful` component
  src/domains/transaction/components/TransactionDetail/TransactionExplorerLink/TransactionExplorerLink.tsx
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2890 feat: basic ledger setup and listener
  .eslintrc.js
  .github/workflows/e2e.yml
  .github/workflows/format.yml
  .github/workflows/test.yml
  .storybook/main.js
  .storybook/mocks/fsMock.js
  .yarnrc
  config-overrides.js
  package.json
  src/app/App.tsx
  src/domains/network/data.ts
  src/domains/transaction/components/LedgerListener/LedgerListener.models.ts
  src/domains/transaction/components/LedgerListener/LedgerListener.test.tsx
  src/domains/transaction/components/LedgerListener/LedgerListener.ts
  src/domains/transaction/components/LedgerListener/index.ts
  src/electron/index.js
  tsconfig.json
  yarn.lock
Labels: Complexity: High, Type: Feature

#2896 refactor: adjustments and fixes in delegate registration details
  src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.test.tsx
  src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.tsx
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2895 test: add e2e tests to vote transaction
  src/domains/transaction/e2e/ipfs-transaction.e2e.ts
  src/domains/transaction/e2e/single-transfer.e2e.ts
  src/domains/transaction/e2e/transactions-routing.e2e.ts
  src/domains/transaction/e2e/vote-transaction.e2e.ts
Labels: Complexity: Medium, Test: Unit

#2894 fix: render the address table if select another network on the voting page
  src/domains/vote/components/AddressTable/AddressRow/AddressRowSkeleton.tsx
  src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#2897 feat: add delegate resignation details
  src/domains/transaction/components/DelegateResignationDetail/DelegateResignationDetail.stories.tsx
  src/domains/transaction/components/DelegateResignationDetail/DelegateResignationDetail.test.tsx
  src/domains/transaction/components/DelegateResignationDetail/DelegateResignationDetail.tsx
  src/domains/transaction/components/DelegateResignationDetail/__snapshots__/DelegateResignationDetail.test.tsx.snap
  src/domains/transaction/components/DelegateResignationDetail/index.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/i18n.ts
Labels: Complexity: High, Type: Feature

#2899 chore: update Platform SDK dependencies
  package.json
  src/domains/contact/components/ContactForm/ContactForm.tsx
  src/domains/contact/components/CreateContact/CreateContact.tsx
  src/domains/contact/components/UpdateContact/UpdateContact.tsx
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/network/components/SelectNetwork/SelectNetworkInput.tsx
  src/domains/network/data.ts
  src/domains/setting/components/CustomPeers/CustomPeers.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/TransactionDetail/TransactionNetwork/TransactionNetwork.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendIpfs/Step1.tsx
  src/domains/transaction/pages/SendTransfer/Step1.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/wallet/pages/CreateWallet/Step1.tsx
  src/domains/wallet/pages/CreateWallet/Step4.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/Step1.tsx
  src/domains/wallet/pages/ImportWallet/Step2.tsx
  src/domains/wallet/pages/ImportWallet/Step3.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/tests/fixtures/env/storage-mainnet.json
  src/tests/fixtures/env/storage.json
  yarn.lock
Labels: Complexity: High

#2893 fix: hide border on sender in detail modals
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/IpfsDetail.tsx
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.tsx
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SecondSignatureDetail/SecondSignatureDetail.tsx
  src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionAmount/__snapshots__/TransactionAmount.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionConfirmations/__snapshots__/TransactionConfirmations.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionDetail.styles.ts
  src/domains/transaction/components/TransactionDetail/TransactionDetail.tsx
  src/domains/transaction/components/TransactionDetail/TransactionExplorerLink/__snapshots__/TransactionExplorerLink.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionFee/__snapshots__/TransactionFee.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionMemo/__snapshots__/TransactionMemo.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionNetwork/__snapshots__/TransactionNetwork.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionRecipients/__snapshots__/TransactionRecipients.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionSender/__snapshots__/TransactionSender.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionTimestamp/__snapshots__/TransactionTimestamp.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/__snapshots__/TransactionDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransferDetail/TransferDetail.tsx
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#2900 fix: adjust network to new format in jest mock
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/DelegateResignationDetail/__snapshots__/DelegateResignationDetail.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
Labels: Complexity: Low, Type: Bugfix

#2898 refactor: adjustments and fixes in vote details
  src/domains/transaction/components/TransactionDetail/TransactionFee/TransactionFee.tsx
  src/domains/transaction/components/TransactionDetail/TransactionVotes/TransactionVotes.test.tsx
  src/domains/transaction/components/TransactionDetail/TransactionVotes/TransactionVotes.tsx
  src/domains/transaction/components/TransactionDetail/TransactionVotes/__snapshots__/TransactionVotes.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionVotes/index.ts
  src/domains/transaction/components/TransactionDetail/index.ts
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/VoteDetail/VoteDetail.stories.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.test.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.tsx
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/transaction/pages/SendVote/Step4.tsx
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor
