Repository ArkEcosystem/desktop-wallet, pull requests merged in 2020-05, with the labels that each got.

#1822 feat: fetch remote fees from node api
  __tests__/unit/components/Input/InputFee.spec.js
  src/renderer/components/Input/InputFee.vue
  src/renderer/services/client.js
  src/renderer/utils/index.js
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#1904 refactor: transfer & multipayment in single modal
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmMultiPayment.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormMultiPayment.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormTransfer.spec.js
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmMultiPayment.vue
  src/renderer/components/Transaction/TransactionForm/TransactionForm.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormMultiPayment.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/index.js
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Transaction/TransactionRecipientList.vue
  src/renderer/components/Transaction/TransactionShow/TransactionShow.vue
  src/renderer/components/Transaction/index.js
  src/renderer/components/Wallet/WalletHeading/WalletHeadingPrimaryActions.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: High, Type: Refactor

#1899 chore(ledger): fix payload encoding
  __tests__/unit/services/ledger-service.spec.js
  __tests__/unit/services/transaction.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  src/renderer/services/ledger-service.js
  src/renderer/services/transaction.js
  src/renderer/store/modules/ledger.js
Labels: Complexity: Low, Type: Task

#1897 refactor: replace some lodash methods with native alternatives
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Collapse/CollapseAccordion.vue
  src/renderer/components/Input/InputAddress.vue
  src/renderer/components/Input/InputCurrency.vue
  src/renderer/components/Input/InputDelegate.vue
  src/renderer/components/Input/InputGrid/InputGrid.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue
  src/renderer/components/PluginManager/PluginManagerSideMenu.vue
  src/renderer/components/Selection/mixin-selection-image.js
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/pages/Wallet/WalletNew.vue
  src/renderer/services/client.js
  src/renderer/services/plugin-manager/setup/languages-setup.js
  src/renderer/services/plugin-manager/setup/themes-setup.js
  src/renderer/services/synchronizer.js
  src/renderer/store/index.js
  src/renderer/store/modules/network.js
  src/renderer/store/modules/peer.js
  src/renderer/utils/index.js
Labels: Complexity: Low, Type: Refactor

#1913 refactor: remove v2 from endpoint requests
  __tests__/unit/components/Network/NetworkModal.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/store/modules/delegate.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  __tests__/unit/store/modules/peer.spec.js
  __tests__/unit/store/modules/transaction.spec.js
  package.json
  src/renderer/services/client.js
  src/renderer/store/modules/peer.js
  yarn.lock
Labels: Complexity: Low, Type: Task

#1923 fix: timeout NPM requests and continue execution
  src/renderer/App.vue
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/adapters/npm-adapter.js
  src/renderer/services/wallet.js
  src/renderer/store/modules/network.js
  src/renderer/utils/http.js
Labels: Complexity: Low, Type: Bugfix

#1927 fix: ensure that password has value before validating it and better regex
  __tests__/unit/components/Input/InputPassword.spec.js
  src/renderer/components/Input/InputPassword.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Refactor

#1924 fix: use local seed list if peer discovery fails
  src/renderer/store/modules/peer/devnet.json
  src/renderer/store/modules/peer/fallback.js
  src/renderer/store/modules/peer/index.js
  src/renderer/store/modules/peer/mainnet.json
Labels: Complexity: High, Type: Bugfix

#1938 fix: remove debug error
  src/renderer/store/modules/peer/index.js
Labels: Complexity: Low, Type: Bugfix

#1939 chore: replace `@arkecosystem/platform-sdk` with `@arkecosystem/platform-sdk-markets`
  .eslintrc.js
  __tests__/unit.jest.conf.js
  __tests__/unit/__utils__/setup.js
  __tests__/unit/services/client.spec.js
  package.json
  src/renderer/services/price-api.ts
  yarn.lock
Labels: Complexity: Undetermined, Type: Task

#1940 chore: update dependencies to latest version
  .electron-vue/webpack.renderer.config.js
  .electron-vue/webpack.web.config.js
  __tests__/unit.jest.conf.js
  package.json
  yarn.lock
Labels: Complexity: Undetermined, Type: Task

#1936 feat: auto-add the recipient if loading the modal using a URI
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormTransfer.spec.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Feature

#1956 chore: set `allowRendererProcessReuse` to `false` to support ledger
  src/main/index.js
Labels: Complexity: Low, Type: Task

#1888 feat: reload multisignature list when adding/updating the ms peer
  src/renderer/components/Wallet/WalletMultiSignature/WalletMultiSignature.vue
Labels: Complexity: Low, Type: Feature

#1957 fix: does not show success message when canceling a save file dialog
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirm.vue
Labels: Complexity: Low, Type: Bugfix

#1975 refactor: replace `getdomain` dependency with native `URL`
  package.json
  src/renderer/components/PluginManager/PluginManagerModals/PluginDetailsModal.vue
  yarn.lock
Labels: Complexity: Low, Type: Refactor

#1977 feat: bind `Environment` instance on boot as `Vue.$env`
  src/renderer/main.js
  src/renderer/plugins/env.ts
  src/types.d.ts
Labels: Complexity: Low, Type: Feature

#1978 refactor: use `Vue` as EventBus instead of `Emittery`
  __tests__/unit/services/plugin-manager/sandbox/events-sandbox.spec.js
  package.json
  src/renderer/App.vue
  src/renderer/components/AlertMessage/AlertMessage.vue
  src/renderer/components/Dashboard/DashboardTransactions.vue
  src/renderer/components/Input/InputAddress.vue
  src/renderer/components/Modal/ModalWindow.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Transaction/TransactionShow/TransactionShow.vue
  src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechains.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeading.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingPrimaryActions.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.js
  src/renderer/components/Wallet/WalletTransactions/WalletTransactionsMultiSignature.js
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/plugins/alert-events.js
  src/renderer/plugins/event-bus.js
  src/renderer/services/plugin-manager/sandbox/events-sandbox.js
  src/renderer/services/synchronizer/wallets.js
  src/renderer/store/modules/ledger.js
  src/renderer/store/modules/network.js
  src/renderer/store/modules/transaction.js
  src/types.d.ts
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor

#1980 fix: use `EventBus.$off` instead of `EventBus.off`
  package.json
  src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechains.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeading.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.js
  src/renderer/components/Wallet/WalletTransactions/WalletTransactionsMultiSignature.js
  src/renderer/pages/Wallet/WalletAll.vue
  src/renderer/services/plugin-manager/sandbox/events-sandbox.js
  yarn.lock
Labels: Complexity: Medium, Type: Bugfix

#1981 refactor: pass in specific HTTP client to Environment
  package.json
  src/renderer/main.js
  src/renderer/plugins/env.ts
  src/renderer/plugins/http-client.ts
  src/renderer/services/http.ts
  tailwind.config.js
  tsconfig.json
  yarn.lock
Labels: Complexity: High, Type: Refactor

#1983 refactor: register `Vue.$eventBus` through a plugin
  src/renderer/App.vue
  src/renderer/main.js
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/plugins/env.ts
  src/renderer/plugins/event-bus.js
  src/renderer/plugins/event-bus.ts
  src/types.d.ts
Labels: Complexity: Undetermined, Type: Refactor

#1984 fix: explicitly import `eventBus` instance
  __tests__/unit/__utils__/setup.js
  __tests__/unit/services/plugin-manager/sandbox/events-sandbox.spec.js
  src/renderer/components/Button/ButtonSwitch.vue
  src/renderer/components/Collapse/CollapseAccordion.vue
  src/renderer/components/Input/InputCurrency.vue
  src/renderer/components/Input/InputLanguage.vue
  src/renderer/components/Input/InputPublicKey.vue
  src/renderer/components/Input/InputSelect.vue
  src/renderer/components/Input/InputText.vue
  src/renderer/components/Input/InputToggle/InputToggle.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue
  src/renderer/components/Menu/MenuNavigation/MenuNavigation.vue
  src/renderer/components/Menu/MenuStep/MenuStep.vue
  src/renderer/components/Menu/MenuTab/MenuTab.vue
  src/renderer/components/PluginManager/PluginManagerButtons/PluginManagerButtonSwitch.vue
  src/renderer/components/Selection/SelectionNetwork.vue
  src/renderer/components/Wallet/WalletSelection.vue
  src/renderer/models/base.js
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/services/synchronizer/wallets.js
  src/renderer/store/modules/ledger.js
  src/renderer/store/modules/network.js
  src/renderer/store/modules/transaction.js
Labels: Complexity: Medium, Type: Bugfix

#1987 fix: use `@Model` annotation for custom model
  src/renderer/components/Button/ButtonSwitch.vue
  src/renderer/components/Collapse/CollapseAccordion.vue
  src/renderer/components/Input/InputCurrency.vue
  src/renderer/components/Input/InputLanguage.vue
  src/renderer/components/Input/InputPublicKey.vue
  src/renderer/components/Input/InputSelect.vue
  src/renderer/components/Input/InputText.vue
  src/renderer/components/Input/InputToggle/InputToggle.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue
  src/renderer/components/Menu/MenuNavigation/MenuNavigation.vue
  src/renderer/components/Menu/MenuStep/MenuStep.vue
  src/renderer/components/Menu/MenuTab/MenuTab.vue
  src/renderer/components/PluginManager/PluginManagerButtons/PluginManagerButtonSwitch.vue
  src/renderer/components/Selection/SelectionNetwork.vue
  src/renderer/components/Wallet/WalletSelection.vue
Labels: Complexity: Medium, Type: Bugfix

#1988 refactor: use `Changed` suffix for `@Watch` handlers
  src/renderer/App.vue
  src/renderer/components/Button/ButtonSwitch.vue
  src/renderer/components/Collapse/Collapse.vue
  src/renderer/components/Collapse/CollapseAccordion.vue
  src/renderer/components/Input/InputAddress.vue
  src/renderer/components/Input/InputCurrency.vue
  src/renderer/components/Input/InputDelegate.vue
  src/renderer/components/Input/InputEditableList.vue
  src/renderer/components/Input/InputLanguage.vue
  src/renderer/components/Input/InputPassword.vue
  src/renderer/components/Input/InputPublicKey.vue
  src/renderer/components/Input/InputSelect.vue
  src/renderer/components/Input/InputText.vue
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue
  src/renderer/components/Menu/MenuNavigation/MenuNavigation.vue
  src/renderer/components/Menu/MenuTab/MenuTab.vue
  src/renderer/components/Modal/ModalExportWallets.vue
  src/renderer/components/Modal/ModalLoader.vue
  src/renderer/components/Passphrase/PassphraseInput.vue
  src/renderer/components/Passphrase/PassphraseVerification.vue
  src/renderer/components/PluginManager/PluginManagerButtons/PluginManagerButtonSwitch.vue
  src/renderer/components/PluginManager/PluginManagerSearchBar.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechains.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeading.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingSecondaryActions.vue
  src/renderer/components/Wallet/WalletSelection.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFiltersSearchInput.vue
  src/renderer/components/Wallet/WalletSignVerify/WalletSignVerify.vue
  src/renderer/components/Wallet/WalletTransactions/mixin.vue
  src/renderer/components/utils/Identicon.vue
  src/renderer/pages/Wallet/WalletImport.vue
  src/renderer/pages/Wallet/WalletShow.vue
Labels: Complexity: High, Type: Refactor

#1991 chore: disable splashscreen during development
  src/main/index.js
Labels: Complexity: Medium, Type: Task

#1992 refactor: replace `utils/http` with `HttpClient`
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormTransfer.spec.js
  src/renderer/components/App/AppUpdater.vue
  src/renderer/components/ListDivided/ListDividedItem.vue
  src/renderer/components/PluginManager/PluginManagerModals/PluginDetailsModal.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/main.js
  src/renderer/models/base.js
  src/renderer/services/http.ts
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/adapters/npm-adapter.js
  src/renderer/services/wallet.js
  src/renderer/store/modules/network.js
  src/renderer/utils/http.js
  tailwind.config.js
Labels: Complexity: Medium, Type: Refactor

#1993 refactor: remove announcements
  __tests__/unit/components/App/AppSidemenu/AppSidemenu.spec.js
  __tests__/unit/services/feed.spec.js
  __tests__/unit/store/modules/announcements.spec.js
  config/index.js
  package.json
  src/renderer/App.vue
  src/renderer/components/Announcements/AnnouncementsPost.vue
  src/renderer/components/Announcements/index.ts
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/enums/vuex.ts
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Announcements.vue
  src/renderer/plugins/alert-events.js
  src/renderer/router/index.js
  src/renderer/services/price-api.ts
  src/renderer/services/synchronizer.js
  src/renderer/services/synchronizer/announcements.js
  src/renderer/services/synchronizer/index.js
  src/renderer/services/wallet.js
  src/renderer/store/index.js
  src/renderer/store/migrations/2.8.2 - remove summary from read announcements.js
  src/renderer/store/modules/announcements.js
Labels: Complexity: High, Type: Refactor

#1997 feat: add alert component & storybook
  .storybook/.babelrc
  .storybook/addons.ts
  .storybook/main.js
  .storybook/preview.ts
  .storybook/tsconfig.json
  __tests__/unit.jest.conf.js
  __tests__/unit/app/Alert/Alert.test.ts
  package.json
  postcss.config.js
  src/renderer/app/Alert/Alert.stories.ts
  src/renderer/app/Alert/Alert.vue
  src/renderer/app/Navbar/Navbar.stories.ts
  tailwind.config.js
  yarn.lock
Labels: Complexity: Undetermined, Type: Feature

#1998 chore: update dependencies
  .eslintrc.json
  __tests__/unit/app/Alert/Alert.test.ts
  package.json
  postcss.config.js
  src/renderer/app/Alert/Alert.vue
  src/renderer/app/Navbar/Navbar.stories.ts
  src/renderer/domain/profile/pages/ProfileNew.vue
  tailwind.config.js
  yarn.lock
Labels: Complexity: Undetermined, Type: Task
