Repository ArkEcosystem/desktop-wallet, pull requests merged in 2020-03, with the labels that each got.

#1749 refactor: extract crypto behaviors out of the client service
  __tests__/unit/__utils__/error-capturer.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/services/crypto/transaction-signer.spec.js
  __tests__/unit/services/crypto/utils.spec.js
  __tests__/unit/services/feed.spec.js
  __tests__/unit/services/wallet.spec.js
  src/renderer/services/client.js
  src/renderer/services/crypto/bridgechain-registration.builder.js
  src/renderer/services/crypto/bridgechain-resignation.builder.js
  src/renderer/services/crypto/bridgechain-update.builder.js
  src/renderer/services/crypto/business-registration.builder.js
  src/renderer/services/crypto/business-resignation.builder.js
  src/renderer/services/crypto/business-update.builder.js
  src/renderer/services/crypto/configure-magistrate-transactions.js
  src/renderer/services/crypto/delegate-registration.builder.js
  src/renderer/services/crypto/delegate-resignation.builder.js
  src/renderer/services/crypto/ipfs.builder.js
  src/renderer/services/crypto/multi-payment.builder.js
  src/renderer/services/crypto/multi-signature.builder.js
  src/renderer/services/crypto/second-signature-registration.builder.js
  src/renderer/services/crypto/transaction-builder.service.js
  src/renderer/services/crypto/transaction-signer.js
  src/renderer/services/crypto/transfer.builder.js
  src/renderer/services/crypto/utils.js
  src/renderer/services/crypto/vote.builder.js
  src/renderer/services/wallet.js
Labels: Complexity: Undetermined, Type: Refactor

#1729 feat: integrate vuex-persist with exclusion of large data
  src/main/index.js
  src/renderer/App.vue
  src/renderer/SplashScreen.vue
  src/renderer/models/network.js
  src/renderer/services/wallet.js
  src/renderer/store/index.js
  src/renderer/store/modules/network.js
  src/renderer/store/plugins/vuex-persist.js
  src/renderer/styles/_general.css
  tailwind.js
Labels: Complexity: Medium, Type: Feature

#1756 fix: splashscreen showing on main window hide
  src/main/index.js
  src/main/menu.js
Labels: Complexity: High, Type: Bugfix

#1754 refactor: move `__watchProfile` out of the `ClientService`
  __tests__/unit/App.spec.js
  src/renderer/App.vue
  src/renderer/services/client.js
  src/renderer/store/modules/peer.js
Labels: Complexity: Medium, Type: Refactor

#1760 fix: main window fullscreen state when closing and re-opening
  src/main/index.js
Labels: Complexity: High, Type: Bugfix

#1759 refactor: replace various lodash methods with native alternatives
  src/renderer/components/App/AppSidemenu/AppSidemenuPlugins.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Input/InputAddress.vue
  src/renderer/components/Input/InputCurrency.vue
  src/renderer/components/Menu/MenuStep/MenuStep.vue
  src/renderer/components/Modal/ModalExportWallets.vue
  src/renderer/components/Passphrase/PassphraseVerification.vue
  src/renderer/components/PluginManager/PluginManagerSearchBar.vue
  src/renderer/components/PluginManager/PluginManagerSideMenu.vue
  src/renderer/components/PluginManager/PluginManagerTable.vue
  src/renderer/components/Transaction/TransactionForm/TransactionForm.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletSelection.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/components/Wallet/WalletSignVerify/WalletSignVerify.vue
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.js
  src/renderer/components/Wallet/WalletTransactions/WalletTransactionsMultiSignature.js
  src/renderer/mixins/index.js
  src/renderer/models/base.js
  src/renderer/models/profile.js
  src/renderer/pages/Profile/ProfileAll.vue
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/adapters/npm-adapter.js
  src/renderer/services/plugin-manager/component/get-context.js
  src/renderer/services/plugin-manager/sandbox/messaging-sandbox.js
  src/renderer/services/plugin-manager/setup/themes-setup.js
  src/renderer/services/plugin-manager/setup/wallet-tabs-setup.js
  src/renderer/services/price-api.js
  src/renderer/services/price-api/coin-cap.js
  src/renderer/services/price-api/coin-gecko.js
  src/renderer/services/price-api/crypto-compare.js
  src/renderer/services/synchronizer.js
  src/renderer/services/synchronizer/wallets.js
  src/renderer/store/base.js
  src/renderer/store/index.js
  src/renderer/store/migrations/2.4.0 - fix letter avatars.js
  src/renderer/store/migrations/2.5.2 - add marketChartOptions to profile.js
  src/renderer/store/modules/profile.js
  src/renderer/store/modules/transaction.js
  src/renderer/store/modules/wallet.js
  src/renderer/store/plugins/vuex-persist-migrations.js
  src/renderer/store/plugins/vuex-persist.js
  src/renderer/utils/index.js
Labels: Complexity: Medium, Type: Feature

#1755 perf: remove summary when marking announcement as read
  src/renderer/components/Announcements/AnnouncementsPost.vue
  src/renderer/models/announcement.js
  src/renderer/store/migrations/2.8.2 - remove summary from read announcements.js
  src/renderer/store/modules/announcements.js
Labels: Complexity: Low, Status: Member Approved, Type: Performance

#1741 feat: add links to multipayment list on transaction show
  src/renderer/components/Transaction/TransactionMultiPaymentList.vue
  src/renderer/components/Transaction/TransactionShow/TransactionShow.vue
  src/renderer/components/Wallet/WalletAddress.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Feature

#1742 fix: fetch wallet when adding/creating as contact
  src/renderer/components/Modal/ModalRename.vue
  src/renderer/pages/Contact/ContactNew.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1743 feat: show alternative balances in wallet grid
  src/renderer/components/Wallet/WalletGrid.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Feature

#1762 fix: access windows.main instead of window.main
  src/main/index.js
Labels: Complexity: Low, Type: Bugfix

#1763 fix: clear history on window reload via shortcuts
  src/main/index.js
Labels: Complexity: Low, Type: Bugfix

#1765 feat: plugin images & slider
  src/renderer/assets/svg/caret-left.svg
  src/renderer/assets/svg/caret-right.svg
  src/renderer/components/PluginManager/PluginManagerModals/PluginDetailsModal.vue
  src/renderer/components/PluginManager/PluginSlider.vue
  src/renderer/components/PluginManager/index.js
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/config-sanitizers.js
  src/renderer/services/plugin-manager/plugin-configuration.js
Labels: Complexity: Medium, Type: Feature

#1733 refactor: improve ledger ux
  __tests__/unit/store/modules/ledger.spec.js
  package.json
  src/renderer/components/Wallet/WalletHeading/WalletHeadingInfo.vue
  src/renderer/services/wallet.js
  src/renderer/store/modules/ledger.js
  yarn.lock
Labels: Complexity: Low, Type: Refactor

#1737 fix: add sorting to bridgechains table
  __tests__/unit/components/Wallet/WalletBusiness/WalletBusinessBridgechains.spec.js
  __tests__/unit/services/client.spec.js
  src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechains.vue
  src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechainsTable.vue
  src/renderer/services/client.js
  src/renderer/services/wallet.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1753 refactor: replace moment with dayjs
  package.json
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/mixins/formatter.js
  src/renderer/services/crypto/transaction-signer.js
  src/renderer/services/datetime.js
  src/renderer/services/plugin-manager.js
  src/renderer/services/price-api/coin-cap.js
  src/renderer/services/price-api/coin-gecko.js
  src/renderer/services/price-api/crypto-compare.js
  src/renderer/store/modules/transaction.js
  yarn.lock
Labels: Complexity: Low, Type: Refactor

#1769 refactor: more generic userLanguage handling
  src/renderer/mixins/formatter.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Refactor

#1768 fix: reload shortcut from other apps
  src/index.ejs
  src/main/index.js
  src/main/menu.js
Labels: Complexity: Low, Type: Bugfix

#1773 chore: update splash font
  src/renderer/SplashScreen.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Task

#1771 chore: bump version to 2.9.0
  .github/workflows/test.yml
  package.json
Labels: Complexity: Low, Type: Release

#1777 chore: add staging to workflow
  .github/workflows/draft-artifacts.yml
  .github/workflows/test.yml
  package.json
  yarn.lock
Labels: Complexity: Low, Type: Task

#1792 feat: expose more ui components to plugins
  src/renderer/services/plugin-manager/setup/ui-components-setup.js
Labels: Complexity: Low, Type: Feature

#1790 refactor: allow all global plugin options to be retrieved at once
  __tests__/unit/services/plugin-manager/sandbox/storage-sandbox.spec.js
  src/renderer/services/plugin-manager/sandbox/storage-sandbox.js
Labels: Bounty: Tier 4, Complexity: Low, Type: Refactor

#1789 feat: expose current peer to plugins and allow options in requests
  __tests__/unit/services/plugin-manager/sandbox/peer-current-sandbox.spec.js
  src/renderer/services/plugin-manager/sandbox/peer-current-sandbox.js
Labels: Bounty: Tier 4, Complexity: Low, Type: Feature

#1780 feat: expose the bignumber plugin and datetime service to plugins
  src/renderer/i18n/locales/en-US.js
  src/renderer/services/plugin-manager/plugin-permission.js
  src/renderer/services/plugin-manager/plugin-sandbox.js
  src/renderer/services/plugin-manager/sandbox/big-number-sandbox.js
  src/renderer/services/plugin-manager/sandbox/datetime-sandbox.js
Labels: Bounty: Tier 4, Complexity: Low, Type: Feature

#1787 chore: add 'watch' to allowed component keys
  src/renderer/services/plugin-manager/component/validate.js
Labels: Complexity: Low, Type: Task

#1793 feat: expose save/open dialogs to plugins
  config/index.js
  src/renderer/assets/svg/arrow-sent-received.svg
  src/renderer/mixins/electron.js
  src/renderer/pages/Contact/ContactAll.vue
  src/renderer/services/plugin-manager/plugin-permission.js
  src/renderer/services/plugin-manager/plugin-sandbox.js
  src/renderer/services/plugin-manager/sandbox/dialogs-sandbox.js
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Type: Feature

#1794 test: add unit tests for dialogs sandbox and electron mixin
  __tests__/unit/mixins/electron.spec.js
  __tests__/unit/services/plugin-manager/sandbox/dialogs-sandbox.spec.js
Labels: Bounty: Tier 5, Complexity: Medium, Status: Contributor Approved, Test: Unit

#1796 feat: allow to hide cancel button of confirmation modal
  __tests__/unit/components/Modal/ModalConfirmation.spec.js
  src/renderer/components/Modal/ModalConfirmation.vue
Labels: Complexity: Low, Status: Contributor Approved, Type: Feature

#1795 feat: expose profiles themes to plugins
  src/renderer/store/modules/profile.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#1781 fix: update dark theme for disabled button in menu
  src/renderer/components/Wallet/WalletHeading/WalletHeadingSecondaryActions.vue
  src/renderer/styles/_theme.css
Labels: Complexity: Low, Type: Bugfix

#1784 fix: dark theme tweaks
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdownItem.vue
  src/renderer/components/Transaction/TransactionStatusIcon.vue
Labels: Complexity: Low, Type: Bugfix

#1786 refactor: replace pricing api with @arkecosystem/platform-sdk
  __tests__/unit/__mocks__/@/services/wallet.js
  __tests__/unit/components/Network/NetworkModal.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainResignation.spec.js
  __tests__/unit/components/Wallet/WalletIpfs.spec.js
  __tests__/unit/components/Wallet/WalletTransactions/WalletTransactionsMultiSignature.spec.js
  __tests__/unit/pages/PluginManager/PluginManager.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/services/crypto/transaction-signer.spec.js
  __tests__/unit/services/price-api.spec.js
  config/index.js
  package.json
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/services/price-api.js
  src/renderer/services/price-api.ts
  src/renderer/services/price-api/coin-cap.js
  src/renderer/services/price-api/coin-gecko.js
  src/renderer/services/price-api/crypto-compare.js
  src/renderer/store/modules/market.js
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor

#1779 fix: access the vue-i18n property at the root
  src/renderer/components/Wallet/WalletHeading/WalletHeadingSecondaryActions.vue
Labels: Complexity: Low, Type: Bugfix

#1774 refactor: change wording for contact delete button
  src/renderer/components/Wallet/WalletHeading/WalletHeadingSecondaryActions.vue
  src/renderer/components/Wallet/WalletRemovalConfirmation.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Refactor

#1791 fix: multisig transaction type/group
  src/renderer/components/Transaction/TransactionTable/TransactionTableMultiSignature.vue
Labels: Complexity: Low, Type: Bugfix

#1758 fix: include typegroup when setting last fee
  __tests__/unit/store/modules/session.spec.js
  src/renderer/components/Input/InputFee.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/store/migrations/2.8.2 - fix last fees.js
  src/renderer/store/modules/session.js
Labels: Bounty: Tier 4, Complexity: Low, Type: Refactor

#1736 refactor: adjust business transaction form validation
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBusiness/TransactionFormBusinessUpdate.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBusiness/mixin.spec.js
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessUpdate.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBusiness/mixin.vue
  src/renderer/components/Wallet/WalletBusiness/WalletBusinessShowBridgechain.vue
Labels: Bounty: Tier 3, Complexity: Medium, Status: Member Approved, Type: Refactor

#1785 fix: back button after wallet reload
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
Labels: Complexity: Low

#1803 chore: bump version in all github configurations
  .github/workflows/draft-artifacts.yml
  .github/workflows/publish-release.yml
  scripts/version-artifacts.sh
Labels: Complexity: Low, Type: Task

#1808 feat: expose peer discovery to plugins
  __tests__/unit/services/plugin-manager/sandbox/peer-all-sandbox.spec.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/services/plugin-manager/plugin-permission.js
  src/renderer/services/plugin-manager/plugin-sandbox.js
  src/renderer/services/plugin-manager/sandbox/peer-all-sandbox.js
  src/renderer/services/plugin-manager/sandbox/peer-current-sandbox.js
Labels: Bounty: Tier 4, Complexity: Low, Type: Feature

#1802 fix: last fees migration
  src/renderer/store/migrations/2.9.0 - fix last fees.js
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#1747 fix: don't manipulate raw transaction when it is stored
  __tests__/unit/__mocks__/@/services/wallet.js
  __tests__/unit/components/Transaction/TransactionModal.spec.js
  src/renderer/components/Transaction/TransactionModal.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Bugfix

#1770 refactor: fix alignment of menu dropdown components
  __tests__/unit/components/Menu/MenuDropdown.spec.js
  src/renderer/components/App/AppIntro/AppIntro.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuNetworkStatus.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdown.vue
  src/renderer/components/PluginManager/PluginManagerButtons/PluginManagerButtonFilter.vue
  src/renderer/components/Wallet/WalletGrid.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Refactor

#1804 chore: add translation for DIALOGS permission
  src/renderer/i18n/locales/en-US.js
Labels: Bounty: Tier 6, Complexity: Low, Status: Member Approved, Type: Task

#1798 fix: unset innerHTML of plugin style when setting default theme
  src/renderer/App.vue
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#1782 chore: update mac menu titles
  package.json
  src/main/menu.js
Labels: Complexity: Low, Type: Bugfix

#1757 test: app components
  __tests__/unit/components/App/AppFooter.spec.js
  __tests__/unit/components/App/AppSidemenu/AppSidemenu.spec.js
  __tests__/unit/components/App/AppSidemenu/AppSidemenuImportantNotification.spec.js
  __tests__/unit/components/App/AppUpdater.spec.js
Labels: Bounty: Tier 4, Complexity: High, Status: Member Approved

#1805 fix: break words if the vendor field message is large
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmTransfer.vue
  src/renderer/components/Transaction/TransactionShow/TransactionShow.vue
Labels: Complexity: Low, Type: Bugfix

#1811 chore: fix alternative currency alignment
  src/renderer/components/Input/InputCurrency.vue
Labels: Bounty: Tier 5, Complexity: Low, Status: Contributor Approved, Status: Member Approved, Type: Task

#1826 refactor: try to fetch local plugin images first
  src/renderer/services/plugin-manager.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Refactor

#1815 feat: allow plugins to clear all options at once
  __tests__/unit/services/plugin-manager/sandbox/storage-sandbox.spec.js
  src/renderer/services/plugin-manager/sandbox/storage-sandbox.js
Labels: Bounty: Tier 4, Complexity: Medium, Status: Contributor Approved, Status: Member Approved, Type: Feature

#1814 refactor: wait for next tick when focussing password/passphrase input
  src/renderer/components/Input/InputPassword.vue
  src/renderer/components/Passphrase/PassphraseInput.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Refactor

#1767 feat: allow to set a default fee type
  __tests__/unit/components/Input/InputFee.spec.js
  __tests__/unit/store/modules/session.spec.js
  src/renderer/components/Input/InputFee.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/profile.js
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/store/modules/session.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Status: Needs Review, Type: Feature

#1833 feat: add scope to plugin routes and menu items
  __tests__/unit/services/plugin-manager/setup/menu-items-setup.spec.js
  __tests__/unit/services/plugin-manager/setup/routes-setup.spec.js
  src/renderer/services/plugin-manager/sandbox/route-sandbox.js
  src/renderer/services/plugin-manager/setup/menu-items-setup.js
  src/renderer/services/plugin-manager/setup/routes-setup.js
Labels: Bounty: Tier 4, Complexity: Low, Type: Feature

#1832 fix: remove sort option for IPFS from table
  src/renderer/components/Transaction/TransactionTable/TransactionTable.vue
Labels: Complexity: Low, Type: Bugfix

#1824 fix: include last delegate page when fetching
  __tests__/unit/store/modules/delegate.spec.js
  src/renderer/store/modules/delegate.js
Labels: Complexity: Low, Type: Bugfix

#1810 feat: multipayment display modals details
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmMultiPayment.spec.js
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmMultiPayment.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Transaction/TransactionShow/TransactionShow.vue
  src/renderer/i18n/locales/en-US.js
Labels: Bounty: Tier 3, Complexity: Low, Status: Contributor Approved, Status: Member Approved, Type: Feature

#1829 fix: plugin grid sorting
  __tests__/unit/components/PluginManager/PluginManagerGrid.spec.js
  src/renderer/components/PluginManager/PluginManagerGrid.vue
Labels: Complexity: Low, Type: Bugfix

#1831 feat: use the left and right arrows on the keyboard to switch between the plugin images
  src/renderer/components/PluginManager/PluginManagerModals/PluginImageModal.vue
Labels: Complexity: Low, Type: Feature

#1820 fix: add scrollbar to installed plugin list
  src/renderer/components/App/AppSidemenu/AppSidemenuPlugins.vue
Labels: Complexity: Low, Type: Bugfix

#1836 chore: add dayjs quarters plugin
  src/renderer/services/datetime.js
Labels: Bounty: Tier 5, Complexity: Low, Type: Task

#1837 feat: add names to plugin themes
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/services/plugin-manager/setup/themes-setup.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Feature

#1823 feat: sort menu items alphabetically
  __tests__/unit/components/utils/Sorting.spec.js
  __tests__/unit/store/modules/plugin.spec.js
  __tests__/unit/utils/sort-by-props.spec.js
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/mixins/wallet.js
  src/renderer/store/modules/plugin.js
  src/renderer/utils/index.js
  src/renderer/utils/sort-by-props.js
Labels: Bounty: Tier 4, Complexity: High, Type: Feature

#1830 refactor: activate the plugin menu item when navigating to plugin route
  __tests__/unit/components/App/AppSidemenu/AppSidemenu.spec.js
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/App/AppSidemenu/AppSidemenuPlugins.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Contributor Approved, Type: Refactor

#1816 fix: also delete global options when removing a plugin
  src/renderer/components/PluginManager/PluginManagerModals/PluginRemovalModal.vue
  src/renderer/store/modules/plugin.js
Labels: Bounty: Tier 4, Complexity: Low, Type: Bugfix

#1828 fix: close modal using the esc key after pressing other keys
  src/renderer/components/Modal/ModalWindow.vue
Labels: Complexity: Low, Type: Bugfix

#1818 fix: periodically update bridgechain list
  __tests__/unit/components/Wallet/WalletBusiness/WalletBusinessBridgechains.spec.js
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Wallet/WalletBusiness/WalletBusinessBridgechains.vue
  src/renderer/services/transaction.js
Labels: Complexity: Low, Type: Bugfix

#1834 fix: multisignature improvements
  __tests__/unit/services/transaction.spec.js
  package.json
  src/renderer/components/Transaction/TransactionForm/TransactionForm.vue
  src/renderer/components/Transaction/TransactionShow/TransactionShowMultiSignature.vue
  src/renderer/services/crypto/bridgechain-resignation.builder.js
  src/renderer/services/crypto/transaction-signer.js
  src/renderer/services/transaction.js
  yarn.lock
Labels: Complexity: High, Type: Bugfix

#1788 fix: bridgechain form ux when going to page 2
  src/renderer/components/Input/InputPassword.vue
  src/renderer/components/Passphrase/PassphraseInput.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.vue
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#1843 fix: windows builds
  .github/workflows/draft-artifacts.yml
  .github/workflows/publish-release.yml
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#1766 feat: fetch known wallets from repository
  __tests__/unit/components/Network/NetworkModal.spec.js
  config/networks/devnet.json
  config/networks/mainnet.json
  src/renderer/App.vue
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/network.js
  src/renderer/store/modules/network.js
Labels: Complexity: Low, Status: Member Approved, Type: Task

#1841 fix: spacing & word wrap of alerts
  src/renderer/components/AlertMessage/AlertMessage.vue
Labels: Complexity: Low, Type: Bugfix

#1850 chore: bump version to 2.9.1
  .github/workflows/draft-artifacts.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  package.json
Labels: Complexity: Medium, Type: Task

#1848 feat: allow plugins to add languages
  __tests__/unit/App.spec.js
  __tests__/unit/components/PluginManager/PluginManagerModals/PluginDetailsModal.spec.js
  __tests__/unit/components/PluginManager/PluginManagerSideMenu.spec.js
  __tests__/unit/i18n/i18n-setup.spec.js
  __tests__/unit/store/modules/plugin.spec.js
  config/index.js
  src/renderer/App.vue
  src/renderer/assets/images/flags/README.md
  src/renderer/assets/images/flags/bg-BG.svg
  src/renderer/assets/images/flags/cs-CZ.svg
  src/renderer/assets/images/flags/da-DK.svg
  src/renderer/assets/images/flags/de-DE.svg
  src/renderer/assets/images/flags/default.svg
  src/renderer/assets/images/flags/el-GR.svg
  src/renderer/assets/images/flags/es-ES.svg
  src/renderer/assets/images/flags/fr-FR.svg
  src/renderer/assets/images/flags/it-IT.svg
  src/renderer/assets/images/flags/ja-JP.svg
  src/renderer/assets/images/flags/ko-KR.svg
  src/renderer/assets/images/flags/nb-NO.svg
  src/renderer/assets/images/flags/nl-NL.svg
  src/renderer/assets/images/flags/pl-PL.svg
  src/renderer/assets/images/flags/pt-BR.svg
  src/renderer/assets/images/flags/ro-RO.svg
  src/renderer/assets/images/flags/ru-RU.svg
  src/renderer/assets/images/flags/se-SE.svg
  src/renderer/assets/images/flags/sk-SK.svg
  src/renderer/assets/images/flags/tr-TR.svg
  src/renderer/assets/images/flags/uk-UA.svg
  src/renderer/assets/images/flags/vi-VN.svg
  src/renderer/assets/images/flags/zh-CN.svg
  src/renderer/components/App/AppIntro/AppIntro.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdownItem.vue
  src/renderer/components/PluginManager/PluginManagerModals/PluginDetailsModal.vue
  src/renderer/components/PluginManager/PluginManagerSideMenu.vue
  src/renderer/i18n/i18n-setup.js
  src/renderer/i18n/index.js
  src/renderer/i18n/languages/en-US.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/PluginManager.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/services/image-manager.js
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/plugin-permission.js
  src/renderer/services/plugin-manager/plugin-setup.js
  src/renderer/services/plugin-manager/setup/languages-setup.js
  src/renderer/store/modules/plugin.js
  src/renderer/store/modules/session.js
Labels: Bounty: Tier 0, Complexity: High, Status: Contributor Approved, Status: Member Approved, Status: Needs Review, Type: Feature

#1851 refactor: disable columns from sorting
  src/renderer/components/Transaction/TransactionTable/TransactionTable.vue
  src/renderer/components/Transaction/TransactionTable/TransactionTableMultiSignature.vue
  src/renderer/styles/_table.css
Labels: Complexity: Low, Type: Refactor

#1857 refactor: check for confirm modal title or note
  src/renderer/components/Modal/ModalConfirmation.vue
Labels: Complexity: Low, Status: Member Approved, Type: Refactor

#1854 feat: include wallet vote in publicByProfileId getter
  __tests__/unit/store/modules/wallet.spec.js
  src/renderer/store/modules/wallet.js
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved, Status: Needs Testcase, Type: Feature

#1859 fix: plugin min version
  __tests__/unit/services/plugin-manager.spec.js
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Bugfix

#1863 ci: create draft release workflow
  .github/workflows/publish-release.yml
Labels: Complexity: Low, Type: Task

#1862 Push to staging
  .github/workflows/publish-release.yml
  __tests__/unit/App.spec.js
  __tests__/unit/components/PluginManager/PluginManagerModals/PluginDetailsModal.spec.js
  __tests__/unit/components/PluginManager/PluginManagerSideMenu.spec.js
  __tests__/unit/i18n/i18n-setup.spec.js
  __tests__/unit/services/plugin-manager.spec.js
  __tests__/unit/store/modules/plugin.spec.js
  __tests__/unit/store/modules/wallet.spec.js
  config/index.js
  src/renderer/App.vue
  src/renderer/assets/images/flags/README.md
  src/renderer/assets/images/flags/bg-BG.svg
  src/renderer/assets/images/flags/cs-CZ.svg
  src/renderer/assets/images/flags/da-DK.svg
  src/renderer/assets/images/flags/de-DE.svg
  src/renderer/assets/images/flags/default.svg
  src/renderer/assets/images/flags/el-GR.svg
  src/renderer/assets/images/flags/es-ES.svg
  src/renderer/assets/images/flags/fr-FR.svg
  src/renderer/assets/images/flags/it-IT.svg
  src/renderer/assets/images/flags/ja-JP.svg
  src/renderer/assets/images/flags/ko-KR.svg
  src/renderer/assets/images/flags/nb-NO.svg
  src/renderer/assets/images/flags/nl-NL.svg
  src/renderer/assets/images/flags/pl-PL.svg
  src/renderer/assets/images/flags/pt-BR.svg
  src/renderer/assets/images/flags/ro-RO.svg
  src/renderer/assets/images/flags/ru-RU.svg
  src/renderer/assets/images/flags/se-SE.svg
  src/renderer/assets/images/flags/sk-SK.svg
  src/renderer/assets/images/flags/tr-TR.svg
  src/renderer/assets/images/flags/uk-UA.svg
  src/renderer/assets/images/flags/vi-VN.svg
  src/renderer/assets/images/flags/zh-CN.svg
  src/renderer/components/App/AppIntro/AppIntro.vue
  src/renderer/components/Menu/MenuDropdown/MenuDropdownItem.vue
  src/renderer/components/Modal/ModalConfirmation.vue
  src/renderer/components/PluginManager/PluginManagerModals/PluginDetailsModal.vue
  src/renderer/components/PluginManager/PluginManagerSideMenu.vue
  src/renderer/i18n/i18n-setup.js
  src/renderer/i18n/index.js
  src/renderer/i18n/languages/en-US.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/pages/PluginManager.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/services/image-manager.js
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/plugin-permission.js
  src/renderer/services/plugin-manager/plugin-setup.js
  src/renderer/services/plugin-manager/setup/languages-setup.js
  src/renderer/store/modules/plugin.js
  src/renderer/store/modules/session.js
  src/renderer/store/modules/wallet.js
Labels: Complexity: Undetermined, Status: Needs Review

#1864 fix: plugin footer override on destroy
  __tests__/unit/components/Plugin/PluginWrapper.spec.js
  src/renderer/components/Plugin/PluginWrapper.vue
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#1865 refactor: rename minVersion property to minimumVersion
  __tests__/unit/services/plugin-manager.spec.js
  __tests__/unit/store/modules/plugin.spec.js
  src/renderer/services/plugin-manager.js
  src/renderer/services/plugin-manager/config-sanitizers.js
  src/renderer/services/plugin-manager/plugin-configuration.js
  src/renderer/store/modules/plugin.js
Labels: Complexity: Low, Type: Refactor

#1874 chore: remove vue-i18n-extract and some readme tweaks
  README.md
  package.json
  yarn.lock
Labels: Complexity: Low, Type: Task
