Repository ArkEcosystem/desktop-wallet, pull requests merged in 2020-10, with the labels that each got.

#2903 fix: use ledger mock for testing
  jest.setup.js
  package.json
  src/app/App.tsx
  src/domains/transaction/components/LedgerListener/LedgerListener.test.tsx
  src/domains/transaction/components/LedgerListener/LedgerListener.ts
  yarn.lock
Labels: Complexity: Medium, Type: Bugfix

#2901 test: fix `act` errors
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
Labels: Complexity: Low, Test: Unit

#2904 chore: update Platform SDK dependencies
  package.json
  src/domains/network/data.ts
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  yarn.lock
Labels: Complexity: High

#2905 refactor: adjustments to delegate registration form
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/steps/FormStep.tsx
  src/domains/transaction/components/DelegateRegistrationForm/steps/ReviewStep.tsx
  src/domains/transaction/components/DelegateRegistrationForm/steps/index.ts
  src/domains/transaction/components/MultiSignatureDetail/Step1.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionDetail.styles.ts
  src/domains/transaction/components/TransactionDetail/TransactionDetail.tsx
  src/domains/transaction/components/TransactionDetail/__snapshots__/TransactionDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.models.ts
  src/domains/transaction/pages/SendEntityRegistration/Step3.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/Step2.tsx
  src/domains/transaction/pages/SendIpfs/Step4.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/Step4.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/Step1.tsx
  src/domains/transaction/pages/SendVote/Step2.tsx
  src/domains/transaction/pages/SendVote/Step4.tsx
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Step3.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2906 chore: update Platform SDK dependencies
  package.json
  src/domains/network/data.ts
  yarn.lock
Labels: Complexity: High

#2907 feat: close modal with ESC key
  src/app/components/Modal/Modal.test.tsx
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
Labels: Complexity: Medium, Type: Feature

#2908 refactor: add message to select a network on the voting page
  src/domains/vote/i18n.ts
  src/domains/vote/pages/Votes/Votes.test.tsx
  src/domains/vote/pages/Votes/Votes.tsx
Labels: Complexity: Low, Type: Refactor

#2920 refactor: adjustments to delegate second signature form
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step1.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step2.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step3.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step4.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2913 fix: check if the extra styles of the network is not undefined
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
Labels: Complexity: Low, Type: Bugfix

#2917 fix: open external links to the blockfolio app
  src/domains/news/components/BlockfolioAd/BlockfolioAd.tsx
  src/domains/news/components/BlockfolioAd/__snapshots__/BlockfolioAd.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#2915 refactor: filter networks on input
  src/domains/network/components/SelectNetwork/SelectNetwork.test.tsx
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2910 refactor: improve amount and send max in send transfer
  src/domains/transaction/components/AddRecipient/AddRecipient.models.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.stories.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/Step1.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2912 feat: search for a news when pressing the enter key on the input
  src/app/components/Modal/Modal.test.tsx
  src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/domains/news/components/NewsOptions/NewsOptions.test.tsx
  src/domains/news/components/NewsOptions/NewsOptions.tsx
Labels: Complexity: Low, Type: Feature

#2911 fix: show exchange currency in navbar
  src/app/components/Icon/Icon.test.tsx
  src/app/components/Icon/Icon.tsx
  src/app/components/Icon/__snapshots__/Icon.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
Labels: Complexity: Medium, Type: Bugfix

#2916 refactor: import wallet and sync data in background
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/utils/testing-library.tsx
Labels: Complexity: Medium, Type: Refactor

#2924 fix: wallet order in dashboard wallet grid
  src/app/components/Slider/Slider.tsx
  src/app/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/domains/dashboard/components/Wallets/Wallets.test.tsx
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/plugin/components/PluginInfo/__snapshots__/PluginInfo.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/styles/base.css
Labels: Complexity: High, Type: Bugfix

#2922 fix: sync fees to new network
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
Labels: Complexity: Low, Type: Bugfix

#2918 fix: flush wallet transactions
  src/app/hooks/use-synchronizer.test.tsx
  src/app/hooks/use-synchronizer.tsx
  src/domains/wallet/e2e/wallet-details.e2e.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.test.tsx
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.tsx
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2935 chore: set cryptocompare as default market provider
  src/domains/profile/e2e/create-profile-action.e2e.ts
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#2934 chore: change welcome text
  src/app/__snapshots__/App.test.tsx.snap
  src/domains/profile/e2e/create-profile-routing.e2e.ts
  src/domains/profile/e2e/welcome-screen.e2e.ts
  src/domains/profile/i18n.ts
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/splash/e2e/splash-screen.e2e.ts
Labels: Complexity: Medium, Type: Task

#2933 refactor: disable msq buttons
  src/app/__snapshots__/App.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2932 refactor: add title to welcome page
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/images/ark-logo.svg
  src/app/components/Layout/components/Page/Page.tsx
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/Splash.tsx
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2931 feat: implement delegate to entity update
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.models.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/routing.ts
  src/tests/fixtures/registrations/entity-delegates.json
Labels: Complexity: Undetermined, Type: Feature

#2937 chore: update welcome-banner.svg
  src/app/assets/images/welcome-banner.svg
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2936 feat: generic toast handler in settings pages
  src/domains/setting/i18n.ts
  src/domains/setting/pages/Settings/Settings.models.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/setting/pages/Settings/available-settings/Password.tsx
  src/domains/setting/pages/Settings/available-settings/Peer.tsx
  src/domains/setting/pages/Settings/available-settings/Plugins.tsx
  src/styles/toasts.css
  src/tailwind.config.js
Labels: Complexity: High, Type: Feature

#2938 refactor: add title to create profile page
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2943 fix: add border props as classnames
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2927 refactor: adjustments to entity registration
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.test.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx
  src/domains/transaction/components/EntityRegistrationForm/FormStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/ReviewStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/SummaryStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/index.ts
  src/domains/transaction/components/LinkCollection/LinkCollection.test.tsx
  src/domains/transaction/components/LinkCollection/LinkCollection.tsx
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/LinkList/LinkList.tsx
  src/domains/transaction/components/LinkList/__snapshots__/LinkList.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.stories.tsx
  src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.test.tsx
  src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.tsx
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/validations/EntityRegistration.ts
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#2940 refactor: position modal in center
  src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap
  src/app/components/Modal/Modal.test.tsx
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/app/components/Modal/utils.ts
  src/app/components/SearchResource/__snapshots__/SearchResource.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap
  src/domains/plugin/components/BlacklistPlugins/__snapshots__/BlacklistPlugins.test.tsx.snap
  src/domains/plugin/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap
  src/domains/plugin/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/DeleteProfile/__snapshots__/DeleteProfile.test.tsx.snap
  src/domains/profile/components/ProfileCreated/__snapshots__/ProfileCreated.test.tsx.snap
  src/domains/profile/components/ResetProfile/__snapshots__/ResetProfile.test.tsx.snap
  src/domains/profile/components/SignIn/__snapshots__/SignIn.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/RepositoryModal/__snapshots__/RepositoryModal.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/components/AdvancedMode/__snapshots__/AdvancedMode.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/DelegateResignationDetail/__snapshots__/DelegateResignationDetail.test.tsx.snap
  src/domains/transaction/components/EntityDetail/__snapshots__/EntityDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SecondSignatureDetail/__snapshots__/SecondSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
  src/domains/wallet/components/LedgerWallet/__snapshots__/LedgerWallet.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/components/VerifyMessageStatus/__snapshots__/VerifyMessageStatus.test.tsx.snap
  src/domains/wallet/components/WalletUpdate/__snapshots__/WalletUpdate.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2949 chore: update welcome-banner.svg
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/images/welcome-banner.svg
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/splash/pages/Splash/Splash.tsx
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Low, Type: Task

#2948 fix: add profile wallets to recipients search
  src/app/i18n/common/i18n.ts
  src/domains/contact/components/ContactListItem/ContactListItem.models.ts
  src/domains/contact/components/ContactListItem/ContactListItem.test.tsx
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/SearchContact.tsx
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/profile/components/SelectRecipient/SelectRecipient.tsx
  src/tests/fixtures/coins/ark/wallets/D61mfSggzbvQgTUe6JhYKH2doHaqJ3Dyib.json
Labels: Complexity: High, Status: Needs Review, Type: Bugfix

#2947 feat: add `EmptyBlock` component
  src/app/components/EmptyBlock/EmptyBlock.stories.tsx
  src/app/components/EmptyBlock/EmptyBlock.test.tsx
  src/app/components/EmptyBlock/EmptyBlock.tsx
  src/app/components/EmptyBlock/__snapshots__/EmptyBlock.test.tsx.snap
  src/app/components/EmptyBlock/index.tsx
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/vote/components/MyVoteTable/MyVoteTable.tsx
  src/domains/vote/components/MyVoteTable/__snapshots__/MyVoteTable.test.tsx.snap
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Feature

#2945 feat: reload settings route after saving
  src/app/App.tsx
  src/app/hooks/index.ts
  src/app/hooks/use-reload-path.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/Settings.tsx
  src/router/RouterView.test.tsx
  src/router/RouterView.tsx
Labels: Complexity: Medium

#2946 feat: add password protection on `Welcome` card actions
  src/domains/profile/pages/Welcome/Welcome.test.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Labels: Complexity: High, Type: Feature

#2941 refactor: implement new design for the page create profile
  src/app/assets/svg/upload.svg
  src/app/components/SelectProfileImage/SelectProfileImage.tsx
  src/app/components/SelectProfileImage/__snapshots__/SelectProfileImage.test.tsx.snap
  src/domains/profile/e2e/create-profile-action.e2e.ts
  src/domains/profile/i18n.ts
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/i18n.ts
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2958 refactor: reduce wallet card count on dashboard
  src/app/components/Slider/Slider.tsx
  src/app/components/Slider/__snapshots__/Slider.test.tsx.snap
  src/domains/dashboard/components/Wallets/Wallets.test.tsx
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugin/components/PluginInfo/__snapshots__/PluginInfo.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2942 feat: implement dark mode logic
  src/app/App.test.tsx
  src/app/App.tsx
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/svg/unvote.svg
  src/app/assets/svg/vote-unvote.svg
  src/app/assets/svg/vote.svg
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/SearchBar/SearchBar.tsx
  src/app/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/app/components/SearchResource/__snapshots__/SearchResource.test.tsx.snap
  src/app/contexts/Theme/Theme.tsx
  src/app/contexts/Theme/index.ts
  src/app/contexts/index.ts
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/components/SearchHelp/__snapshots__/SearchHelp.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/components/AddBlacklistPlugin/__snapshots__/AddBlacklistPlugin.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx
  src/domains/transaction/components/TotalAmountBox/__snapshots__/TotalAmountBox.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/components/DelegateTable/DelegateTable.tsx
  src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/styles/base.css
  src/styles/variables.css
  src/tailwind.config.js
  src/tests/fixtures/env/storage.json
  src/types.d.ts
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2962 refactor: hide percentage bar if portfolio has no balance
  package.json
  src/app/components/WalletCard/WalletCard.test.tsx
  src/app/components/WalletListItem/WalletListItem.test.tsx
  src/domains/dashboard/i18n.ts
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/vote/components/AddressTable/AddressRow/AddressRow.test.tsx
  src/utils/storybook.tsx
  yarn.lock
Labels: Complexity: Undetermined, Type: Refactor

#2955 feat: throw error for missing mocks
  src/app/App.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/transaction/e2e/common.ts
  src/domains/transaction/e2e/delegate-registration.e2e.ts
  src/domains/transaction/e2e/delegate-resignation.e2e.ts
  src/domains/transaction/e2e/entity-update.e2e.ts
  src/domains/transaction/e2e/ipfs-transaction.e2e.ts
  src/domains/transaction/e2e/mocks.ts
  src/domains/transaction/e2e/multiple-transfer.e2e.ts
  src/domains/transaction/e2e/single-transfer.e2e.ts
  src/domains/transaction/e2e/vote-transaction.e2e.ts
  src/domains/vote/e2e/common.ts
  src/domains/vote/e2e/votes.e2e.ts
  src/domains/wallet/e2e/common.ts
  src/domains/wallet/e2e/create-wallet-action.e2e.ts
  src/domains/wallet/e2e/wallet-details.e2e.ts
  src/tests/fixtures/coins/ark/transactions/business-registration.json
  src/tests/fixtures/coins/ark/transactions/delegate-registrations.json
  src/tests/fixtures/coins/ark/transactions/search/addresses-D5sRKWckH4rE1hQ9eeMeHAepgyC3cvJtwb-1-15.json
  src/tests/fixtures/coins/ark/transactions/search/addresses-D8rr7B1d6TL6pf14LgMz4sKp1VBMs6YUYD-1-15.json
  src/tests/fixtures/coins/ark/transactions/search/addresses-D8rr7B1d6TL6pf14LgMz4sKp1VBMs6YUYD-2-15.json
  src/tests/fixtures/coins/ark/transactions/search/addresses-DC8ghUdhS8w8d11K8cFQ37YsLBFhL3Dq2P-1-15.json
  src/tests/fixtures/coins/ark/transactions/search/addresses-DDA5nM7KEqLeTtQKv5qGgcnc6dpNBKJNTS-1-15.json
  src/tests/fixtures/coins/ark/transactions/search/no-results.json
  src/tests/fixtures/coins/ark/wallets/034151a3ec46b5670a682b0a63394f863587d1bc97483b1b6c70eb58e7f0aed192.json
  src/tests/fixtures/coins/ark/wallets/D68sFcspN2LVd9HZpf98c7bXkNimK3M6AZ.json
  src/tests/fixtures/coins/ark/wallets/DDA5nM7KEqLeTtQKv5qGgcnc6dpNBKJNTS.json
  src/tests/fixtures/coins/ark/wallets/not-found.json
  src/utils/e2e-utils.ts
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#2953 fix: correct texts for transaction review steps
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#2968 refactor: add missing mocks on e2e tests
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/utils/e2e-utils.ts
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#2961 fix: adjust sizes on condensed `RecipientList`
  src/domains/transaction/components/MultiSignatureRegistrationForm/Step2.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/components/RecipientList/RecipientList.models.ts
  src/domains/transaction/components/RecipientList/RecipientList.test.tsx
  src/domains/transaction/components/RecipientList/RecipientList.tsx
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/i18n.ts
Labels: Complexity: Low, Type: Bugfix

#2929 feat: AIP26 handling
  src/app/App.test.tsx
  src/app/App.tsx
  src/app/hooks/index.ts
  src/app/hooks/use-deeplink.test.tsx
  src/app/hooks/use-deeplink.ts
  src/app/i18n/common/i18n.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/Step1.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/router/RouterView.tsx
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#2969 fix: remove duplicated import
  src/app/App.tsx
Labels: bugfix, low

#2923 fix: make step divisible in `InputRange`
  src/app/components/Input/InputRange.test.tsx
  src/app/components/Input/InputRange.tsx
  src/app/components/Input/__snapshots__/InputRange.test.tsx.snap
  src/app/components/Input/utils.ts
  src/domains/transaction/components/DelegateRegistrationForm/steps/FormStep.tsx
  src/domains/transaction/components/InputFee/InputFee.test.tsx
  src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/Step1.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step1.tsx
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#2976 chore: add Lucio as code owner
  CODEOWNERS
Labels: Complexity: Low, task

#2979 fix: adjust fallback to guarantee step is valid
  src/app/components/Input/utils.ts
Labels: Complexity: Low, bugfix

#2975 fix: not show the button to view more if the wallet has no transactions
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
Labels: Complexity: Low, bugfix

#2974 refactor: remove duplicate import statement of hooks
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/hooks/index.ts
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/exchange/pages/Exchange/Exchange.tsx
  src/domains/help/pages/Article/Article.tsx
  src/domains/help/pages/Faq/Faq.tsx
  src/domains/help/pages/Main/Main.tsx
  src/domains/news/pages/News/News.tsx
  src/domains/plugin/pages/PluginDetails/PluginDetails.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/setting/pages/Settings/available-settings/Password.tsx
  src/domains/setting/pages/Settings/available-settings/Plugins.tsx
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.tsx
  src/domains/transaction/components/DelegateRegistrationForm/steps/FormStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.tsx
  src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.tsx
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendVote/SendVote.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/wallet/components/WalletBottomSheetMenu/WalletBottomSheetMenu.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.tsx
Labels: Complexity: Medium, refactor

#2978 fix: check if transaction response has any items
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.tsx
  src/tests/fixtures/coins/ark/devnet/transactions.json
Labels: Complexity: Low, bugfix

#2950 fix: limit networks with profile wallets
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/vote/e2e/votes.e2e.ts
  src/domains/vote/pages/Votes/Votes.tsx
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#2954 fix: my contacts table
  src/domains/contact/components/ContactListItem/ContactListItem.models.ts
  src/domains/contact/components/ContactListItem/ContactListItem.test.tsx
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/wallet/components/WalletListItem/WalletListItem.test.tsx
  src/domains/wallet/components/WalletListItem/WalletListItem.tsx
  src/domains/wallet/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/wallet/components/WalletListItem/index.ts
Labels: Complexity: High, Status: Needs Review, Type: Bugfix

#2963 refactor: filter options in the select dropdown
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/SelectDropdown/SelectDropdown.stories.tsx
  src/app/components/SelectDropdown/SelectDropdown.test.tsx
  src/app/components/SelectDropdown/SelectDropdown.tsx
  src/app/components/SelectDropdown/SelectDropdownInput.tsx
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/SelectDropdown/styles.ts
  src/app/i18n/common/i18n.ts
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/profile/e2e/create-profile-action.e2e.ts
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/e2e/save-settings.e2e.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/LinkCollection.test.tsx
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/e2e/delegate-registration.e2e.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2982 fix: break words for long vendorfield in the tooltip
  src/app/__snapshots__/App.test.tsx.snap
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowInfo.tsx
  src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/wallet/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
Labels: Complexity: Undetermined, Type: Bugfix

#2981 fix: set `currency.value` when changing the input fee
  src/domains/transaction/components/DelegateRegistrationForm/steps/FormStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/FormStep.tsx
  src/domains/transaction/components/InputFee/InputFee.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step1.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/pages/SendTransfer/Step1.tsx
  src/domains/transaction/pages/SendVote/Step1.tsx
Labels: Complexity: Undetermined, Type: Bugfix

#2985 refactor: adjust wallet card designs
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/svg/import.svg
  src/app/assets/svg/plus.svg
  src/app/assets/svg/settings.svg
  src/app/components/Card/Card.tsx
  src/app/components/WalletCard/WalletCard.test.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/WalletsControls.tsx
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx
  src/domains/transaction/components/TotalAmountBox/__snapshots__/TotalAmountBox.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Undetermined, Type: Refactor

#2987 refactor: adjustments and fixes in multisig details
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/Signatures.tsx
  src/domains/transaction/components/MultiSignatureDetail/SummaryStep.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/Signatures.test.tsx.snap
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2983 fix: allow the user to change cryptoasset on the send transaction page
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/Step1.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/Step1.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: Undetermined, Type: Bugfix

#2997 refactor: add dedicated recipient search components
  src/app/components/Table/Table.tsx
  src/domains/contact/components/ContactListItem/ContactListItem.models.ts
  src/domains/contact/components/ContactListItem/ContactListItem.test.tsx
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/SearchContact.tsx
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/SearchContact/index.ts
  src/domains/contact/i18n.ts
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/profile/components/SelectRecipient/SelectRecipient.test.tsx
  src/domains/profile/components/SelectRecipient/SelectRecipient.tsx
  src/domains/profile/components/SelectRecipient/__snapshots__/SelectRecipient.test.tsx.snap
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/components/SearchRecipient/SearchRecipient.stories.tsx
  src/domains/transaction/components/SearchRecipient/SearchRecipient.test.tsx
  src/domains/transaction/components/SearchRecipient/SearchRecipient.tsx
  src/domains/transaction/components/SearchRecipient/__snapshots__/SearchRecipient.test.tsx.snap
  src/domains/transaction/components/SearchRecipient/index.ts
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionTable.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/transaction/e2e/single-transfer.e2e.ts
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/wallet/components/SearchWallet/SearchWallet.tsx
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletListItem/WalletListItem.test.tsx
  src/domains/wallet/components/WalletListItem/WalletListItem.tsx
  src/domains/wallet/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/wallet/components/WalletListItem/index.ts
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2996 test: update `SendIpfs` routes
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
Labels: Complexity: Low, Test: Unit

#2993 fix: avoid amount fill in add recipient when no deeplink
  src/domains/transaction/components/AddRecipient/AddRecipient.models.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/Step1.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#2991 fix: pending multisignature transactions
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.test.tsx
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.tsx
Labels: Complexity: Low, Type: Bugfix

#2992 refactor: transaction form validation
  src/app/hooks/validations.ts
  src/app/i18n/common/i18n.ts
  src/domains/profile/components/SelectRecipient/SelectRecipient.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/RecipientList/RecipientList.models.ts
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/Step1.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/validations/SendTransfer.ts
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#3002 refactor: add multisignature icons to table
  src/app/assets/svg/awaiting-final-signature.svg
  src/app/assets/svg/awaiting-other-signature.svg
  src/app/assets/svg/awaiting-our-signature.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/send.svg
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.test.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
Labels: Complexity: Medium, Type: Refactor

#3003 deps: update Platform SDK dependencies
  package.json
  src/app/assets/svg/index.ts
  src/app/assets/svg/vote-combination.svg
  src/domains/transaction/components/MultiSignatureDetail/SummaryStep.tsx
  src/domains/transaction/components/TransactionDetail/TransactionVotes/TransactionVotes.tsx
  src/domains/transaction/components/TransactionDetail/TransactionVotes/__snapshots__/TransactionVotes.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/components/DelegateTable/DelegateTable.tsx
  src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/tests/fixtures/coins/ark/devnet/wallets/D61mfSggzbvQgTUe6JhYKH2doHaqJ3Dyib.json
  src/tests/fixtures/coins/ark/devnet/wallets/D8rr7B1d6TL6pf14LgMz4sKp1VBMs6YUYD.json
  src/tests/fixtures/coins/ark/devnet/wallets/D9YiyRYMBS2ofzqkufjrkB9nHofWgJLM7f.json
  src/tests/fixtures/coins/ark/devnet/wallets/DFJ5Z51F1euNNdRUQJKQVdG4h495LZkc6T.json
  src/tests/fixtures/coins/ark/devnet/wallets/DKrACQw7ytoU2gjppy3qKeE2dQhZjfXYqu.json
  yarn.lock
Labels: Complexity: High

#2994 refactor: adjustments and fixes in transfer form
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/SummaryStep.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionAmount/TransactionAmount.tsx
  src/domains/transaction/components/TransactionDetail/TransactionRecipients/TransactionRecipients.test.tsx
  src/domains/transaction/components/TransactionDetail/TransactionRecipients/TransactionRecipients.tsx
  src/domains/transaction/components/TransactionDetail/TransactionRecipients/__snapshots__/TransactionRecipients.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransferDetail/TransferDetail.tsx
  src/domains/transaction/pages/SendTransfer/Step1.tsx
  src/domains/transaction/pages/SendTransfer/Step2.tsx
  src/domains/transaction/pages/SendTransfer/Step4.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2995 fix: votes should be available only for supported networks
  src/domains/vote/pages/Votes/Votes.tsx
Labels: Complexity: Low, Type: Bugfix

#3005 chore: update banner
  README.md
  banner.png
Labels: Complexity: Low, Type: Task

#2989 feat: sign transactions with a multisignature wallet
  src/app/components/WalletCard/WalletCard.test.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.test.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.test.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureRegistrationDetail.test.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureRegistrationDetail.tsx
  src/domains/transaction/components/MultiSignatureDetail/SummaryStep.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.test.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/e2e/ipfs-transaction.e2e.ts
  src/domains/transaction/e2e/single-transfer.e2e.ts
  src/domains/transaction/e2e/transactions-routing.e2e.ts
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendVote/SendVote.test.tsx
  src/domains/transaction/pages/SendVote/SendVote.tsx
  src/domains/vote/components/AddressTable/AddressRow/AddressRow.test.tsx
  src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRow.test.tsx.snap
  src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap
  src/domains/vote/e2e/votes.e2e.ts
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/e2e/common.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/tests/fixtures/coins/ark/devnet/transactions/byAddress/DJXg9Vqg2tofRNrMAvMzhZTkegu8QyyNQq-1-15.json
  src/tests/fixtures/coins/ark/devnet/wallets/D8rr7B1d6TL6pf14LgMz4sKp1VBMs6YUYD.json
  src/tests/fixtures/coins/ark/devnet/wallets/DJXg9Vqg2tofRNrMAvMzhZTkegu8QyyNQq.json
  src/utils/e2e-utils.ts
  src/utils/testing-library.tsx
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#3001 refactor: some wallet options should only be available for supported networks
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.test.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2990 fix: register entity should be available only for ark wallet
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#3006 refactor: update transaction icons
  src/app/assets/svg/bridgechain.svg
  src/app/assets/svg/business.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/ipfs.svg
  src/app/assets/svg/module.svg
  src/app/assets/svg/multipayment.svg
  src/app/assets/svg/plugin.svg
  src/app/assets/svg/product.svg
  src/app/assets/svg/timelock.svg
  src/app/components/Notifications/Notifications.stories.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionVotes/TransactionVotes.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowRecipientIcon.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx
  src/domains/transaction/i18n.ts
  src/domains/wallet/data.ts
Labels: Complexity: High, Type: Refactor

#3009 fix: save dashboard settings
  src/domains/dashboard/components/FilterWallets/FilterWallets.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.test.tsx
Labels: Complexity: Low, Type: Bugfix

#3013 deps: update Platform SDK dependencies
  package.json
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.test.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/WalletRegistrations.test.tsx
  src/utils/e2e-utils.ts
  yarn.lock
Labels: Complexity: High

#3008 refactor: use table components in link collection
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/RadioButton/RadioButton.styles.ts
  src/app/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/LinkCollection/LinkCollection.test.tsx
  src/domains/transaction/components/LinkCollection/LinkCollection.tsx
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#3011 feat: add LegacyMagistrateDetail component
  src/domains/transaction/components/LegacyMagistrateDetail/LegacyMagistrateDetail.test.tsx
  src/domains/transaction/components/LegacyMagistrateDetail/LegacyMagistrateDetail.tsx
  src/domains/transaction/components/LegacyMagistrateDetail/__snapshots__/LegacyMagistrateDetail.test.tsx.snap
  src/domains/transaction/components/LegacyMagistrateDetail/index.ts
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
Labels: Complexity: Undetermined, Type: Feature

#3010 fix: show module icon for module entity transactions
  src/app/assets/svg/multipayment.svg
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.tsx
Labels: Complexity: Medium, Type: Bugfix

#3004 refactor: confirm pending multisignature transactions
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.test.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.test.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.test.tsx
  src/domains/transaction/i18n.ts
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.test.tsx
  src/domains/wallet/pages/WalletDetails/hooks/use-wallet-transactions.tsx
Labels: Complexity: High, Type: Refactor

#3017 refactor: multipayment should be available only for supported networks
  src/domains/transaction/components/AddRecipient/AddRecipient.models.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/Step1.tsx
Labels: Complexity: Medium, Type: Refactor

#3020 fix: retrieve multisignature recipientId through get method
  src/domains/transaction/components/MultiSignatureDetail/SummaryStep.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#3015 refactor: add external icon to signed transaction table rows
  src/app/components/Table/Table.test.tsx
  src/app/components/Table/Table.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Undetermined, Type: Refactor

#3016 refactor: reorganize provider icons
  src/app/assets/svg/bitbucket.svg
  src/app/assets/svg/discord.svg
  src/app/assets/svg/facebook.svg
  src/app/assets/svg/github.svg
  src/app/assets/svg/gitlab.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/instagram.svg
  src/app/assets/svg/linkedin.svg
  src/app/assets/svg/medium.svg
  src/app/assets/svg/npm.svg
  src/app/assets/svg/providers/bitbucket.svg
  src/app/assets/svg/providers/discord.svg
  src/app/assets/svg/providers/facebook.svg
  src/app/assets/svg/providers/flickr.svg
  src/app/assets/svg/providers/github.svg
  src/app/assets/svg/providers/gitlab.svg
  src/app/assets/svg/providers/imgur.svg
  src/app/assets/svg/providers/index.ts
  src/app/assets/svg/providers/instagram.svg
  src/app/assets/svg/providers/linkedin.svg
  src/app/assets/svg/providers/medium.svg
  src/app/assets/svg/providers/npm.svg
  src/app/assets/svg/providers/reddit.svg
  src/app/assets/svg/providers/slack.svg
  src/app/assets/svg/providers/telegram.svg
  src/app/assets/svg/providers/twitter.svg
  src/app/assets/svg/providers/vimeo.svg
  src/app/assets/svg/providers/wechat.svg
  src/app/assets/svg/providers/youtube.svg
  src/app/assets/svg/reddit.svg
  src/app/assets/svg/slack.svg
  src/app/assets/svg/twitter.svg
Labels: Complexity: Medium, Type: Refactor

#3018 feat: hide wallet card actions dropdown
  src/app/components/WalletCard/WalletCard.test.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Labels: Complexity: Medium, Type: Feature

#3012 refactor: adjust styles of labels
  src/app/components/Label/Label.styles.tsx
  src/app/components/Label/Label.test.tsx
  src/app/components/Label/Label.tsx
  src/app/components/Label/__snapshots__/Label.test.tsx.snap
  src/app/components/Notifications/__snapshots__/NotificationTransactionItem.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/news/components/NewsCard/NewsCard.tsx
  src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/DelegateResignationDetail/__snapshots__/DelegateResignationDetail.test.tsx.snap
  src/domains/transaction/components/EntityRegistrationForm/__snapshots__/EntityRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionAmount/TransactionAmount.tsx
  src/domains/transaction/components/TransactionDetail/TransactionAmount/__snapshots__/TransactionAmount.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionDetail.tsx
  src/domains/transaction/components/TransactionDetail/TransactionRecipients/__snapshots__/TransactionRecipients.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/__snapshots__/SendEntityUpdate.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/Step2.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#3022 feat: persist the type of view (grid & list)
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Labels: Complexity: Low, Type: Feature

#2999 feat: add missing aip36 registrations
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/transaction/components/EntityRegistrationForm/FormStep.tsx
  src/domains/transaction/e2e/delegate-registration.e2e.ts
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.models.ts
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.test.tsx
  src/domains/transaction/pages/SendEntityRegistration/SendEntityRegistration.tsx
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityRegistration/__snapshots__/SendEntityRegistration.test.tsx.snap
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#3014 refactor: handle`InputFee` state and types
  src/app/components/Input/InputRange.tsx
  src/app/hooks/index.ts
  src/app/hooks/use-currency-display.test.tsx
  src/app/hooks/use-currency-display.ts
  src/app/hooks/validations.test.tsx
  src/app/hooks/validations.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/steps/FormStep.tsx
  src/domains/transaction/components/DelegateResignationForm/FormStep.tsx
  src/domains/transaction/components/EntityRegistrationForm/EntityRegistrationForm.tsx
  src/domains/transaction/components/EntityRegistrationForm/FormStep.tsx
  src/domains/transaction/components/EntityResignationSteps/FormStep.tsx
  src/domains/transaction/components/InputFee/InputFee.test.tsx
  src/domains/transaction/components/InputFee/InputFee.tsx
  src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap
  src/domains/transaction/components/InputFee/hooks.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/Step1.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/Step1.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.test.tsx
  src/domains/transaction/pages/SendEntityResignation/SendEntityResignation.tsx
  src/domains/transaction/pages/SendEntityResignation/__snapshots__/SendEntityResignation.test.tsx.snap
  src/domains/transaction/pages/SendEntityUpdate/SendEntityUpdate.tsx
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendVote/SendVote.tsx
  src/domains/transaction/pages/SendVote/Step1.tsx
  src/domains/transaction/validations/Common.ts
  src/domains/transaction/validations/MultiSignatureRegistration.ts
  src/domains/transaction/validations/SendIpfs.ts
  src/domains/transaction/validations/SendTransfer.ts
  src/domains/transaction/validations/SendVote.ts
  src/domains/transaction/validations/index.ts
Labels: Status: Needs Review, Type: Refactor

#3023 feat: show delegate names in recipient column
  src/domains/dashboard/components/Transactions/Transactions.test.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/data.ts
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.tsx
  src/tailwind.config.js
  src/tests/fixtures/transactions/index.ts
Labels: Complexity: Medium, Type: Feature

#3021 fix: resize wallet type icons in list view
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
  src/domains/vote/components/AddressTable/AddressRow/__snapshots__/AddressRow.test.tsx.snap
  src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#3024 feat: prepend amounts with sign
  src/app/components/Amount/Amount.tsx
  src/app/components/Notifications/__snapshots__/NotificationTransactionItem.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/RecipientList/RecipientList.tsx
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionAmount/TransactionAmount.tsx
  src/domains/transaction/components/TransactionDetail/TransactionAmount/__snapshots__/TransactionAmount.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionRecipients/__snapshots__/TransactionRecipients.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Feature

#3029 chore: increase dashboard transactions page limit
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/tests/fixtures/coins/ark/devnet/transactions/byAddress/D5sRKWckH4rE1hQ9eeMeHAepgyC3cvJtwb-1-30.json
  src/tests/fixtures/coins/ark/devnet/transactions/byAddress/D8rr7B1d6TL6pf14LgMz4sKp1VBMs6YUYD-1-30.json
  src/tests/fixtures/coins/ark/devnet/transactions/byAddress/DC8ghUdhS8w8d11K8cFQ37YsLBFhL3Dq2P-1-30.json
  src/tests/fixtures/coins/ark/devnet/transactions/byAddress/DJXg9Vqg2tofRNrMAvMzhZTkegu8QyyNQq-1-30.json
  src/utils/e2e-utils.ts
Labels: Complexity: Low, Type: Task

#3028 fix: alignment of card icons
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Card/Card.tsx
  src/app/components/Card/__snapshots__/Card.test.tsx.snap
  src/app/components/Card/__snapshots__/CardControl.test.tsx.snap
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#3032 fix: update the vote status icon
  src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
  src/domains/vote/components/DelegateTable/DelegateRow/DelegateRow.tsx
  src/domains/vote/components/DelegateTable/DelegateRow/__snapshots__/DelegateRow.test.tsx.snap
  src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#3034 refactor: add Tooltip component
  src/app/components/Clipboard/Clipboard.tsx
  src/app/components/Form/FormLabel.tsx
  src/app/components/Link/Link.tsx
  src/app/components/SelectProfileImage/SelectProfileImage.tsx
  src/app/components/Tooltip/Tooltip.test.tsx
  src/app/components/Tooltip/Tooltip.tsx
  src/app/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
  src/app/components/Tooltip/index.ts
  src/app/components/TruncateMiddle/TruncateMiddle.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/network/components/NetworkIcon/NetworkIcon.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/MultiSignatureDetail/Signatures.tsx
  src/domains/transaction/components/TransactionDetail/TransactionAmount/TransactionAmount.tsx
  src/domains/transaction/components/TransactionDetail/TransactionConfirmations/TransactionConfirmations.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowConfirmation.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowInfo.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx
  src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
  src/domains/vote/components/DelegateTable/DelegateRow/DelegateRow.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletRegistrations/WalletRegistrations.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx
  src/styles/app.css
  src/styles/tooltips.css
Labels: Complexity: High, Type: Refactor

#3019 feat: save wallet display settings on the dashboard page
  src/app/i18n/common/i18n.ts
  src/domains/dashboard/components/FilterWallets/FilterWallets.stories.tsx
  src/domains/dashboard/components/FilterWallets/FilterWallets.test.tsx
  src/domains/dashboard/components/FilterWallets/FilterWallets.tsx
  src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/dashboard/components/Wallets/Wallets.test.tsx
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Labels: Complexity: Low, Type: Feature

#3031 fix: prevent wrapping label and date in `TransactionRow`
  src/app/components/Notifications/__snapshots__/NotificationTransactionItem.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#3025 fix: check if wallets are synced with the network
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/transaction/pages/SendEntityRegistration/Step1.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
Labels: Complexity: Low, Type: Bugfix

#3035 fix: also add min-width to table headers
  src/app/components/Table/Table.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Medium, Type: Bugfix

#3037 feat: hide `WalletVote` and `WalletRegistrations` if not supported by network
  package.json
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/tailwind.config.js
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#3030 fix: update sort by of wallets in the list view
  src/domains/dashboard/components/Wallets/Wallets.tsx
Labels: Complexity: Low, Type: Bugfix
