Repository ArkEcosystem/desktop-wallet, pull requests merged in 2020-04, with the labels that each got.

#1866 fix: use margin instead of border as separator
  src/renderer/components/Button/ButtonDropdown.vue
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved, Type: Bugfix

#1868 ci: use changelog as body when drafting a release
  .github/workflows/publish-release.yml
Labels: Complexity: Low

#1870 fix: break words for long vendorfield
  src/renderer/components/Transaction/TransactionShow/TransactionShowMultiSignature.vue
Labels: Complexity: Low, Type: Bugfix

#1871 feat: add additional filters to the plugin manager
  __tests__/unit/store/modules/plugin.spec.js
  src/renderer/components/PluginManager/PluginManagerButtons/PluginManagerButtonFilter.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/store/modules/plugin.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Feature

#1882 ci: use actions/checkout@v2
  .github/workflows/draft-artifacts.yml
  .github/workflows/format.yml
  .github/workflows/test.yml
  package.json
Labels: Complexity: Low

#1894 refactor: remove lodash findkey
  src/renderer/components/Selection/SelectionTheme.vue
  src/renderer/components/Transaction/TransactionModal.vue
Labels: Complexity: Low, Type: Refactor

#1893 chore: remove the cursor and opacity for avatar and background selection
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
Labels: Complexity: Low, Type: Task

#1877 feat: add icon indicator for multisig wallets
  src/renderer/assets/svg/multi-signature.svg
  src/renderer/components/Wallet/WalletGrid.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingPrimaryActions.vue
  src/renderer/components/Wallet/WalletTable.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Medium, Type: Feature

#1883 chore: adjust the window size to its content not to show scroll bar
  src/main/menu.js
Labels: Complexity: Low, Type: Task

#1873 refactor: plugin sliders into single component to reduce duplication
  __tests__/unit/components/Slider/Navigation.spec.js
  __tests__/unit/components/Slider/Pagination.spec.js
  __tests__/unit/components/Slider/SliderImage.spec.js
  __tests__/unit/components/Slider/SliderImageModal.spec.js
  src/renderer/components/PluginManager/PluginManagerModals/PluginDetailsModal.vue
  src/renderer/components/PluginManager/PluginManagerModals/PluginImageModal.vue
  src/renderer/components/PluginManager/PluginManagerModals/index.js
  src/renderer/components/PluginManager/PluginSlider.vue
  src/renderer/components/PluginManager/index.js
  src/renderer/components/Slider/Navigation.vue
  src/renderer/components/Slider/Pagination.vue
  src/renderer/components/Slider/SliderImage.vue
  src/renderer/components/Slider/SliderImageModal.vue
  src/renderer/components/Slider/index.js
Labels: Complexity: High, Type: Refactor

#1885 fix: break words for long vendorfield in the tooltip
  src/renderer/components/Transaction/TransactionTable/TransactionTable.vue
Labels: Complexity: Low, Type: Bugfix

#1884 fix: highlight text color on qrcode modal
  src/renderer/components/Modal/ModalQrCodeScanner.vue
Labels: Complexity: Low, Type: Bugfix

#1881 fix: don't show error when canceling open file dialog
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/mixins/electron.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1892 fix: exclude empty wallets and don't show success message when canceling a save file dialog
  src/renderer/components/Modal/ModalExportWallets.vue
Labels: Complexity: Low, Type: Bugfix

#1880 fix: add clearTimeout to the button clipboard component
  src/renderer/components/Button/ButtonClipboard.vue
Labels: Complexity: Low, Type: Bugfix

#1896 refactor: update code to install vue-devtools
  src/main/index.dev.js
Labels: Complexity: Low, Type: Refactor

#1901 fix: break words or truncate if the name of the wallet is long
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainRegistration.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainResignation.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainUpdate.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessRegistration.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessResignation.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessUpdate.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmDelegateRegistration.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmDelegateResignation.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmIpfs.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmMultiPayment.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmMultiSignature.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmSecondSignature.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmTransfer.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmVote.spec.js
  src/renderer/components/Input/InputField.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainRegistration.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainResignation.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainUpdate.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessRegistration.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessResignation.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBusiness/TransactionConfirmBusinessUpdate.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmDelegateResignation.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmIpfs.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmMultiPayment.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmMultiSignature.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmSecondSignature.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmTransfer.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmVote.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/TransactionFormBridgechainResignation.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBusiness/TransactionFormBusinessResignation.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBusiness/mixin.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateRegistration.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormDelegateResignation.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormIpfs.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormMultiPayment.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormMultiSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormSecondSignature.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormTransfer.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionShow/TransactionShow.vue
  src/renderer/components/Transaction/TransactionShow/TransactionShowMultiSignature.vue
Labels: Complexity: Medium, Type: Bugfix

#1907 chore(config): add plugin comment
  config/index.js
Labels: Complexity: Low, Type: Task
