Repository ArkEcosystem/desktop-wallet, pull requests merged in 2020-06, with the labels that each got.

#1995 feat: profile pages
  package.json
  src/renderer/App.vue
  src/renderer/SplashScreen.vue
  src/renderer/app/Button/ButtonSwitch.vue
  src/renderer/app/ListDivided/ListDivided.vue
  src/renderer/app/ListDivided/ListDividedItem.vue
  src/renderer/app/ListDivided/index.ts
  src/renderer/app/Navbar/Navbar.vue
  src/renderer/assets/images/close.svg
  src/renderer/assets/images/settings.svg
  src/renderer/assets/images/upload_button.svg
  src/renderer/assets/svg/.keep
  src/renderer/assets/svg/close.svg
  src/renderer/domain/profile/pages/ProfileNew.vue
  src/renderer/domain/profile/pages/ProfileWelcome.vue
  src/renderer/styles/_animations.css
  src/renderer/styles/_buttons.css
  src/renderer/styles/_forms.css
  src/renderer/styles/_theme.css
  src/renderer/styles/style.css
  tailwind.config.js
  yarn.lock
Labels: Complexity: Low, Type: Feature

#2001 chore: organise certain parts under the `app` namespace
  .electron-vue/webpack.renderer.config.js
  .prettierrc.json
  src/renderer/App.vue
  src/renderer/app/Alert/Alert.vue
  src/renderer/app/App.vue
  src/renderer/app/Button/ButtonSwitch.vue
  src/renderer/app/ListDivided/ListDivided.vue
  src/renderer/app/ListDivided/ListDividedItem.vue
  src/renderer/app/SplashScreen.vue
  src/renderer/app/components/Alert/Alert.stories.ts
  src/renderer/app/components/Alert/Alert.vue
  src/renderer/app/components/Button/ButtonSwitch.vue
  src/renderer/app/components/Button/index.ts
  src/renderer/app/components/ListDivided/ListDivided.vue
  src/renderer/app/components/ListDivided/ListDividedItem.vue
  src/renderer/app/components/ListDivided/index.ts
  src/renderer/app/components/Navbar/Navbar.stories.ts
  src/renderer/app/components/Navbar/Navbar.vue
  src/renderer/app/components/Navbar/index.ts
  src/renderer/app/i18n/date-time-formats.ts
  src/renderer/app/i18n/i18n-setup.ts
  src/renderer/app/i18n/index.ts
  src/renderer/app/i18n/languages/en-US.ts
  src/renderer/app/i18n/locales/en-US.ts
  src/renderer/app/router/index.ts
  src/renderer/app/store/index.ts
  src/renderer/app/styles/_animations.css
  src/renderer/app/styles/_buttons.css
  src/renderer/app/styles/_fonts.css
  src/renderer/app/styles/_forms.css
  src/renderer/app/styles/_general.css
  src/renderer/app/styles/_theme.css
  src/renderer/app/styles/style.css
  src/renderer/domain/profile/pages/ProfileNew.vue
  src/renderer/domain/profile/pages/ProfileWelcome.vue
  src/renderer/main.js
  src/renderer/splashscreen.js
  src/renderer/styles/_fonts.css
  tailwind.config.js
Labels: Complexity: High, Type: Task

#2002 chore: update `platform-sdk-*`
  package.json
  src/types.d.ts
  yarn.lock
Labels: Complexity: Medium, Type: Task

#2003 test: add dummy tests for first components
  .electron-vue/webpack.renderer.config.js
  __tests__/unit.jest.conf.js
  config/index.js
  config/networks/devnet.json
  config/networks/mainnet.json
  config/peers/devnet.json
  config/peers/mainnet.json
  src/renderer/app/components/Alert/Alert.test.ts
  src/renderer/domain/profile/pages/ProfileNew.test.ts
  src/renderer/domain/profile/pages/ProfileNew.vue
  src/renderer/domain/profile/pages/ProfileWelcome.test.ts
  src/renderer/domain/profile/pages/ProfileWelcome.vue
Labels: Complexity: High, Test: Unit

#2004 feat: create new profile (without avatar)
  __tests__/unit.jest.conf.js
  config/index.js
  package.json
  src/renderer/app/components/Alert/Alert.test.ts
  src/renderer/app/components/Alert/__snapshots__/Alert.test.ts.snap
  src/renderer/app/components/Form/FormError.test.ts
  src/renderer/app/components/Form/FormError.vue
  src/renderer/app/components/Form/__snapshots__/FormError.test.ts.snap
  src/renderer/app/components/Form/index.ts
  src/renderer/app/components/ListDivided/ListDivided.vue
  src/renderer/app/components/ListDivided/ListDividedItem.vue
  src/renderer/app/components/ListDivided/index.ts
  src/renderer/app/i18n/i18n-setup.ts
  src/renderer/app/i18n/index.ts
  src/renderer/domain/profile/pages/ProfileNew.test.ts
  src/renderer/domain/profile/pages/ProfileNew.vue
  src/renderer/domain/profile/pages/ProfileWelcome.test.ts
  src/renderer/domain/profile/pages/__snapshots__/ProfileNew.test.ts.snap
  src/renderer/domain/profile/pages/__snapshots__/ProfileWelcome.test.ts.snap
  src/renderer/main.js
  src/renderer/support/mixins/index.ts
  yarn.lock
Labels: Complexity: High, Type: Feature

#2005 chore: setup e2e environment
  .github/workflows/build.yml
  .github/workflows/test.yml
  .gitignore
  __tests__/e2e/__utils__/setup.js
  __tests__/e2e/app.spec.js
  __tests__/e2e/pages/1-window.spec.js
  __tests__/e2e/pages/2-welcome.spec.js
  __tests__/e2e/pages/3-profile-new.spec.js
  __tests__/unit.jest.conf.js
  src/renderer/domain/profile/pages/ProfileNew.test.ts
  tailwind.config.js
Labels: Complexity: Undetermined, Type: Task

#2007 feat: list profiles and generate avatars
  package.json
  src/renderer/app/components/ListDivided/ListDividedItem.vue
  src/renderer/domain/profile/pages/ProfileNew.test.ts
  src/renderer/domain/profile/pages/ProfileWelcome.vue
  yarn.lock
Labels: Complexity: High, Type: Feature

#2008 test: unit tests for plugin registration
  __tests__/unit.jest.conf.js
  src/renderer/domain/profile/pages/ProfileWelcome.test.ts
  src/renderer/domain/profile/pages/ProfileWelcome.vue
  src/renderer/domain/profile/pages/__snapshots__/ProfileWelcome.test.ts.snap
  src/renderer/support/plugins/env.test.ts
  src/renderer/support/plugins/http-client.test.ts
Labels: Complexity: Medium, Test: Unit

#2009 test: add basic `render` tests with snapshots
  src/renderer/app/App.test.ts
  src/renderer/app/SplashScreen.vue
  src/renderer/app/Splashscreen.test.ts
  src/renderer/app/__snapshots__/App.test.ts.snap
  src/renderer/app/__snapshots__/Splashscreen.test.ts.snap
  src/renderer/app/components/Button/ButtonSwitch.test.ts
  src/renderer/app/components/Button/ButtonSwitch.vue
  src/renderer/app/components/Button/__snapshots__/ButtonSwitch.test.ts.snap
  src/renderer/app/components/ListDivided/ListDivided.test.ts
  src/renderer/app/components/ListDivided/ListDividedItem.test.ts
  src/renderer/app/components/ListDivided/__snapshots__/ListDivided.test.ts.snap
  src/renderer/app/components/ListDivided/__snapshots__/ListDividedItem.test.ts.snap
  src/renderer/app/components/Navbar/Navbar.test.ts
  src/renderer/app/components/Navbar/__snapshots__/Navbar.test.ts.snap
  src/renderer/domain/profile/pages/ProfileNew.test.ts
  src/renderer/support/services/http.test.ts
Labels: Complexity: Medium, Test: Unit

#2010 chore: update storybook CSS path
  .storybook/preview.ts
Labels: Complexity: Low, Type: Task

#2011 ci: run E2E tests as github workflow
  .github/workflows/test.yml
  src/renderer/app/Splashscreen.test.ts
  src/renderer/app/__snapshots__/Splashscreen.test.ts.snap
  src/renderer/app/components/ListDivided/ListDividedItem.vue
Labels: Complexity: Low, Status: Needs Review

#2013 feat: more UI components
  src/renderer/app/components/Button/Button.stories.ts
  src/renderer/app/components/Button/Button.test.ts
  src/renderer/app/components/Button/Button.vue
  src/renderer/app/components/Button/ButtonSwitch.test.ts
  src/renderer/app/components/Button/ButtonSwitch.vue
  src/renderer/app/components/Button/__snapshots__/Button.test.ts.snap
  src/renderer/app/components/Button/__snapshots__/ButtonSwitch.test.ts.snap
  src/renderer/app/components/Button/index.ts
  src/renderer/app/components/ListDivided/ListDividedItem.vue
  src/renderer/app/components/Toggle/Toggle.stories.ts
  src/renderer/app/components/Toggle/Toggle.test.ts
  src/renderer/app/components/Toggle/Toggle.vue
  src/renderer/app/components/Toggle/__snapshots__/Toggle.test.ts.snap
  src/renderer/app/components/Toggle/index.ts
  src/renderer/domain/profile/pages/ProfileNew.test.ts
  src/renderer/domain/profile/pages/ProfileNew.vue
  src/renderer/domain/profile/pages/ProfileWelcome.test.ts
  src/renderer/domain/profile/pages/ProfileWelcome.vue
  src/renderer/domain/profile/pages/__snapshots__/ProfileNew.test.ts.snap
  src/renderer/domain/profile/pages/__snapshots__/ProfileWelcome.test.ts.snap
  src/renderer/domain/wallet/components/WalletMnemonicList.stories.ts
  src/renderer/domain/wallet/components/WalletMnemonicList.test.ts
  src/renderer/domain/wallet/components/WalletMnemonicList.vue
  src/renderer/domain/wallet/components/__snapshots__/WalletMnemonicList.test.ts.snap
  tailwind.config.js
Labels: Complexity: High, Type: Feature

#2012 feat: add `SvgIcon` component
  src/renderer/app/components/ListDivided/ListDividedItem.vue
  src/renderer/app/components/Navbar/Navbar.test.ts
  src/renderer/app/components/Navbar/Navbar.vue
  src/renderer/app/components/Navbar/__snapshots__/Navbar.test.ts.snap
  src/renderer/app/components/SvgIcon/SvgIcon.test.ts
  src/renderer/app/components/SvgIcon/SvgIcon.vue
  src/renderer/app/components/SvgIcon/__snapshots__/SvgIcon.test.ts.snap
  src/renderer/app/components/SvgIcon/index.ts
  src/renderer/assets/images/close.svg
  src/renderer/assets/images/default.svg
  src/renderer/assets/svg/settings.svg
  src/renderer/assets/svg/upload.svg
  src/renderer/domain/profile/pages/ProfileNew.test.ts
  src/renderer/domain/profile/pages/ProfileNew.vue
  src/renderer/domain/profile/pages/ProfileWelcome.test.ts
  src/renderer/domain/profile/pages/ProfileWelcome.vue
  src/renderer/domain/profile/pages/__snapshots__/ProfileNew.test.ts.snap
  src/renderer/domain/profile/pages/__snapshots__/ProfileWelcome.test.ts.snap
  src/renderer/support/mixins/assets.ts
  src/renderer/support/mixins/index.ts
  src/renderer/support/services/image-manager.ts
  tailwind.config.js
Labels: Complexity: Low, Type: Feature

#2015 test: enforce 100% coverage at all times
  .babelrc
  .gitignore
  __tests__/unit/__support__/setup.js
  jest.config.js
  package.json
  src/renderer/app/components/ListDivided/ListDividedItem.vue
  src/renderer/app/components/Navbar/Navbar.test.ts
  src/renderer/app/components/Navbar/Navbar.vue
  src/renderer/app/components/SvgIcon/SvgIcon.test.ts
  src/renderer/app/components/SvgIcon/SvgIcon.vue
  src/renderer/app/components/SvgIcon/__snapshots__/SvgIcon.test.ts.snap
  src/renderer/domain/profile/pages/ProfileNew.test.ts
  src/renderer/domain/profile/pages/ProfileNew.vue
  src/renderer/domain/profile/pages/ProfileWelcome.test.ts
  src/renderer/domain/profile/pages/ProfileWelcome.vue
  src/renderer/domain/profile/pages/__snapshots__/ProfileNew.test.ts.snap
  src/renderer/support/mixins/assets.test.ts
  src/renderer/support/mixins/assets.ts
  src/renderer/support/mixins/index.ts
  src/renderer/support/plugins/event-bus.test.ts
  src/renderer/support/plugins/event-bus.ts
  src/renderer/support/services/http.test.ts
  src/renderer/support/services/http.ts
  src/renderer/support/services/image-manager.test.ts
  src/renderer/support/services/image-manager.ts
  tailwind.config.js
  yarn.lock
Labels: Complexity: Medium, Type: Refactor

#2017 chore: update Platform SDK
  package.json
  src/renderer/app/components/ListDivided/ListDividedItem.vue
  src/renderer/domain/profile/pages/CreateProfile.test.ts
  src/renderer/domain/profile/pages/CreateProfile.vue
  src/renderer/domain/profile/pages/__snapshots__/CreateProfile.test.ts.snap
  src/renderer/domain/profile/routes.ts
  src/renderer/support/plugins/env.test.ts
  src/types.d.ts
  yarn.lock
Labels: Complexity: Medium, Type: Task

#2018 feat: add tabs component
  .babelrc
  .eslintrc.json
  .storybook/.babelrc
  .storybook/main.js
  .storybook/preview.ts
  .storybook/tsconfig.json
  package.json
  src/renderer/app/components/ListDivided/ListDividedItem.vue
  src/renderer/app/components/Tabs/Tab.vue
  src/renderer/app/components/Tabs/TabList.vue
  src/renderer/app/components/Tabs/TabPanel.vue
  src/renderer/app/components/Tabs/Tabs.stories.ts
  src/renderer/app/components/Tabs/Tabs.test.ts
  src/renderer/app/components/Tabs/Tabs.vue
  src/renderer/app/components/Tabs/__snapshots__/Tabs.test.ts.snap
  src/renderer/app/components/Tabs/index.ts
  src/renderer/app/components/Tabs/useTab.ts
  src/renderer/main.js
  yarn.lock
Labels: Complexity: High, Type: Feature

#2020 ci: apply eslint and prettier rules
  .github/workflows/format.yml
Labels: Complexity: Low

#2019 chore: some improvements to the `ListDivided` component
  .storybook/main.js
  .storybook/preview.ts
  src/renderer/app/components/ListDivided/ListDivided.stories.ts
  src/renderer/app/components/ListDivided/ListDivided.vue
  src/renderer/app/components/ListDivided/ListDividedItem.test.ts
  src/renderer/app/components/ListDivided/ListDividedItem.vue
  src/renderer/app/components/ListDivided/__snapshots__/ListDividedItem.test.ts.snap
  src/renderer/app/components/Tabs/Tab.vue
  src/renderer/app/components/Tabs/TabList.vue
  src/renderer/app/components/Tabs/TabPanel.vue
  src/renderer/app/components/Tabs/Tabs.stories.ts
  src/renderer/app/components/Tabs/Tabs.test.ts
  src/renderer/app/components/Tabs/Tabs.vue
  src/renderer/app/components/Tabs/index.ts
  src/renderer/app/components/Tabs/useTab.ts
  src/renderer/main.js
Labels: Complexity: Medium, Type: Task

#2027 ci: add format and unit test workflow
  .eslintignore
  .github/stale.yml
  .github/workflows/format.yml
  .github/workflows/test.yml
  package.json
  yarn.lock
Labels: Complexity: Medium

#2028 test: add select component tests
  package.json
  src/app/components/Select/Select.tsx
  src/app/components/Select/__tests__/Select.spec.tsx
  src/app/components/Select/__tests__/__snapshots__/Select.spec.tsx.snap
  src/index.tsx
Labels: Complexity: Medium

#2029 test: add step indicator specs
  package.json
  src/app/components/StepIndicator/__tests__/StepIndicator.spec.tsx
  src/app/components/StepIndicator/__tests__/__snapshots__/StepIndicator.spec.tsx.snap
Labels: Complexity: Low

#2030 test: increase coverage
  src/app/components/Alert/__tests__/Alert.spec.tsx
  src/app/components/Alert/__tests__/__snapshots__/Alert.spec.tsx.snap
  src/app/components/Button/__tests__/Button.spec.tsx
  src/app/components/Button/__tests__/__snapshots__/Button.spec.tsx.snap
  src/app/components/Card/CardControl.tsx
  src/app/components/Card/__tests__/CardControl.spec.tsx
  src/app/components/Card/__tests__/__snapshots__/CardControl.spec.tsx.snap
Labels: Complexity: Medium

#2031 tests: add tabs specs
  src/app/components/SvgIcon/SvgIcon.tsx
  src/app/components/Tabs/Tabs.tsx
  src/app/components/Tabs/__tests__/Tabs.spec.tsx
  src/app/components/Tabs/__tests__/__snapshots__/Tabs.spec.tsx.snap
Labels: Complexity: Medium

#2032 tests: add toggle specs
  src/app/components/Toggle/Toggle.stories.tsx
  src/app/components/Toggle/Toggle.tsx
  src/app/components/Toggle/__tests__/Toggle.spec.tsx
  src/app/components/Toggle/__tests__/__snapshots__/Toggle.spec.tsx.snap
Labels: Complexity: Medium

#2033 chore: import modules using absolute paths
  src/app/components/Input/Input.tsx
  src/app/components/ListDivided/ListDividedItem.stories.tsx
  src/app/components/ListDivided/__tests__/ListDivided.spec.tsx
  src/app/components/NavBar/NavBar.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/wallets/pages/ImportWallet/ImportWallet.tsx
  src/router/index.tsx
Labels: Complexity: Low, Type: Task

#2034 refactor: improve svg icon
  package.json
  src/app/components/SvgIcon/SvgIcon.tsx
  src/app/components/SvgIcon/__tests__/SvgIcon.spec.tsx
  src/app/components/SvgIcon/__tests__/__snapshots__/SvgIcon.spec.tsx.snap
  src/resources/assets/svg/index.ts
  yarn.lock
Labels: Complexity: Medium, Type: Refactor

#2035 test: add profile card specs
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__tests__/ProfileCard.spec.tsx
  src/domains/profile/components/ProfileCard/__tests__/__snapshots__/ProfileCard.spec.tsx.snap
Labels: Complexity: Medium

#2036 feat: add electron about window
  .eslintrc.js
  package.json
  public/electron.js
  public/menu.js
  yarn.lock
Labels: Complexity: Low, Type: Feature

#2037 ci: apply `prettier` and `eslint` rules
  .eslintrc.js
  .github/workflows/format.yml
  .storybook/main.js
  config-overrides.js
  package.json
  public/menu.js
  src/app/components/Button/index.ts
  src/app/components/Button/style.ts
  src/app/components/Select/index.ts
  src/app/components/StepIndicator/index.ts
  src/app/components/Tabs/useTab.ts
  src/app/components/Toggle/index.ts
  src/i18n/locales/en-US/config.ts
  src/i18n/locales/index.ts
  src/tailwind.config.js
  src/types.d.ts
Labels: Complexity: High

#2038 test: improvements and maintenance
  package.json
  src/app/components/Form/Form.tsx
  src/app/components/Input/Input.tsx
  src/app/components/ListDivided/ListDivided.tsx
  src/app/components/ListDivided/__tests__/__snapshots__/ListDivided.spec.tsx.snap
  src/app/components/SvgIcon/SvgIcon.tsx
  src/app/components/SvgIcon/__tests__/__snapshots__/SvgIcon.spec.tsx.snap
  src/domains/profile/components/ProfileCard/__tests__/__snapshots__/ProfileCard.spec.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__tests__/CreateProfile.spec.tsx
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
  src/domains/wallets/pages/ImportWallet/ImportWallet.tsx
  src/setupTests.ts
  yarn.lock
Labels: Complexity: High, Type: Feature

#2042 chore: apply svg dimensions
  src/app/components/SvgIcon/SvgIcon.tsx
  src/app/components/SvgIcon/__tests__/__snapshots__/SvgIcon.spec.tsx.snap
  src/domains/profile/components/ProfileCard/__tests__/__snapshots__/ProfileCard.spec.tsx.snap
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
Labels: Complexity: Low, Type: Task

#2043 chore: move electron files to `src` folder and some tweaks
  .editorconfig
  .eslintignore
  .eslintrc.js
  LICENSE
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/electron/index.js
  src/electron/menu.js
  src/tailwind.config.js
Labels: Complexity: High, Type: Task

#2045 test: increase coverage
  package.json
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/__tests__/index.spec.ts
  src/app/components/Card/CardControl.tsx
  src/app/components/Card/__tests__/__snapshots__/CardControl.spec.tsx.snap
  src/domains/profile/pages/CreateProfile/__tests__/CreateProfile.spec.tsx
  src/domains/profile/pages/Welcome/__tests__/Welcome.spec.tsx
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
  src/domains/wallets/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallets/pages/ImportWallet/__tests__/ImportWallet.spec.tsx
  src/domains/wallets/pages/ImportWallet/__tests__/__snapshots__/ImportWallet.spec.tsx.snap
  src/domains/wallets/pages/ImportWallet/index.tsx
Labels: Complexity: High, Status: Needs Review

#2047 refactor: avoid default exports
  .storybook/Layout.tsx
  .storybook/preview.js
  src/app/components/Alert/Alert.stories.tsx
  src/app/components/Alert/Alert.tsx
  src/app/components/Alert/__tests__/Alert.spec.tsx
  src/app/components/Alert/__tests__/__snapshots__/Alert.spec.tsx.snap
  src/app/components/Alert/style.ts
  src/app/components/Button/__tests__/__snapshots__/Button.spec.tsx.snap
  src/app/components/Button/style.ts
  src/app/components/ListDivided/ListDivided.tsx
  src/app/components/ListDivided/index.tsx
  src/app/components/SvgIcon/SvgIcon.tsx
  src/app/components/SvgIcon/index.tsx
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
  src/domains/profile/pages/Welcome/__tests__/Welcome.spec.tsx
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
  src/domains/profile/routing.tsx
  src/domains/wallets/pages/ImportWallet/__tests__/ImportWallet.spec.tsx
  src/domains/wallets/pages/ImportWallet/__tests__/__snapshots__/ImportWallet.spec.tsx.snap
  src/i18n/index.ts
  src/i18n/locales/en-US/config.ts
  src/i18n/locales/en-US/messages.ts
  src/i18n/locales/index.ts
  src/index.tsx
  src/resources/assets/images/index.ts
  src/resources/assets/svg/index.ts
  src/router/index.tsx
Labels: Complexity: Medium, Type: Refactor

#2051 test: setup cypress and E2E tests
  .eslintrc.js
  .github/workflows/test.yml
  cypress.json
  cypress/integration/startup.spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  tsconfig.json
  yarn.lock
Labels: Complexity: High, Type: Feature

#2054 feat: add side bar component
  .storybook/preview.js
  cypress/plugins/index.js
  package.json
  src/app/components/SideBar/SideBar.stories.tsx
  src/app/components/SideBar/SideBar.tsx
  src/app/components/SideBar/SideBarItem/SideBarItem.stories.tsx
  src/app/components/SideBar/SideBarItem/SideBarItem.tsx
  src/app/components/SideBar/SideBarItem/__tests__/SideBarItem.spec.tsx
  src/app/components/SideBar/SideBarItem/__tests__/__snapshots__/SideBarItem.spec.tsx.snap
  src/app/components/SideBar/SideBarItem/index.tsx
  src/app/components/SideBar/__tests__/SideBar.spec.tsx
  src/app/components/SideBar/__tests__/__snapshots__/SideBar.spec.tsx.snap
  src/app/components/SideBar/index.ts
  src/resources/assets/svg/general.svg
  src/resources/assets/svg/index.ts
  src/resources/assets/svg/peer.svg
  src/resources/assets/svg/plugin.svg
  yarn.lock
Labels: Complexity: High, Type: Feature

#2053 feat: add form components
  package.json
  src/app/components/Button/Button.tsx
  src/app/components/Button/__tests__/__snapshots__/Button.spec.tsx.snap
  src/app/components/Form/Form.stories.tsx
  src/app/components/Form/Form.tsx
  src/app/components/Form/FormError/FormError.tsx
  src/app/components/Form/FormError/index.tsx
  src/app/components/Form/FormField.tsx
  src/app/components/Form/FormHelperText.tsx
  src/app/components/Form/FormLabel.tsx
  src/app/components/Form/__tests__/Form.spec.tsx
  src/app/components/Form/__tests__/FormField.spec.tsx
  src/app/components/Form/__tests__/FormHelperText.spec.tsx
  src/app/components/Form/__tests__/FormLabel.spec.tsx
  src/app/components/Form/__tests__/__snapshots__/Form.spec.tsx.snap
  src/app/components/Form/__tests__/__snapshots__/FormHelperText.spec.tsx.snap
  src/app/components/Form/__tests__/__snapshots__/FormLabel.spec.tsx.snap
  src/app/components/Form/index.tsx
  src/app/components/Form/useFormField.tsx
  src/app/components/Input/Input.stories.tsx
  src/app/components/Input/Input.tsx
  src/app/components/Input/__tests__/Input.spec.tsx
  src/app/components/Input/__tests__/__snapshots__/Input.spec.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
  src/domains/wallets/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallets/pages/ImportWallet/__tests__/ImportWallet.spec.tsx
  src/domains/wallets/pages/ImportWallet/__tests__/__snapshots__/ImportWallet.spec.tsx.snap
  yarn.lock
Labels: Complexity: High, Type: Feature

#2055 feat: add input group & password
  src/app/components/Form/FormField.tsx
  src/app/components/Icon/Icon.stories.tsx
  src/app/components/Icon/Icon.tsx
  src/app/components/Icon/__tests__/Icon.spec.tsx
  src/app/components/Icon/__tests__/__snapshots__/Icon.spec.tsx.snap
  src/app/components/Icon/index.tsx
  src/app/components/Input/Input.stories.tsx
  src/app/components/Input/InputGroup.stories.tsx
  src/app/components/Input/InputGroup.tsx
  src/app/components/Input/InputPassword.tsx
  src/app/components/Input/__tests__/InputGroup.spec.tsx
  src/app/components/Input/__tests__/InputPassword.spec.tsx
  src/app/components/Input/__tests__/__snapshots__/InputGroup.spec.tsx.snap
  src/app/components/Input/__tests__/__snapshots__/InputPassword.spec.tsx.snap
  src/app/components/Input/index.tsx
  src/app/components/SideBar/SideBarItem/SideBarItem.tsx
  src/app/components/SideBar/SideBarItem/__tests__/__snapshots__/SideBarItem.spec.tsx.snap
  src/app/components/SideBar/__tests__/__snapshots__/SideBar.spec.tsx.snap
  src/app/components/SvgIcon/index.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__tests__/__snapshots__/ProfileCard.spec.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
  src/domains/wallets/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallets/pages/ImportWallet/__tests__/__snapshots__/ImportWallet.spec.tsx.snap
  src/resources/assets/svg/eye-off.svg
  src/resources/assets/svg/eye.svg
  src/resources/assets/svg/index.ts
Labels: Complexity: High

#2052 feat: add `<Divider>` component
  src/app/components/Divider/Divider.stories.tsx
  src/app/components/Divider/Divider.tsx
  src/app/components/Divider/__tests__/Divider.spec.tsx
  src/app/components/Divider/__tests__/__snapshots__/Divider.spec.tsx.snap
  src/app/components/Divider/index.ts
  src/app/components/Divider/style.ts
Labels: Complexity: Low, Type: Feature

#2057 refactor: `Select` and `Textarea` with validation
  src/app/components/Alert/Alert.stories.tsx
  src/app/components/Button/Button.stories.tsx
  src/app/components/Card/Card.stories.tsx
  src/app/components/Divider/Divider.stories.tsx
  src/app/components/Form/Form.stories.tsx
  src/app/components/Icon/Icon.stories.tsx
  src/app/components/Input/Input.stories.tsx
  src/app/components/Input/InputGroup.stories.tsx
  src/app/components/ListDivided/ListDivided.stories.tsx
  src/app/components/ListDivided/ListDividedItem.stories.tsx
  src/app/components/NavBar/NavBar.stories.tsx
  src/app/components/Select/Select.stories.tsx
  src/app/components/Select/Select.tsx
  src/app/components/Select/__tests__/Select.spec.tsx
  src/app/components/Select/__tests__/__snapshots__/Select.spec.tsx.snap
  src/app/components/SideBar/SideBar.stories.tsx
  src/app/components/SideBar/SideBarItem/SideBarItem.stories.tsx
  src/app/components/StepIndicator/StepIndicator.stories.tsx
  src/app/components/Tabs/Tabs.stories.tsx
  src/app/components/Textarea/Textarea.stories.tsx
  src/app/components/Textarea/Textarea.tsx
  src/app/components/Textarea/__tests__/Textarea.spec.tsx
  src/app/components/Textarea/__tests__/__snapshots__/Textarea.spec.tsx.snap
  src/app/components/Textarea/index.ts
  src/app/components/Toggle/Toggle.stories.tsx
  src/resources/assets/svg/chevron-down.svg
  src/resources/assets/svg/index.ts
  src/tailwind.config.js
Labels: Complexity: High, Type: Refactor

#2061 chore: add tailwindcss debug screens
  package.json
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/index.tsx
  src/tailwind.config.js
  yarn.lock
Labels: Complexity: Low

#2059 feat: add `WalletMnemonicList` component
  src/domains/profile/components/ProfileCard/ProfileCard.stories.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.stories.tsx
  src/domains/profile/pages/Welcome/Welcome.stories.tsx
  src/domains/wallets/components/WalletMnemonicList/WalletMnemonicList.stories.tsx
  src/domains/wallets/components/WalletMnemonicList/WalletMnemonicList.tsx
  src/domains/wallets/components/WalletMnemonicList/__tests__/WalletMnemonicList.spec.tsx
  src/domains/wallets/components/WalletMnemonicList/__tests__/__snapshots__/WalletMnemonicList.spec.tsx.snap
  src/domains/wallets/components/WalletMnemonicList/index.ts
  src/domains/wallets/pages/ImportWallet/ImportWallet.stories.tsx
Labels: Complexity: Medium, Type: Feature

#2062 feat: modal component
  .editorconfig
  src/app/components/Button/Button.tsx
  src/app/components/Button/__tests__/Button.spec.tsx
  src/app/components/Button/__tests__/__snapshots__/Button.spec.tsx.snap
  src/app/components/Button/style.ts
  src/app/components/Modal/Modal.stories.tsx
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__tests__/Modal.spec.tsx
  src/app/components/Modal/__tests__/__snapshots__/Modal.spec.tsx.snap
  src/app/components/Modal/index.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
  src/resources/assets/svg/cross-slim.svg
  src/resources/assets/svg/index.ts
  src/styles/app.css
  src/styles/headings.css
  src/tailwind.config.js
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#2063 fix: responsive welcome page and some tweaks
  src/app/components/Modal/Modal.stories.tsx
  src/app/components/Modal/index.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
  src/styles/app.css
Labels: Complexity: Low, Type: Bugfix

#2064 feat: component dropdown
  src/app/components/Dropdown/Dropdown.stories.tsx
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/Dropdown/__tests__/Dropdown.spec.tsx
  src/app/components/Dropdown/__tests__/__snapshots__/Dropdown.spec.tsx.snap
  src/app/components/Dropdown/hooks.ts
Labels: Complexity: High

#2066 feat: add settings page
  src/app/components/Form/FormLabel.tsx
  src/app/components/Form/__tests__/__snapshots__/FormLabel.spec.tsx.snap
  src/app/components/Header/Header.tsx
  src/app/components/Header/__tests__/Header.spec.tsx
  src/app/components/Header/__tests__/__snapshots__/Header.spec.tsx.snap
  src/app/components/Header/index.ts
  src/app/components/ListDivided/ListDivided.tsx
  src/app/components/ListDivided/ListDividedItem.tsx
  src/app/components/ListDivided/__tests__/__snapshots__/ListDivided.spec.tsx.snap
  src/app/components/ListDivided/__tests__/__snapshots__/ListDividedItem.spec.tsx.snap
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
  src/domains/settings/pages/Settings/Settings.stories.tsx
  src/domains/settings/pages/Settings/Settings.tsx
  src/domains/settings/pages/Settings/__tests__/Settings.spec.tsx
  src/domains/settings/pages/Settings/__tests__/__snapshots__/Settings.spec.tsx.snap
  src/domains/settings/pages/Settings/available-settings/General.tsx
  src/domains/settings/pages/Settings/available-settings/index.ts
  src/domains/settings/pages/Settings/index.tsx
Labels: Complexity: Undetermined, Type: Feature

#2067 feat: add circle component
  src/app/components/Circle/Circle.stories.tsx
  src/app/components/Circle/Circle.tsx
  src/app/components/Circle/__tests__/Circle.spec.tsx
  src/app/components/Circle/__tests__/__snapshots__/Circle.spec.tsx.snap
  src/app/components/Circle/index.ts
  src/app/components/Circle/style.ts
Labels: Complexity: Medium, Type: Feature

#2070 fix: build errors
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/Dropdown/index.ts
  src/app/components/Header/index.ts
  src/app/components/ListDivided/ListDividedItem.tsx
  src/domains/settings/pages/Settings/Settings.tsx
  src/domains/settings/pages/Settings/__tests__/__snapshots__/Settings.spec.tsx.snap
  src/domains/settings/pages/Settings/available-settings/General.tsx
  src/domains/settings/pages/Settings/available-settings/index.ts
Labels: Complexity: High, Type: Bugfix

#2069 feat: add sign message component
  src/app/components/Circle/Circle.tsx
  src/app/components/Circle/__tests__/Circle.spec.tsx
  src/app/components/Circle/__tests__/__snapshots__/Circle.spec.tsx.snap
  src/app/components/Circle/style.ts
  src/app/components/Dropdown/__tests__/Dropdown.spec.tsx
  src/app/components/Input/InputPassword.tsx
  src/app/components/Input/__tests__/InputPassword.spec.tsx
  src/app/components/Input/__tests__/__snapshots__/InputPassword.spec.tsx.snap
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__tests__/__snapshots__/Modal.spec.tsx.snap
  src/domains/wallets/components/SignMessage/SignMessage.stories.tsx
  src/domains/wallets/components/SignMessage/SignMessage.tsx
  src/domains/wallets/components/SignMessage/__tests__/SignMessage.spec.tsx
  src/domains/wallets/components/SignMessage/__tests__/__snapshots__/SignMessage.spec.tsx.snap
  src/domains/wallets/components/SignMessage/index.ts
  src/resources/assets/svg/qrcode.svg
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2072 feat: add address format component
  src/app/components/Address/Address.stories.tsx
  src/app/components/Address/Address.tsx
  src/app/components/Address/__tests__/Address.spec.tsx
  src/app/components/Address/__tests__/__snapshots__/Address.spec.tsx.snap
  src/app/components/Address/index.ts
  src/app/components/Address/utils.ts
Labels: Complexity: Medium, Type: Feature

#2081 fix: update create profile page
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__tests__/CreateProfile.spec.tsx
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
Labels: Complexity: High, Type: Bugfix

#2079 chore: add marketsquare icon
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
  src/resources/assets/svg/index.ts
  src/resources/assets/svg/msq.svg
Labels: Complexity: Medium, Type: Task

#2078 feat: add verify message
  src/app/components/Alert/Alert.tsx
  src/app/components/Alert/__tests__/__snapshots__/Alert.spec.tsx.snap
  src/domains/wallets/components/VerifyMessage/VerifyMessage.stories.tsx
  src/domains/wallets/components/VerifyMessage/VerifyMessage.tsx
  src/domains/wallets/components/VerifyMessage/__tests__/VerifyMessage.spec.tsx
  src/domains/wallets/components/VerifyMessage/__tests__/__snapshots__/VerifyMessage.spec.tsx.snap
  src/domains/wallets/components/VerifyMessage/index.ts
Labels: Complexity: High, Type: Feature

#2077 feat: add WalletMnemonicVerification component
  config-overrides.js
  package.json
  src/app/components/Tabs/Tabs.tsx
  src/app/components/Tabs/__tests__/Tabs.spec.tsx
  src/app/components/Tabs/__tests__/__snapshots__/Tabs.spec.tsx.snap
  src/domains/wallets/components/MnemonicVerification/MnemonicVerification.stories.tsx
  src/domains/wallets/components/MnemonicVerification/MnemonicVerification.tsx
  src/domains/wallets/components/MnemonicVerification/MnemonicVerificationOptions.tsx
  src/domains/wallets/components/MnemonicVerification/MnemonicVerificationProgress.tsx
  src/domains/wallets/components/MnemonicVerification/__tests__/MnemonicVerification.spec.tsx
  src/domains/wallets/components/MnemonicVerification/__tests__/MnemonicVerificationOptions.spec.tsx
  src/domains/wallets/components/MnemonicVerification/__tests__/MnemonicVerificationProgress.spec.tsx
  src/domains/wallets/components/MnemonicVerification/__tests__/__snapshots__/MnemonicVerificationProgress.spec.tsx.snap
  src/domains/wallets/components/MnemonicVerification/__tests__/utils/shuffleOptions.spec.ts
  src/domains/wallets/components/MnemonicVerification/index.ts
  src/domains/wallets/components/MnemonicVerification/utils/shuffleOptions.ts
  src/domains/wallets/pages/ImportWallet/ImportWallet.tsx
  src/resources/assets/svg/checkmark.svg
  src/resources/assets/svg/index.ts
  src/tailwind.config.js
  yarn.lock
Labels: Complexity: High, Type: Feature

#2076 feat: add wallet card component
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/WalletCard/WalletCard.stories.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__tests__/WalletCard.spec.tsx
  src/app/components/WalletCard/__tests__/__snapshots__/WalletCard.spec.tsx.snap
  src/app/components/WalletCard/index.ts
Labels: Complexity: High

#2074 feat: update wallet name modal
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/app/components/Form/FormLabel.tsx
  src/app/components/Form/__tests__/__snapshots__/FormLabel.spec.tsx.snap
  src/app/components/Modal/Modal.stories.tsx
  src/app/components/Modal/Modal.tsx
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
  src/domains/settings/pages/Settings/__tests__/__snapshots__/Settings.spec.tsx.snap
  src/domains/wallets/components/SignMessage/SignMessage.tsx
  src/domains/wallets/components/UpdateWalletName/UpdateWalletName.stories.tsx
  src/domains/wallets/components/UpdateWalletName/UpdateWalletName.tsx
  src/domains/wallets/components/UpdateWalletName/__tests__/UpdateWalletName.spec.tsx
  src/domains/wallets/components/UpdateWalletName/__tests__/__snapshots__/UpdateWalletName.spec.tsx.snap
  src/domains/wallets/components/UpdateWalletName/index.tsx
  src/i18n/index.ts
  src/i18n/locales/en-US/messages.ts
  src/i18n/utils.ts
Labels: Complexity: High, Type: Feature

#2071 feat: add dropdown to profile card
  src/domains/profile/components/ProfileCard/ProfileCard.stories.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__tests__/ProfileCard.spec.tsx
  src/domains/profile/components/ProfileCard/__tests__/__snapshots__/ProfileCard.spec.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Medium, Type: Feature

#2080 feat: contact us modal component
  .eslintignore
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/app/components/Dropdown/__tests__/__snapshots__/Dropdown.spec.tsx.snap
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__tests__/__snapshots__/Modal.spec.tsx.snap
  src/app/components/WalletCard/__tests__/__snapshots__/WalletCard.spec.tsx.snap
  src/domains/help/components/ContactUs/ContactUs.stories.tsx
  src/domains/help/components/ContactUs/ContactUs.tsx
  src/domains/help/components/ContactUs/__tests__/ContactUs.spec.tsx
  src/domains/help/components/ContactUs/__tests__/__snapshots__/ContactUs.spec.tsx.snap
  src/domains/help/components/ContactUs/index.tsx
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
  src/domains/wallets/components/MnemonicVerification/MnemonicVerification.tsx
  src/domains/wallets/components/MnemonicVerification/MnemonicVerificationProgress.tsx
  src/domains/wallets/components/MnemonicVerification/__tests__/MnemonicVerificationOptions.spec.tsx
  src/domains/wallets/components/MnemonicVerification/__tests__/MnemonicVerificationProgress.spec.tsx
  src/domains/wallets/components/UpdateWalletName/UpdateWalletName.stories.tsx
  src/domains/wallets/components/UpdateWalletName/__tests__/__snapshots__/UpdateWalletName.spec.tsx.snap
  src/domains/wallets/components/VerifyMessage/__tests__/__snapshots__/VerifyMessage.spec.tsx.snap
  src/i18n/locales/en-US/messages.ts
  src/resources/assets/svg/discord.svg
  src/resources/assets/svg/index.ts
  src/resources/assets/svg/send.svg
  src/resources/assets/svg/slack.svg
  src/resources/assets/svg/twitter.svg
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2026 feat(ledger): add schnorr support
  __tests__/unit/__mocks__/@arkecosystem/ledger-transport.js
  __tests__/unit/services/ledger-service.spec.js
  __tests__/unit/services/transaction.spec.js
  __tests__/unit/store/modules/ledger.spec.js
  package.json
  src/renderer/services/ledger-service.js
  src/renderer/services/transaction.js
  src/renderer/store/modules/ledger.js
  yarn.lock
Labels: Complexity: Medium, Type: Feature

#2084 fix: show indicator that no network connection is established
  src/renderer/SplashScreen.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Bugfix

#2097 feat: add `<NavigationHeader>` component
  src/app/assets/svg/arrow-back.svg
  src/app/assets/svg/index.ts
  src/app/components/NavigationHeader/NavigationHeader.stories.tsx
  src/app/components/NavigationHeader/NavigationHeader.tsx
  src/app/components/NavigationHeader/__tests__/NavigationHeader.spec.tsx
  src/app/components/NavigationHeader/__tests__/__snapshots__/NavigationHeader.spec.tsx.snap
  src/app/components/NavigationHeader/index.ts
Labels: Complexity: Medium, Type: Feature

#2087 refactor: replace `react-intl` with `react-i18next`
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/app/components/Dropdown/__tests__/Dropdown.spec.tsx
  src/app/components/Input/__tests__/InputPassword.spec.tsx
  src/app/components/Modal/__tests__/Modal.spec.tsx
  src/app/components/SideBar/SideBarItem/__tests__/SideBarItem.spec.tsx
  src/app/i18n/common/i18n.ts
  src/app/i18n/helpers/index.ts
  src/app/i18n/index.ts
  src/domains/help/components/ContactUs/ContactUs.tsx
  src/domains/help/components/ContactUs/__tests__/ContactUs.spec.tsx
  src/domains/help/components/ContactUs/__tests__/__snapshots__/ContactUs.spec.tsx.snap
  src/domains/help/i18n.ts
  src/domains/profile/components/ProfileCard/__tests__/ProfileCard.spec.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__tests__/Welcome.spec.tsx
  src/domains/wallets/components/UpdateWalletName/UpdateWalletName.tsx
  src/domains/wallets/components/UpdateWalletName/__tests__/UpdateWalletName.spec.tsx
  src/domains/wallets/components/UpdateWalletName/__tests__/__snapshots__/UpdateWalletName.spec.tsx.snap
  src/domains/wallets/i18n.ts
  src/domains/wallets/pages/ImportWallet/__tests__/ImportWallet.spec.tsx
  src/i18n/index.ts
  src/i18n/locales/en-US/config.ts
  src/i18n/locales/en-US/messages.ts
  src/i18n/locales/index.ts
  src/i18n/utils.ts
  src/index.tsx
  yarn.lock
Labels: Complexity: Undetermined, Type: Bugfix

#2096 feat: add create wallet page
  package.json
  src/app/assets/svg/copy.svg
  src/app/assets/svg/download.svg
  src/app/assets/svg/file-password.svg
  src/app/assets/svg/index.ts
  src/app/components/Form/FormLabel.tsx
  src/app/components/Form/__tests__/__snapshots__/FormLabel.spec.tsx.snap
  src/domains/help/components/ContactUs/__tests__/__snapshots__/ContactUs.spec.tsx.snap
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
  src/domains/settings/pages/Settings/__tests__/__snapshots__/Settings.spec.tsx.snap
  src/domains/wallets/components/MnemonicList/MnemonicList.stories.tsx
  src/domains/wallets/components/MnemonicList/MnemonicList.tsx
  src/domains/wallets/components/MnemonicList/__tests__/MnemonicList.spec.tsx
  src/domains/wallets/components/MnemonicList/__tests__/__snapshots__/MnemonicList.spec.tsx.snap
  src/domains/wallets/components/MnemonicList/index.ts
  src/domains/wallets/components/UpdateWalletName/__tests__/__snapshots__/UpdateWalletName.spec.tsx.snap
  src/domains/wallets/components/VerifyMessage/__tests__/__snapshots__/VerifyMessage.spec.tsx.snap
  src/domains/wallets/components/WalletMnemonicList/index.ts
  src/domains/wallets/pages/CreateWallet/CreateWallet.stories.tsx
  src/domains/wallets/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallets/pages/CreateWallet/__tests__/CreateWallet.spec.tsx
  src/domains/wallets/pages/CreateWallet/__tests__/__snapshots__/CreateWallet.spec.tsx.snap
  src/domains/wallets/pages/CreateWallet/index.ts
  yarn.lock
Labels: Complexity: Undetermined, Type: Feature

#2085 feat: add Badge component
  src/app/assets/svg/ark.svg
  src/app/assets/svg/btc.svg
  src/app/assets/svg/eth.svg
  src/app/components/Badge/Badge.stories.tsx
  src/app/components/Badge/Badge.tsx
  src/app/components/Badge/__tests__/Badge.spec.tsx
  src/app/components/Badge/__tests__/__snapshots__/Badge.spec.tsx.snap
  src/app/components/Badge/index.ts
  src/app/components/Badge/style.ts
Labels: Complexity: High

#2092 feat: add SelectNetwork component
  src/app/components/SelectNetwork/SelectNetwork.stories.tsx
  src/app/components/SelectNetwork/SelectNetwork.tsx
  src/app/components/SelectNetwork/__tests__/SelectNetwork.spec.tsx
  src/app/components/SelectNetwork/__tests__/__snapshots__/SelectNetwork.spec.tsx.snap
  src/app/components/SelectNetwork/index.ts
Labels: Complexity: High

#2093 feat: add `FilterWallets` component
  src/app/components/FilterWallets/FilterWallets.stories.tsx
  src/app/components/FilterWallets/FilterWallets.tsx
  src/app/components/FilterWallets/__tests__/FilterWallets.spec.tsx
  src/app/components/FilterWallets/__tests__/__snapshots__/FilterWallets.spec.tsx.snap
  src/app/components/FilterWallets/index.ts
Labels: Complexity: High, Type: Feature

#2098 feat: add `WalletsControls` component
  src/app/assets/svg/filters.svg
  src/app/assets/svg/grid.svg
  src/app/assets/svg/import.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/list.svg
  src/app/assets/svg/plus.svg
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/Dropdown/style.ts
  src/app/components/FilterWallets/FilterWallets.tsx
  src/app/components/FilterWallets/__tests__/__snapshots__/FilterWallets.spec.tsx.snap
  src/app/components/WalletsControls/WalletsControls.stories.tsx
  src/app/components/WalletsControls/WalletsControls.tsx
  src/app/components/WalletsControls/__tests__/WalletsControls.spec.tsx
  src/app/components/WalletsControls/__tests__/__snapshots__/WalletsControls.spec.tsx.snap
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__tests__/__snapshots__/ProfileCard.spec.tsx.snap
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
Labels: Complexity: High

#2099 ci: compress SVG assets with `svgo` if they change
  .github/workflows/compress.yml
  src/app/assets/svg/ark.svg
  src/app/assets/svg/arrow-back.svg
  src/app/assets/svg/btc.svg
  src/app/assets/svg/checkmark.svg
  src/app/assets/svg/chevron-down.svg
  src/app/assets/svg/close.svg
  src/app/assets/svg/copy.svg
  src/app/assets/svg/cross-slim.svg
  src/app/assets/svg/discord.svg
  src/app/assets/svg/download.svg
  src/app/assets/svg/eth.svg
  src/app/assets/svg/eye-off.svg
  src/app/assets/svg/eye.svg
  src/app/assets/svg/file-password.svg
  src/app/assets/svg/filters.svg
  src/app/assets/svg/general.svg
  src/app/assets/svg/grid.svg
  src/app/assets/svg/import.svg
  src/app/assets/svg/list.svg
  src/app/assets/svg/msq.svg
  src/app/assets/svg/peer.svg
  src/app/assets/svg/plugin.svg
  src/app/assets/svg/plus.svg
  src/app/assets/svg/qrcode.svg
  src/app/assets/svg/settings.svg
  src/app/assets/svg/slack.svg
  src/app/assets/svg/twitter.svg
  src/app/assets/svg/upload.svg
  src/domains/profile/images/welcome-banner.svg
Labels: Complexity: Low

#2100 chore: add `Inter` font family
  src/app/assets/fonts/Inter-Bold.otf
  src/app/assets/fonts/Inter-BoldItalic.otf
  src/app/assets/fonts/Inter-ExtraBold.otf
  src/app/assets/fonts/Inter-ExtraBoldItalic.otf
  src/app/assets/fonts/Inter-Italic.otf
  src/app/assets/fonts/Inter-Medium.otf
  src/app/assets/fonts/Inter-MediumItalic.otf
  src/app/assets/fonts/Inter-Regular.otf
  src/app/assets/fonts/Inter-SemiBold.otf
  src/app/assets/fonts/Inter-SemiBoldItalic.otf
  src/styles/app.css
  src/styles/fonts.css
  src/tailwind.config.js
Labels: Complexity: Low, Type: Task

#2090 feat: delete wallet
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/app/assets/images/delete-banner.svg
  src/app/assets/images/index.ts
  src/app/assets/svg/index.ts
  src/app/assets/svg/trash.svg
  src/app/components/Modal/Modal.tsx
  src/app/i18n/common/i18n.ts
  src/domains/wallets/components/DeleteWallet/DeleteWallet.stories.tsx
  src/domains/wallets/components/DeleteWallet/DeleteWallet.tsx
  src/domains/wallets/components/DeleteWallet/__tests__/DeleteWallet.spec.tsx
  src/domains/wallets/components/DeleteWallet/__tests__/__snapshots__/DeleteWallet.spec.tsx.snap
  src/domains/wallets/components/DeleteWallet/index.tsx
  src/domains/wallets/i18n.ts
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2101 fix: add missing contact heading
  src/domains/help/components/ContactUs/ContactUs.tsx
  src/domains/help/components/ContactUs/__tests__/__snapshots__/ContactUs.spec.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2102 fix: add missing name wallet image
  src/app/assets/images/index.ts
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__tests__/__snapshots__/Modal.spec.tsx.snap
  src/domains/help/components/ContactUs/__tests__/__snapshots__/ContactUs.spec.tsx.snap
  src/domains/wallets/components/DeleteWallet/__tests__/__snapshots__/DeleteWallet.spec.tsx.snap
  src/domains/wallets/components/UpdateWalletName/UpdateWalletName.tsx
  src/domains/wallets/components/UpdateWalletName/__tests__/__snapshots__/UpdateWalletName.spec.tsx.snap
  src/domains/wallets/components/VerifyMessage/__tests__/__snapshots__/VerifyMessage.spec.tsx.snap
  src/domains/wallets/images/index.ts
  src/domains/wallets/images/name-wallet.svg
  src/styles/headings.css
Labels: Complexity: Medium

#2091 feat: modal profile created
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/app/i18n/helpers/index.ts
  src/domains/profile/components/ProfileCreated/ProfileCreated.stories.tsx
  src/domains/profile/components/ProfileCreated/ProfileCreated.tsx
  src/domains/profile/components/ProfileCreated/__tests__/ProfileCreated.spec.tsx
  src/domains/profile/components/ProfileCreated/__tests__/__snapshots__/ProfileCreated.spec.tsx.snap
  src/domains/profile/components/ProfileCreated/index.tsx
  src/domains/profile/i18n.ts
  src/domains/profile/images/index.tsx
  src/domains/profile/images/profile-created-banner.svg
Labels: Complexity: Medium, Type: Feature

#2104 feat: add verify message status
  src/app/assets/svg/confirmed.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/mistake.svg
  src/domains/wallets/components/VerifyMessageStatus/VerifyMessageStatus.stories.tsx
  src/domains/wallets/components/VerifyMessageStatus/VerifyMessageStatus.tsx
  src/domains/wallets/components/VerifyMessageStatus/__tests__/VerifyMessageStatus.spec.tsx
  src/domains/wallets/components/VerifyMessageStatus/__tests__/__snapshots__/VerifyMessageStatus.spec.tsx.snap
  src/domains/wallets/components/VerifyMessageStatus/index.ts
Labels: Complexity: High, Type: Feature

#2103 feat: add `Table` component
  package.json
  src/app/assets/svg/arrowdown.svg
  src/app/assets/svg/arrowup.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/sort.svg
  src/app/components/Table/Table.stories.tsx
  src/app/components/Table/Table.tsx
  src/app/components/Table/__tests__/Table.spec.tsx
  src/app/components/Table/__tests__/__snapshots__/Table.spec.tsx.snap
  src/app/components/Table/index.ts
  src/app/components/Table/style.ts
  yarn.lock
Labels: Complexity: High, Type: Feature

#2105 fix: settings button
  src/app/assets/svg/close.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/reset.svg
  src/domains/settings/pages/Settings/Settings.stories.tsx
  src/domains/settings/pages/Settings/__tests__/__snapshots__/Settings.spec.tsx.snap
  src/domains/settings/pages/Settings/available-settings/General.tsx
Labels: Complexity: Medium, Type: Bugfix

#2108 feat: label component
  src/app/components/Label/Label.stories.tsx
  src/app/components/Label/Label.tsx
  src/app/components/Label/__tests__/Label.spec.tsx
  src/app/components/Label/__tests__/__snapshots__/Label.spec.tsx.snap
  src/app/components/Label/index.tsx
  src/app/components/Label/style.tsx
Labels: Complexity: Medium, Type: Feature

#2107 feat: add `WalletListItem` component
  src/app/assets/svg/index.ts
  src/app/assets/svg/ledger.svg
  src/app/assets/svg/multisig.svg
  src/app/assets/svg/star.svg
  src/app/components/Table/Table.tsx
  src/app/components/Table/__tests__/__snapshots__/Table.spec.tsx.snap
  src/app/components/WalletListItem/WalletListItem.stories.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__tests__/WalletListItem.spec.tsx
  src/app/components/WalletListItem/__tests__/__snapshots__/WalletListItem.spec.tsx.snap
  src/app/components/WalletListItem/index.ts
Labels: Complexity: High

#2111 ci: run tests against node 12 and 14
  .github/workflows/test.yml
Labels: Complexity: Low

#2106 feat: add `<CircleProgressBar>` component
  src/app/components/CircleProgressBar/CircleProgressBar.stories.tsx
  src/app/components/CircleProgressBar/CircleProgressBar.tsx
  src/app/components/CircleProgressBar/__tests__/CircleProgressBar.spec.tsx
  src/app/components/CircleProgressBar/__tests__/__snapshots__/CircleProgressBar.spec.tsx.snap
  src/app/components/CircleProgressBar/index.ts
Labels: Complexity: Low, Type: Feature

#2112 chore: install `@arkecosystem/platform-sdk-*` dependencies
  .github/workflows/build.yml
  .github/workflows/format.yml
  .github/workflows/test.yml
  package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2113 chore: rename `Textarea` to `TextArea`
  src/app/components/Form/Form.stories.tsx
  src/app/components/TextArea/TextArea.stories.tsx
  src/app/components/TextArea/TextArea.tsx
  src/app/components/TextArea/__tests__/TextArea.spec.tsx
  src/app/components/TextArea/__tests__/__snapshots__/TextArea.spec.tsx.snap
  src/app/components/TextArea/index.ts
  src/app/components/Textarea/Textarea.stories.tsx
  src/app/components/Textarea/Textarea.tsx
  src/app/components/Textarea/index.ts
  src/domains/help/components/ContactUs/ContactUs.tsx
  src/domains/help/components/ContactUs/__tests__/__snapshots__/ContactUs.spec.tsx.snap
Labels: Complexity: Medium, Status: Needs Review, Type: Task

#2110 feat: add signed message modal
  src/app/assets/svg/delegate.svg
  src/app/assets/svg/index.ts
  src/app/components/Address/Address.tsx
  src/app/components/Address/__tests__/Address.spec.tsx
  src/app/components/Address/__tests__/__snapshots__/Address.spec.tsx.snap
  src/app/components/ListDivided/ListDividedItem.tsx
  src/app/components/ListDivided/__tests__/__snapshots__/ListDivided.spec.tsx.snap
  src/app/components/ListDivided/__tests__/__snapshots__/ListDividedItem.spec.tsx.snap
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__tests__/__snapshots__/Modal.spec.tsx.snap
  src/app/components/WalletCard/__tests__/__snapshots__/WalletCard.spec.tsx.snap
  src/domains/help/components/ContactUs/__tests__/__snapshots__/ContactUs.spec.tsx.snap
  src/domains/profile/components/ProfileCreated/__tests__/__snapshots__/ProfileCreated.spec.tsx.snap
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.spec.tsx.snap
  src/domains/settings/pages/Settings/__tests__/__snapshots__/Settings.spec.tsx.snap
  src/domains/wallets/components/DeleteWallet/__tests__/__snapshots__/DeleteWallet.spec.tsx.snap
  src/domains/wallets/components/SignMessage/SignMessage.stories.tsx
  src/domains/wallets/components/SignMessage/SignMessage.tsx
  src/domains/wallets/components/SignMessage/__tests__/SignMessage.spec.tsx
  src/domains/wallets/components/SignMessage/__tests__/__snapshots__/SignMessage.spec.tsx.snap
  src/domains/wallets/components/UpdateWalletName/__tests__/__snapshots__/UpdateWalletName.spec.tsx.snap
  src/domains/wallets/components/VerifyMessage/__tests__/__snapshots__/VerifyMessage.spec.tsx.snap
  src/domains/wallets/components/VerifyMessageStatus/__tests__/__snapshots__/VerifyMessageStatus.spec.tsx.snap
Labels: Complexity: High, Type: Feature

#2115 chore: modify `Label` styling
  src/app/components/Label/Label.tsx
  src/app/components/Label/__tests__/__snapshots__/Label.spec.tsx.snap
  src/app/components/Label/style.tsx
Labels: Complexity: Low, Type: Task

#2116 feat: add `TransactionListItem` component
  src/app/assets/svg/index.ts
  src/app/assets/svg/received.svg
  src/app/assets/svg/sent.svg
  src/app/components/Table/Table.tsx
  src/app/components/TransactionListItem/TransactionListItem.stories.tsx
  src/app/components/TransactionListItem/TransactionListItem.tsx
  src/app/components/TransactionListItem/__tests__/TransactionListItem.spec.tsx
  src/app/components/TransactionListItem/__tests__/__snapshots__/TransactionListItem.spec.tsx.snap
  src/app/components/TransactionListItem/index.ts
Labels: Complexity: High, Type: Feature

#2118 fix: remove QRCode icon from password field
  src/app/components/Input/InputPassword.tsx
  src/app/components/Input/__tests__/InputPassword.spec.tsx
  src/app/components/Input/__tests__/__snapshots__/InputPassword.spec.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2117 refactor: styled wrappers in jsx
  src/app/components/Badge/Badge.tsx
  src/app/components/Badge/__tests__/__snapshots__/Badge.spec.tsx.snap
  src/app/components/Badge/style.ts
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/Dropdown/style.ts
  src/app/components/FilterWallets/__tests__/__snapshots__/FilterWallets.spec.tsx.snap
  src/app/components/Input/InputPassword.tsx
  src/app/components/Input/__tests__/__snapshots__/InputPassword.spec.tsx.snap
  src/app/components/SelectNetwork/__tests__/__snapshots__/SelectNetwork.spec.tsx.snap
  src/app/components/Table/Table.tsx
  src/app/components/Table/__tests__/__snapshots__/Table.spec.tsx.snap
  src/app/components/Table/style.ts
Labels: Complexity: Medium, Type: Refactor

#2120 feat: add `Slider` component
  package.json
  src/app/components/Slider/Slider.stories.tsx
  src/app/components/Slider/Slider.tsx
  src/app/components/Slider/__tests__/Slider.spec.tsx
  src/app/components/Slider/__tests__/__snapshots__/Slider.spec.tsx.snap
  src/app/components/Slider/index.ts
  yarn.lock
Labels: Complexity: High, Type: Feature

#2109 feat: transfer detail modal
  .github/workflows/compress.yml
  .github/workflows/format.yml
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/app/assets/svg/delegate.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/smartbridge.svg
  src/app/components/TransactionDetail/TransactionDetail.stories.tsx
  src/app/components/TransactionDetail/TransactionDetail.tsx
  src/app/components/TransactionDetail/__tests__/TransactionDetail.spec.tsx
  src/app/components/TransactionDetail/__tests__/__snapshots__/TransactionDetail.spec.tsx.snap
  src/app/components/TransactionDetail/index.tsx
  src/app/i18n/helpers/index.ts
  src/domains/transaction/components/TransferDetail/TransferDetail.stories.tsx
  src/domains/transaction/components/TransferDetail/TransferDetail.tsx
  src/domains/transaction/components/TransferDetail/__tests__/TransferDetail.spec.tsx
  src/domains/transaction/components/TransferDetail/__tests__/__snapshots__/TransferDetail.spec.tsx.snap
  src/domains/transaction/components/TransferDetail/index.tsx
  src/domains/transaction/i18n.tsx
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2121 refactor: improve `CreateWallet` design
  src/app/assets/svg/alert-danger.svg
  src/app/assets/svg/alert-default.svg
  src/app/assets/svg/alert-success.svg
  src/app/assets/svg/checkmark.svg
  src/app/assets/svg/download.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/ok.svg
  src/app/components/Alert/Alert.stories.tsx
  src/app/components/Alert/Alert.tsx
  src/app/components/Alert/__tests__/__snapshots__/Alert.spec.tsx.snap
  src/app/components/Alert/style.ts
  src/app/components/Card/Card.tsx
  src/app/components/Card/CardControl.tsx
  src/app/components/Card/__tests__/__snapshots__/Card.spec.tsx.snap
  src/app/components/Card/__tests__/__snapshots__/CardControl.spec.tsx.snap
  src/app/components/Circle/Circle.stories.tsx
  src/app/components/Circle/__tests__/__snapshots__/Circle.spec.tsx.snap
  src/app/components/Circle/style.ts
  src/app/components/FilterWallets/__tests__/__snapshots__/FilterWallets.spec.tsx.snap
  src/app/components/SelectNetwork/__tests__/__snapshots__/SelectNetwork.spec.tsx.snap
  src/app/components/StepIndicator/StepIndicator.tsx
  src/app/components/StepIndicator/__tests__/__snapshots__/StepIndicator.spec.tsx.snap
  src/app/components/TransactionListItem/__tests__/__snapshots__/TransactionListItem.spec.tsx.snap
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__tests__/__snapshots__/WalletCard.spec.tsx.snap
  src/app/components/WalletListItem/__tests__/__snapshots__/WalletListItem.spec.tsx.snap
  src/domains/help/components/ContactUs/__tests__/__snapshots__/ContactUs.spec.tsx.snap
  src/domains/profile/components/ProfileCard/__tests__/__snapshots__/ProfileCard.spec.tsx.snap
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.spec.tsx.snap
  src/domains/transaction/components/TransferDetail/__tests__/__snapshots__/TransferDetail.spec.tsx.snap
  src/domains/wallets/components/MnemonicVerification/MnemonicVerification.tsx
  src/domains/wallets/components/MnemonicVerification/MnemonicVerificationProgress.tsx
  src/domains/wallets/components/MnemonicVerification/__tests__/__snapshots__/MnemonicVerificationProgress.spec.tsx.snap
  src/domains/wallets/components/SignMessage/SignMessage.tsx
  src/domains/wallets/components/VerifyMessage/__tests__/__snapshots__/VerifyMessage.spec.tsx.snap
  src/domains/wallets/pages/CreateWallet/CreateWallet.stories.tsx
  src/domains/wallets/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallets/pages/CreateWallet/__tests__/__snapshots__/CreateWallet.spec.tsx.snap
  src/domains/wallets/pages/ImportWallet/__tests__/__snapshots__/ImportWallet.spec.tsx.snap
  src/styles/headings.css
Labels: Complexity: High, Type: Refactor

#2124 feat: wallet update modal
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/app/i18n/common/i18n.ts
  src/domains/wallets/components/WalletUpdate/WalletUpdate.stories.tsx
  src/domains/wallets/components/WalletUpdate/WalletUpdate.tsx
  src/domains/wallets/components/WalletUpdate/__tests__/WalletUpdate.spec.tsx
  src/domains/wallets/components/WalletUpdate/__tests__/__snapshots__/WalletUpdate.spec.tsx.snap
  src/domains/wallets/components/WalletUpdate/index.tsx
  src/domains/wallets/i18n.ts
  src/domains/wallets/images/index.ts
  src/domains/wallets/images/wallet-update-ready.svg
  src/domains/wallets/images/wallet-update.svg
Labels: Complexity: Medium, Type: Feature

#2125 feat: multipayment detail modal
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/app/components/TransactionDetail/TransactionDetail.tsx
  src/app/components/TransactionDetail/__tests__/TransactionDetail.spec.tsx
  src/app/components/TransactionDetail/__tests__/__snapshots__/TransactionDetail.spec.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.stories.tsx
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.tsx
  src/domains/transaction/components/MultiPaymentDetail/__tests__/MultiPaymentDetail.spec.tsx
  src/domains/transaction/components/MultiPaymentDetail/__tests__/__snapshots__/MultiPaymentDetail.spec.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/index.tsx
  src/domains/transaction/components/Recipient/Recipient.stories.tsx
  src/domains/transaction/components/Recipient/Recipient.tsx
  src/domains/transaction/components/Recipient/__tests__/Recipient.spec.tsx
  src/domains/transaction/components/Recipient/__tests__/__snapshots__/Recipient.spec.tsx.snap
  src/domains/transaction/components/Recipient/index.ts
  src/domains/transaction/i18n.tsx
Labels: Complexity: High, Type: Feature

#2119 feat: add `<Spinner>` component
  src/app/components/Spinner/Spinner.stories.tsx
  src/app/components/Spinner/Spinner.tsx
  src/app/components/Spinner/__tests__/Spinner.spec.tsx
  src/app/components/Spinner/__tests__/__snapshots__/Spinner.spec.tsx.snap
  src/app/components/Spinner/index.ts
  src/app/components/Spinner/style.ts
Labels: Complexity: Low, Type: Feature

#2126 feat: initial multisig detail modal
  src/__tests__/__snapshots__/index.spec.ts.snap
  src/app/assets/svg/index.ts
  src/app/assets/svg/status-clock.svg
  src/app/i18n/common/i18n.ts
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.stories.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx
  src/domains/transaction/components/MultiSignatureDetail/__tests__/MultiSignatureDetail.spec.tsx
  src/domains/transaction/components/MultiSignatureDetail/__tests__/__snapshots__/MultiSignatureDetail.spec.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/index.tsx
  src/domains/transaction/i18n.tsx
Labels: Complexity: High, Type: Feature

#2127 ci: only install `rustywind` during workflow
  .github/workflows/format.yml
  package.json
  yarn.lock
Labels: Complexity: Low, Status: Needs Review

#2130 refactor: use `default` fallback for switch statements
  src/app/components/Button/Button.styles.ts
  src/app/components/Button/__tests__/__snapshots__/Button.test.tsx.snap
  src/app/components/Circle/Circle.styles.ts
  src/app/components/Circle/__tests__/__snapshots__/Circle.test.tsx.snap
  src/app/components/FilterWallets/__tests__/__snapshots__/FilterWallets.test.tsx.snap
  src/app/components/Modal/__tests__/__snapshots__/Modal.test.tsx.snap
  src/app/components/SelectNetwork/__tests__/__snapshots__/SelectNetwork.test.tsx.snap
  src/app/components/Spinner/Spinner.styles.ts
  src/app/components/TransactionListItem/__tests__/__snapshots__/TransactionListItem.test.tsx.snap
  src/app/components/WalletCard/__tests__/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/__tests__/__snapshots__/WalletListItem.test.tsx.snap
  src/app/components/WalletsControls/__tests__/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/help/components/ContactUs/__tests__/__snapshots__/ContactUs.test.tsx.snap
  src/domains/profile/components/ProfileCreated/__tests__/__snapshots__/ProfileCreated.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.test.tsx.snap
  src/domains/settings/pages/Settings/__tests__/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__tests__/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__tests__/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__tests__/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/Recipient/__tests__/__snapshots__/Recipient.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__tests__/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__tests__/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/wallets/components/DeleteWallet/__tests__/__snapshots__/DeleteWallet.test.tsx.snap
  src/domains/wallets/components/UpdateWalletName/__tests__/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallets/components/VerifyMessage/__tests__/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallets/components/VerifyMessageStatus/__tests__/__snapshots__/VerifyMessageStatus.test.tsx.snap
  src/domains/wallets/components/WalletUpdate/__tests__/__snapshots__/WalletUpdate.test.tsx.snap
  src/domains/wallets/pages/CreateWallet/__tests__/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallets/pages/ImportWallet/__tests__/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2132 feat: add dashboard `Transactions` component
  src/app/components/TransactionListItem/TransactionListItem.tsx
  src/app/components/TransactionListItem/__tests__/__snapshots__/TransactionListItem.test.tsx.snap
  src/domains/dashboard/components/Transactions/Transactions.stories.tsx
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/components/Transactions/__tests__/Transactions.spec.tsx
  src/domains/dashboard/components/Transactions/__tests__/__snapshots__/Transactions.spec.tsx.snap
  src/domains/dashboard/components/Transactions/index.tsx
  src/domains/dashboard/data.ts
Labels: Complexity: Undetermined, Type: Feature

#2131 refactor: move wallet components to domain
  src/domains/dashboard/components/FilterWallets/FilterWallets.stories.tsx
  src/domains/dashboard/components/FilterWallets/FilterWallets.tsx
  src/domains/dashboard/components/FilterWallets/__tests__/FilterWallets.spec.tsx
  src/domains/dashboard/components/FilterWallets/__tests__/__snapshots__/FilterWallets.spec.tsx.snap
  src/domains/dashboard/components/FilterWallets/index.ts
  src/domains/dashboard/components/WalletsControls/WalletsControls.stories.tsx
  src/domains/dashboard/components/WalletsControls/WalletsControls.tsx
  src/domains/dashboard/components/WalletsControls/__tests__/WalletsControls.spec.tsx
  src/domains/dashboard/components/WalletsControls/__tests__/__snapshots__/WalletsControls.spec.tsx.snap
  src/domains/dashboard/components/WalletsControls/index.tsx
Labels: Complexity: Low, Type: Refactor

#2133 feat: add dashboard `Wallets` component
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__tests__/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__tests__/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/dashboard/components/Wallets/Wallets.stories.tsx
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__tests__/Wallets.test.tsx
  src/domains/dashboard/components/Wallets/__tests__/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/Wallets/index.tsx
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2135 feat: add `Dashboard` domain page
  src/app/components/Slider/Slider.tsx
  src/app/components/Slider/__tests__/__snapshots__/Slider.test.tsx.snap
  src/app/components/Table/Table.styles.ts
  src/app/components/Table/__tests__/__snapshots__/Table.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.stories.tsx
  src/domains/dashboard/components/FilterWallets/FilterWallets.tsx
  src/domains/dashboard/components/FilterWallets/__tests__/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/dashboard/components/Transactions/__tests__/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__tests__/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.stories.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__tests__/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/__tests__/__snapshots__/Dashboard.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/index.tsx
Labels: Complexity: High, Type: Feature

#2136 feat: add `InputRange` component
  package.json
  src/app/components/Input/InputRange.stories.tsx
  src/app/components/Input/InputRange.tsx
  src/app/components/Input/__tests__/InputRange.test.tsx
  src/app/components/Input/__tests__/__snapshots__/InputRange.test.tsx.snap
  src/app/components/Range/Range.stories.tsx
  src/app/components/Range/Range.tsx
  src/app/components/Range/__tests__/Range.test.tsx
  src/app/components/Range/__tests__/__snapshots__/Range.test.tsx.snap
  src/app/components/Range/index.ts
  src/tailwind.config.js
  yarn.lock
Labels: Complexity: High, Type: Feature

#2128 feat: add `<Checkbox>` component
  package.json
  src/app/components/Checkbox/Checkbox.stories.tsx
  src/app/components/Checkbox/Checkbox.styles.ts
  src/app/components/Checkbox/Checkbox.tsx
  src/app/components/Checkbox/__tests__/Checkbox.test.tsx
  src/app/components/Checkbox/__tests__/__snapshots__/Checkbox.test.tsx.snap
  src/app/components/Checkbox/index.ts
  yarn.lock
Labels: Complexity: Medium, Type: Feature

#2137 feat: add `RadioButton` component
  src/app/components/RadioButton/RadioButton.stories.tsx
  src/app/components/RadioButton/RadioButton.tsx
  src/app/components/RadioButton/__tests__/RadioButton.test.tsx
  src/app/components/RadioButton/__tests__/__snapshots__/RadioButton.test.tsx.snap
  src/app/components/RadioButton/index.ts
  src/app/components/RadioButton/useRadioState.tsx
Labels: Complexity: Medium, Type: Feature

#2139 fix: display back button in 1st step of create wallet page
  src/domains/wallets/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallets/pages/CreateWallet/__tests__/__snapshots__/CreateWallet.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#2138 refactor: spinner component
  src/app/components/Checkbox/__tests__/Checkbox.test.tsx
  src/app/components/Spinner/Spinner.styles.ts
  src/app/components/Spinner/__tests__/Spinner.test.tsx
Labels: Complexity: Medium, Type: Refactor

#2140 refactor: rename `CircleProgressBar` to `CircularProgressBar` and some tweaks
  src/app/components/CircleProgressBar/CircleProgressBar.stories.tsx
  src/app/components/CircleProgressBar/CircleProgressBar.tsx
  src/app/components/CircleProgressBar/__tests__/CircleProgressBar.test.tsx
  src/app/components/CircleProgressBar/__tests__/__snapshots__/CircleProgressBar.test.tsx.snap
  src/app/components/CircleProgressBar/index.ts
  src/app/components/CircularProgressBar/CircularProgressBar.stories.tsx
  src/app/components/CircularProgressBar/CircularProgressBar.tsx
  src/app/components/CircularProgressBar/__tests__/CircularProgressBar.test.tsx
  src/app/components/CircularProgressBar/__tests__/__snapshots__/CircularProgressBar.test.tsx.snap
  src/app/components/CircularProgressBar/index.ts
  src/domains/wallets/components/WalletUpdate/WalletUpdate.tsx
  src/domains/wallets/components/WalletUpdate/__tests__/__snapshots__/WalletUpdate.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2141 feat: add `InputCounter` component
  src/app/components/Input/Input.stories.tsx
  src/app/components/Input/InputCounter.tsx
  src/app/components/Input/__tests__/InputCounter.test.tsx
  src/app/components/Input/__tests__/__snapshots__/InputCounter.test.tsx.snap
  src/app/components/Input/index.tsx
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/settings/pages/Settings/__tests__/__snapshots__/Settings.test.tsx.snap
  src/domains/wallets/components/VerifyMessage/__tests__/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallets/pages/CreateWallet/__tests__/__snapshots__/CreateWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Feature

#2142 chore: add toggle content prop on `Dropdown`
  src/app/components/Dropdown/Dropdown.stories.tsx
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/Dropdown/__tests__/Dropdown.test.tsx
  src/app/components/Dropdown/__tests__/__snapshots__/Dropdown.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#2143 feat: add `NavBar` component
  cypress/fixtures/example.json
  cypress/integration/startup.spec.js
  src/app/assets/svg/index.ts
  src/app/assets/svg/notification.svg
  src/app/assets/svg/receive.svg
  src/app/components/Circle/Circle.styles.ts
  src/app/components/Circle/Circle.tsx
  src/app/components/NavBar/NavBar.stories.tsx
  src/app/components/NavBar/NavBar.tsx
  src/app/components/NavBar/__tests__/NavBar.test.tsx
  src/app/components/NavBar/__tests__/__snapshots__/NavBar.test.tsx.snap
  src/app/components/NavBar/style.ts
  src/domains/profile/pages/CreateProfile/__tests__/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/__tests__/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__tests__/Welcome.test.tsx
  src/domains/profile/pages/Welcome/__tests__/__snapshots__/Welcome.test.tsx.snap
Labels: Complexity: High

#2145 docs: add coding standards for reactjs
  CODING_STANDARDS.md
Labels: Complexity: Medium, Type: Documentation

#2148 feat: add compact variant to `TransactionListItem`
  src/app/components/TransactionListItem/TransactionListItem.stories.tsx
  src/app/components/TransactionListItem/TransactionListItem.test.tsx
  src/app/components/TransactionListItem/TransactionListItem.tsx
  src/app/components/TransactionListItem/__snapshots__/TransactionListItem.test.tsx.snap
  src/app/components/TransactionListItem/models.ts
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
Labels: Complexity: High, Type: Feature

#2149 feat: add `Notifications` component
  src/app/components/Notifications/Notifications.stories.tsx
  src/app/components/Notifications/Notifications.test.tsx
  src/app/components/Notifications/Notifications.tsx
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Notifications/index.ts
  src/app/components/Table/Table.tsx
Labels: Complexity: High, Type: Feature

#2156 feat: search bar component
  src/__snapshots__/index.test.ts.snap
  src/app/assets/svg/arrowdown.svg
  src/app/components/Dropdown/Dropdown.styles.ts
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Table/Table.tsx
  src/app/components/Table/__snapshots__/Table.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/app/i18n/helpers/index.ts
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/search/components/SearchBar/SearchBar.stories.tsx
  src/domains/search/components/SearchBar/SearchBar.test.tsx
  src/domains/search/components/SearchBar/SearchBar.tsx
  src/domains/search/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/domains/search/components/SearchBar/index.ts
  src/domains/search/components/SearchBarOptions/SearchBarOptions.stories.tsx
  src/domains/search/components/SearchBarOptions/SearchBarOptions.test.tsx
  src/domains/search/components/SearchBarOptions/SearchBarOptions.tsx
  src/domains/search/components/SearchBarOptions/__snapshots__/SearchBarOptions.test.tsx.snap
  src/domains/search/components/SearchBarOptions/index.ts
  src/domains/search/i18n.ts
Labels: Complexity: High, Type: Feature

#2157 feat: add singleAction variant to wallet list item component
  src/app/components/WalletListItem/WalletListItem.stories.tsx
  src/app/components/WalletListItem/WalletListItem.test.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
Labels: Complexity: Medium, Type: Feature

#2155 feat: multisignature steps
  src/__snapshots__/index.test.ts.snap
  src/app/assets/images/index.ts
  src/app/assets/images/success-banner.svg
  src/app/i18n/common/i18n.ts
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.stories.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.test.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/i18n.tsx
Labels: Complexity: Undetermined, Type: Feature

#2152 feat: integrate `Notifications` in `NavBar`
  src/app/components/NavBar/NavBar.stories.tsx
  src/app/components/NavBar/NavBar.tsx
  src/app/components/NavBar/__snapshots__/NavBar.test.tsx.snap
  src/app/components/Notifications/Notifications.stories.tsx
  src/app/components/Notifications/Notifications.tsx
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Notifications/models.ts
  src/app/components/Table/Table.styles.ts
  src/app/components/Table/Table.tsx
  src/app/components/Table/__snapshots__/Table.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Labels: Complexity: High, Type: Feature

#2151 feat: add receive funds component
  src/__snapshots__/index.test.ts.snap
  src/domains/wallets/components/ReceiveFunds/ReceiveFunds.stories.tsx
  src/domains/wallets/components/ReceiveFunds/ReceiveFunds.test.tsx
  src/domains/wallets/components/ReceiveFunds/ReceiveFunds.tsx
  src/domains/wallets/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallets/components/ReceiveFunds/index.ts
  src/domains/wallets/i18n.ts
Labels: Complexity: High, Type: Feature

#2144 feat: add size props to modal component
  src/app/components/Modal/Modal.stories.tsx
  src/app/components/Modal/Modal.test.tsx
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/profile/components/ProfileCreated/__snapshots__/ProfileCreated.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/wallets/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
  src/domains/wallets/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallets/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallets/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallets/components/VerifyMessageStatus/__snapshots__/VerifyMessageStatus.test.tsx.snap
  src/domains/wallets/components/WalletUpdate/__snapshots__/WalletUpdate.test.tsx.snap
Labels: Complexity: High, Type: Feature

#2154 feat: add install plugin modal
  src/__snapshots__/index.test.ts.snap
  src/app/components/Circle/Circle.stories.tsx
  src/app/components/Circle/Circle.styles.ts
  src/app/components/Circle/Circle.test.tsx
  src/app/components/Circle/__snapshots__/Circle.test.tsx.snap
  src/app/components/CircularProgressBar/CircularProgressBar.tsx
  src/app/components/NavBar/__snapshots__/NavBar.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/app/components/TransactionListItem/TransactionListItem.test.tsx
  src/app/components/TransactionListItem/__snapshots__/TransactionListItem.test.tsx.snap
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/app/i18n/helpers/index.ts
  src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugins/components/InstallPlugin/InstallPlugin.stories.tsx
  src/domains/plugins/components/InstallPlugin/InstallPlugin.test.tsx
  src/domains/plugins/components/InstallPlugin/InstallPlugin.tsx
  src/domains/plugins/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
  src/domains/plugins/components/InstallPlugin/index.ts
  src/domains/plugins/i18n.ts
  src/domains/plugins/images/.gitkeep
  src/domains/plugins/pages/.gitkeep
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/Recipient/__snapshots__/Recipient.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/wallets/components/ReceiveFunds/__snapshots__/ReceiveFunds.test.tsx.snap
  src/domains/wallets/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Medium, Type: Feature

#2158 feat: search modal component
  src/__snapshots__/index.test.ts.snap
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/app/components/NavBar/__snapshots__/NavBar.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Table/Table.styles.ts
  src/app/components/Table/__snapshots__/Table.test.tsx.snap
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/search/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/domains/search/components/SearchBarOptions/SearchBarOptions.tsx
  src/domains/search/components/SearchBarOptions/__snapshots__/SearchBarOptions.test.tsx.snap
  src/domains/search/components/SearchModal/SearchModal.stories.tsx
  src/domains/search/components/SearchModal/SearchModal.test.tsx
  src/domains/search/components/SearchModal/SearchModal.tsx
  src/domains/search/components/SearchModal/__snapshots__/SearchModal.test.tsx.snap
  src/domains/search/components/SearchModal/index.ts
  src/domains/search/i18n.ts
Labels: Complexity: High, Type: Feature

#2159 feat: expose `Environment` from `@arkecosystem/platform-sdk-profiles`
  package.json
  src/__snapshots__/index.test.ts.snap
  src/app/contexts/Environment.test.tsx
  src/app/contexts/Environment.tsx
  src/app/contexts/__snapshots__/Environment.test.tsx.snap
  src/app/contexts/index.ts
  src/app/services/HttpClient.test.ts
  src/app/services/HttpClient.ts
  src/app/services/index.ts
  src/domains/profile/components/ProfileCard/ProfileCard.test.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.stories.tsx
  src/domains/profile/pages/Welcome/Welcome.test.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/index.tsx
  yarn.lock
Labels: Complexity: High, Type: Feature

#2160 refactor: sign message modal (signed state)
  src/domains/wallets/components/SignMessage/SignMessage.stories.tsx
  src/domains/wallets/components/SignMessage/SignMessage.test.tsx
  src/domains/wallets/components/SignMessage/SignMessage.tsx
  src/domains/wallets/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2165 feat: adds clipboard component
  src/app/components/Clipboard/Clipboard.stories.tsx
  src/app/components/Clipboard/Clipboard.test.tsx
  src/app/components/Clipboard/Clipboard.tsx
  src/app/components/Clipboard/__snapshots__/Clipboard.test.tsx.snap
  src/app/components/Clipboard/index.ts
Labels: Complexity: Medium, Type: Feature

#2163 feat: ledger wallet modal
  src/__snapshots__/index.test.ts.snap
  src/domains/wallets/components/LedgerWallet/LedgerWallet.stories.tsx
  src/domains/wallets/components/LedgerWallet/LedgerWallet.test.tsx
  src/domains/wallets/components/LedgerWallet/LedgerWallet.tsx
  src/domains/wallets/components/LedgerWallet/__snapshots__/LedgerWallet.test.tsx.snap
  src/domains/wallets/components/LedgerWallet/index.ts
  src/domains/wallets/i18n.ts
  src/domains/wallets/images/index.ts
  src/domains/wallets/images/waiting-ledger.svg
Labels: Complexity: Medium, Type: Feature

#2166 fix: full width on recipients list
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmMultiPayment.vue
Labels: Complexity: Low, Type: Bugfix

#2167 feat: select account modal
  src/__snapshots__/index.test.ts.snap
  src/app/components/Modal/Modal.test.tsx
  src/app/components/Modal/Modal.tsx
  src/app/components/Modal/__snapshots__/Modal.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/search/components/SearchBar/SearchBar.stories.tsx
  src/domains/search/components/SearchBarFilters/SearchBarFilters.stories.tsx
  src/domains/search/components/SearchBarFilters/SearchBarFilters.test.tsx
  src/domains/search/components/SearchBarFilters/SearchBarFilters.tsx
  src/domains/search/components/SearchBarFilters/__snapshots__/SearchBarFilters.test.tsx.snap
  src/domains/search/components/SearchBarFilters/index.ts
  src/domains/wallets/components/ReceiveFunds/ReceiveFunds.tsx
  src/domains/wallets/components/SelectAccount/SelectAccount.stories.tsx
  src/domains/wallets/components/SelectAccount/SelectAccount.test.tsx
  src/domains/wallets/components/SelectAccount/SelectAccount.tsx
  src/domains/wallets/components/SelectAccount/__snapshots__/SelectAccount.test.tsx.snap
  src/domains/wallets/components/SelectAccount/index.ts
  src/domains/wallets/data.ts
  src/domains/wallets/i18n.ts
Labels: Complexity: Undetermined

#2168 test: fix the warning not involved in act for `MultiSignatureDetail` tests
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.test.tsx
Labels: Complexity: Low, Test: Unit

#2170 ci: increase watchers for chokidar
  .github/workflows/test.yml
  package.json
Labels: Complexity: Low

#2162 docs: add naming conventions
  NAMING_CONVENTIONS.md
Labels: Complexity: Low, Status: Needs Review, Type: Documentation

#2171 refactor: rename `NavBar` to `NavigationBar` to comply with naming conventions
  NAMING_CONVENTIONS.md
  src/app/components/NavBar/index.tsx
  src/app/components/NavigationBar/NavigationBar.stories.tsx
  src/app/components/NavigationBar/NavigationBar.styles.ts
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/NavigationBar/index.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2161 refactor: rename `RadioButton` component to `SelectionBar`
  NAMING_CONVENTIONS.md
  src/app/components/RadioButton/RadioButton.stories.tsx
  src/app/components/RadioButton/index.ts
  src/app/components/SelectionBar/SelectionBar.stories.tsx
  src/app/components/SelectionBar/SelectionBar.test.tsx
  src/app/components/SelectionBar/SelectionBar.tsx
  src/app/components/SelectionBar/__snapshots__/SelectionBar.test.tsx.snap
  src/app/components/SelectionBar/index.ts
  src/app/components/SelectionBar/useSelectionState.tsx
Labels: Complexity: Medium, Type: Refactor

#2172 refactor: explicitly import components
  src/app/components/Card/Card.test.tsx
  src/app/components/Card/CardControl.test.tsx
  src/app/components/Card/__snapshots__/CardControl.test.tsx.snap
  src/app/components/Header/Header.test.tsx
  src/app/components/Input/Input.test.tsx
  src/app/components/Label/Label.test.tsx
  src/app/components/ListDivided/ListDivided.test.tsx
  src/app/components/ListDivided/ListDividedItem.test.tsx
  src/app/components/Modal/Modal.stories.tsx
  src/app/components/Modal/Modal.test.tsx
  src/app/components/NavigationHeader/NavigationHeader.test.tsx
  src/app/components/Select/Select.test.tsx
  src/app/components/SideBar/SideBar.stories.tsx
  src/app/components/SideBar/SideBar.test.tsx
  src/app/components/SideBar/SideBarItem/SideBarItem.test.tsx
  src/app/components/StepIndicator/StepIndicator.test.tsx
  src/app/components/Tabs/Tabs.test.tsx
  src/app/components/Toggle/Toggle.test.tsx
  src/app/components/TransactionDetail/TransactionDetail.test.tsx
  src/domains/help/components/ContactUs/ContactUs.stories.tsx
  src/domains/help/components/ContactUs/ContactUs.test.tsx
  src/domains/plugins/components/InstallPlugin/InstallPlugin.stories.tsx
  src/domains/plugins/components/InstallPlugin/InstallPlugin.test.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.test.tsx
  src/domains/profile/components/ProfileCreated/ProfileCreated.stories.tsx
  src/domains/profile/components/ProfileCreated/ProfileCreated.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/Welcome/Welcome.test.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/search/components/SearchBar/SearchBar.test.tsx
  src/domains/search/components/SearchBarFilters/SearchBarFilters.test.tsx
  src/domains/search/components/SearchBarOptions/SearchBarOptions.test.tsx
  src/domains/search/components/SearchModal/SearchModal.test.tsx
  src/domains/settings/pages/Settings/Settings.test.tsx
  src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.stories.tsx
  src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.test.tsx
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.stories.tsx
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.test.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.stories.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.test.tsx
  src/domains/transaction/components/Recipient/Recipient.test.tsx
  src/domains/transaction/components/TransferDetail/TransferDetail.stories.tsx
  src/domains/transaction/components/TransferDetail/TransferDetail.test.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.stories.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.test.tsx
  src/domains/wallets/components/DeleteWallet/DeleteWallet.stories.tsx
  src/domains/wallets/components/DeleteWallet/DeleteWallet.test.tsx
  src/domains/wallets/components/LedgerWallet/LedgerWallet.stories.tsx
  src/domains/wallets/components/LedgerWallet/LedgerWallet.test.tsx
  src/domains/wallets/components/ReceiveFunds/ReceiveFunds.test.tsx
  src/domains/wallets/components/SelectAccount/SelectAccount.test.tsx
  src/domains/wallets/components/SignMessage/SignMessage.test.tsx
  src/domains/wallets/components/UpdateWalletName/UpdateWalletName.stories.tsx
  src/domains/wallets/components/UpdateWalletName/UpdateWalletName.test.tsx
  src/domains/wallets/components/VerifyMessage/VerifyMessage.test.tsx
  src/domains/wallets/components/VerifyMessageStatus/VerifyMessageStatus.test.tsx
  src/domains/wallets/components/WalletUpdate/WalletUpdate.stories.tsx
  src/domains/wallets/components/WalletUpdate/WalletUpdate.test.tsx
  src/domains/wallets/pages/ImportWallet/ImportWallet.test.tsx
Labels: Complexity: Medium, Type: Refactor

#2173 chore: setup `eslint-plugin-unused-imports` for eslint rules
  .eslintrc.js
  .github/workflows/test.yml
  package.json
  src/app/components/Clipboard/Clipboard.tsx
  src/app/components/Input/InputGroup.tsx
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/search/components/SearchBar/SearchBar.stories.tsx
  src/domains/search/components/SearchBar/SearchBar.tsx
  src/domains/search/components/SearchBarFilters/SearchBarFilters.stories.tsx
  src/domains/search/components/SearchBarFilters/SearchBarFilters.test.tsx
  src/domains/search/components/SearchBarOptions/SearchBarOptions.stories.tsx
  src/domains/search/components/SearchBarOptions/SearchBarOptions.test.tsx
  src/domains/search/components/SearchModal/SearchModal.stories.tsx
  src/domains/transaction/components/Recipient/Recipient.stories.tsx
  src/domains/transaction/components/Recipient/Recipient.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.tsx
  src/domains/wallets/components/ReceiveFunds/ReceiveFunds.test.tsx
  src/domains/wallets/components/ReceiveFunds/ReceiveFunds.tsx
  src/domains/wallets/components/SelectAccount/SelectAccount.tsx
  yarn.lock
Labels: Complexity: Medium, Type: Task

#2174 test: add HTTP tests that cover actual behaviours
  package.json
  src/app/services/HttpClient.test.ts
  src/app/services/HttpClient.ts
  yarn.lock
Labels: Complexity: Medium, Test: Unit

#2175 ci: setup `actions/cache@v2` to cache `node_modules`
  .github/workflows/build.yml
  .github/workflows/format.yml
  .github/workflows/test.yml
Labels: Complexity: Medium

#2176 chore: add missing `@types/*` dependencies
  package.json
  src/app/services/HttpClient.test.ts
  src/app/services/HttpClient.ts
  yarn.lock
Labels: Complexity: Medium, Type: Task

#2178 chore: install development-only packages as `devDependencies`
  package.json
Labels: Complexity: Low, Type: Task

#2179 ci: setup artifact drafting
  .eslintignore
  .github/workflows/draft-artifacts.yml
  .github/workflows/publish-release.yml
  entitlements.mac.plist
  package.json
  scripts/notarize.js
  scripts/version-artifacts.sh
Labels: Complexity: Medium

#2164 feat: vote for delegate page
  src/app/assets/svg/index.ts
  src/app/assets/svg/transaction_successful.svg
  src/app/components/Address/Address.test.tsx
  src/app/components/Address/Address.tsx
  src/app/components/Clipboard/Clipboard.tsx
  src/app/components/Clipboard/index.tsx
  src/app/components/Icon/Icon.tsx
  src/domains/transaction/pages/VoteForDelegate/VoteForDelegate.stories.tsx
  src/domains/transaction/pages/VoteForDelegate/VoteForDelegate.tsx
  src/domains/transaction/pages/VoteForDelegate/__tests__/VoteForDelegate.spec.tsx
  src/domains/transaction/pages/VoteForDelegate/__tests__/__snapshots__/VoteForDelegate.spec.tsx.snap
  src/domains/transaction/pages/VoteForDelegate/index.tsx
Labels: Complexity: Undetermined, Type: Feature

#2181 refactor: remove navbar from profiles
  cypress/integration/startup.spec.js
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2185 chore: ignore build and coverage paths during format
  .eslintrc.js
  .prettierignore
Labels: Complexity: Low, Type: Task

#2184 feat: add `SelectDropdown` component
  package.json
  src/app/components/SelectDropdown/SelectDropdown.stories.tsx
  src/app/components/SelectDropdown/SelectDropdown.test.tsx
  src/app/components/SelectDropdown/SelectDropdown.tsx
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  yarn.lock
Labels: Complexity: High, Type: Feature

#2195 refactor: consistent button spacing
  src/app/components/DeleteResource/DeleteResource.tsx
  src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap
  src/domains/contacts/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/WalletsControls.tsx
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/help/components/ContactUs/ContactUs.tsx
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/plugins/components/InstallPlugin/InstallPlugin.tsx
  src/domains/plugins/components/InstallPlugin/__snapshots__/InstallPlugin.test.tsx.snap
  src/domains/profile/components/ProfileCreated/ProfileCreated.tsx
  src/domains/profile/components/ProfileCreated/__snapshots__/ProfileCreated.test.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/settings/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/settings/pages/Settings/available-settings/General.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/pages/VoteForDelegate/VoteForDelegate.tsx
  src/domains/transaction/pages/VoteForDelegate/__tests__/__snapshots__/VoteForDelegate.spec.tsx.snap
  src/domains/wallets/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
  src/domains/wallets/components/SignMessage/SignMessage.tsx
  src/domains/wallets/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallets/components/UpdateWalletName/UpdateWalletName.tsx
  src/domains/wallets/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallets/components/VerifyMessage/VerifyMessage.tsx
  src/domains/wallets/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallets/components/WalletUpdate/WalletUpdate.tsx
  src/domains/wallets/components/WalletUpdate/__snapshots__/WalletUpdate.test.tsx.snap
  src/domains/wallets/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallets/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallets/pages/ImportWallet/ImportWallet.tsx
Labels: Complexity: Medium, Type: Refactor

#2194 refactor: details modals tweaks
  src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.tsx
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.tsx
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransferDetail/TransferDetail.tsx
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/VoteDetail.tsx
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2192 feat: ipfs details modal
  src/__snapshots__/index.test.ts.snap
  src/app/assets/svg/index.ts
  src/app/assets/svg/ipfs.svg
  src/domains/transaction/components/IpfsDetailModal/IpfsDetailModal.stories.tsx
  src/domains/transaction/components/IpfsDetailModal/IpfsDetailModal.test.tsx
  src/domains/transaction/components/IpfsDetailModal/IpfsDetailModal.tsx
  src/domains/transaction/components/IpfsDetailModal/__snapshots__/IpfsDetailModal.test.tsx.snap
  src/domains/transaction/components/IpfsDetailModal/index.tsx
  src/domains/transaction/i18n.tsx
Labels: Complexity: High, Type: Feature

#2190 chore: add html coverage reporter
  package.json
Labels: Complexity: Low, Type: Task

#2188 feat: add peer settings
  src/domains/settings/components/PeerList/PeerList.stories.tsx
  src/domains/settings/components/PeerList/PeerList.test.tsx
  src/domains/settings/components/PeerList/PeerList.tsx
  src/domains/settings/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/settings/components/PeerList/index.ts
  src/domains/settings/components/PeerListItem/PeerListItem.stories.tsx
  src/domains/settings/components/PeerListItem/PeerListItem.test.tsx
  src/domains/settings/components/PeerListItem/PeerListItem.tsx
  src/domains/settings/components/PeerListItem/__snapshots__/PeerListItem.test.tsx.snap
  src/domains/settings/components/PeerListItem/index.ts
  src/domains/settings/data.ts
  src/domains/settings/pages/Settings/Settings.test.tsx
  src/domains/settings/pages/Settings/Settings.tsx
  src/domains/settings/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/settings/pages/Settings/available-settings/General.tsx
  src/domains/settings/pages/Settings/available-settings/Peer.tsx
  src/domains/settings/pages/Settings/available-settings/index.ts
Labels: Complexity: Medium, Type: Feature

#2193 refactor: transfer detail modal updates
  src/app/assets/svg/index.ts
  src/app/assets/svg/smartbridge.svg
  src/app/components/Label/Label.styles.tsx
  src/app/components/Label/__snapshots__/Label.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/TransactionListItem/__snapshots__/TransactionListItem.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/TransferDetail/TransferDetail.stories.tsx
  src/domains/transaction/components/TransferDetail/index.tsx
  src/domains/transaction/components/TransferDetailModal/TransferDetailModal.stories.tsx
  src/domains/transaction/components/TransferDetailModal/TransferDetailModal.test.tsx
  src/domains/transaction/components/TransferDetailModal/TransferDetailModal.tsx
  src/domains/transaction/components/TransferDetailModal/__snapshots__/TransferDetailModal.test.tsx.snap
  src/domains/transaction/components/TransferDetailModal/index.tsx
Labels: Complexity: Medium, Type: Refactor

#2187 feat: add `InputCurrency` component
  .eslintrc.js
  package.json
  src/app/components/Input/InputCurrency.stories.tsx
  src/app/components/Input/InputCurrency.test.tsx
  src/app/components/Input/InputCurrency.tsx
  src/app/components/Input/InputRange.test.tsx
  src/app/components/Input/InputRange.tsx
  src/app/components/Input/__snapshots__/InputCurrency.test.tsx.snap
  src/app/components/Input/__snapshots__/InputRange.test.tsx.snap
  src/app/components/Input/index.tsx
  src/domains/transaction/pages/VoteForDelegate/__tests__/__snapshots__/VoteForDelegate.spec.tsx.snap
  yarn.lock
Labels: Complexity: Medium, Type: Feature

#2197 chore: add `react/self-closing-comp` rule
  .eslintrc.js
  src/app/components/Address/Address.test.tsx
  src/app/components/Badge/Badge.stories.tsx
  src/app/components/Badge/Badge.tsx
  src/app/components/Circle/Circle.stories.tsx
  src/app/components/Circle/Circle.test.tsx
  src/app/components/Dropdown/Dropdown.stories.tsx
  src/app/components/Dropdown/Dropdown.test.tsx
  src/app/components/ListDivided/ListDivided.test.tsx
  src/app/components/ListDivided/ListDividedItem.stories.tsx
  src/app/components/NavigationBar/NavigationBar.stories.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/Notifications/Notifications.stories.tsx
  src/app/components/SelectDropdown/SelectDropdown.stories.tsx
  src/app/components/SelectDropdown/SelectDropdown.test.tsx
  src/app/components/SelectDropdown/SelectDropdown.tsx
  src/app/components/SelectNetwork/SelectNetwork.stories.tsx
  src/app/components/SelectNetwork/SelectNetwork.test.tsx
  src/app/components/SelectNetwork/SelectNetwork.tsx
  src/app/components/Table/Table.stories.tsx
  src/app/components/Table/Table.tsx
  src/app/components/TransactionDetail/TransactionDetail.stories.tsx
  src/app/components/TransactionListItem/TransactionListItem.stories.tsx
  src/app/components/TransactionListItem/TransactionListItem.test.tsx
  src/app/components/TransactionListItem/TransactionListItem.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/domains/dashboard/components/FilterWallets/FilterWallets.stories.tsx
  src/domains/dashboard/components/FilterWallets/FilterWallets.tsx
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/WalletsControls/WalletsControls.stories.tsx
  src/domains/dashboard/components/WalletsControls/WalletsControls.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.tsx
  src/domains/transaction/components/IpfsDetailModal/IpfsDetailModal.tsx
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.tsx
  src/domains/transaction/components/MultiSignatureDetail/MultiSignatureDetail.tsx
  src/domains/transaction/components/Recipient/Recipient.tsx
  src/domains/transaction/components/TransferDetailModal/TransferDetailModal.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.tsx
  src/domains/transaction/pages/VoteForDelegate/VoteForDelegate.tsx
  src/domains/wallets/components/SignMessage/SignMessage.tsx
Labels: Complexity: High, Type: Task
