Repository ArkEcosystem/desktop-wallet, pull requests merged in 2020-02, with the labels that each got.

#1617 ci: automatically run and commit eslint results
  .github/workflows/format.yml
  __tests__/unit.jest.conf.js
Labels: Complexity: Low

#1657 chore: bump version to 2.8.0
  .github/workflows/test.yml
  package.json
Labels: Complexity: Low, Type: Task

#1665 fix: translate the keypath values of the background and avatars modal
  __tests__/unit/components/Selection/SelectionBackground.spec.js
  src/renderer/components/Selection/mixin-selection-image.js
Labels: Complexity: Low, Type: Bugfix

#1653 fix: remove mouseup capabilities to trigger modal close.
  __tests__/unit/components/Modal/ModalWindow.spec.js
  src/renderer/components/Modal/ModalWindow.vue
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#1670 chore: remove juan as codeowner
  CODEOWNERS
Labels: Complexity: Low, Type: Task

#1634 fix: add truncate filter to the wallet balance in the profile
  __tests__/unit/pages/Profile/ProfileAll.spec.js
  src/renderer/pages/Profile/ProfileAll.vue
Labels: Complexity: Low, Status: Needs Testcase, Type: Bugfix

#1656 feat: add coincap price api
  __tests__/unit/__fixtures__/services/price-api/coin-cap/assets.json
  __tests__/unit/__fixtures__/services/price-api/coin-cap/historical.json
  __tests__/unit/__fixtures__/services/price-api/coin-cap/rates.json
  __tests__/unit/services/price-api.spec.js
  config/index.js
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/services/price-api.js
  src/renderer/services/price-api/coin-cap.js
Labels: Complexity: Undetermined, Status: Needs Changes, Type: Feature

#1677 chore: update doc link to vote for a delegate
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
Labels: Complexity: Low, Type: Task

#1668 fix: transaction list multi-payment amount
  __tests__/unit/services/transaction.spec.js
  src/renderer/components/Dashboard/DashboardTransactions.vue
  src/renderer/components/Transaction/TransactionAmount.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Transaction/TransactionShow/TransactionShow.vue
  src/renderer/components/Transaction/TransactionStatusIcon.vue
  src/renderer/components/Transaction/TransactionTable/TransactionTable.vue
  src/renderer/components/Transaction/TransactionTable/TransactionTableMultiSignature.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/transaction.js
  src/renderer/services/client.js
  src/renderer/services/synchronizer/wallets.js
  src/renderer/services/transaction.js
Labels: Complexity: Medium, Type: Bugfix

#1667 fix: business, bridgechain & delegate tweaks
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBusiness/mixin.spec.js
  __tests__/unit/services/wallet.spec.js
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBusiness/mixin.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeadingSecondaryActions.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/wallet.js
  src/renderer/services/wallet.js
Labels: Complexity: Low, Type: Bugfix

#1671 chore: add missing locale key & ui tweaks
  src/renderer/components/Input/InputPublicKey.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormMultiSignature.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Task

#1679 refactor: omit themes from list of all plugins
  __tests__/unit/components/PluginManager/PluginManagerSideMenu.spec.js
  src/renderer/components/PluginManager/PluginManagerSideMenu.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/services/plugin-manager.js
  src/renderer/store/modules/plugin.js
Labels: Complexity: Low, Type: Refactor

#1662 fix: off by one error in recipients validation and count in list title
  __tests__/unit/components/Input/InputEditableList.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormMultiPayment.spec.js
  src/renderer/components/Input/InputEditableList.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormMultiPayment.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormMultiSignature.vue
  src/renderer/components/Transaction/TransactionMultiPaymentList.vue
  src/renderer/components/Transaction/TransactionMultiSignatureList.vue
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#1659 fix: user custom sort function to sort by balance
  __tests__/unit/components/Wallet/WalletSidebar.spec.js
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1681 fix: truncate profile name
  src/renderer/pages/Profile/ProfileEdition.vue
Labels: Complexity: Low, Type: Bugfix

#1647 feat: additional pricing apis
  __tests__/unit/__fixtures__/services/crypto-compare-historical.json
  __tests__/unit/__fixtures__/services/crypto-compare-market.json
  __tests__/unit/__fixtures__/services/price-api/coin-cap/assets.json
  __tests__/unit/__fixtures__/services/price-api/coin-cap/historical.json
  __tests__/unit/__fixtures__/services/price-api/coin-cap/rates.json
  __tests__/unit/__fixtures__/services/price-api/coin-gecko/historical.json
  __tests__/unit/__fixtures__/services/price-api/coin-gecko/market.json
  __tests__/unit/__fixtures__/services/price-api/crypto-compare/historical.json
  __tests__/unit/__fixtures__/services/price-api/crypto-compare/market.json
  __tests__/unit/components/Network/NetworkModal.spec.js
  __tests__/unit/services/crypto-compare.spec.js
  __tests__/unit/services/price-api.spec.js
  __tests__/unit/store/modules/session.spec.js
  config/index.js
  src/renderer/components/App/AppSidemenu/AppSidemenuSettings.vue
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/components/Network/NetworkModal.vue
  src/renderer/components/utils/LineChart.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/profile.js
  src/renderer/pages/Dashboard.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/pages/Profile/ProfileNew.vue
  src/renderer/services/client.js
  src/renderer/services/crypto-compare.js
  src/renderer/services/price-api.js
  src/renderer/services/price-api/coin-cap.js
  src/renderer/services/price-api/coin-gecko.js
  src/renderer/services/price-api/crypto-compare.js
  src/renderer/store/modules/market.js
  src/renderer/store/modules/session.js
Labels: Complexity: Undetermined, Type: Feature

#1682 fix: hide vote button for resigned delegates and add status
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormVote.spec.js
  src/renderer/components/Input/InputDelegate.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#1663 feat: added snap package
  package.json
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#1686 ci: include commit hash in the build name
  .github/workflows/test.yml
Labels: Complexity: Low

#1689 chore: bump version to 2.8.1
  .github/workflows/test.yml
  package.json
Labels: Complexity: Low, Type: Task

#1691 fix: splashscreen fullscreen & ui tweaks
  src/main/index.js
  src/renderer/SplashScreen.vue
Labels: Complexity: Low, Type: Bugfix

#1694 chore: Make multipayment word consistent
  src/renderer/i18n/locales/en-US.js
Labels: Bounty: Tier 6, Complexity: Low, Type: Task

#1697 chore: Make multisignature text consistent
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Task

#1695 fix: plugin downloads
  src/main/index.js
  src/main/plugin-manager.js
Labels: Complexity: Medium, Type: Bugfix

#1693 ci: draft releases when merging to master
  .github/workflows/release.yml
  .github/workflows/test.yml
  .gitignore
  .travis.yml
  build/entitlements.mac.plist
  package.json
  scripts/notarize.js
  scripts/version-artifacts.sh
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review

#1698 chore: remove splashscreen.js
  src/main/splashscreen.js
Labels: Complexity: Low, Type: Task

#1700 ci: more reliable check to identify a fork
  scripts/notarize.js
Labels: Complexity: Low

#1701 ci: add flag to intentionally skip notarisation
  .github/workflows/test.yml
  scripts/notarize.js
Labels: Complexity: Low

#1704 fix: retrieve fullscreen state after splashscreen
  src/main/index.js
Labels: Complexity: Low, Type: Bugfix

#1708 fix: reset ready state when changing chart period
  src/renderer/components/MarketChart/MarketChart.vue
Labels: Complexity: Low, Type: Bugfix

#1612 refactor: set currentPage / currentPerPage only if different from current value
  __tests__/unit/components/Wallet/WalletTransactions/WalletTransactions.spec.js
  src/renderer/components/Wallet/WalletTransactions/WalletTransactions.js
Labels: Complexity: Low, Status: Member Approved, Type: Refactor

#1641 refactor: scroll on menu tab, not on container
  src/renderer/components/Menu/MenuTab/MenuTab.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
Labels: Complexity: Low, Status: Member Approved, Type: Refactor

#1642 fix: sidebar widths and icon orientation
  src/renderer/assets/svg/collapse.svg
  src/renderer/assets/svg/expand.svg
  src/renderer/components/Wallet/WalletSidebar/WalletSidebar.vue
  src/renderer/components/Wallet/WalletSidebar/WalletSidebarFilters.vue
  src/renderer/pages/Wallet/WalletShow.vue
  tailwind.js
Labels: Bounty: Tier 4, Complexity: Medium, Status: Member Approved, Type: Bugfix

#1643 fix: close button animation of announcements
  src/renderer/components/Announcements/AnnouncementsPost.vue
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved, Type: Bugfix

#1654 feat: close confirmation modal
  __tests__/unit/components/Modal/ModalCloseConfirmation.spec.js
  __tests__/unit/components/Modal/ModalWindow.spec.js
  src/renderer/components/Input/InputAddress.vue
  src/renderer/components/Modal/ModalCloseConfirmation.vue
  src/renderer/components/Modal/ModalWindow.vue
  src/renderer/components/Modal/index.js
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/es-ES.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/i18n/locales/pt-BR.js
Labels: Complexity: High, Status: Needs Review, Type: Feature

#1666 fix: erase bug on input fee
  __tests__/unit/components/Input/InputFee.spec.js
  src/renderer/components/Input/InputCurrency.vue
  src/renderer/components/Input/InputFee.vue
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#1707 refactor: cache-bust plugin whitelist & blacklist
  __tests__/unit/services/plugin-manager.spec.js
  src/renderer/services/plugin-manager.js
Labels: Complexity: Low, Type: Refactor

#1583 test: plugin manager unit tests
  __tests__/unit/__fixtures__/store/profile.js
  __tests__/unit/components/PluginManager/PluginManagerButtons/PluginManagerButtonSwitch.spec.js
  __tests__/unit/components/PluginManager/PluginManagerModals/PluginInstallModal.spec.js
  __tests__/unit/components/PluginManager/PluginManagerTable.spec.js
  __tests__/unit/services/release.spec.js
  __tests__/unit/store/modules/plugin.spec.js
  src/renderer/components/PluginManager/PluginManagerButtons/PluginManagerButtonSwitch.vue
  src/renderer/components/PluginManager/PluginManagerModals/PluginDetailsModal.vue
  src/renderer/store/modules/plugin.js
Labels: Complexity: Medium, Status: Member Approved, Status: Needs Review, Test: Unit

#1706 feat: store plugin manager menu open status
  __tests__/unit/pages/PluginManager/PluginManager.spec.js
  src/renderer/models/profile.js
  src/renderer/pages/PluginManager.vue
  src/renderer/store/modules/session.js
Labels: Complexity: Low, Type: Feature

#1711 fix: use showSaveDialog with promise instead of callback
  src/renderer/mixins/electron.js
Labels: Complexity: Low, Type: Bugfix

#1692 fix: custom peer host validation
  src/renderer/components/Modal/ModalPeer.vue
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/es-ES.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/i18n/locales/pt-BR.js
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#1683 perf: perform various operations in bulk
  __tests__/unit/services/client.spec.js
  __tests__/unit/store/modules/announcements.spec.js
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
  src/renderer/pages/Announcements.vue
  src/renderer/services/client.js
  src/renderer/store/modules/announcements.js
  src/renderer/store/modules/delegate.js
  src/renderer/store/modules/transaction.js
Labels: Complexity: Medium, Type: Refactor

#1714 fix: set the menu tab item to stretch
  src/renderer/components/Menu/MenuTab/MenuTab.vue
Labels: Complexity: Low, Type: Bugfix

#1715 fix: use showOpenDialog with promise instead of callback
  src/renderer/mixins/electron.js
Labels: Bounty: Tier 4, Complexity: Low, Type: Bugfix

#1495 feat: class-based languages for localization
  __tests__/unit/__utils__/i18n.js
  config/index.js
  package.json
  src/renderer/assets/images/flags/README.md
  src/renderer/assets/images/flags/bg-BG.svg
  src/renderer/assets/images/flags/cs-CZ.svg
  src/renderer/assets/images/flags/da-DK.svg
  src/renderer/assets/images/flags/de-DE.svg
  src/renderer/assets/images/flags/el-GR.svg
  src/renderer/assets/images/flags/es-ES.svg
  src/renderer/assets/images/flags/fr-FR.svg
  src/renderer/assets/images/flags/it-IT.svg
  src/renderer/assets/images/flags/ja-JP.svg
  src/renderer/assets/images/flags/ko-KR.svg
  src/renderer/assets/images/flags/nb-NO.svg
  src/renderer/assets/images/flags/nl-NL.svg
  src/renderer/assets/images/flags/pl-PL.svg
  src/renderer/assets/images/flags/pt-BR.svg
  src/renderer/assets/images/flags/ro-RO.svg
  src/renderer/assets/images/flags/ru-RU.svg
  src/renderer/assets/images/flags/se-SE.svg
  src/renderer/assets/images/flags/sk-SK.svg
  src/renderer/assets/images/flags/tr-TR.svg
  src/renderer/assets/images/flags/uk-UA.svg
  src/renderer/assets/images/flags/vi-VN.svg
  src/renderer/assets/images/flags/zh-CN.svg
  src/renderer/components/utils/Identicon.vue
  src/renderer/i18n/index.js
  src/renderer/i18n/languages/en-US.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/i18n/locales/es-ES.js
  src/renderer/i18n/locales/it-IT.js
  src/renderer/i18n/locales/pt-BR.js
  src/renderer/i18n/number-formats.js
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#1716 fix: dashboard show transaction
  src/renderer/components/Transaction/TransactionShow/TransactionShow.vue
Labels: Complexity: Low, Type: Bugfix

#1717 test: amount tooltip on transaction show modal
  __tests__/unit/components/Transaction/TransactionShow.spec.js
Labels: Complexity: Medium, Test: Unit

#1718 fix: transaction submit when invalid password
  src/renderer/components/Transaction/TransactionForm/mixin.js
  src/renderer/i18n/locales/en-US.js
Labels: Complexity: Low, Type: Bugfix

#1638 refactor: simplify blurred modal backdrop & ui tweaks
  src/renderer/App.vue
  src/renderer/components/App/AppSidemenu/AppSidemenu.vue
  src/renderer/components/Button/ButtonDropdown.vue
  src/renderer/components/Modal/ModalCloseConfirmation.vue
  src/renderer/components/Modal/ModalWindow.vue
  src/renderer/components/Wallet/WalletDetails/WalletDetails.vue
  src/renderer/components/Wallet/WalletHeading/WalletHeading.vue
  src/renderer/pages/Wallet/WalletShow.vue
  src/renderer/styles/_general.css
Labels: Bounty: Tier 4, Complexity: Medium, Status: Member Approved, Type: Refactor

#1719 fix: warning when navigating to current route again
  src/renderer/router/index.js
Labels: Complexity: Low, Type: Bugfix

#1721 deps: downgrade jest to 24.9.0
  package.json
  yarn.lock
Labels: Bounty: Tier 6, Complexity: Undetermined

#1727 style: remove eslint warn messages
  src/renderer/components/Transaction/TransactionMultiSignatureList.vue
  src/renderer/store/modules/session.js
Labels: Complexity: Low, Type: Bugfix

#1723 fix: 422 when sorting by sender or recipient
  src/renderer/components/Transaction/TransactionTable/TransactionTable.vue
  src/renderer/components/Transaction/TransactionTable/TransactionTableMultiSignature.vue
Labels: Complexity: Low, Type: Bugfix

#1722 fix: ledger error when checking version
  __tests__/unit/store/modules/ledger.spec.js
  src/renderer/store/modules/ledger.js
Labels: Complexity: Low, Type: Bugfix

#1633 fix: avatar error on new profile during onboarding
  __tests__/unit.jest.conf.js
  __tests__/unit/App.spec.js
  package.json
  src/renderer/App.vue
  yarn.lock
Labels: Complexity: Low, Status: Needs Changes, Status: Needs Testcase, Type: Bugfix

#1724 refactor: remove amount column from ipfs table and realign columns
  src/renderer/components/Transaction/TransactionTable/TransactionTable.vue
Labels: Bounty: Tier 4, Complexity: Low, Type: Refactor

#1696 refactor: update splashscreen bg colour
  src/main/index.js
  src/renderer/SplashScreen.vue
  src/renderer/styles/_general.css
  tailwind.js
Labels: Complexity: Low, Type: Refactor

#1732 chore: square splashscreen logo
  src/renderer/SplashScreen.vue
Labels: Bounty: Tier 5, Complexity: Low, Status: Member Approved, Type: Task

#1725 fix: notifications for magistrate transactions
  src/renderer/i18n/locales/en-US.js
  src/renderer/services/synchronizer/wallets.js
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1734 fix: show splash screen on reload
  src/main/index.js
  src/main/menu.js
Labels: Complexity: Low, Type: Bugfix

#1730 refactor: adjust bridgechain transaction form validation
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainRegistration.spec.js
  __tests__/unit/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainUpdate.spec.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.spec.js
  src/renderer/components/Input/InputEditableList.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainRegistration.vue
  src/renderer/components/Transaction/TransactionConfirm/TransactionConfirmBridgechain/TransactionConfirmBridgechainUpdate.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormBridgechain/mixin.vue
  src/renderer/components/Transaction/TransactionPeerList.vue
  src/renderer/i18n/locales/en-US.js
Labels: Bounty: Tier 3, Complexity: Medium, Status: Member Approved, Type: Refactor
