Repository ArkEcosystem/desktop-wallet, pull requests merged in 2020-01, with the labels that each got.

#1589 feat: add advanced mode option to profile settings
  __tests__/unit/components/PluginManager/PluginManagerButtons/PluginManagerButtonInstallSource.spec.js
  __tests__/unit/store/modules/session.spec.js
  src/renderer/components/PluginManager/PluginManagerButtons/PluginManagerButtonInstallSource.vue
  src/renderer/components/Profile/ProfileAdvancedModeConfirmation.vue
  src/renderer/components/Profile/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/profile.js
  src/renderer/pages/PluginManager.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/store/modules/session.js
Labels: Complexity: Low, Type: Feature

#1585 fix: re-render chart if currency changed while being inactive
  src/renderer/components/MarketChart/MarketChart.vue
Labels: Complexity: Low, Status: Member Approved, Type: Bugfix

#1597 fix: refactor blur filter to handle portal registration
  src/renderer/App.vue
  src/renderer/components/Modal/ModalWindow.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix

#1598 feat: plugins whitelist
  config/index.js
  src/renderer/App.vue
  src/renderer/services/plugin-manager.js
  src/renderer/store/modules/plugin.js
Labels: Complexity: Low, Type: Feature

#1600 release: 2.7.0
  __tests__/unit/components/PluginManager/PluginManagerButtons/PluginManagerButtonInstallSource.spec.js
  __tests__/unit/store/modules/session.spec.js
  config/index.js
  package.json
  src/renderer/App.vue
  src/renderer/components/MarketChart/MarketChart.vue
  src/renderer/components/Modal/ModalWindow.vue
  src/renderer/components/PluginManager/PluginManagerButtons/PluginManagerButtonInstallSource.vue
  src/renderer/components/Profile/ProfileAdvancedModeConfirmation.vue
  src/renderer/components/Profile/index.js
  src/renderer/i18n/locales/en-US.js
  src/renderer/models/profile.js
  src/renderer/pages/PluginManager.vue
  src/renderer/pages/Profile/ProfileEdition.vue
  src/renderer/services/plugin-manager.js
  src/renderer/store/modules/plugin.js
  src/renderer/store/modules/session.js
  yarn.lock
Labels: Complexity: High, Type: Release

#1601 fix: delete plugin when no data stored
  __tests__/unit/components/PluginManager/PluginManagerModals/PluginRemovalModal.spec.js
  src/renderer/components/PluginManager/PluginManagerModals/PluginRemovalModal.vue
  src/renderer/store/modules/plugin.js
Labels: Complexity: Low, Type: Bugfix

#1623 fix: memory leak for tests
  package.json
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#1625 fix: limit delegate query to 100 & dynamic per page options
  __tests__/unit/components/Wallet/WalletDelegates.spec.js
  src/renderer/components/Wallet/WalletDelegates/WalletDelegates.vue
Labels: Bounty: Tier 4, Complexity: Low, Status: Member Approved, Type: Bugfix
