Repository ArkEcosystem/desktop-wallet, pull requests merged in 2020-08, with the labels that each got.

#2574 chore: move currency icons to own module
  src/app/assets/svg/currencies/index.ts
  src/app/assets/svg/index.ts
Labels: Complexity: Low, Type: Task

#2576 refactor: adjust vertical alignment and wallet table fix on dashboard
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/data.ts
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2573 refactor: pass active profile to pages
  src/app/components/Layout/components/Page/Page.tsx
  src/app/components/NavigationBar/NavigationBar.stories.tsx
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/Exchange.tsx
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/Article.tsx
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/Faq.tsx
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/Main.tsx
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/PluginDetails.tsx
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.tsx
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/LinkCollection.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/MnemonicVerification/MnemonicVerification.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Feature

#2575 refactor: adjust vertical alignment and font sizes in line chart
  src/app/components/LineChart/LineChart.tsx
  src/app/components/LineChart/__snapshots__/LineChart.test.tsx.snap
  src/app/components/PercentageBar/PercentageBar.tsx
  src/app/components/PercentageBar/__snapshots__/PercentageBar.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: High, Type: Refactor

#2577 refactor: limit max height of SelectDropdown
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/SelectDropdown/styles.ts
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2580 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2579 feat: add avatar with contact initials
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
Labels: Complexity: Low, Type: Feature

#2572 refactor: update navbar image with the uploaded avatar
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Feature

#2570 fix: create wallet issues
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/profile/e2e/create-profile-action.e2e.ts
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#2584 test: fix NEO mock e2e tests
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
Labels: Complexity: Low, Test: Unit

#2578 feat: handle contact update in contact list
  package.json
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/CreateContact/CreateContact.stories.tsx
  src/domains/contact/components/CreateContact/CreateContact.tsx
  src/domains/contact/components/DeleteContact/DeleteContact.stories.tsx
  src/domains/contact/components/DeleteContact/DeleteContact.test.tsx
  src/domains/contact/components/DeleteContact/DeleteContact.tsx
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/UpdateContact.test.tsx
  src/domains/contact/components/UpdateContact/UpdateContact.tsx
  src/domains/contact/components/index.ts
  src/domains/contact/e2e/common.ts
  src/domains/contact/e2e/contacts-routing.e2e.ts
  src/domains/contact/e2e/create-contact.e2e.ts
  src/domains/contact/e2e/update-contact.e2e.ts
  src/domains/contact/pages/Contacts/Contacts.test.tsx
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#2588 chore: add i18n to the crumb label
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/help/i18n.ts
  src/domains/help/pages/Article/Article.tsx
  src/domains/help/pages/Faq/Faq.tsx
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/Main.tsx
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/News.tsx
  src/domains/plugin/i18n.ts
  src/domains/plugin/pages/PluginDetails/PluginDetails.tsx
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
Labels: Complexity: Medium, Type: Task

#2587 chore: add `noShadow` to the network icon in the `SelectNetworkInput`
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/network/components/SelectNetwork/SelectNetworkInput.tsx
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#2586 refactor: add sub form wrapper component
  src/app/components/Form/SubForm.test.tsx
  src/app/components/Form/SubForm.tsx
  src/app/components/Form/__snapshots__/SubForm.test.tsx.snap
  src/app/components/Form/index.tsx
  src/domains/contact/components/ContactForm/ContactForm.tsx
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/transaction/components/AddRecipient/AddRecipient.styles.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: High, Type: Feature

#2571 feat: list transactions on dashboard
  .eslintrc.js
  package.json
  src/app/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
  src/app/components/Notifications/Notifications.stories.tsx
  src/app/components/Notifications/Notifications.test.tsx
  src/app/components/Notifications/Notifications.tsx
  src/app/components/Notifications/models.ts
  src/app/components/PercentageBar/PercentageBar.tsx
  src/app/components/PercentageBar/__snapshots__/PercentageBar.test.tsx.snap
  src/app/components/RadioButton/__snapshots__/RadioButton.test.tsx.snap
  src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.tsx
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/data.ts
  src/domains/dashboard/pages/Dashboard/Dashboard.stories.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionCompactRow.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionCompactRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowConfirmation.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowConfirmation.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowInfo.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowInfo.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/components/WalletVote/WalletVote.test.tsx
  src/domains/wallet/components/WalletVote/WalletVote.tsx
  src/domains/wallet/data.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/index.tsx
  src/tests/fixtures/transactions/index.ts
  src/utils/storybook.tsx
  yarn.lock
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#2589 ci: pass repository token to codecov action
  .github/workflows/test.yml
Labels: Complexity: Low

#2590 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High

#2592 test: add contact deletion tests
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/components/SearchContact/__snapshots__/SearchContact.test.tsx.snap
  src/domains/contact/e2e/delete-contact.e2e.ts
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
Labels: Complexity: Medium, Test: Unit

#2591 feat: add application error display
  src/app/App.tsx
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/images/index.ts
  src/app/i18n/helpers/index.ts
  src/domains/error/i18n.ts
  src/domains/error/images/cannot-connect-banner.svg
  src/domains/error/images/error-banner.svg
  src/domains/error/images/index.ts
  src/domains/error/pages/ApplicationError/ApplicationError.stories.tsx
  src/domains/error/pages/ApplicationError/ApplicationError.test.tsx
  src/domains/error/pages/ApplicationError/ApplicationError.tsx
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/ApplicationError/index.ts
  src/domains/error/pages/Offline/Offline.stories.tsx
  src/domains/error/pages/Offline/Offline.test.tsx
  src/domains/error/pages/Offline/Offline.tsx
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/error/pages/Offline/index.ts
  src/domains/error/pages/index.ts
  src/domains/offline/i18n.ts
Labels: Complexity: Medium, Type: Feature

#2594 chore: update Platform SDK dependencies
  package.json
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  yarn.lock
Labels: Complexity: High

#2595 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High

#2585 feat: implement route middleware
  src/app/App.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/hooks/env.test.tsx
  src/app/hooks/env.ts
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/help/pages/Article/Article.tsx
  src/domains/help/pages/Faq/Faq.tsx
  src/domains/help/pages/Main/Main.tsx
  src/domains/news/pages/News/News.tsx
  src/domains/plugin/pages/PluginDetails/PluginDetails.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.tsx
  src/domains/profile/middleware.test.ts
  src/domains/profile/middleware.ts
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.test.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
  src/domains/vote/pages/Votes/Votes.stories.tsx
  src/domains/vote/pages/Votes/Votes.test.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/middleware.test.ts
  src/domains/wallet/middleware.ts
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/router/RouterView.test.tsx
  src/router/RouterView.tsx
  src/router/index.tsx
  src/router/interfaces.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#2596 refactor: implementation changes on `ContactForm`
  src/domains/contact/components/ContactForm/ContactForm.test.tsx
  src/domains/contact/components/ContactForm/ContactForm.tsx
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/contact/i18n.ts
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2583 fix: add validation and default value on `UpdateWalletName`
  src/domains/wallet/components/UpdateWalletName/UpdateWalletName.test.tsx
  src/domains/wallet/components/UpdateWalletName/UpdateWalletName.tsx
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/e2e/update-wallet-name-action.e2e.ts
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
Labels: Complexity: Low, Type: Bugfix

#2602 chore: remove error message when select an item of dropdown
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2599 refactor: show form in `SignMessage` when closing modal
  src/domains/wallet/components/SignMessage/SignMessage.tsx
  src/domains/wallet/components/VerifyMessageStatus/VerifyMessageStatus.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
Labels: Complexity: Low, Type: Refactor

#2593 feat: implement auto logoff
  package.json
  src/app/App.tsx
  src/app/i18n/common/i18n.ts
  src/domains/profile/middleware.test.ts
  src/domains/profile/middleware.ts
  src/domains/setting/e2e/settings-routing.e2e.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/router/RouterView.tsx
  src/router/interfaces.ts
  src/utils/electron-utils.test.ts
  src/utils/electron-utils.ts
Labels: Complexity: Low, Type: Feature

#2597 refactor: add `CreateContact` validations and tests
  src/domains/contact/components/CreateContact/CreateContact.stories.tsx
  src/domains/contact/components/CreateContact/CreateContact.test.tsx
  src/domains/contact/components/CreateContact/CreateContact.tsx
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/e2e/create-contact.e2e.ts
  src/domains/contact/i18n.ts
Labels: Complexity: High, Type: Refactor

#2600 chore: disable devtools in e2e
  package.json
  public/electron.js
  src/electron/index.js
Labels: Complexity: Low, Type: Task

#2598 refactor: load transactions from wallet in details page
  package.json
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2603 chore: update Platform SDK dependencies
  package.json
  src/app/components/Notifications/Notifications.stories.tsx
  src/app/components/Notifications/Notifications.test.tsx
  src/domains/dashboard/data.ts
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx
  src/domains/wallet/data.ts
  src/tests/fixtures/transactions/index.ts
  yarn.lock
Labels: Complexity: High

#2604 fix: respect query parameters for POST requests
  package.json
  src/app/services/HttpClient.ts
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  yarn.lock
Labels: Complexity: High

#2605 refactor: format amount in `TransactionRow` with `BigNumber#toHuman`
  src/app/components/Notifications/Notifications.stories.tsx
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/domains/dashboard/data.ts
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/data.ts
  src/tests/fixtures/transactions/index.ts
Labels: Complexity: Low

#2607 refactor: pass `BigNumber` to `TotalAmountBox`
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.stories.tsx
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.test.tsx
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx
  src/domains/transaction/components/TotalAmountBox/__snapshots__/TotalAmountBox.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2608 fix: show balances as human-readable strings
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Low

#2606 refactor: add `UpdateContact` validations and tests
  src/domains/contact/components/UpdateContact/UpdateContact.test.tsx
  src/domains/contact/components/UpdateContact/UpdateContact.tsx
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/contact/e2e/update-contact.e2e.ts
Labels: Complexity: Medium, Type: Refactor

#2609 fix: wallet labeling issues
  src/domains/wallet/components/UpdateWalletName/UpdateWalletName.tsx
  src/domains/wallet/e2e/update-wallet-name-action.e2e.ts
Labels: Complexity: Low, Type: Bugfix

#2611 feat: add `Amount` component
  src/app/components/Amount/Amount.stories.tsx
  src/app/components/Amount/Amount.test.tsx
  src/app/components/Amount/Amount.tsx
  src/app/components/Amount/index.ts
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/ProfileCard/ProfileCard.stories.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.test.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.stories.tsx
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.test.tsx
  src/domains/transaction/components/TotalAmountBox/TotalAmountBox.tsx
  src/domains/transaction/components/TotalAmountBox/__snapshots__/TotalAmountBox.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/components/WalletHeader/WalletHeader.stories.tsx
  src/domains/wallet/components/WalletHeader/WalletHeader.test.tsx
  src/domains/wallet/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2615 chore: update Platform SDK dependencies
  package.json
  src/app/components/Notifications/Notifications.stories.tsx
  src/app/components/Notifications/Notifications.test.tsx
  src/domains/dashboard/data.ts
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx
  src/domains/wallet/data.ts
  src/tests/fixtures/transactions/index.ts
  yarn.lock
Labels: Complexity: High

#2617 feat: implement `Splash` screen
  src/app/App.test.tsx
  src/app/App.tsx
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/images/index.ts
  src/app/components/CircularProgressBar/CircularProgressBar.test.tsx
  src/app/components/CircularProgressBar/CircularProgressBar.tsx
  src/app/components/CircularProgressBar/__snapshots__/CircularProgressBar.test.tsx.snap
  src/app/i18n/helpers/index.ts
  src/domains/splash/e2e/splash-screen.e2e.ts
  src/domains/splash/i18n.ts
  src/domains/splash/images/index.ts
  src/domains/splash/images/splash-banner.svg
  src/domains/splash/pages/Splash/Splash.stories.tsx
  src/domains/splash/pages/Splash/Splash.test.tsx
  src/domains/splash/pages/Splash/Splash.tsx
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/splash/pages/Splash/index.ts
  src/domains/splash/pages/index.ts
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2612 fix: add maxlength & validations in profile name
  src/app/__snapshots__/App.test.tsx.snap
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/i18n.ts
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/i18n.ts
  src/domains/setting/pages/Settings/available-settings/General.tsx
Labels: Complexity: Medium, Type: Bugfix

#2613 refactor: keep track of logoff threshold in middleware
  src/app/__snapshots__/App.test.tsx.snap
  src/domains/profile/e2e/welcome-screen.e2e.ts
  src/domains/profile/middleware.test.ts
  src/domains/profile/middleware.ts
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/setting/e2e/settings-routing.e2e.ts
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/tests/fixtures/env/storage.json
Labels: Complexity: Medium, Type: Refactor

#2623 ci: always update before installing new packages
  .github/workflows/build.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/format.yml
  .github/workflows/test.yml
Labels: Complexity: Low

#2624 fix: send JSON headers to avoid malformed responses
  src/app/services/HttpClient.ts
Labels: Complexity: Low

#2625 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High

#2622 feat: paginate transactions table
  src/app/services/HttpClient.test.ts
  src/domains/dashboard/components/Transactions/Transactions.stories.tsx
  src/domains/dashboard/components/Transactions/Transactions.test.tsx
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/tests/fixtures/coins/ark/transactions.json
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2621 feat: add animated loader
  src/app/assets/svg/index.ts
  src/app/assets/svg/loader-logo.svg
  src/app/components/CircularProgressBar/CircularProgressBar.tsx
  src/app/components/Loader/Loader.stories.tsx
  src/app/components/Loader/Loader.styles.ts
  src/app/components/Loader/Loader.test.tsx
  src/app/components/Loader/Loader.tsx
  src/app/components/Loader/__snapshots__/Loader.test.tsx.snap
  src/app/components/Loader/index.ts
Labels: Complexity: High, Type: Feature

#2619 fix: always add wallet icons cell in wallets table row
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/tailwind.config.js
  src/utils/storybook.tsx
Labels: Complexity: High, Type: Bugfix

#2626 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High

#2628 chore: update Platform SDK dependencies
  package.json
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.tsx
  yarn.lock
Labels: Complexity: High, Type: Task

#2627 fix: align pending transactions
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionTable.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2630 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2629 chore: fix registrations icons
  src/domains/wallet/components/WalletRegistrations/WalletRegistrations.tsx
  src/domains/wallet/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2632 chore: add entity icon
  src/app/assets/svg/entity.svg
  src/app/assets/svg/index.ts
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.tsx
Labels: Complexity: Low, Type: Task

#2635 feat: cache HTTP requests based on their URL
  src/app/services/Cache.test.ts
  src/app/services/Cache.ts
  src/app/services/HttpClient.test.ts
  src/app/services/HttpClient.ts
  src/app/services/index.ts
Labels: Complexity: Medium

#2633 chore: update fixture data
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/tests/fixtures/coins/ark/wallets/D5sRKWckH4rE1hQ9eeMeHAepgyC3cvJtwb.json
  src/tests/fixtures/env/storage.json
Labels: Complexity: Undetermined, Type: Task

#2634 build: make all packages as external
  .github/workflows/test.yml
  .storybook/main.js
  .testcafe-electron-rc
  .testcafe-electron-rc.js
  .testcaferc.json
  config-overrides.js
  package.json
  public/electron.js
  public/menu.js
  src/app/App.tsx
  src/domains/contact/e2e/contacts-routing.e2e.ts
  src/domains/contact/e2e/create-contact.e2e.ts
  src/domains/contact/e2e/delete-contact.e2e.ts
  src/domains/contact/e2e/update-contact.e2e.ts
  src/domains/dashboard/e2e/dashboard-routing.e2e.ts
  src/domains/dashboard/e2e/navbar-routing.e2e.ts
  src/domains/plugin/e2e/plugins-routing.e2e.ts
  src/domains/profile/e2e/create-profile-action.e2e.ts
  src/domains/profile/e2e/create-profile-routing.e2e.ts
  src/domains/profile/e2e/delete-profile-action.e2e.ts
  src/domains/profile/e2e/navigate-profile-settings.e2e.ts
  src/domains/profile/e2e/welcome-screen.e2e.ts
  src/domains/setting/e2e/settings-routing.e2e.ts
  src/domains/splash/e2e/splash-screen.e2e.ts
  src/domains/transaction/e2e/transactions-routing.e2e.ts
  src/domains/wallet/e2e/create-wallet-action.e2e.ts
  src/domains/wallet/e2e/delete-wallet-action.e2e.ts
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
  src/domains/wallet/e2e/sign-message-action.e2e.ts
  src/domains/wallet/e2e/update-wallet-name-action.e2e.ts
  src/domains/wallet/e2e/verify-message-action.e2e.ts
  src/domains/wallet/e2e/wallets-routing.e2e.ts
  src/electron/index.js
  src/tailwind.config.js
  src/utils/e2e-utils.test.ts
  src/utils/e2e-utils.ts
  tsconfig.json
  yarn.lock
Labels: Complexity: High, Status: Needs Review

#2636 refactor: include method and data in cache key
  package.json
  src/app/services/HttpClient.ts
  yarn.lock
Labels: Complexity: Low

#2614 feat: add `InputAddress` component
  src/app/assets/svg/qrcode.svg
  src/app/components/Input/Input.stories.tsx
  src/app/components/Input/InputAddress.test.tsx
  src/app/components/Input/InputAddress.tsx
  src/app/components/Input/__snapshots__/InputAddress.test.tsx.snap
  src/app/components/Input/__snapshots__/InputGroup.test.tsx.snap
  src/app/components/Input/index.tsx
  src/app/i18n/common/i18n.ts
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Feature

#2638 refactor: adjust splash/welcome screens according to the designs
  src/app/App.test.tsx
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/images/index.ts
  src/app/assets/images/welcome-banner.svg
  src/domains/profile/i18n.ts
  src/domains/profile/images/index.tsx
  src/domains/profile/images/welcome-banner.svg
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.test.tsx
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/splash/images/index.ts
  src/domains/splash/pages/Splash/Splash.tsx
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2637 fix: spacing and alignment in wallet details components
  src/domains/wallet/components/WalletBottomSheetMenu/WalletBottomSheetMenu.tsx
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/components/WalletRegistrations/WalletRegistrations.test.tsx
  src/domains/wallet/components/WalletRegistrations/WalletRegistrations.tsx
  src/domains/wallet/components/WalletRegistrations/__snapshots__/WalletRegistrations.test.tsx.snap
  src/domains/wallet/components/WalletVote/WalletVote.tsx
  src/domains/wallet/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2641 chore: import all SDK packages
  package.json
  src/app/App.tsx
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/network/data.ts
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  yarn.lock
Labels: Complexity: High, Type: Task

#2642 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High

#2639 chore: rename `selectAsset` variations to `selectNetworkInput`
  src/domains/contact/components/ContactForm/ContactForm.test.tsx
  src/domains/contact/components/CreateContact/CreateContact.test.tsx
  src/domains/contact/components/UpdateContact/UpdateContact.test.tsx
  src/domains/contact/pages/Contacts/Contacts.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/vote/pages/Votes/Votes.test.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
Labels: Complexity: Medium, Type: Task

#2643 fix: dashboard tests
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
Labels: Complexity: Low, Type: Bugfix

#2646 chore: temporarily remove eth network data
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/network/data.ts
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2644 refactor: show required field icon by default
  src/app/components/Form/Form.stories.tsx
  src/app/components/Form/FormLabel.tsx
  src/app/components/Form/__snapshots__/FormLabel.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#2649 feat: implement offline splashscreen
  src/app/App.test.tsx
  src/app/App.tsx
  src/app/__snapshots__/App.test.tsx.snap
  src/app/hooks/index.ts
  src/app/hooks/network-status.test.tsx
  src/app/hooks/network-status.ts
  src/domains/splash/e2e/splash-screen.e2e.ts
Labels: Complexity: Medium, Type: Feature

#2651 fix: electron build
  .github/workflows/draft-artifacts.yml
  config-overrides.js
  package.json
  src/app/App.test.tsx
  src/app/App.tsx
  src/app/__snapshots__/App.test.tsx.snap
  src/electron/index.js
  src/electron/menu.js
  yarn.lock
Labels: Complexity: Medium, Type: Refactor

#2650 feat: add validation for duplicate address
  src/app/components/Input/InputAddress.test.tsx
  src/app/components/Input/InputAddress.tsx
  src/app/i18n/common/i18n.ts
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Low, Type: Feature

#2653 fix: transaction send functionality tests
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/app/services/HttpClient.ts
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Bugfix

#2610 feat: transfer send functionality
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Input/InputPassword.tsx
  src/app/components/Input/InputRange.stories.tsx
  src/app/components/Input/InputRange.test.tsx
  src/app/components/Input/InputRange.tsx
  src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap
  src/app/components/WalletCard/WalletCard.tsx
  src/app/services/HttpClient.ts
  src/domains/profile/components/SearchAddress/SearchAddress.stories.tsx
  src/domains/profile/components/SearchAddress/SearchAddress.test.tsx
  src/domains/profile/components/SearchAddress/SearchAddress.tsx
  src/domains/profile/components/SearchAddress/__snapshots__/SearchAddress.test.tsx.snap
  src/domains/profile/components/SelectAddress/SelectAddress.stories.tsx
  src/domains/profile/components/SelectAddress/SelectAddress.test.tsx
  src/domains/profile/components/SelectAddress/SelectAddress.tsx
  src/domains/profile/components/SelectAddress/__snapshots__/SelectAddress.test.tsx.snap
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/InputFee/InputFee.stories.tsx
  src/domains/transaction/components/InputFee/InputFee.tsx
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/RecipientList/RecipientList.models.ts
  src/domains/transaction/components/RecipientList/RecipientList.tsx
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.stories.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.styles.ts
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/Registration/Registration.stories.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.stories.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.stories.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.stories.tsx
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.stories.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.stories.tsx
  src/domains/transaction/pages/UpdateRegistration/UpdateRegistration.tsx
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/tests/fixtures/coins/ark/node-fees.json
  src/tests/fixtures/coins/ark/transaction-fees.json
  src/tests/fixtures/coins/ark/transaction.json
  src/utils/testing-library.tsx
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2652 feat: add `ContactForm` address validations
  src/app/components/Input/InputAddress.test.tsx
  src/app/components/Input/InputAddress.tsx
  src/app/components/Input/__snapshots__/InputAddress.test.tsx.snap
  src/domains/contact/components/ContactForm/ContactForm.test.tsx
  src/domains/contact/components/ContactForm/ContactForm.tsx
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/contact/e2e/create-contact.e2e.ts
  src/domains/contact/e2e/update-contact.e2e.ts
  src/domains/contact/i18n.ts
Labels: Complexity: High, Type: Feature

#2655 chore: update Platform SDK dependencies
  package.json
  src/app/components/Input/InputAddress.tsx
  src/domains/contact/components/ContactForm/ContactForm.tsx
  yarn.lock
Labels: Complexity: High, Type: Task

#2648 refactor: paginate wallet details transactions
  src/domains/wallet/e2e/wallet-details.e2e.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2661 feat: add electron util to open external links
  src/utils/electron-utils.test.ts
  src/utils/electron-utils.ts
Labels: Complexity: Low, Type: Feature

#2654 feat: add the `Completed` page after a successful import wallet
  src/app/i18n/common/i18n.ts
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Type: Feature

#2666 refactor: add the `openExternal()` electron to the `Link` component
  src/app/components/Link/Link.stories.tsx
  src/app/components/Link/Link.test.tsx
  src/app/components/Link/Link.tsx
  src/app/components/Link/__snapshots__/Link.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/components/WalletVote/WalletVote.tsx
  src/domains/wallet/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2667 refactor: update the `WalletUpdate` modal to use tab steps
  src/domains/wallet/components/WalletUpdate/WalletUpdate.stories.tsx
  src/domains/wallet/components/WalletUpdate/WalletUpdate.test.tsx
  src/domains/wallet/components/WalletUpdate/WalletUpdate.tsx
  src/domains/wallet/components/WalletUpdate/__snapshots__/WalletUpdate.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2656 chore: upgrade storybook
  .env
  .gitignore
  package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2665 refactor: remove the required field icon for optional fields
  src/app/components/Form/FormLabel.tsx
  src/app/components/Form/__snapshots__/FormLabel.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2669 chore: fix `Dropdown` scrollbar
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/SelectDropdown/styles.ts
  src/domains/help/components/ContactUs/__snapshots__/ContactUs.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/LinkCollection/__snapshots__/LinkCollection.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#2659 fix: windows builds
  config-overrides.js
  package.json
  src/polyfill/memcpy.js
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Bugfix

#2668 feat: load wallet from route for transaction send
  src/domains/dashboard/e2e/navbar-routing.e2e.ts
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/routing.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/utils/storybook.tsx
Labels: Complexity: High, Type: Feature

#2658 feat: implement skeleton in transaction tables
  config-overrides.js
  package.json
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Table/Table.tsx
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/HistoryModal/__snapshots__/HistoryModal.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowSkeleton.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  yarn.lock
Labels: Complexity: Undetermined, Type: Feature

#2670 fix: select recipient field input
  src/domains/profile/components/SelectRecipient/SelectRecipient.test.tsx
  src/domains/profile/components/SelectRecipient/SelectRecipient.tsx
Labels: Complexity: Low, Type: Bugfix

#2672 fix: add maxlength & validations in wallet name
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
Labels: Type: Bugfix

#2671 fix: set selected network on the pages create wallet and import wallet
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
Labels: Complexity: Low, Type: Bugfix

#2677 refactor: generalise send transaction form component
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2680 feat: ipfs transaction
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/news/components/AddAssets/AddAssets.tsx
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/setting/components/CustomPeers/CustomPeers.tsx
  src/domains/setting/components/CustomPeers/__snapshots__/CustomPeers.test.tsx.snap
  src/domains/setting/components/PeerList/__snapshots__/PeerList.test.tsx.snap
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.stories.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.test.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.stories.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/routing.ts
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/WalletHeader/WalletHeader.stories.tsx
  src/domains/wallet/components/WalletHeader/WalletHeader.test.tsx
  src/domains/wallet/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/tests/fixtures/coins/ark/transactions.json
  src/tests/fixtures/coins/ark/transactions/ipfs.json
  src/tests/fixtures/coins/ark/transactions/transfer.json
  src/utils/storybook.tsx
Labels: Complexity: Undetermined, Type: Feature

#2681 feat: implement multi payment transaction
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: Low, Type: Feature

#2682 refactor: fill out ipfs detail modal
  src/domains/transaction/components/IpfsDetail/IpfsDetail.test.tsx
  src/domains/transaction/components/IpfsDetail/IpfsDetail.tsx
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransferDetail/TransferDetail.test.tsx
  src/domains/transaction/components/TransferDetail/TransferDetail.tsx
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2683 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#2684 fix: avoid using raw transaction data
  src/app/components/Notifications/Notifications.stories.tsx
  src/app/components/Notifications/Notifications.test.tsx
  src/domains/dashboard/data.ts
  src/domains/transaction/components/IpfsDetail/IpfsDetail.test.tsx
  src/domains/transaction/components/IpfsDetail/IpfsDetail.tsx
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx
  src/domains/transaction/components/TransferDetail/TransferDetail.tsx
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/wallet/data.ts
  src/tests/fixtures/transactions/index.ts
Labels: Complexity: Low

#2685 chore: add AIP36 transaction support through SDK
  package.json
  src/app/components/Notifications/Notifications.stories.tsx
  src/app/components/Notifications/Notifications.test.tsx
  src/domains/dashboard/data.ts
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientLabel.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx
  src/domains/wallet/data.ts
  src/tests/fixtures/transactions/index.ts
  yarn.lock
Labels: Complexity: High

#2688 refactor: use `SignedTransactionData` for transaction sent screen information
  package.json
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  yarn.lock
Labels: Complexity: High

#2679 feat: implement blockfolio signals
  config-overrides.js
  package.json
  src/app/components/FilterNetwork/FilterNetwork.tsx
  src/app/components/Link/Link.tsx
  src/domains/dashboard/e2e/navbar-routing.e2e.ts
  src/domains/network/data.ts
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/news/components/NewsCard/NewsCard.stories.tsx
  src/domains/news/components/NewsCard/NewsCard.test.tsx
  src/domains/news/components/NewsCard/NewsCard.tsx
  src/domains/news/components/NewsCard/NewsCardSkeleton.tsx
  src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap
  src/domains/news/components/NewsCard/index.tsx
  src/domains/news/components/NewsOptions/NewsOptions.stories.tsx
  src/domains/news/components/NewsOptions/NewsOptions.test.tsx
  src/domains/news/components/NewsOptions/NewsOptions.tsx
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/news/data.ts
  src/domains/news/e2e/common.ts
  src/domains/news/e2e/filtering.e2e.ts
  src/domains/news/e2e/news-routing.e2e.ts
  src/domains/news/i18n.ts
  src/domains/news/images/index.ts
  src/domains/news/images/no-results.svg
  src/domains/news/pages/News/News.stories.tsx
  src/domains/news/pages/News/News.test.tsx
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/tests/fixtures/news/empty-response.json
  src/tests/fixtures/news/filtered.json
  src/tests/fixtures/news/page-1.json
  src/tests/fixtures/news/page-2.json
  yarn.lock
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2689 refactor: copy transaction ID instead of whole transaction
  src/app/i18n/common/i18n.ts
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: Low

#2690 fix: remove usage of `dist` imports
  package.json
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.test.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  yarn.lock
Labels: Complexity: High

#2691 fix: use `SignedTransactionData` for IPFS sent page
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.test.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
Labels: Complexity: Low

#2686 test: add mock test to multi-payment transactions
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/tests/fixtures/coins/ark/transactions.json
  src/tests/fixtures/coins/ark/transactions/transfer-multiple.json
Labels: Complexity: Medium, Test: Unit

#2693 fix: hide view more button for wallets below a count of 10
  src/domains/dashboard/components/Wallets/Wallets.test.tsx
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
Labels: Complexity: Low

#2692 fix: make `WalletListItem` clickable to navigate to wallet details
  src/app/components/WalletCard/WalletCard.test.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/app/components/WalletListItem/WalletListItem.test.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/wallet/components/SearchWallet/SearchWallet.test.tsx
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/WalletBottomSheetMenu.test.tsx
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Low

#2696 fix: extra padding for smartbridge field to avoid max hint overlap
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: Low

#2697 fix: validate IPFS hash before the user can submit the transaction
  src/app/components/WalletCard/WalletCard.test.tsx
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.test.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
Labels: Complexity: Medium

#2698 refactor: detail modal vote
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/transaction/components/IpfsDetail/IpfsDetail.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.stories.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/VoteDetail/VoteDetail.test.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.tsx
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
Labels: Complexity: Undetermined, Status: Needs Review, Type: Refactor

#2703 ci: remove CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: Complexity: Low

#2701 refactor: change avatar button color on hover
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
Labels: Complexity: Medium, Type: Refactor

#2702 chore: remove background color from InputAddonEnd
  src/app/components/Input/InputAddress.tsx
  src/app/components/Input/InputPassword.tsx
  src/app/components/Input/__snapshots__/InputAddress.test.tsx.snap
  src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#2704 chore: fix login/sign in terminology
  package.json
  src/app/__snapshots__/App.test.tsx.snap
  src/domains/profile/components/SignIn/__snapshots__/SignIn.test.tsx.snap
  src/domains/profile/i18n.ts
  src/domains/profile/middleware.ts
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/i18n.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/tests/fixtures/env/storage.json
  src/utils/storybook.tsx
  yarn.lock
Labels: Complexity: High, Type: Task

#2705 chore: increase sign in timeout to 60 seconds
  src/domains/profile/components/SignIn/SignIn.test.tsx
  src/domains/profile/components/SignIn/SignIn.tsx
Labels: Complexity: Low, Type: Task

#2712 chore: remove screenshot protection from profile fixtures
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/tests/fixtures/env/storage.json
Labels: Complexity: Low, Type: Task

#2714 test: await input change in sign in test
  src/domains/profile/components/SignIn/SignIn.test.tsx
Labels: Complexity: Low

#2715 chore: update Platform SDK dependencies
  jest.setup.js
  package.json
  src/app/App.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.test.tsx
  yarn.lock
Labels: Complexity: High, Type: Task

#2713 fix: adjust transaction row link props
  src/app/components/Link/Link.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2716 refactor: update transaction amount to show currency
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowAmount.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.stories.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionTable.tsx
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2718 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High

#2722 refactor: adjust navbar styles
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#2721 fix: dynamic Circle shadow color
  src/app/components/Circle/Circle.styles.ts
  src/app/components/Circle/Circle.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowMode.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowRecipientIcon.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/__snapshots__/TransactionRowRecipientIcon.test.tsx.snap
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2695 feat: registration process & delegate registration form
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Input/InputRange.tsx
  src/app/components/SelectDropdown/SelectDropdown.tsx
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/TransactionDetail/TransactionDetail.tsx
  src/app/components/TransactionDetail/__snapshots__/TransactionDetail.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/BusinessRegistrationForm/BusinessRegistrationForm.test.tsx
  src/domains/transaction/components/BusinessRegistrationForm/BusinessRegistrationForm.tsx
  src/domains/transaction/components/BusinessRegistrationForm/__snapshots__/BusinessRegistrationForm.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/index.ts
  src/domains/transaction/components/InputFee/InputFee.test.tsx
  src/domains/transaction/components/InputFee/InputFee.tsx
  src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/__snapshots__/IpfsDetail.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/components/TransferDetail/__snapshots__/TransferDetail.test.tsx.snap
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/transaction/e2e/delegate-registration.e2e.ts
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/Registration/Registration.models.ts
  src/domains/transaction/pages/Registration/Registration.stories.tsx
  src/domains/transaction/pages/Registration/Registration.test.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.test.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/transaction/routing.ts
  src/domains/vote/components/VoteList/__snapshots__/VoteList.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/tests/fixtures/coins/ark/transactions/delegate-registration.json
  src/utils/testing-library.tsx
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2724 refactor: move screenshotprotection to profile middleware
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/profile/components/SignIn/SignIn.test.tsx
  src/domains/profile/middleware.test.ts
  src/domains/profile/middleware.ts
  src/domains/splash/e2e/splash-screen.e2e.ts
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2717 feat: add `MyRegistrations` delegate list
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/i18n/common/i18n.ts
  src/domains/profile/data.ts
  src/domains/profile/e2e/my-registrations-routing.e2e.ts
  src/domains/profile/pages/MyRegistrations/MyRegistrations.stories.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/BlockchainTable.stories.tsx
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/BlockchainTable.test.tsx
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/BlockchainTable.tsx
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/BusinessTable.stories.tsx
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/BusinessTable.test.tsx
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/BusinessTable.tsx
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateRowItem.test.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateRowItem.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateRowItemSkeleton.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateTable.stories.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateTable.test.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateTable.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateRowItem.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/setting/e2e/settings-routing.e2e.ts
  src/domains/transaction/routing.ts
  src/tests/fixtures/delegates/D5sRKWckH4rE1hQ9eeMeHAepgyC3cvJtwb.json
Labels: Complexity: High, Status: Needs Review, Type: Feature

#2727 refactor: wallet card ui fixes
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2725 refactor: registration page adjustments
  src/app/components/TransactionDetail/TransactionDetail.test.tsx
  src/app/components/TransactionDetail/TransactionDetail.tsx
  src/app/components/TransactionDetail/__snapshots__/TransactionDetail.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2726 test: refactor wallet e2e tests
  .github/workflows/test.yml
  .testcaferc.json
  jest.setup.js
  src/domains/wallet/e2e/common.ts
  src/domains/wallet/e2e/delete-wallet-action.e2e.ts
  src/domains/wallet/e2e/sign-message-action.e2e.ts
  src/domains/wallet/e2e/update-wallet-name-action.e2e.ts
  src/domains/wallet/e2e/verify-message-action.e2e.ts
  src/domains/wallet/e2e/wallet-details.e2e.ts
  src/utils/e2e-utils.test.ts
  src/utils/e2e-utils.ts
Labels: Complexity: High, Test: Unit

#2729 fix: `VoteDetails` test errors
  src/domains/transaction/components/VoteDetail/VoteDetail.test.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.tsx
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2731 chore: set balance/fiat font weight to semibold
  src/domains/wallet/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2732 fix: adjust icon in `AddRecipient`
  .svgo.yml
  src/app/assets/svg/questionmark.svg
  src/domains/transaction/components/AddRecipient/AddRecipient.styles.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2728 chore: update Platform SDK dependencies
  package.json
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  yarn.lock
Labels: Complexity: High

#2736 refactor: scroll restoration upon route change
  src/app/App.tsx
Labels: Complexity: Low, Type: Refactor

#2735 refactor: add baseColor prop to toggle
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Toggle/Toggle.tsx
  src/app/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#2734 refactor: navigation bar and logo adjustments
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/images/ark-logo.png
  src/app/assets/images/ark-logo.svg
  src/app/assets/images/index.ts
  src/app/components/Layout/components/Page/Page.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/ApplicationError.tsx
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/Offline.tsx
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/help/pages/Article/__snapshots__/Article.test.tsx.snap
  src/domains/help/pages/Faq/__snapshots__/Faq.test.tsx.snap
  src/domains/help/pages/Main/__snapshots__/Main.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BlockchainTable/__snapshots__/BlockchainTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/BusinessTable/__snapshots__/BusinessTable.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/Splash.tsx
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/types.d.ts
Labels: Complexity: Undetermined, Type: Refactor

#2739 ci: screenshots path
  .github/workflows/test.yml
  .testcaferc.json
Labels: Complexity: Low

#2738 fix: allow setting an empty wallet name
  src/app/i18n/common/i18n.ts
  src/domains/wallet/components/UpdateWalletName/UpdateWalletName.test.tsx
  src/domains/wallet/components/UpdateWalletName/UpdateWalletName.tsx
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/e2e/update-wallet-name-action.e2e.ts
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#2742 refactor: common base component for all cards
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Card/Card.tsx
  src/app/components/Card/__snapshots__/Card.test.tsx.snap
  src/app/components/Card/__snapshots__/CardControl.test.tsx.snap
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/WalletCard/WalletCard.test.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/components/ExchangeCard/ExchangeCard.stories.tsx
  src/domains/exchange/components/ExchangeCard/ExchangeCard.test.tsx
  src/domains/exchange/components/ExchangeCard/ExchangeCard.tsx
  src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap
  src/domains/exchange/pages/Exchange/Exchange.test.tsx
  src/domains/exchange/pages/Exchange/Exchange.tsx
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/components/NewsCard/NewsCard.tsx
  src/domains/news/components/NewsCard/__snapshots__/NewsCard.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/components/PluginCard/PluginCard.test.tsx
  src/domains/plugin/components/PluginCard/PluginCard.tsx
  src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap
  src/domains/plugin/components/PluginGrid/PluginGrid.test.tsx
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/e2e/plugins-routing.e2e.ts
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.test.tsx
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/components/ProfileCard/ProfileCard.test.tsx
  src/domains/profile/components/ProfileCard/ProfileCard.tsx
  src/domains/profile/components/ProfileCard/__snapshots__/ProfileCard.test.tsx.snap
  src/domains/profile/components/SignIn/__snapshots__/SignIn.test.tsx.snap
  src/domains/profile/pages/Welcome/Welcome.test.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
Labels: Complexity: Undetermined, Status: Needs Review

#2700 feat: sync delegates in background
  .testcaferc.json
  src/app/App.test.tsx
  src/app/App.tsx
  src/app/__snapshots__/App.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.test.tsx
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/VoteDetail/VoteDetail.test.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.tsx
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.test.tsx
  src/domains/vote/e2e/votes.e2e.ts
  src/domains/wallet/e2e/wallet-details.e2e.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/tests/fixtures/transactions/index.ts
  src/utils/testing-library.tsx
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2741 refactor: details delegate registration
  src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.stories.tsx
  src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.test.tsx
  src/domains/transaction/components/DelegateRegistrationDetail/DelegateRegistrationDetail.tsx
  src/domains/transaction/components/DelegateRegistrationDetail/__snapshots__/DelegateRegistrationDetail.test.tsx.snap
  src/domains/transaction/components/IpfsDetail/IpfsDetail.test.tsx
  src/domains/transaction/components/IpfsDetail/IpfsDetail.tsx
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.test.tsx
  src/domains/transaction/components/MultiPaymentDetail/MultiPaymentDetail.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.test.tsx
  src/domains/transaction/components/TransactionDetailModal/TransactionDetailModal.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowConfirmation.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRowConfirmation.tsx
  src/domains/transaction/components/TransferDetail/TransferDetail.test.tsx
  src/domains/transaction/components/TransferDetail/TransferDetail.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.test.tsx
  src/domains/transaction/components/VoteDetail/VoteDetail.tsx
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#2745 refactor: explicitly align dropdown content and remove min width
  src/app/components/Dropdown/Dropdown.styles.ts
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#2746 chore: adjust font sizes in dropdown and card control
  src/app/components/Dropdown/Dropdown.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/WalletsControls.tsx
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
Labels: Complexity: Low, Type: Task

#2744 chore: update Platform SDK dependencies
  package.json
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/network/data.ts
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.test.tsx
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.test.tsx
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/tests/fixtures/env/storage.json
  yarn.lock
Labels: Complexity: High

#2749 style: add explicit height to SideBarItem
  src/app/components/SideBar/SideBarItem/SideBarItem.tsx
  src/app/components/SideBar/SideBarItem/__snapshots__/SideBarItem.test.tsx.snap
  src/app/components/SideBar/__snapshots__/SideBar.test.tsx.snap
  src/domains/plugin/e2e/plugins-routing.e2e.ts
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
Labels: Complexity: Medium, Type: Standards

#2750 refactor: add position type and nests dropdown content
  src/app/components/Badge/Badge.tsx
  src/app/components/Dropdown/Dropdown.styles.ts
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/types.d.ts
Labels: Complexity: Undetermined, Type: Refactor

#2751 chore: update Platform SDK dependencies
  package.json
  src/app/App.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.test.tsx
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/utils/testing-library.tsx
  yarn.lock
Labels: Complexity: High

#2747 feat: implement delegate resignation
  src/app/__snapshots__/App.test.tsx.snap
  src/domains/profile/e2e/common.ts
  src/domains/transaction/e2e/common.ts
  src/domains/transaction/e2e/delegate-resignation.e2e.ts
  src/domains/transaction/e2e/mocks.ts
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.models.ts
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.test.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/Step1.tsx
  src/domains/transaction/pages/ResignRegistration/Step2.tsx
  src/domains/transaction/pages/ResignRegistration/Step3.tsx
  src/domains/transaction/pages/ResignRegistration/Step4.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/index.ts
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#2752 feat: implement starring of wallets
  src/domains/wallet/components/WalletHeader/WalletHeader.stories.tsx
  src/domains/wallet/components/WalletHeader/WalletHeader.test.tsx
  src/domains/wallet/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
  src/domains/wallet/e2e/wallet-details.e2e.ts
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/utils/e2e-interfaces.ts
Labels: Complexity: High, Type: Feature

#2757 refactor: consume tx data in `TransactionSuccessful` step
  src/domains/transaction/components/TransactionSuccessful/TransactionSuccessful.tsx
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/Registration/Registration.tsx
  src/domains/transaction/pages/Registration/__snapshots__/Registration.test.tsx.snap
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.models.ts
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/Step1.tsx
  src/domains/transaction/pages/ResignRegistration/Step2.tsx
  src/domains/transaction/pages/ResignRegistration/Step4.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendIPFSTransaction/SendIPFSTransaction.tsx
  src/domains/transaction/pages/SendIPFSTransaction/__snapshots__/SendIPFSTransaction.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/transaction/pages/SendVoteTransaction/__snapshots__/SendVoteTransaction.test.tsx.snap
  src/domains/transaction/pages/TransactionSend/TransactionSend.tsx
  src/domains/transaction/pages/TransactionSend/__snapshots__/TransactionSend.test.tsx.snap
  src/domains/transaction/pages/UpdateRegistration/__snapshots__/UpdateRegistration.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#2756 chore: update Platform SDK dependencies
  package.json
  src/app/App.tsx
  src/domains/profile/pages/MyRegistrations/MyRegistrations.test.tsx
  src/domains/profile/pages/MyRegistrations/__snapshots__/MyRegistrations.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateRowItem.test.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateRowItem.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/DelegateTable.test.tsx
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateRowItem.test.tsx.snap
  src/domains/profile/pages/MyRegistrations/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/TransactionDetailModal/__snapshots__/TransactionDetailModal.test.tsx.snap
  src/domains/transaction/components/VoteDetail/VoteDetail.tsx
  src/domains/transaction/components/VoteDetail/__snapshots__/VoteDetail.test.tsx.snap
  src/domains/transaction/pages/Registration/Registration.test.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.models.ts
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.test.tsx
  src/domains/transaction/pages/ResignRegistration/ResignRegistration.tsx
  src/domains/transaction/pages/ResignRegistration/__snapshots__/ResignRegistration.test.tsx.snap
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.test.tsx
  src/domains/transaction/pages/SendVoteTransaction/SendVoteTransaction.tsx
  src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/tests/fixtures/coins/ark/delegates-devnet.json
  src/tests/fixtures/transactions/index.ts
  src/utils/testing-library.tsx
  yarn.lock
Labels: Complexity: High
