Repository ArkEcosystem/desktop-wallet, pull requests merged in 2021-03, with the labels that each got.

#3424 chore: update readme build command for windows
  README.md
Labels: Complexity: Low, Status: Member Approved

#3389 feat: implement plugin filtering
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/SearchBarPluginFilters.test.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/SearchBarPluginFilters.tsx
  src/app/components/SearchBar/SearchBarPluginFilters/__snapshots__/SearchBarPluginFilters.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/plugin/i18n.ts
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/plugins/context/PluginManagerProvider.test.tsx
  src/plugins/context/PluginManagerProvider.tsx
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#3420 refactor: adjust paddings, margins and styles in settings components
  src/app/components/ListDivided/ListDividedItem.tsx
  src/app/components/ListDivided/__snapshots__/ListDivided.test.tsx.snap
  src/app/components/ListDivided/__snapshots__/ListDividedItem.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/setting/pages/Settings/available-settings/Peer.tsx
  src/domains/setting/pages/Settings/available-settings/Plugins.tsx
Labels: Complexity: Medium, Type: Refactor

#3437 refactor: re-order plugin actions in cards and list
  src/domains/plugin/components/PluginCard/PluginCard.tsx
  src/domains/plugin/components/PluginGrid/PluginGrid.test.tsx
  src/domains/plugin/components/PluginList/PluginList.test.tsx
  src/domains/plugin/components/PluginListItem/PluginListItem.test.tsx
  src/domains/plugin/components/PluginListItem/PluginListItem.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.test.tsx
Labels: Complexity: Medium, Type: Refactor

#3434 refactor: wait for profile synchronization to vote
  src/domains/wallet/pages/WalletDetails/WalletDetails.test.tsx
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx
Labels: Complexity: Low, Type: Refactor

#3429 refactor: adjust columns in `AddExchange` table
  src/domains/exchange/components/AddExchange/AddExchange.tsx
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#3436 fix: logo display in plugin list
  src/domains/plugin/components/PluginImage/PluginImage.tsx
  src/domains/plugin/components/PluginImage/__snapshots__/PluginImage.test.tsx.snap
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/components/PluginListItem/PluginListItem.tsx
  src/domains/plugin/components/PluginListItem/__snapshots__/PluginListItem.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/styles/base.css
  src/tailwind.config.js
Labels: Complexity: Undetermined, Type: Bugfix

#3431 fix: adjust password settings validations
  src/app/i18n/common/i18n.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/Password.tsx
  src/domains/setting/validations/Settings.ts
Labels: Complexity: High, Type: Bugfix

#3422 refactor: remove `Update Ledger in Background` option
  src/domains/setting/e2e/save-settings.e2e.ts
  src/domains/setting/i18n.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
Labels: Complexity: Medium, Type: Refactor

#3440 refactor: split name and author and fix logo in add exchange table
  src/domains/exchange/components/AddExchange/AddExchange.test.tsx
  src/domains/exchange/components/AddExchange/AddExchange.tsx
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
  src/domains/exchange/i18n.ts
  src/domains/exchange/pages/Exchange/Exchange.test.tsx
Labels: Complexity: Medium, Type: Refactor

#3442 refactor: re-order plugin actions in header
  src/domains/plugin/components/PluginHeader/PluginHeader.test.tsx
  src/domains/plugin/components/PluginHeader/PluginHeader.tsx
  src/domains/plugin/pages/PluginDetails/PluginDetails.test.tsx
Labels: Complexity: Low, Type: Refactor

#3443 fix: sync filtered packages with search query in `PluginManager`
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
Labels: Complexity: Low, Type: Bugfix

#3433 refactor: abort ledger scanner
  src/app/contexts/Ledger/hooks/__snapshots__/scanner.test.tsx.snap
  src/app/contexts/Ledger/hooks/scanner.test.tsx
  src/app/contexts/Ledger/hooks/scanner.ts
  src/domains/wallet/pages/ImportWallet/Ledger/LedgerScanStep.tsx
Labels: Complexity: Medium, Type: Refactor

#3430 refactor: adjust paddings in `Section` component
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Header/Header.tsx
  src/app/components/Header/__snapshots__/Header.test.tsx.snap
  src/app/components/Layout/components/Section/Section.test.tsx
  src/app/components/Layout/components/Section/Section.tsx
  src/app/components/Layout/components/Section/__snapshots__/Section.test.tsx.snap
  src/app/components/Layout/index.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/PortfolioChart/__snapshots__/PortfolioChart.test.tsx.snap
  src/domains/dashboard/components/Transactions/Transactions.tsx
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/Exchange.tsx
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/PluginDetails.tsx
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/ErrorStep/__snapshots__/ErrorStep.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/TransactionSuccessful/__snapshots__/TransactionSuccessful.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerConnectionStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerScanStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#3432 fix: clear multiple recipient inputs upon addition
  src/domains/profile/components/SelectRecipient/SelectRecipient.test.tsx
  src/domains/profile/components/SelectRecipient/SelectRecipient.tsx
  src/domains/profile/components/SelectRecipient/__snapshots__/SelectRecipient.test.tsx.snap
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/validations/SendTransfer.test.tsx
Labels: Complexity: Low, Type: Bugfix

#3402 refactor: ensure connection to sign transactions with ledger
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.test.tsx
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.tsx
  src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap
  src/domains/transaction/hooks/use-transaction-builder.test.tsx
  src/domains/transaction/hooks/use-transaction-builder.ts
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/SendVote.test.tsx
  src/domains/transaction/pages/SendVote/SendVote.tsx
  src/domains/wallet/components/Ledger/LedgerWaitingApp.tsx
  src/domains/wallet/components/Ledger/LedgerWaitingDevice.tsx
  src/utils/testing-library.tsx
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#3452 chore: update dashboard snapshot
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
Labels: Complexity: Low, Type: Task

#3450 refactor: update avatar only on blur
  src/app/components/SelectProfileImage/SelectProfileImage.tsx
  src/app/components/SelectProfileImage/__snapshots__/SelectProfileImage.test.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.test.tsx
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
Labels: Complexity: Undetermined, Type: Refactor

#3439 refactor: adjust `Install Plugin from URL` to new design
  src/domains/plugin/components/PluginManualInstallModal/PluginManualInstallModal.tsx
  src/domains/plugin/components/PluginManualInstallModal/__snapshots__/PluginManualInstallModal.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#3438 refactor: update exchange ui
  src/app/i18n/common/i18n.ts
  src/domains/dashboard/e2e/navbar-routing.e2e.ts
  src/domains/exchange/components/ExchangeCard/ExchangeCard.test.tsx
  src/domains/exchange/components/ExchangeCard/ExchangeCard.tsx
  src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap
  src/domains/exchange/components/ExchangeGrid/ExchangeGrid.test.tsx
  src/domains/exchange/components/ExchangeGrid/ExchangeGrid.tsx
  src/domains/exchange/components/ExchangeGrid/__snapshots__/ExchangeGrid.test.tsx.snap
  src/domains/exchange/components/ExchangeGrid/index.ts
  src/domains/exchange/components/ExchangeImage/ExchangeImage.test.tsx
  src/domains/exchange/components/ExchangeImage/ExchangeImage.tsx
  src/domains/exchange/components/ExchangeImage/__snapshots__/ExchangeImage.test.tsx.snap
  src/domains/exchange/components/ExchangeImage/index.ts
  src/domains/exchange/i18n.ts
  src/domains/exchange/pages/Exchange/Exchange.test.tsx
  src/domains/exchange/pages/Exchange/Exchange.tsx
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/exchange/routing.test.tsx
  src/domains/exchange/routing.ts
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#3403 refactor: move transaction history toggle to settings page
  src/app/components/FilterNetwork/FilterNetwork.tsx
  src/app/components/FilterNetwork/__snapshots__/FilterNetwork.test.tsx.snap
  src/app/contexts/Configuration/Configuration.test.tsx
  src/app/contexts/Configuration/__snapshots__/Configuration.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/dashboard/components/FilterWallets/FilterWallets.test.tsx
  src/domains/dashboard/components/FilterWallets/FilterWallets.tsx
  src/domains/dashboard/components/FilterWallets/__snapshots__/FilterWallets.test.tsx.snap
  src/domains/dashboard/components/FilterWallets/hooks.test.tsx
  src/domains/dashboard/components/FilterWallets/hooks.ts
  src/domains/dashboard/components/FilterWallets/models.ts
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/Wallets.test.tsx
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/WalletsControls.test.tsx
  src/domains/dashboard/i18n.ts
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/hooks/use-dashboard-config.test.tsx
  src/domains/dashboard/pages/Dashboard/hooks/use-dashboard-config.ts
  src/domains/dashboard/pages/Dashboard/models.ts
  src/domains/setting/i18n.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#3459 chore(deps): update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High, Type: Task

#3463 refactor: redefine dynamic table header classes using `classnames` package
  src/app/components/Table/Table.tsx
  src/app/components/Table/__snapshots__/Table.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/WalletsList.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/components/AddExchange/__snapshots__/AddExchange.test.tsx.snap
  src/domains/plugin/components/BestPlugins/__snapshots__/BestPlugins.test.tsx.snap
  src/domains/plugin/components/FeaturedPlugins/__snapshots__/FeaturedPlugins.test.tsx.snap
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/transaction/components/ConfirmSendTransaction/__snapshots__/ConfirmSendTransaction.test.tsx.snap
  src/domains/transaction/components/MultiPaymentDetail/__snapshots__/MultiPaymentDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureDetail/__snapshots__/MultiSignatureDetail.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/components/SearchRecipient/__snapshots__/SearchRecipient.test.tsx.snap
  src/domains/transaction/components/TransactionDetail/TransactionRecipients/__snapshots__/TransactionRecipients.test.tsx.snap
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/UnconfirmedTransactionTable/__snapshots__/UnconfirmedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/vote/components/AddressTable/__snapshots__/AddressTable.test.tsx.snap
  src/domains/vote/components/DelegateTable/__snapshots__/DelegateTable.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/SearchWallet.tsx
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerScanStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#3462 test: adjust navbar e2e test
  src/domains/dashboard/e2e/navbar-routing.e2e.ts
Labels: Complexity: Low, Test: Unit

#3455 feat: show red dot indicator when wallet filters are changed
  src/app/components/LayoutControls/LayoutControls.test.tsx
  src/app/components/LayoutControls/LayoutControls.tsx
  src/app/components/LayoutControls/__snapshots__/LayoutControls.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/WalletsControls.tsx
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
Labels: Complexity: Medium, Type: Feature

#3456 fix: adjust invalid state in fee input
  src/app/components/Input/InputRange.test.tsx
  src/app/components/Input/InputRange.tsx
  src/app/components/Input/__snapshots__/InputRange.test.tsx.snap
  src/app/components/Range/Range.test.tsx
  src/app/components/Range/Range.tsx
  src/app/components/Range/__snapshots__/Range.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#3446 refactor: apply new designs in `SelectNetwork`
  .github/workflows/e2e.yml
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/contact/e2e/create-contact.e2e.ts
  src/domains/contact/e2e/update-contact.e2e.ts
  src/domains/network/components/NetworkIcon/NetworkIcon.test.tsx
  src/domains/network/components/NetworkOption/NetworkOption.test.tsx
  src/domains/network/components/NetworkOption/NetworkOption.tsx
  src/domains/network/components/NetworkOption/__snapshots__/NetworkOption.test.tsx.snap
  src/domains/network/components/NetworkOption/index.ts
  src/domains/network/components/SelectNetwork/SelectNetwork.test.tsx
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/setting/components/CreatePeer/__snapshots__/CreatePeer.test.tsx.snap
  src/domains/setting/components/PeerForm/__snapshots__/PeerForm.test.tsx.snap
  src/domains/setting/components/UpdatePeer/UpdatePeer.test.tsx
  src/domains/setting/components/UpdatePeer/__snapshots__/UpdatePeer.test.tsx.snap
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/wallet/e2e/common.ts
  src/domains/wallet/e2e/create-wallet-action.e2e.ts
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerConnectionStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerScanStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#3427 feat: update all plugins functionality
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/i18n.ts
  src/domains/plugin/pages/PluginDetails/PluginDetails.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/plugins/context/PluginManagerProvider.test.tsx
  src/tests/fixtures/plugins/downloads/@dated/delegate-calculator-plugin.json
  src/tests/fixtures/plugins/registry-response.json
  src/tests/fixtures/plugins/registry/@dated/delegate-calculator-plugin.json
  src/tests/fixtures/plugins/whitelist.json
  src/utils/e2e-utils.ts
  src/utils/testing-library.tsx
Labels: Complexity: Undetermined, Status: Needs Review, Type: Feature

#3474 deps: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High

#3471 refactor: implement new alert designs
  src/app/assets/svg/alert-danger.svg
  src/app/assets/svg/alert-hint.svg
  src/app/assets/svg/alert-info.svg
  src/app/assets/svg/alert-success.svg
  src/app/assets/svg/alert-warning.svg
  src/app/components/Alert/Alert.test.tsx
  src/app/components/Alert/Alert.tsx
  src/app/components/Alert/__snapshots__/Alert.test.tsx.snap
  src/domains/plugin/components/PluginInfo/__snapshots__/PluginInfo.test.tsx.snap
  src/domains/plugin/components/PluginManualInstallModal/PluginManualInstallModal.tsx
  src/domains/plugin/components/PluginManualInstallModal/__snapshots__/PluginManualInstallModal.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFundsForm.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerConnectionStep.test.tsx.snap
  src/styles/variables.css
Labels: Complexity: High, Type: Refactor

#3472 fix: add forgotten call to get translation
  src/domains/transaction/components/MultiSignatureRegistrationForm/MultiSignatureRegistrationForm.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#3467 fix: adjust label color of transaction history setting
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
Labels: Complexity: Low, Type: Bugfix

#3470 refactor: implement new send all button design
  src/app/components/ButtonGroup/ButtonGroup.tsx
  src/app/components/ButtonGroup/__snapshots__/ButtonGroup.test.tsx.snap
  src/app/i18n/common/i18n.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/InputAmount/InputAmount.tsx
  src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/e2e/multiple-transfer.e2e.ts
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: High, Type: Refactor

#3468 feat: remember if advanced mode has been accepted
  src/app/i18n/common/i18n.ts
  src/domains/setting/components/AdvancedMode/AdvancedMode.tsx
  src/domains/setting/components/AdvancedMode/__snapshots__/AdvancedMode.test.tsx.snap
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
Labels: Complexity: Medium, Type: Feature

#3475 fix: return only unique permissions
  src/plugins/core/configuration/plugin-configuration.ts
Labels: Complexity: Low, Type: Bugfix

#3469 refactor: add dark mode styles to selected network option
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/network/components/NetworkOption/NetworkOption.tsx
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/setting/components/CreatePeer/__snapshots__/CreatePeer.test.tsx.snap
  src/domains/setting/components/PeerForm/__snapshots__/PeerForm.test.tsx.snap
  src/domains/setting/components/UpdatePeer/__snapshots__/UpdatePeer.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#3478 fix: use https for wallets.ark.io
  config/networks/mainnet.json
  src/renderer/store/modules/network.js
Labels: Complexity: Low

#3480 chore: merge 2.0 to staging
  .github/workflows/draft-artifacts.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  README.md
  __tests__/unit/__utils__/setup.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormVote.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/services/crypto/transaction-signer.spec.js
  config/networks/devnet.json
  config/networks/mainnet.json
  package.json
  src/renderer/components/Passphrase/PassphraseInput.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Wallet/WalletAddress.vue
  src/renderer/models/network.js
  src/renderer/services/client.js
  src/renderer/services/crypto/transaction-signer.js
  src/renderer/services/wallet.js
  src/renderer/store/modules/network.js
  src/renderer/store/modules/wallet.js
  yarn.lock
Labels: Complexity: High, Type: Task

#3481 release: 2.9.5
  .github/workflows/draft-artifacts.yml
  .github/workflows/publish-release.yml
  .github/workflows/test.yml
  README.md
  __tests__/unit/__utils__/setup.js
  __tests__/unit/components/Transaction/TransactionForm/TransactionFormVote.spec.js
  __tests__/unit/services/client.spec.js
  __tests__/unit/services/crypto/transaction-signer.spec.js
  config/networks/devnet.json
  config/networks/mainnet.json
  package.json
  src/renderer/components/Passphrase/PassphraseInput.vue
  src/renderer/components/Transaction/TransactionForm/TransactionFormVote.vue
  src/renderer/components/Transaction/TransactionModal.vue
  src/renderer/components/Wallet/WalletAddress.vue
  src/renderer/models/network.js
  src/renderer/services/client.js
  src/renderer/services/crypto/transaction-signer.js
  src/renderer/services/wallet.js
  src/renderer/store/modules/network.js
  src/renderer/store/modules/wallet.js
  yarn.lock
Labels: Complexity: High, Type: Release

#3410 feat: implement profile export
  src/app/assets/svg/export.svg
  src/app/assets/svg/index.ts
  src/app/i18n/common/i18n.ts
  src/domains/setting/hooks/use-profile-export.test.tsx
  src/domains/setting/hooks/use-profile-export.ts
  src/domains/setting/i18n.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/Export.tsx
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/setting/pages/Settings/available-settings/index.ts
Labels: Complexity: Medium, Status: Needs Review

#3479 refactor: properly align and style plugin progress bars
  src/app/components/Tooltip/Tooltip.tsx
  src/app/hooks/index.ts
  src/app/hooks/use-theme-name.test.tsx
  src/app/hooks/use-theme-name.ts
  src/app/hooks/use-theme.test.tsx
  src/app/hooks/use-theme.ts
  src/domains/error/pages/ApplicationError/ApplicationError.tsx
  src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/components/PluginHeader/__snapshots__/PluginHeader.test.tsx.snap
  src/domains/plugin/components/PluginImage/PluginImage.styles.ts
  src/domains/plugin/components/PluginImage/PluginImage.test.tsx
  src/domains/plugin/components/PluginImage/PluginImage.tsx
  src/domains/plugin/components/PluginImage/__snapshots__/PluginImage.test.tsx.snap
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/components/PluginListItem/__snapshots__/PluginListItem.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
Labels: Complexity: High, Type: Refactor

#3477 refactor: show loading state during wallet creation
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/Step1.tsx
Labels: Complexity: Low, Type: Refactor

#3476 chore: use `Header` component in create profile
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
Labels: Complexity: High, Type: Task

#3466 feat: add copy column in `Contacts`
  src/domains/contact/components/ContactListItem/ContactListItem.tsx
  src/domains/contact/components/ContactListItem/__snapshots__/ContactListItem.test.tsx.snap
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
Labels: Complexity: High, Type: Feature

#3465 refactor: adjust multiple wallet import to new design
  src/app/assets/svg/edit.svg
  src/app/components/Input/Input.test.tsx
  src/app/components/Input/Input.tsx
  src/domains/transaction/components/TransactionDetail/TransactionDetail.styles.ts
  src/domains/transaction/components/TransactionDetail/TransactionDetail.tsx
  src/domains/wallet/components/UpdateWalletName/UpdateWalletName.test.tsx
  src/domains/wallet/components/UpdateWalletName/UpdateWalletName.tsx
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.test.tsx
  src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.tsx
  src/domains/wallet/pages/ImportWallet/Ledger/LedgerTabs.test.tsx
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
Labels: Complexity: High, Status: Needs Review, Type: Refactor

#3483 feat: ability to import wallet by private key
  src/app/i18n/common/i18n.ts
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/Step2.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Low, Status: Needs Review, Type: Feature

#3482 refactor: handle empty fee input
  package.json
  src/app/components/Input/InputCurrency.tsx
  src/app/components/Input/InputRange.tsx
  src/app/hooks/use-currency-display.test.tsx
  src/app/hooks/use-currency-display.ts
  src/app/hooks/use-validation.test.tsx
  src/app/i18n/common/i18n.ts
  src/domains/transaction/components/InputFee/InputFee.tsx
  src/domains/transaction/components/InputFee/hooks.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/validations/Common.ts
  yarn.lock
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#3488 chore: add border to contacts page header
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
Labels: Complexity: Low, Type: Task

#3486 refactor: adjust colors in recipients list
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/components/RecipientList/RecipientList.tsx
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#3497 feat: import wallet by encrypted WIF
  package.json
  src/app/i18n/common/i18n.ts
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/Step2.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  yarn.lock
Labels: Complexity: Undetermined, Type: Feature

#3496 refactor: adjust mnemonic tooltip and disabled 2nd mnemonic input
  src/app/i18n/common/i18n.ts
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.tsx
  src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/transaction/validations/Authentication.ts
Labels: Complexity: Low, Type: Refactor

#3494 refactor: disable network options if input is disabled
  src/domains/network/components/NetworkOption/NetworkOption.test.tsx
  src/domains/network/components/NetworkOption/NetworkOption.tsx
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#3493 refactor: show update stats also in plugin grid
  src/domains/plugin/components/PluginCard/PluginCard.tsx
  src/domains/plugin/components/PluginGrid/PluginGrid.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#3492 refactor: remove recipients/participants based on index
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/MultiSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/AddParticipant.test.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/AddParticipant.tsx
  src/domains/transaction/components/RecipientList/RecipientList.models.ts
  src/domains/transaction/components/RecipientList/RecipientList.tsx
Labels: Complexity: Low, Type: Refactor

#3487 chore: remove `PluginsCategory` page
  src/domains/plugin/i18n.ts
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.test.tsx
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.tsx
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/index.tsx
  src/domains/plugin/pages/index.ts
  src/domains/plugin/routing.ts
Labels: Complexity: Undetermined, Type: Task

#3489 fix: display plugin update stats properly
  src/plugins/context/PluginManagerProvider.test.tsx
  src/plugins/context/PluginManagerProvider.tsx
Labels: Complexity: Low, Type: Bugfix

#3484 refactor: rename `Home` to `Latest` and add i18n
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.test.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/i18n.ts
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#3495 refactor: remove contacts banner
  src/app/assets/images/index.ts
  src/domains/contact/i18n.ts
  src/domains/contact/images/contacts-banner.svg
  src/domains/contact/images/dark/contacts-banner.svg
  src/domains/contact/images/dark/index.ts
  src/domains/contact/images/index.ts
  src/domains/contact/pages/Contacts/Contacts.test.tsx
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#3435 refactor: add plugin updates confirmation modal
  src/app/components/Dropdown/Dropdown.test.tsx
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/app/components/Table/TableCell.tsx
  src/domains/exchange/components/ExchangeCard/__snapshots__/ExchangeCard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/plugin/components/PluginCard/PluginCard.tsx
  src/domains/plugin/components/PluginCard/__snapshots__/PluginCard.test.tsx.snap
  src/domains/plugin/components/PluginGrid/PluginGrid.tsx
  src/domains/plugin/components/PluginGrid/__snapshots__/PluginGrid.test.tsx.snap
  src/domains/plugin/components/PluginHeader/PluginHeader.tsx
  src/domains/plugin/components/PluginImage/PluginImage.tsx
  src/domains/plugin/components/PluginListItem/PluginListItem.tsx
  src/domains/plugin/components/PluginUpdatesConfirmation/PluginUpdatesConfirmation.test.tsx
  src/domains/plugin/components/PluginUpdatesConfirmation/PluginUpdatesConfirmation.tsx
  src/domains/plugin/components/PluginUpdatesConfirmation/__snapshots__/PluginUpdatesConfirmation.test.tsx.snap
  src/domains/plugin/components/PluginUpdatesConfirmation/index.ts
  src/domains/plugin/i18n.ts
  src/domains/plugin/pages/PluginDetails/PluginDetails.test.tsx
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#3511 chore: remove obsolete todo about progress in `InstallPlugin`
  src/domains/plugin/components/InstallPlugin/InstallPlugin.tsx
Labels: Complexity: Low, Type: Task

#3506 refactor: show shadow also with logo-only variant
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#3505 fix: conditionally add/remove event listener on modals
  src/app/components/Modal/hooks.ts
Labels: Complexity: Low, Type: Bugfix

#3504 fix: adjust `SendTransfer` form state
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
Labels: Complexity: Low, Type: Bugfix

#3503 refactor: generate wallet when clicking on continue
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/Step1.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#3453 refactor: add cryptoasset step to send transfer from navbar
  src/domains/dashboard/e2e/navbar-routing.e2e.ts
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendTransfer/FormStep.tsx
  src/domains/transaction/pages/SendTransfer/NetworkStep.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#3500 fix: show the plugin size for non-installed packages
  src/domains/plugin/components/PluginHeader/PluginHeader.tsx
  src/domains/plugin/components/PluginHeader/__snapshots__/PluginHeader.test.tsx.snap
  src/domains/plugin/components/PluginHeader/components/PluginSpecs/PluginSpecs.test.tsx
  src/domains/plugin/components/PluginHeader/components/PluginSpecs/PluginSpecs.tsx
  src/domains/plugin/components/PluginHeader/components/PluginSpecs/__snapshots__/PluginSpecs.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/PluginDetails.tsx
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/plugins/context/PluginManagerProvider.test.tsx
  src/plugins/context/PluginManagerProvider.tsx
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3501 refactor: add all plugins tab
  src/domains/plugin/components/PluginGrid/PluginGrid.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/i18n.ts
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#3491 feat: import wallet by WIF
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/Step2.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Undetermined, Type: Feature

#3502 fix: display the url on plugin details page
  src/domains/plugin/components/PluginHeader/__snapshots__/PluginHeader.test.tsx.snap
  src/domains/plugin/components/PluginHeader/components/PluginSpecs/PluginSpecs.tsx
  src/domains/plugin/components/PluginHeader/components/PluginSpecs/__snapshots__/PluginSpecs.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/plugins/core/configuration/plugin-configuration.test.ts
  src/plugins/core/configuration/plugin-configuration.ts
Labels: Complexity: Low, Type: Bugfix

#3485 fix: do not switch to multi when going back to form with only one recipient
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
Labels: Complexity: High, Type: Bugfix

#3509 refactor: add plugin updates to queue
  src/domains/plugin/hooks/use-plugin-update-queue.test.tsx
  src/domains/plugin/hooks/use-plugin-update-queue.ts
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
Labels: Complexity: Medium, Status: Needs Review, Type: Refactor

#3522 deps: update Platform SDK dependencies
  package.json
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  yarn.lock
Labels: Complexity: High

#3525 refactor: update verify message modal
  src/app/components/Toggle/Toggle.test.tsx
  src/app/components/Toggle/Toggle.tsx
  src/app/components/Toggle/__snapshots__/Toggle.test.tsx.snap
  src/app/hooks/use-validation.ts
  src/domains/wallet/components/VerifyMessage/VerifyMessage.test.tsx
  src/domains/wallet/components/VerifyMessage/VerifyMessage.tsx
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/components/VerifyMessageStatus/VerifyMessageStatus.tsx
  src/domains/wallet/components/VerifyMessageStatus/__snapshots__/VerifyMessageStatus.test.tsx.snap
  src/domains/wallet/e2e/verify-message-action.e2e.ts
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/validations/VerifyMessage.ts
  src/domains/wallet/validations/index.ts
Labels: Complexity: Undetermined, Type: Refactor

#3527 refactor: ignore form context in header search bar
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/app/components/Input/Input.tsx
Labels: Complexity: Low, Type: Refactor

#3526 refactor: get rid of act warnings in sign message tests
  src/domains/wallet/components/SignMessage/SignMessage.test.tsx
Labels: Complexity: Low, Type: Refactor

#3523 refactor: hide network options on form step
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/network/components/SelectNetwork/SelectNetwork.test.tsx
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/setting/components/CreatePeer/__snapshots__/CreatePeer.test.tsx.snap
  src/domains/setting/components/PeerForm/__snapshots__/PeerForm.test.tsx.snap
  src/domains/setting/components/UpdatePeer/__snapshots__/UpdatePeer.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerConnectionStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerScanStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#3521 refactor: adjustments to export settings
  src/domains/setting/hooks/use-profile-export.test.tsx
  src/domains/setting/hooks/use-profile-export.ts
  src/domains/setting/i18n.ts
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/Export.tsx
  src/domains/setting/pages/Settings/available-settings/Plugins.tsx
Labels: Complexity: Medium, Type: Refactor

#3518 fix: do not reset fee when going back in vote form
  src/domains/transaction/pages/SendVote/FormStep.tsx
  src/domains/transaction/pages/SendVote/SendVote.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
Labels: Complexity: Low, Type: Bugfix

#3512 refactor: periodic fetch plugins
  src/app/App.test.tsx
  src/app/hooks/use-env-synchronizer.test.tsx
  src/app/hooks/use-env-synchronizer.ts
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
Labels: Complexity: Low, Status: Needs Review, Type: Refactor

#3464 feat: implement profile import
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/svg/dwe-file.svg
  src/app/assets/svg/index.ts
  src/app/assets/svg/json-file.svg
  src/app/components/SelectFile/SelectFile.test.tsx
  src/app/components/SelectFile/SelectFile.tsx
  src/app/components/SelectFile/__snapshots__/SelectFile.test.tsx.snap
  src/app/components/SelectFile/index.tsx
  src/app/hooks/use-files.test.tsx
  src/app/hooks/use-files.ts
  src/app/i18n/common/i18n.ts
  src/domains/profile/components/FilePreview/FilePreview.test.tsx
  src/domains/profile/components/FilePreview/FilePreview.tsx
  src/domains/profile/components/FilePreview/__snapshots__/FilePreview.test.tsx.snap
  src/domains/profile/components/FilePreview/index.ts
  src/domains/profile/components/PasswordModal/PasswordModal.test.tsx
  src/domains/profile/components/PasswordModal/PasswordModal.tsx
  src/domains/profile/components/PasswordModal/__snapshots__/PasswordModal.test.tsx.snap
  src/domains/profile/components/PasswordModal/index.ts
  src/domains/profile/hooks/use-profile-import.test.tsx
  src/domains/profile/hooks/use-profile-import.ts
  src/domains/profile/i18n.ts
  src/domains/profile/middleware.ts
  src/domains/profile/pages/ImportProfile/ErrorStep.test.tsx
  src/domains/profile/pages/ImportProfile/ErrorStep.tsx
  src/domains/profile/pages/ImportProfile/ImportProfile.test.tsx
  src/domains/profile/pages/ImportProfile/ImportProfile.tsx
  src/domains/profile/pages/ImportProfile/ProcessingImportStep.test.tsx
  src/domains/profile/pages/ImportProfile/ProcessingImportStep.tsx
  src/domains/profile/pages/ImportProfile/ProfileFormStep.test.tsx
  src/domains/profile/pages/ImportProfile/ProfileFormStep.tsx
  src/domains/profile/pages/ImportProfile/SelectFileStep.test.tsx
  src/domains/profile/pages/ImportProfile/SelectFileStep.tsx
  src/domains/profile/pages/ImportProfile/__snapshots__/ErrorStep.test.tsx.snap
  src/domains/profile/pages/ImportProfile/__snapshots__/ImportProfile.test.tsx.snap
  src/domains/profile/pages/ImportProfile/__snapshots__/ProcessingImportStep.test.tsx.snap
  src/domains/profile/pages/ImportProfile/__snapshots__/ProfileFormStep.test.tsx.snap
  src/domains/profile/pages/ImportProfile/__snapshots__/SelectFileStep.test.tsx.snap
  src/domains/profile/pages/ImportProfile/index.tsx
  src/domains/profile/pages/ImportProfile/models.ts
  src/domains/profile/pages/Welcome/Welcome.tsx
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/profile/pages/index.tsx
  src/domains/profile/routing.ts
  src/tests/fixtures/profile/import/corrupted-profile.dwe
  src/tests/fixtures/profile/import/d2_test_wallets-empty.json
  src/tests/fixtures/profile/import/d2_test_wallets.json
  src/tests/fixtures/profile/import/password-protected-profile.dwe
  src/tests/fixtures/profile/import/profile.dwe
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#3513 feat: implement optional encryption password for wallets
  src/app/components/Header/Header.test.tsx
  src/app/components/Header/Header.tsx
  src/app/components/Header/__snapshots__/Header.test.tsx.snap
  src/app/hooks/use-validation.ts
  src/domains/wallet/components/EncryptPasswordStep/EncryptPasswordStep.test.tsx
  src/domains/wallet/components/EncryptPasswordStep/EncryptPasswordStep.tsx
  src/domains/wallet/components/EncryptPasswordStep/__snapshots__/EncryptPasswordStep.test.tsx.snap
  src/domains/wallet/components/EncryptPasswordStep/index.tsx
  src/domains/wallet/e2e/common.ts
  src/domains/wallet/e2e/create-wallet-action.e2e.ts
  src/domains/wallet/e2e/import-wallet-action.e2e.ts
  src/domains/wallet/hooks/use-wallet-import.ts
  src/domains/wallet/hooks/use-wallet-sync.ts
  src/domains/wallet/i18n.ts
  src/domains/wallet/pages/CreateWallet/ConfirmPassphrase.test.tsx
  src/domains/wallet/pages/CreateWallet/ConfirmPassphraseStep.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.test.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/EncryptionPasswordStep.test.tsx
  src/domains/wallet/pages/CreateWallet/SelectNetworkStep.test.tsx
  src/domains/wallet/pages/CreateWallet/SelectNetworkStep.tsx
  src/domains/wallet/pages/CreateWallet/SuccessStep.test.tsx
  src/domains/wallet/pages/CreateWallet/SuccessStep.tsx
  src/domains/wallet/pages/CreateWallet/WalletOverviewStep.test.tsx
  src/domains/wallet/pages/CreateWallet/WalletOverviewStep.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/SelectNetworkStep.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/SuccessStep.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/WalletOverviewStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/validations/EncryptPassword.test.tsx
  src/domains/wallet/validations/EncryptPassword.ts
  src/domains/wallet/validations/index.ts
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#3510 fix: remove double error message on receive funds modal
  src/domains/wallet/components/ReceiveFunds/ReceiveFundsForm.test.tsx
  src/domains/wallet/components/ReceiveFunds/ReceiveFundsForm.tsx
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFundsForm.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#3524 feat: allow plugins to use modals
  src/plugins/core/plugin-controller-repository.ts
  src/tests/fixtures/plugins/packages/plugin-test-custom-button/package.json
  src/tests/fixtures/plugins/packages/plugin-test-launch/index.js
  src/tests/fixtures/plugins/packages/plugin-test-launch/package.json
Labels: Complexity: Low, Type: Feature

#3520 refactor: adjust all header search and filter buttons/icons
  src/app/components/ControlButton/ControlButton.test.tsx
  src/app/components/ControlButton/ControlButton.tsx
  src/app/components/ControlButton/__snapshots__/ControlButton.test.tsx.snap
  src/app/components/ControlButton/index.ts
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.test.tsx
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/app/components/Header/HeaderSearchBar/__snapshots__/HeaderSearchBar.test.tsx.snap
  src/app/components/LayoutControls/LayoutControls.test.tsx
  src/app/components/LayoutControls/LayoutControls.tsx
  src/app/components/LayoutControls/__snapshots__/LayoutControls.test.tsx.snap
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/WalletsControls.tsx
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/transaction/components/SearchRecipient/SearchRecipient.tsx
  src/domains/transaction/components/SearchRecipient/__snapshots__/SearchRecipient.test.tsx.snap
  src/domains/vote/components/VotesFilter/VotesFilter.tsx
  src/domains/vote/components/VotesFilter/__snapshots__/VotesFilter.test.tsx.snap
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/SearchWallet.tsx
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Undetermined

#3533 test: fix act warning in `LedgerImportStep`
  src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.test.tsx
Labels: Complexity: Low, Test: Unit

#3534 refactor: save wallet name when pressing enter during import
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#3535 refactor: hide max amount if fee input has errors
  src/domains/transaction/components/AddRecipient/AddRecipient.models.ts
  src/domains/transaction/components/AddRecipient/AddRecipient.test.tsx
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/pages/SendTransfer/FormStep.tsx
Labels: Complexity: Medium, Type: Refactor

#3544 chore: update Platform SDK dependencies
  package.json
  src/domains/wallet/validations/VerifyMessage.test.tsx
  yarn.lock
Labels: Complexity: High, Type: Task

#3542 refactor: adjust import ledger name forms
  src/app/components/Address/Address.tsx
  src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.test.tsx
  src/domains/wallet/pages/ImportWallet/Ledger/LedgerImportStep.tsx
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#3543 fix: hide navbar border on scroll
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/ImportProfile/__snapshots__/ImportProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#3546 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: Undetermined, Status: Needs Review

#3548 fix: prevent multiple app instances
  src/electron/index.ts
  src/electron/utils/single-instance.ts
Labels: Complexity: Low, Type: Bugfix

#3536 feat: ask user confirmation to leave settings page
  src/__snapshots__/index.test.ts.snap
  src/app/components/ConfirmationModal/ConfirmationModal.test.tsx
  src/app/components/ConfirmationModal/ConfirmationModal.tsx
  src/app/components/ConfirmationModal/__snapshots__/ConfirmationModal.test.tsx.snap
  src/app/components/ConfirmationModal/index.ts
  src/app/components/Modal/Modal.tsx
  src/app/i18n/common/i18n.ts
  src/domains/profile/components/PasswordModal/__snapshots__/PasswordModal.test.tsx.snap
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/wallet/components/SignMessage/SignMessage.test.tsx
  src/index.test.ts
  src/index.test.tsx
  src/index.tsx
Labels: Complexity: High, Status: Needs Review, Type: Feature

#3537 feat: use password encryption when sending transactions
  src/app/i18n/common/i18n.ts
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.test.tsx
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.test.tsx
  src/domains/transaction/components/DelegateRegistrationForm/DelegateRegistrationForm.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/MultiSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/MultiSignatureRegistrationForm.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.test.tsx
  src/domains/transaction/components/SecondSignatureRegistrationForm/SecondSignatureRegistrationForm.tsx
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.test.tsx
  src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.tsx
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/SendRegistration.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/SendVote.test.tsx
  src/domains/transaction/pages/SendVote/SendVote.tsx
  src/domains/transaction/validations/Authentication.test.tsx
  src/domains/transaction/validations/Authentication.ts
  src/utils/debounce.test.ts
  src/utils/debounce.ts
Labels: Complexity: High, Type: Feature

#3545 refactor: remove randomly failing test
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#3540 refactor: require protocol in github url
  src/app/assets/svg/file.svg
  src/app/components/Form/FormLabel.tsx
  src/app/components/Form/__snapshots__/FormLabel.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/plugin/components/PluginManualInstallModal/PluginManualInstallModal.test.tsx
  src/domains/plugin/components/PluginManualInstallModal/PluginManualInstallModal.tsx
  src/domains/plugin/components/PluginManualInstallModal/__snapshots__/PluginManualInstallModal.test.tsx.snap
  src/domains/plugin/i18n.ts
  src/domains/plugin/pages/PluginManager/PluginManager.test.tsx
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/profile/components/PasswordModal/__snapshots__/PasswordModal.test.tsx.snap
  src/domains/profile/components/SignIn/__snapshots__/SignIn.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/ImportProfile/__snapshots__/ProfileFormStep.test.tsx.snap
  src/domains/setting/components/CreatePeer/__snapshots__/CreatePeer.test.tsx.snap
  src/domains/setting/components/PeerForm/__snapshots__/PeerForm.test.tsx.snap
  src/domains/setting/components/UpdatePeer/__snapshots__/UpdatePeer.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/Plugins.tsx
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFundsForm.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/SelectNetworkStep.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/SuccessStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerConnectionStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerScanStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#3555 refactor: adjustments to sign in modal
  src/domains/profile/components/SignIn/SignIn.tsx
  src/domains/profile/components/SignIn/__snapshots__/SignIn.test.tsx.snap
  src/domains/profile/i18n.ts
Labels: Complexity: Low, Type: Refactor

#3554 fix: toggle dropdown menu when clicking on caret
  src/app/components/SelectDropdown/SelectDropdown.test.tsx
  src/app/components/SelectDropdown/SelectDropdown.tsx
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/ImportProfile/__snapshots__/ProfileFormStep.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#3556 refactor: hide converted balance if wallet belongs to test network
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.test.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/__snapshots__/WalletHeader.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#3553 fix: prevent state update if unmounted on wallet details page
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
Labels: Complexity: Low, Type: Bugfix

#3541 feat: allow plugins to sign messages
  src/app/PluginProviders.tsx
  src/domains/transaction/components/RecipientList/RecipientList.tsx
  src/domains/wallet/components/SignMessage/FormStep.tsx
  src/domains/wallet/components/SignMessage/SignMessage.test.tsx
  src/domains/wallet/components/SignMessage/SignMessage.tsx
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
  src/plugins/README.md
  src/plugins/services/index.tsx
  src/plugins/services/message/MessagePluginService.test.tsx
  src/plugins/services/message/MessagePluginService.tsx
  src/plugins/services/message/index.tsx
  src/plugins/services/message/use-sign-message-modal.tsx
  src/plugins/types.ts
  src/tests/fixtures/plugins/packages/plugin-test-launch/index.js
  src/tests/fixtures/plugins/packages/plugin-test-launch/package.json
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#3552 fix: register `suppressWarning` on all transaction forms
  src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.tsx
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
  src/domains/transaction/pages/SendRegistration/SendRegistration.tsx
  src/domains/transaction/pages/SendVote/SendVote.tsx
Labels: Complexity: Low, Type: Bugfix

#3519 fix: back button behavior on windows
  package.json
  src/app/hooks/use-deeplink.test.tsx
  src/app/hooks/use-deeplink.ts
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/index.tsx
  yarn.lock
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3549 chore: update react-hook-form
  package.json
  src/app/components/Input/InputAddress.tsx
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/ImportProfile/ProfileFormStep.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  yarn.lock
Labels: Complexity: High, Status: Needs Review, Type: Task

#3547 refactor: replace dashboard config hook with wallet config
  src/domains/dashboard/components/FilterWallets/hooks.ts
  src/domains/dashboard/hooks/index.ts
  src/domains/dashboard/hooks/use-wallet-config.test.tsx
  src/domains/dashboard/hooks/use-wallet-config.ts
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/hooks/index.ts
  src/domains/dashboard/pages/Dashboard/index.tsx
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
Labels: Complexity: Low, Type: Refactor

#3561 refactor: disable wallet filters while profile has no wallets
  src/app/components/ControlButton/ControlButton.test.tsx
  src/app/components/ControlButton/ControlButton.tsx
  src/app/components/ControlButton/__snapshots__/ControlButton.test.tsx.snap
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/Header/HeaderSearchBar/__snapshots__/HeaderSearchBar.test.tsx.snap
  src/app/components/LayoutControls/__snapshots__/LayoutControls.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/FilterWallets/hooks.ts
  src/domains/dashboard/components/FilterWallets/models.ts
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/WalletsControls/WalletsControls.tsx
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/transaction/components/SearchRecipient/__snapshots__/SearchRecipient.test.tsx.snap
  src/domains/vote/components/VotesFilter/__snapshots__/VotesFilter.test.tsx.snap
  src/domains/vote/pages/Votes/Votes.test.tsx
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#3562 chore: adjust empty transactions text on wallets
  src/domains/wallet/i18n.ts
Labels: Complexity: Low, Type: Task

#3560 fix: removal of correct handler for correct listener
  src/app/hooks/use-updater.ts
Labels: Complexity: Low, Status: Needs Review, Type: Bugfix

#3558 feat: sign messages with wif
  package.json
  src/domains/transaction/validations/Authentication.ts
  src/domains/wallet/components/SignMessage/FormStep.tsx
  src/domains/wallet/components/SignMessage/SignMessage.test.tsx
  src/domains/wallet/components/SignMessage/SignMessage.tsx
  src/domains/wallet/components/SignMessage/hooks/use-message-signer.test.tsx
  src/domains/wallet/components/SignMessage/hooks/use-message-signer.ts
  yarn.lock
Labels: Complexity: Low, Type: Feature

#3566 feat: show display type in blank wallet cards
  src/app/components/ControlButton/ControlButton.tsx
  src/app/components/ControlButton/__snapshots__/ControlButton.test.tsx.snap
  src/app/components/Header/HeaderSearchBar/__snapshots__/HeaderSearchBar.test.tsx.snap
  src/app/components/LayoutControls/__snapshots__/LayoutControls.test.tsx.snap
  src/app/components/WalletCard/WalletCard.test.tsx
  src/app/components/WalletCard/WalletCard.tsx
  src/app/components/WalletCard/__snapshots__/WalletCard.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/Wallets/hooks.ts
  src/domains/dashboard/components/WalletsControls/__snapshots__/WalletsControls.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/plugin/components/PluginManagerControls/__snapshots__/PluginManagerControls.test.tsx.snap
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/transaction/components/SearchRecipient/__snapshots__/SearchRecipient.test.tsx.snap
  src/domains/vote/components/VotesFilter/__snapshots__/VotesFilter.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
Labels: Complexity: High, Type: Feature

#3567 fix: adjust notification dot border color on hover
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/Notifications/NotificationsDropdown.tsx
  src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Bugfix

#3564 refactor: show empty message based on display type
  src/domains/dashboard/components/Wallets/Wallets.tsx
  src/domains/dashboard/components/Wallets/WalletsList.test.tsx
  src/domains/dashboard/components/Wallets/WalletsList.tsx
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/WalletsList.test.tsx.snap
  src/domains/dashboard/components/Wallets/models.ts
  src/domains/dashboard/i18n.ts
Labels: Complexity: Undetermined, Type: Refactor

#3551 fix: input range error when clicking on thumb
  package.json
  src/app/components/Range/Range.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  yarn.lock
Labels: Complexity: Low, Type: Bugfix

#3559 chore: remove unused variable on Input component
  src/app/components/Input/Input.tsx
Labels: Complexity: Low, Type: Task

#3563 fix: sign transactions with wif and 2nd mnemonic
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.test.tsx
  src/domains/transaction/components/AuthenticationStep/AuthenticationStep.tsx
Labels: Complexity: Low, Type: Bugfix

#3574 refactor: add errors to min participants input
  src/domains/transaction/components/MultiSignatureRegistrationForm/FormStep.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/validations/MultiSignatureRegistration.ts
  src/domains/wallet/pages/ImportWallet/ImportWallet.test.tsx
Labels: Complexity: Low, Type: Refactor

#3573 refactor: conditionally disable remove button of recipient list item
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/AddParticipant.test.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/AddParticipant.tsx
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/components/RecipientList/RecipientList.models.ts
  src/domains/transaction/components/RecipientList/RecipientList.test.tsx
  src/domains/transaction/components/RecipientList/RecipientList.tsx
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#3572 refactor: adjust notifications empty state
  src/app/assets/images/dark/empty-notifications.svg
  src/app/assets/images/dark/index.ts
  src/app/assets/images/empty-notifications.svg
  src/app/assets/images/index.ts
  src/app/components/EmptyBlock/EmptyBlock.tsx
  src/app/components/EmptyBlock/__snapshots__/EmptyBlock.test.tsx.snap
  src/app/components/Notifications/Notifications.tsx
  src/app/components/Notifications/NotificationsSkeleton.tsx
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
  src/app/components/Notifications/index.ts
  src/app/components/Notifications/models.ts
  src/app/components/Notifications/styles.ts
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/WalletsList.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
Labels: Complexity: Medium, Type: Refactor

#3577 chore: update Platform SDK dependencies
  package.json
  yarn.lock
Labels: Complexity: High, Type: Task
