Repository ArkEcosystem/desktop-wallet, pull requests merged in 2021-02, with the labels that each got.

#3292 chore: update contribution guidelines url
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Bounty: Tier 5

#3291 chore: update homebrew install mechanism
  README.md
Labels: Bounty: Tier 5

#3378 test: increase `src/domains/contact` coverage to 100%
  .github/workflows/test.yml
  scripts/generate-test-workflow.js
  src/domains/contact/__snapshots__/routing.test.tsx.snap
  src/domains/contact/routing.test.tsx
Labels: Complexity: Low, Test: Unit

#3379 test: increase `src/domains/dashboard` coverage to 100%
  .github/workflows/test.yml
  scripts/generate-test-workflow.js
Labels: Complexity: Low, Test: Unit

#3380 test: increase `src/domains/exchange` coverage to 100%
  .github/workflows/test.yml
  scripts/generate-test-workflow.js
  src/domains/exchange/routing.test.tsx
Labels: Complexity: Low, Test: Unit

#3381 test: increase `src/domains/news` coverage to 100%
  .github/workflows/test.yml
  scripts/generate-test-workflow.js
  src/domains/news/routing.test.tsx
Labels: Complexity: Low, Test: Unit

#3382 fix: parse process.env.REACT_APP_IS_E2E
  src/app/App.tsx
Labels: Complexity: Low, Type: Bugfix

#3385 test: get rid of error in TableRow tests
  src/app/components/Table/TableRow.test.tsx
  src/app/components/Table/__snapshots__/TableRow.test.tsx.snap
Labels: Complexity: Low, Test: Unit

#3384 test: increase `src/domains/profile` coverage to 100%
  .github/workflows/test.yml
  scripts/generate-test-workflow.js
  src/domains/profile/routing.test.tsx
Labels: Complexity: Low, Test: Unit

#3387 refactor: set explicit id on date column
  src/domains/transaction/components/TransactionTable/TransactionTable.tsx
Labels: Complexity: Low, Type: Refactor

#3386 refactor: sort plugin table by title
  src/domains/plugin/components/PluginList/PluginList.test.tsx
  src/domains/plugin/components/PluginList/PluginList.tsx
  src/domains/plugin/components/PluginList/__snapshots__/PluginList.test.tsx.snap
  src/domains/plugin/components/PluginListItem/PluginListItem.tsx
  src/domains/plugin/components/PluginListItem/__snapshots__/PluginListItem.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Undetermined, Type: Refactor

#3388 test: increase `src/domains/setting` coverage to 100%
  .github/workflows/test.yml
  scripts/generate-test-workflow.js
  src/domains/setting/routing.test.tsx
Labels: Complexity: Low, Test: Unit

#3383 feat: sentry error reporting
  package.json
  src/app/App.tsx
  src/app/sentry/SentryErrorBoundary.tsx
  src/app/sentry/SentryProvider.test.tsx
  src/app/sentry/SentryProvider.tsx
  src/app/sentry/SentryRouterWrapper.test.tsx
  src/app/sentry/SentryRouterWrapper.tsx
  src/domains/setting/i18n.ts
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/utils/e2e-utils.ts
  yarn.lock
Labels: Complexity: High, Status: Needs Review, Type: Feature

#3398 feat: add fee warning to delegate resignation form
  src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.test.tsx
  src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.tsx
Labels: Complexity: Medium, Type: Feature

#3397 feat: add fee warning to registration form
  src/domains/transaction/pages/SendRegistration/SendRegistration.test.tsx
  src/domains/transaction/pages/SendRegistration/SendRegistration.tsx
Labels: Complexity: Medium, Type: Feature

#3396 feat: add fee warning to vote form
  src/domains/transaction/pages/SendVote/SendVote.test.tsx
  src/domains/transaction/pages/SendVote/SendVote.tsx
Labels: Complexity: Medium, Type: Feature

#3395 feat: add fee warning to ipfs form
  src/domains/transaction/pages/SendIpfs/SendIpfs.test.tsx
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
Labels: Complexity: Medium, Type: Feature

#3393 fix: add missing margin in Vote form
  src/domains/transaction/pages/SendVote/FormStep.tsx
Labels: Complexity: Low, Type: Bugfix

#3392 test: increase `src/domains/splash` coverage to 100%
  .github/workflows/test.yml
  scripts/generate-test-workflow.js
  src/domains/splash/pages/Splash/Splash.test.tsx
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
Labels: Complexity: High, Test: Unit

#3390 fix: loop errors in scanner.test.tsx
  src/app/contexts/Ledger/hooks/__snapshots__/scanner.test.tsx.snap
  src/app/contexts/Ledger/hooks/scanner.test.tsx
Labels: Complexity: Medium, Test: Unit, Type: Bugfix

#3399 chore: install `@arkecosystem/platform-sdk-egld`
  package.json
  src/app/App.tsx
  src/app/assets/svg/currencies/egld.svg
  src/app/assets/svg/currencies/index.ts
  src/domains/network/data.ts
  yarn.lock
Labels: Complexity: Undetermined, Status: Needs Review

#3400 build: remove the E2E flag for production build
  package.json
Labels: Complexity: Low

#3401 test: increase `src/domains/transaction` coverage to 100%
  .github/workflows/test.yml
  scripts/generate-test-workflow.js
  src/domains/transaction/components/SendTransactionForm/SendTransactionForm.tsx
  src/domains/transaction/routing.test.tsx
  src/domains/transaction/utils.test.ts
  src/domains/transaction/validations/Common.test.tsx
  src/domains/transaction/validations/SendTransfer.test.tsx
Labels: Complexity: Medium, Test: Unit

#3413 test: increase `src/domains/vote` coverage to 100%
  .github/workflows/test.yml
  scripts/generate-test-workflow.js
  src/domains/vote/routing.test.tsx
Labels: Complexity: Low, Test: Unit

#3414 refactor: use danger variant buttons for destructive actions
  src/app/components/Button/Button.styles.ts
  src/app/components/Button/__snapshots__/Button.test.tsx.snap
  src/app/components/DeleteResource/DeleteResource.tsx
  src/app/components/DeleteResource/__snapshots__/DeleteResource.test.tsx.snap
  src/app/components/SelectProfileImage/__snapshots__/SelectProfileImage.test.tsx.snap
  src/domains/contact/components/ContactForm/ContactForm.tsx
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/DeleteContact/__snapshots__/DeleteContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/plugin/components/PluginUninstallConfirmation/PluginUninstallConfirmation.tsx
  src/domains/plugin/components/PluginUninstallConfirmation/__snapshots__/PluginUninstallConfirmation.test.tsx.snap
  src/domains/profile/components/DeleteProfile/__snapshots__/DeleteProfile.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/setting/components/DeletePeer/__snapshots__/DeletePeer.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/components/RecipientList/RecipientList.tsx
  src/domains/transaction/components/RecipientList/__snapshots__/RecipientList.test.tsx.snap
  src/domains/wallet/components/DeleteWallet/__snapshots__/DeleteWallet.test.tsx.snap
Labels: Complexity: Medium

#3412 refactor: dynamically set shadow on navigation bar
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/hooks/index.ts
  src/app/hooks/use-scroll.test.tsx
  src/app/hooks/use-scroll.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#3407 refactor: reduce navbar height
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/Notifications/NotificationsDropdown.tsx
  src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Undetermined, Type: Refactor

#3404 refactor: display only title in the plugin view page
  src/domains/plugin/pages/PluginView/PluginView.test.tsx
  src/domains/plugin/pages/PluginView/PluginView.tsx
  src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#3391 fix: redirect on welcome screen when reloading password protected profile page
  src/app/App.test.tsx
  src/app/App.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/hooks/use-profile-synchronizer.test.tsx
  src/app/hooks/use-profile-synchronizer.ts
Labels: Complexity: Low, Type: Bugfix

#3405 refactor: remove breadcrumbs
  src/app/components/Breadcrumbs/Breadcrumbs.test.tsx
  src/app/components/Breadcrumbs/Breadcrumbs.tsx
  src/app/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap
  src/app/components/Breadcrumbs/index.ts
  src/app/components/Layout/components/Page/Page.test.tsx
  src/app/components/Layout/components/Page/Page.tsx
  src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap
  src/domains/contact/pages/Contacts/Contacts.tsx
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/plugin/e2e/plugins-routing.e2e.ts
  src/domains/plugin/pages/PluginDetails/PluginDetails.tsx
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/PluginsCategory.tsx
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/setting/pages/Settings/Settings.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/SendDelegateResignation.tsx
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/SendIpfs.tsx
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/SendRegistration.tsx
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/SendVote.tsx
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/Votes.tsx
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#3406 refactor: remove gray dividers from `Page` and `Sections`
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Layout/components/Page/Page.tsx
  src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap
  src/app/components/Layout/components/Section/Section.test.tsx
  src/app/components/Layout/components/Section/Section.tsx
  src/app/components/Layout/components/Section/__snapshots__/Section.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/PortfolioChart/__snapshots__/PortfolioChart.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginView/PluginView.tsx
  src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: High, Type: Refactor

#3408 refactor: remove arrow from user icon
  src/app/components/Avatar/Avatar.test.tsx
  src/app/components/Avatar/Avatar.tsx
  src/app/components/Avatar/__snapshots__/Avatar.test.tsx.snap
  src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.test.tsx
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#3411 feat: add back button to navigation bar
  src/app/__snapshots__/App.test.tsx.snap
  src/app/assets/svg/arrow-left.svg
  src/app/components/Layout/components/Page/Page.tsx
  src/app/components/Layout/components/Page/__snapshots__/Page.test.tsx.snap
  src/app/components/NavigationBar/NavigationBar.tsx
  src/app/components/NavigationBar/__snapshots__/NavigationBar.test.tsx.snap
  src/app/components/NavigationBar/components/BackButton/BackButton.styles.ts
  src/app/components/NavigationBar/components/BackButton/BackButton.test.tsx
  src/app/components/NavigationBar/components/BackButton/BackButton.tsx
  src/app/components/NavigationBar/components/BackButton/__snapshots__/BackButton.test.tsx.snap
  src/app/components/NavigationBar/components/BackButton/index.ts
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/Dashboard.tsx
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/Exchange.tsx
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginView/__snapshots__/PluginView.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Undetermined, Type: Feature

#3416 chore: adjust dark mode table hover color
  src/app/components/Notifications/__snapshots__/NotificationTransactionItem.test.tsx.snap
  src/app/components/Notifications/__snapshots__/Notifications.test.tsx.snap
  src/app/components/Notifications/__snapshots__/NotificationsDropdown.test.tsx.snap
  src/app/components/Table/TableRow.styles.ts
  src/app/components/WalletListItem/WalletListItem.test.tsx
  src/app/components/WalletListItem/WalletListItem.tsx
  src/app/components/WalletListItem/__snapshots__/WalletListItem.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/WalletsList.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/SignedTransactionTable.tsx
  src/domains/transaction/components/TransactionTable/SignedTransactionTable/__snapshots__/SignedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionCompactRow.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionCompactRow.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.test.tsx
  src/domains/transaction/components/TransactionTable/TransactionRow/TransactionRow.tsx
  src/domains/transaction/components/TransactionTable/UnconfirmedTransactionTable/UnconfirmedTransactionRow.tsx
  src/domains/transaction/components/TransactionTable/UnconfirmedTransactionTable/UnconfirmedTransactionTable.test.tsx
  src/domains/transaction/components/TransactionTable/UnconfirmedTransactionTable/__snapshots__/UnconfirmedTransactionTable.test.tsx.snap
  src/domains/transaction/components/TransactionTable/__snapshots__/TransactionTable.test.tsx.snap
  src/domains/vote/components/AddressTable/AddressRow/AddressRow.tsx
  src/domains/wallet/components/WalletBottomSheetMenu/__snapshots__/WalletBottomSheetMenu.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
Labels: Complexity: Medium, Type: Task

#3417 fix: plugin manager navbar offset and height
  src/domains/plugin/components/PluginManagerNavigationBar/PluginManagerNavigationBar.tsx
  src/domains/plugin/components/PluginManagerNavigationBar/__snapshots__/PluginManagerNavigationBar.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/tailwind.config.js
Labels: Complexity: Medium, Type: Bugfix

#3419 fix: dropdown styles
  src/app/assets/svg/trash.svg
  src/app/components/Dropdown/Dropdown.tsx
  src/app/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap
  src/domains/transaction/components/FilterTransactions/__snapshots__/FilterTransactions.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletHeader/WalletHeader.tsx
Labels: Complexity: High, Type: Bugfix

#3415 refactor: simplify `Section` and add background color to wallet vote
  src/app/__snapshots__/App.test.tsx.snap
  src/app/components/Layout/components/Section/Section.test.tsx
  src/app/components/Layout/components/Section/Section.tsx
  src/app/components/Layout/components/Section/__snapshots__/Section.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/dashboard/components/PortfolioChart/__snapshots__/PortfolioChart.test.tsx.snap
  src/domains/dashboard/components/Transactions/__snapshots__/Transactions.test.tsx.snap
  src/domains/dashboard/components/Wallets/__snapshots__/Wallets.test.tsx.snap
  src/domains/dashboard/pages/Dashboard/__snapshots__/Dashboard.test.tsx.snap
  src/domains/error/pages/ApplicationError/__snapshots__/ApplicationError.test.tsx.snap
  src/domains/error/pages/Offline/__snapshots__/Offline.test.tsx.snap
  src/domains/exchange/pages/Exchange/__snapshots__/Exchange.test.tsx.snap
  src/domains/news/pages/News/News.tsx
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
  src/domains/plugin/pages/PluginManager/PluginManager.tsx
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/plugin/pages/PluginsCategory/__snapshots__/PluginsCategory.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/Welcome/__snapshots__/Welcome.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/splash/pages/Splash/__snapshots__/Splash.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendRegistration/__snapshots__/SendRegistration.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/pages/SendVote/__snapshots__/SendVote.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/WalletDetails.tsx
  src/domains/wallet/pages/WalletDetails/__snapshots__/WalletDetails.test.tsx.snap
  src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVote.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletVote/WalletVoteSkeleton.tsx
  src/domains/wallet/pages/WalletDetails/components/WalletVote/__snapshots__/WalletVote.test.tsx.snap
Labels: Complexity: Undetermined, Type: Refactor

#3409 refactor: restore profile settings to default
  src/app/i18n/common/i18n.ts
  src/domains/profile/components/ResetProfile/ResetProfile.tsx
  src/domains/profile/components/ResetProfile/__snapshots__/ResetProfile.test.tsx.snap
  src/domains/profile/i18n.ts
  src/domains/profile/images/dark/index.ts
  src/domains/profile/images/dark/reset-settings-warning.svg
  src/domains/profile/images/index.tsx
  src/domains/profile/images/reset-settings-warning.svg
  src/domains/setting/e2e/reset-profile.e2e.ts
  src/domains/setting/pages/Settings/Settings.test.tsx
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/setting/pages/Settings/available-settings/General.tsx
Labels: Complexity: Low, Type: Refactor

#3423 chore: readme update
  README.md
Labels: Complexity: Low, Type: Task
