Repository ArkEcosystem/desktop-wallet, pull requests merged in 2021-04, with the labels that each got.

#3585 fix: add type to header search bar button
  src/app/components/Header/HeaderSearchBar/HeaderSearchBar.tsx
  src/app/components/Header/HeaderSearchBar/__snapshots__/HeaderSearchBar.test.tsx.snap
  src/domains/contact/pages/Contacts/__snapshots__/Contacts.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/transaction/components/SearchRecipient/__snapshots__/SearchRecipient.test.tsx.snap
  src/domains/vote/pages/Votes/__snapshots__/Votes.test.tsx.snap
  src/domains/wallet/components/SearchWallet/__snapshots__/SearchWallet.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#3583 refactor: limit plugin description to first line
  src/domains/plugin/components/PluginHeader/PluginHeader.tsx
  src/domains/plugin/components/PluginHeader/__snapshots__/PluginHeader.test.tsx.snap
  src/domains/plugin/pages/PluginDetails/__snapshots__/PluginDetails.test.tsx.snap
Labels: Complexity: Low, Type: Refactor

#3582 refactor: display transaction expiration in ledger review step
  src/app/assets/svg/questionmark.svg
  src/app/i18n/common/i18n.ts
  src/domains/transaction/components/TransactionDetail/TransactionDetail.tsx
  src/domains/transaction/i18n.ts
  src/domains/transaction/pages/SendTransfer/LedgerReview.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.tsx
Labels: Complexity: Medium, Status: In Progress, Type: Refactor

#3579 chore: update translation key
  src/domains/plugin/components/PluginManualInstallModal/__snapshots__/PluginManualInstallModal.test.tsx.snap
  src/domains/plugin/i18n.ts
Labels: Complexity: Low, Type: Task

#3578 fix: do not switch to multi when going back to form with only one recipient
  src/domains/transaction/components/AddRecipient/AddRecipient.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#3576 fix: show plugin placeholder as fallback
  src/domains/plugin/components/PluginImage/PluginImage.test.tsx
  src/domains/plugin/components/PluginImage/PluginImage.tsx
  src/domains/plugin/components/PluginImage/__snapshots__/PluginImage.test.tsx.snap
Labels: Complexity: Low, Type: Bugfix

#3575 feat: add errors to cryptoasset input
  src/app/i18n/common/i18n.ts
  src/domains/network/components/NetworkIcon/NetworkIcon.tsx
  src/domains/network/components/SelectNetwork/SelectNetwork.test.tsx
  src/domains/network/components/SelectNetwork/SelectNetwork.tsx
  src/domains/network/components/SelectNetwork/SelectNetworkInput.tsx
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/setting/components/PeerForm/__snapshots__/PeerForm.test.tsx.snap
  src/domains/setting/components/PeerListItem/__snapshots__/PeerListItem.test.tsx.snap
  src/domains/setting/components/UpdatePeer/__snapshots__/UpdatePeer.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/NetworkStep.tsx
  src/domains/transaction/pages/SendTransfer/SendTransfer.test.tsx
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/transaction/validations/SendTransfer.ts
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerConnectionStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerScanStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: Medium, Status: Needs Review, Type: Feature

#3581 fix: adjust border color of focused input
  src/app/components/Input/Input.tsx
  src/app/components/Input/__snapshots__/Input.test.tsx.snap
  src/app/components/Input/__snapshots__/InputAddress.test.tsx.snap
  src/app/components/Input/__snapshots__/InputCounter.test.tsx.snap
  src/app/components/Input/__snapshots__/InputCurrency.test.tsx.snap
  src/app/components/Input/__snapshots__/InputDefault.test.tsx.snap
  src/app/components/Input/__snapshots__/InputPassword.test.tsx.snap
  src/app/components/Input/__snapshots__/InputRange.test.tsx.snap
  src/app/components/SearchBar/__snapshots__/SearchBar.test.tsx.snap
  src/app/components/Select/__snapshots__/Select.test.tsx.snap
  src/app/components/SelectDropdown/__snapshots__/SelectDropdown.test.tsx.snap
  src/app/components/TextArea/__snapshots__/TextArea.test.tsx.snap
  src/domains/contact/components/ContactForm/__snapshots__/ContactForm.test.tsx.snap
  src/domains/contact/components/CreateContact/__snapshots__/CreateContact.test.tsx.snap
  src/domains/contact/components/UpdateContact/__snapshots__/UpdateContact.test.tsx.snap
  src/domains/network/components/SelectNetwork/__snapshots__/SelectNetwork.test.tsx.snap
  src/domains/news/components/AddAssets/__snapshots__/AddAssets.test.tsx.snap
  src/domains/news/components/NewsOptions/__snapshots__/NewsOptions.test.tsx.snap
  src/domains/news/pages/News/__snapshots__/News.test.tsx.snap
  src/domains/plugin/components/PluginManualInstallModal/__snapshots__/PluginManualInstallModal.test.tsx.snap
  src/domains/plugin/pages/PluginManager/__snapshots__/PluginManager.test.tsx.snap
  src/domains/profile/components/PasswordModal/__snapshots__/PasswordModal.test.tsx.snap
  src/domains/profile/components/SelectAddress/__snapshots__/SelectAddress.test.tsx.snap
  src/domains/profile/components/SelectRecipient/__snapshots__/SelectRecipient.test.tsx.snap
  src/domains/profile/components/SignIn/__snapshots__/SignIn.test.tsx.snap
  src/domains/profile/pages/CreateProfile/__snapshots__/CreateProfile.test.tsx.snap
  src/domains/profile/pages/ImportProfile/__snapshots__/ProfileFormStep.test.tsx.snap
  src/domains/setting/components/CreatePeer/__snapshots__/CreatePeer.test.tsx.snap
  src/domains/setting/components/PeerForm/__snapshots__/PeerForm.test.tsx.snap
  src/domains/setting/components/UpdatePeer/__snapshots__/UpdatePeer.test.tsx.snap
  src/domains/setting/pages/Settings/__snapshots__/Settings.test.tsx.snap
  src/domains/transaction/components/AddRecipient/__snapshots__/AddRecipient.test.tsx.snap
  src/domains/transaction/components/AuthenticationStep/__snapshots__/AuthenticationStep.test.tsx.snap
  src/domains/transaction/components/DelegateRegistrationForm/__snapshots__/DelegateRegistrationForm.test.tsx.snap
  src/domains/transaction/components/InputFee/__snapshots__/InputFee.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/__snapshots__/MultiSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/MultiSignatureRegistrationForm/components/AddParticipant/__snapshots__/AddParticipant.test.tsx.snap
  src/domains/transaction/components/SecondSignatureRegistrationForm/__snapshots__/SecondSignatureRegistrationForm.test.tsx.snap
  src/domains/transaction/components/SendTransactionForm/__snapshots__/SendTransactionForm.test.tsx.snap
  src/domains/transaction/pages/SendDelegateResignation/__snapshots__/SendDelegateResignation.test.tsx.snap
  src/domains/transaction/pages/SendIpfs/__snapshots__/SendIpfs.test.tsx.snap
  src/domains/transaction/pages/SendTransfer/__snapshots__/SendTransfer.test.tsx.snap
  src/domains/wallet/components/NetworkStep/__snapshots__/NetworkStep.test.tsx.snap
  src/domains/wallet/components/ReceiveFunds/__snapshots__/ReceiveFundsForm.test.tsx.snap
  src/domains/wallet/components/SignMessage/__snapshots__/SignMessage.test.tsx.snap
  src/domains/wallet/components/UpdateWalletName/__snapshots__/UpdateWalletName.test.tsx.snap
  src/domains/wallet/components/VerifyMessage/__snapshots__/VerifyMessage.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/CreateWallet.test.tsx.snap
  src/domains/wallet/pages/CreateWallet/__snapshots__/SuccessStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerImportStep.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/Ledger/__snapshots__/LedgerTabs.test.tsx.snap
  src/domains/wallet/pages/ImportWallet/__snapshots__/ImportWallet.test.tsx.snap
Labels: Complexity: High, Type: Bugfix

#3550 refactor: handle profile save when persisting env
  src/app/contexts/Environment/Environment.tsx
  src/app/hooks/index.ts
  src/app/hooks/use-profile-synchronizer.test.tsx
  src/app/hooks/use-profile-synchronizer.ts
  src/app/hooks/use-profile-utils.test.tsx
  src/app/hooks/use-profile-utils.ts
  src/domains/profile/pages/CreateProfile/CreateProfile.tsx
  src/domains/setting/pages/Settings/available-settings/General.tsx
  src/domains/setting/pages/Settings/available-settings/Peer.tsx
  src/domains/transaction/hooks/use-fee-confirmation.ts
  src/domains/wallet/pages/CreateWallet/CreateWallet.tsx
  src/domains/wallet/pages/ImportWallet/ImportWallet.tsx
Labels: Complexity: Low, Status: Needs Review, Type: Refactor
